In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('input/rb/dk_stats_loc.csv')

In [4]:
df[df['Name']=='Jordan Howard']

,year,PlayerID,Name,Team,Week,Opponent,att,yds,yds/att,td,tar,rec,rec_yds,rec_td,fum,def_rk,h/a_1,surface_0,salary,points
2040,2016,18067,Jordan Howard,CHI,2,PHI,3,22,7.3,0,2,2,9,0,0,12,1.0,1.0,4300,5.1
2148,2016,18067,Jordan Howard,CHI,3,DAL,9,45,5.0,0,6,4,47,0,0,3,0.0,0.0,3000,13.2
2235,2016,18067,Jordan Howard,CHI,4,DET,23,111,4.8,0,4,3,21,0,0,9,1.0,1.0,3000,19.2
2320,2016,18067,Jordan Howard,CHI,5,IND,16,118,7.4,0,3,3,45,1,0,25,0.0,0.0,3000,28.3
2496,2016,18067,Jordan Howard,CHI,7,GB,7,22,3.1,0,1,0,0,0,0,10,0.0,1.0,6600,2.2
2570,2016,18067,Jordan Howard,CHI,8,MIN,26,153,5.9,1,4,4,49,0,0,8,1.0,1.0,3300,33.2
2735,2016,18067,Jordan Howard,CHI,10,TB,15,100,6.7,0,0,0,0,0,1,22,0.0,1.0,3000,12.0
2824,2016,18067,Jordan Howard,CHI,11,NYG,17,77,4.5,0,8,1,22,0,0,6,0.0,0.0,4000,10.9
2920,2016,18067,Jordan Howard,CHI,12,TEN,18,84,4.7,0,5,3,43,0,0,2,1.0,1.0,3000,15.7
3008,2016,18067,Jordan Howard,CHI,13,SF,32,117,3.7,3,1,0,0,0,0,32,1.0,1.0,5300,32.7
3192,2016,18067,Jordan Howard,CHI,15,GB,17,90,5.3,1,4,4,23,0,0,10,1.0,1.0,3000,21.3
3386,2016,18067,Jordan Howard,CHI,17,MIN,23,135,5.9,0,0,0,0,0,0,8,0.0,0.0,3700,16.5
3481,2017,18067,Jordan Howard,CHI,1,ATL,13,52,4.0,1,5,3,14,0,0,14,1.0,1.0,3000,15.6
3593,2017,18067,Jordan Howard,CHI,2,TB,9,7,0.8,0,1,0,0,0,0,29,0.0,1.0,4000,0.7
3702,2017,18067,Jordan Howard,CHI,3,PIT,23,140,6.1,2,5,5,26,0,1,18,1.0,1.0,4500,35.6
3919,2017,18067,Jordan Howard,CHI,5,MIN,19,76,4.0,0,0,0,0,0,0,1,1.0,1.0,3000,7.6
4013,2017,18067,Jordan Howard,CHI,6,BAL,36,167,4.6,0,1,1,9,0,0,20,0.0,1.0,4900,21.6
4113,2017,18067,Jordan Howard,CHI,7,CAR,21,65,3.1,0,0,0,0,0,0,3,1.0,1.0,3000,6.5
4207,2017,18067,Jordan Howard,CHI,8,NO,23,102,4.4,0,5,3,19,0,0,17,0.0,0.0,4500,18.1
4390,2017,18067,Jordan Howard,CHI,10,GB,15,54,3.6,0,0,0,0,0,0,24,1.0,1.0,4200,5.4
4480,2017,18067,Jordan Howard,CHI,11,DET,15,125,8.3,1,0,0,0,0,0,31,1.0,1.0,3000,21.5
4579,2017,18067,Jordan Howard,CHI,12,PHI,7,6,0.9,0,2,2,13,0,0,2,0.0,1.0,3000,3.9
4680,2017,18067,Jordan Howard,CHI,13,SF,13,38,2.9,0,2,1,-5,0,0,26,1.0,1.0,3900,4.3
4786,2017,18067,Jordan Howard,CHI,14,CIN,23,147,6.4,2,2,1,8,0,0,30,0.0,0.0,4300,31.5
4888,2017,18067,Jordan Howard,CHI,15,DET,10,37,3.7,0,4,4,26,0,0,31,0.0,0.0,3500,10.3
4990,2017,18067,Jordan Howard,CHI,16,CLE,22,44,2.0,2,0,0,0,0,0,13,1.0,1.0,3900,16.4
5084,2017,18067,Jordan Howard,CHI,17,MIN,9,9,1.0,0,1,1,5,0,0,1,0.0,0.0,3900,2.4
5189,2018,18067,Jordan Howard,CHI,1,GB,15,82,5.5,0,5,5,25,0,0,9,0.0,1.0,5400,15.7
5296,2018,18067,Jordan Howard,CHI,2,SEA,14,35,2.5,0,4,3,33,0,0,10,1.0,1.0,3900,9.8
5395,2018,18067,Jordan Howard,CHI,3,ARI,24,61,2.5,1,2,2,20,0,0,31,0.0,1.0,4900,16.1
5492,2018,18067,Jordan Howard,CHI,4,TB,11,25,2.3,0,1,0,0,0,0,27,1.0,1.0,3000,2.5
5798,2016,18067,Jordan Howard,CHI,6,JAX,15,34,2.3,1,4,2,6,0,0,14,1.0,1.0,3000,12.0
5972,2016,18067,Jordan Howard,CHI,14,DET,13,86,6.6,0,5,2,24,0,0,9,0.0,0.0,3100,13.0
6007,2016,18067,Jordan Howard,CHI,16,WAS,18,119,6.6,0,3,1,9,0,0,26,1.0,1.0,3000,16.8
6070,2017,18067,Jordan Howard,CHI,4,GB,18,53,2.9,1,4,2,10,0,0,24,0.0,1.0,5800,14.3

In [1119]:
loc = pd.read_csv('input/location.csv')

In [1275]:
loc[:17]

    week home away  year
0      1   NE  PIT  2015
1      1  STL  SEA  2015
2      1  CHI   GB  2015
3      1  WAS  MIA  2015
4      1  HOU   KC  2015
5      1  BUF  IND  2015
6      1  JAX  CAR  2015
7      1  NYJ  CLE  2015
8      1  ARI   NO  2015
9      1   SD  DET  2015
10     1  DEN  BAL  2015
11     1   TB  TEN  2015
12     1  OAK  CIN  2015
13     1  DAL  NYG  2015
14     1  ATL  PHI  2015
15     1   SF  MIN  2015
16     2   KC  DEN  2015

In [1120]:
loc['home'].replace('JAC','JAX', inplace=True)

In [1404]:
loc_15 = loc[loc['year']==2015]
loc_15

     week home away  year
0       1   NE  PIT  2015
1       1  STL  SEA  2015
2       1  CHI   GB  2015
3       1  WAS  MIA  2015
4       1  HOU   KC  2015
5       1  BUF  IND  2015
6       1  JAX  CAR  2015
7       1  NYJ  CLE  2015
8       1  ARI   NO  2015
9       1   SD  DET  2015
10      1  DEN  BAL  2015
11      1   TB  TEN  2015
12      1  OAK  CIN  2015
13      1  DAL  NYG  2015
14      1  ATL  PHI  2015
15      1   SF  MIN  2015
16      2   KC  DEN  2015
17      2  CHI  ARI  2015
18      2   NO   TB  2015
19      2  PIT   SF  2015
20      2  BUF   NE  2015
21      2  CLE  TEN  2015
22      2  NYG  ATL  2015
23      2  CAR  HOU  2015
24      2  CIN   SD  2015
25      2  WAS  STL  2015
26      2  MIN  DET  2015
27      2  OAK  BAL  2015
28      2  JAX  MIA  2015
29      2  PHI  DAL  2015
..    ...  ...  ...   ...
226    16  BUF  DAL  2015
227    16  MIA  IND  2015
228    16  NYJ   NE  2015
229    16  ATL  CAR  2015
230    16  TEN  HOU  2015
231    16  BAL  PIT  2015
232    16   TB  CHI  2015
233    16  DET   SF  2015
234    16   KC  CLE  2015
235    16   NO  JAX  2015
236    16  ARI   GB  2015
237    16  SEA  STL  2015
238    16  MIN  NYG  2015
239    16  DEN  CIN  2015
240    17  CLE  PIT  2015
241    17  BUF  NYJ  2015
242    17  CHI  DET  2015
243    17  IND  TEN  2015
244    17  CIN  BAL  2015
245    17  ATL   NO  2015
246    17  MIA   NE  2015
247    17  HOU  JAX  2015
248    17  DAL  WAS  2015
249    17  NYG  PHI  2015
250    17  CAR   TB  2015
251    17  ARI  SEA  2015
252    17  DEN   SD  2015
253    17   SF  STL  2015
254    17   KC  OAK  2015
255    17   GB  MIN  2015

[256 rows x 4 columns]

In [1594]:
temp = df[df['year']==2017]

In [1595]:
week1 = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [1596]:
week12.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
3791,722,Jason Witten,DAL,12,LAC,7,7,100.0,44,0,...,0.0,0,0,0,11.4,null,8,home,turf,2017
3792,1545,Anthony Fasano,MIA,12,NE,0,0,0.0,0,0,...,0.0,0,0,0,0.0,5100,10,away,turf,2017
3793,1658,Greg Olsen,CAR,12,NYJ,4,1,25.0,10,0,...,0.0,0,0,0,2.0,2500,22,away,turf,2017
3794,3061,Marcedes Lewis,JAX,12,ARI,2,1,50.0,10,0,...,0.0,0,0,0,2.0,2500,17,away,grass,2017
3795,5084,Vernon Davis,WAS,12,NYG,1,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,31,home,grass,2017

In [1126]:
loc_16 = loc[loc['year']==2016]
loc_17 = loc[loc['year']==2017]

In [1354]:
loc_17

     week home away  year
512     1   NE   KC  2017
513     1  CLE  PIT  2017
514     1  CIN  BAL  2017
515     1  WAS  PHI  2017
516     1  DET  ARI  2017
517     1  HOU  JAX  2017
518     1  TEN  OAK  2017
519     1  CHI  ATL  2017
520     1  BUF  NYJ  2017
521     1  LAR  IND  2017
522     1   SF  CAR  2017
523     1   GB  SEA  2017
524     1  DAL  NYG  2017
525     1  MIN   NO  2017
526     1  DEN  LAR  2017
527     2  CIN  HOU  2017
528     2  PIT  MIN  2017
529     2   TB  CHI  2017
530     2  BAL  CLE  2017
531     2  JAX  TEN  2017
532     2   KC  PHI  2017
533     2  IND  ARI  2017
534     2  CAR  BUF  2017
535     2   NO   NE  2017
536     2  LAR  MIA  2017
537     2  OAK  NYJ  2017
538     2  SEA   SF  2017
539     2  DEN  DAL  2017
540     2  LAR  WAS  2017
541     2  ATL   GB  2017
..    ...  ...  ...   ...
738    16  WAS  DEN  2017
739    16  NYJ  LAR  2017
740    16   NE  BUF  2017
741    16   KC  MIA  2017
742    16  CIN  DET  2017
743    16  CHI  CLE  2017
744    16   NO  ATL  2017
745    16  CAR   TB  2017
746    16  TEN  LAR  2017
747    16   SF  JAX  2017
748    16  DAL  SEA  2017
749    16  ARI  NYG  2017
750    16  HOU  PIT  2017
751    16  PHI  OAK  2017
752    17  IND  HOU  2017
753    17   NE  NYJ  2017
754    17  DET   GB  2017
755    17  PHI  DAL  2017
756    17  PIT  CLE  2017
757    17  NYG  WAS  2017
758    17  MIN  CHI  2017
759    17  LAR   SF  2017
760    17  SEA  ARI  2017
761    17   TB   NO  2017
762    17  DEN   KC  2017
763    17  LAR  OAK  2017
764    17  MIA  BUF  2017
765    17  TEN  JAX  2017
766    17  BAL  CIN  2017
767    17  ATL  CAR  2017

[256 rows x 4 columns]

In [1597]:
loc_df = loc_17[loc_17['week']==1];home_list = [];
for team in week1['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week1['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1598]:
loc_df = loc_17[loc_17['week']==2];home_list = [];
for team in week2['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week2['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1599]:
loc_df = loc_17[loc_17['week']==3];home_list = [];
for team in week3['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week3['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1600]:
loc_df = loc_17[loc_17['week']==4];home_list = [];
for team in week4['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week4['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1601]:
loc_df = loc_17[loc_17['week']==5];home_list = [];
for team in week5['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week5['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1602]:
loc_df = loc_17[loc_17['week']==6];home_list = [];
for team in week6['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week6['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1603]:
loc_df = loc_17[loc_17['week']==7];home_list = [];
for team in week7['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week7['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1604]:
loc_df = loc_17[loc_17['week']==8];home_list = [];
for team in week8['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week8['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1605]:
loc_df = loc_17[loc_17['week']==9];home_list = [];
for team in week9['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week9['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1606]:
loc_df = loc_17[loc_17['week']==10];home_list = [];
for team in week10['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week10['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1607]:
loc_df = loc_17[loc_17['week']==11];home_list = [];
for team in week11['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week11['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1608]:
loc_df = loc_17[loc_17['week']==12];home_list = [];
for team in week12['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week12['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1609]:
loc_df = loc_17[loc_17['week']==13];home_list = [];
for team in week13['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week13['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1610]:
loc_df = loc_17[loc_17['week']==14];home_list = [];
for team in week14['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week14['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1611]:
loc_df = loc_17[loc_17['week']==15];home_list = [];
for team in week15['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week15['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1612]:
loc_df = loc_17[loc_17['week']==16];home_list = [];
for team in week16['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week16['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1613]:
loc_df = loc_17[loc_17['week']==17];home_list = [];
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')
week17['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [1629]:
te_2017=pd.concat([te_2017,week17])
te_2017.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
4340,19304,Pharaoh Brown,OAK,17,LAC,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,8,away,grass,2017
4341,19335,Antony Auclair,TB,17,NO,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,2,home,grass,2017
4342,19390,Emanuel Byrd,GB,17,DET,2,2,100.0,31,0,...,0.0,0,0,0,5.1,3500,16,away,turf,2017
4343,19410,Ricky Seals-Jones,ARI,17,SEA,1,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,9,away,turf,2017
4344,19579,Tyrone Swoopes,SEA,17,ARI,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,17,home,turf,2017

In [1335]:
qb_2016[0:1]

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,salary,year,def_rk,h/a,surface,FantasyPointsDraftKings
600,611,Joe Flacco,BAL,1,BUF,22,33,66.7,258,7.8,...,4,-3,-0.8,0,6700,2016,8,home,grass,13.02

In [849]:
qb_2017['Week'].unique()

SyntaxError: unexpected EOF while parsing (<ipython-input-849-bc03811fe7ae>, line 1)

In [1266]:
surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'}

In [1632]:
surface = []
for idx, team in enumerate(te_2017['Team']):
    if te_2017.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[te_2017.iloc[idx]['Opponent']])


te_2017['surface'] = surface

In [1633]:
te_2015['surface']

0       grass
1        turf
2        turf
3       grass
4       grass
5       grass
6       grass
7       grass
8        turf
9       grass
10       turf
11       turf
12       turf
13      grass
14       turf
15       turf
16       turf
17       turf
18      grass
19      grass
20       turf
21      grass
22       turf
23       turf
24       turf
25      grass
26       turf
27      grass
28      grass
29      grass
        ...
1415    grass
1416     turf
1417     turf
1418     turf
1419     turf
1420     turf
1421     turf
1422     turf
1423    grass
1424    grass
1425    grass
1426    grass
1427    grass
1428    grass
1429     turf
1430     turf
1431    grass
1432     turf
1433    grass
1434    grass
1435     turf
1436    grass
1437     turf
1438    grass
1439     turf
1440    grass
1441    grass
1442    grass
1443     turf
1444     turf
Name: surface, Length: 1445, dtype: object

In [1634]:
te = pd.concat([te_2015,te_2016])
te = pd.concat([te,te_2017])

In [1635]:
te.shape

(4345, 25)

In [1636]:
df.shape

(4345, 25)

In [1637]:
te_2015[te_2015['Team']=='PIT']

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
11,6293,Matt Spaeth,PIT,1,NE,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,5,away,turf,2015
14,7635,Heath Miller,PIT,1,NE,11,8,72.7,84,0,...,0.0,0,0,0,16.4,3300,5,away,turf,2015
103,6293,Matt Spaeth,PIT,2,SF,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,9,home,grass,2015
104,7635,Heath Miller,PIT,2,SF,2,2,100.0,15,1,...,0.0,0,0,0,11.5,2500,9,home,grass,2015
194,6293,Matt Spaeth,PIT,3,LAR,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,26,away,grass,2015
197,7635,Heath Miller,PIT,3,LAR,3,2,66.7,17,0,...,0.0,0,0,0,3.7,null,26,away,grass,2015
276,7635,Heath Miller,PIT,4,BAL,2,1,50.0,1,0,...,0.0,0,0,0,1.1,2500,4,home,grass,2015
356,6293,Matt Spaeth,PIT,5,LAC,1,0,0.0,0,0,...,0.0,0,0,0,0.0,4600,18,away,grass,2015
358,7635,Heath Miller,PIT,5,LAC,3,3,100.0,46,0,...,0.0,0,0,0,7.6,5300,18,away,grass,2015
437,6293,Matt Spaeth,PIT,6,ARI,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,20,home,grass,2015
439,7635,Heath Miller,PIT,6,ARI,1,1,100.0,5,0,...,0.0,0,0,0,1.5,null,20,home,grass,2015
515,6293,Matt Spaeth,PIT,7,KC,0,0,0.0,0,0,...,0.0,0,0,0,0.0,null,2,away,grass,2015
517,7635,Heath Miller,PIT,7,KC,2,0,0.0,0,0,...,0.0,0,0,0,0.0,4400,2,away,grass,2015
592,6293,Matt Spaeth,PIT,8,CIN,1,1,100.0,4,0,...,0.0,0,0,0,1.4,2500,17,home,grass,2015
594,7635,Heath Miller,PIT,8,CIN,13,10,76.9,105,0,...,0.0,0,0,0,23.5,2500,17,home,grass,2015
672,7635,Heath Miller,PIT,9,OAK,6,3,50.0,32,0,...,0.0,0,0,0,6.2,2500,30,home,grass,2015
732,16920,Jesse James,PIT,9,OAK,2,2,100.0,13,1,...,0.0,0,0,0,9.3,2500,30,home,grass,2015
747,7635,Heath Miller,PIT,10,CLE,7,4,57.1,40,0,...,0.0,0,0,0,8.0,2500,6,home,grass,2015
809,16920,Jesse James,PIT,10,CLE,1,1,100.0,2,0,...,0.0,0,0,0,1.2,2500,6,home,grass,2015
905,6293,Matt Spaeth,PIT,12,SEA,1,1,100.0,6,0,...,0.0,0,0,0,1.6,2800,22,away,turf,2015
907,7635,Heath Miller,PIT,12,SEA,6,5,83.3,45,0,...,0.0,0,0,0,9.5,2500,22,away,turf,2015
980,16920,Jesse James,PIT,12,SEA,2,1,50.0,8,0,...,0.0,0,0,0,3.8,3300,22,away,turf,2015
998,6293,Matt Spaeth,PIT,13,IND,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,23,home,grass,2015
1069,16920,Jesse James,PIT,13,IND,5,3,60.0,30,0,...,0.0,0,0,0,6.0,2500,23,home,grass,2015
1086,6293,Matt Spaeth,PIT,14,CIN,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,17,away,turf,2015
1088,7635,Heath Miller,PIT,14,CIN,10,10,100.0,66,0,...,2.0,0,0,0,16.8,null,17,away,turf,2015
1162,16920,Jesse James,PIT,14,CIN,0,0,0.0,0,0,...,0.0,0,0,0,0.0,5800,17,away,turf,2015
1179,6293,Matt Spaeth,PIT,15,DEN,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,19,home,grass,2015
1181,7635,Heath Miller,PIT,15,DEN,5,3,60.0,12,0,...,0.0,0,0,0,4.2,3700,19,home,grass,2015
1254,16920,Jesse James,PIT,15,DEN,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,19,home,grass,2015
1270,6293,Matt Spaeth,PIT,16,BAL,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,4,away,grass,2015
1272,7635,Heath Miller,PIT,16,BAL,6,5,83.3,49,0,...,0.0,0,0,0,9.9,2500,4,away,grass,2015
1344,16920,Jesse James,PIT,16,BAL,1,1,100.0,3,0,...,0.0,0,0,0,1.3,2500,4,away,grass,2015
1362,6293,Matt Spaeth,PIT,17,CLE,0,0,0.0,0,0,...,0.0,0,0,0,0.0,3900,6,away,grass,2015
1364,7635,Heath Miller,PIT,17,CLE,4,3,75.0,18,1,...,0.0,0,0,0,10.8,2500,6,away,grass,2015
1436,16920,Jesse James,PIT,17,CLE,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,6,away,grass,2015

In [1638]:
te.to_csv('input/te/dk_stats_loc.csv', index=False)

In [344]:
df_17 = df[df['year']==2017]
df_17.shape

(600, 23)

In [1639]:
qb=pd.read_csv('input/qb/dk_stats_loc.csv')

In [1640]:
qb.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'salary', 'year',
       'def_rk', 'h/a', 'surface', 'FantasyPointsDraftKings'],
      dtype='object')

In [346]:
df_15.shape

(600, 23)

In [345]:
qb_2017.shape

(600, 23)

In [78]:
cols = df.columns.tolist()
cols = cols[0:17] + cols[18:] +cols[17:18]
df = df[cols]
df.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,salary,year,def_rk,h/a,surface,FantasyPointsDraftKings
0,611,Joe Flacco,BAL,1,DEN,18,32,56.2,117,3.7,...,0,0,0.0,0,6700,2015,1,away,grass,2.68
1,732,Matt Ryan,ATL,1,PHI,23,34,67.6,298,8.8,...,5,7,1.4,0,7500,2015,30,home,turf,18.62
2,2428,Carson Palmer,ARI,1,NO,19,32,59.4,307,9.6,...,3,14,4.7,0,6500,2015,32,home,grass,28.68
3,2593,Aaron Rodgers,GB,1,CHI,18,23,78.3,189,8.2,...,8,35,4.4,0,8600,2015,25,away,grass,23.06
4,3807,Ben Roethlisberger,PIT,1,NE,26,38,68.4,351,9.2,...,0,0,0.0,0,7300,2015,15,away,turf,22.04

In [79]:
df.to_csv('input/qb/dk_stats_loc.csv', index=False)