In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [2]:
qb= pd.read_csv('input/qb/qb_loc_cleaned.csv')
qb.head()

,games,year,Name,Team,Week,Opponent,att,comp%,yds,td,def_rk,h/a_1,surface_0,points
0,1,2012,Aaron Rodgers,GB,1,SF,44,68.0,303,2,5,1.0,1.0,22.82
1,1,2012,Alex Smith,SF,1,GB,26,77.0,211,2,17,0.0,1.0,17.74
2,1,2012,Andrew Luck,IND,1,CHI,45,51.0,309,1,31,0.0,1.0,9.26
3,1,2012,Andy Dalton,CIN,1,BAL,37,60.0,221,0,19,0.0,1.0,5.94
4,1,2012,Ben Roethlisberger,PIT,1,DEN,40,55.0,245,2,24,0.0,1.0,16.20

In [3]:
qb['year'].unique()

array([2012, 2013, 2014, 2015, 2016, 2017, 2018], dtype=int64)

In [4]:
qb_18=qb[qb['year']==2018]
qb_18['Week'].unique()

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [6]:
qb.sort_values(['Name','games'], inplace=True)

In [84]:
qb.shape

(2354, 14)

In [97]:
wr = pd.read_csv('input/wr/wr_loc_cleaned.csv')
wr.head()

,games,Name,Team,Week,Opponent,tar,rec,yds,td,yds/tar,yds/rec,salary,h/a_1,surface_0,def_rk,year,points
0,1,AJ Green,CIN,1,OAK,8,5,63,0,7.9,12.6,3500,0.0,1.0,22,2015,11.3
1,2,AJ Green,CIN,2,LAC,4,3,45,1,11.2,15.0,3000,1.0,0.0,14,2015,13.5
2,3,AJ Green,CIN,3,BAL,13,10,227,2,17.5,22.7,4800,0.0,1.0,17,2015,47.7
3,4,AJ Green,CIN,4,KC,10,7,82,0,8.2,11.7,3000,1.0,0.0,7,2015,15.2
4,5,AJ Green,CIN,5,SEA,8,6,78,0,9.8,13.0,3000,1.0,0.0,1,2015,13.8

In [4]:
rb.sort_values(['Name','games'],inplace=True)
rb.head()

,games,year,Name,Team,Week,Opponent,att,yds,td,tar,rec_yds,def_rk,h/a_1,surface_0,salary,points
0,1,2017,Aaron Jones,GB,4,CHI,13,49,1,0,0,11,1.0,1.0,3000,10.9
1,2,2017,Aaron Jones,GB,5,DAL,19,125,1,1,9,8,0.0,0.0,3500,23.4
2,3,2017,Aaron Jones,GB,6,MIN,13,41,0,4,1,1,0.0,0.0,4000,5.2
3,4,2017,Aaron Jones,GB,7,NO,17,131,1,5,7,17,1.0,1.0,5000,25.8
4,5,2017,Aaron Jones,GB,9,DET,5,12,0,5,-1,31,1.0,1.0,3000,3.1

In [123]:
wr.sort_values(['Name','Week'],inplace=True)
wr.head()

,games,Name,Team,Week,Opponent,tar,rec,yds,td,yds/tar,yds/rec,salary,h/a_1,surface_0,def_rk,year,points
0,1,AJ Green,CIN,1,OAK,8,5,63,0,7.9,12.6,3500,0.0,1.0,22,2015,11.3
16,17,AJ Green,CIN,1,NYJ,13,12,180,1,13.8,15.0,3600,0.0,0.0,15,2016,39.0
26,27,AJ Green,CIN,1,BAL,10,5,74,0,7.4,14.8,3500,1.0,0.0,5,2017,12.4
42,43,AJ Green,CIN,1,IND,8,6,92,1,11.5,15.3,3100,0.0,0.0,1,2018,20.2
1,2,AJ Green,CIN,2,LAC,4,3,45,1,11.2,15.0,3000,1.0,0.0,14,2015,13.5

In [172]:
def create_sorted_dict (df):
    df_sorted = df.sort_values(['Name','games'])
    sorted_dict = {}
    for player in df_sorted['Name']:
        sorted_dict['{}'.format(player)] = {'year':df_sorted[df_sorted['Name']==player]['year'],
                                            'Opponent':df_sorted[df_sorted['Name']==player]['Opponent'],
                                            'points':df_sorted[df_sorted['Name']==player]['points'],
                                            'def_rk':df_sorted[df_sorted['Name']==player]['def_rk'],
                                            'surface_0':df_sorted[df_sorted['Name']==player]['surface_0'],
                                            'h/a_1':df_sorted[df_sorted['Name']== player]['h/a_1'],
                                            'games': df_sorted[df_sorted['Name']==player]['games']
                                           }
       
    return sorted_dict

In [55]:
rb_sorted_dict = create_sorted_dict(rb)

In [173]:
qb_sorted_dict = create_sorted_dict(qb)

In [174]:
qb_sorted_dict.keys()

dict_keys(['AJ McCarron', 'Aaron Rodgers', 'Alex Smith', 'Andrew Luck', 'Andy Dalton', 'Austin Davis', 'Baker Mayfield', 'Ben Roethlisberger', 'Blaine Gabbert', 'Blake Bortles', 'Brady Quinn', 'Brandon Weeden', 'Brett Hundley', 'Brian Hoyer', 'Brock Osweiler', 'Bruce Gradkowski', 'Byron Leftwich', 'CJ Beathard', 'Cam Newton', 'Carson Palmer', 'Carson Wentz', 'Case Keenum', 'Chad Henne', 'Chad Kelly', 'Charlie Batch', 'Charlie Whitehurst', 'Chase Daniel', 'Christian Ponder', 'Cody Kessler', 'Colin Kaepernick', 'Colt McCoy', 'Cooper Rush', 'Dak Prescott', 'Dan Orlovsky', 'David Carr', 'David Fales', 'Derek Anderson', 'Derek Carr', 'Deshaun Watson', 'Deshone Kizer', 'Drew Brees', 'Drew Stanton', 'EJ Manuel', 'Eli Manning', 'Geno Smith', 'Graham Harrell', 'Greg McElroy', 'Jacoby Brissett', 'Jake Locker', 'Jameis Winston', 'Jared Goff', 'Jason Campbell', 'Jay Cutler', 'Jimmy Clausen', 'Jimmy Garoppolo', 'Joe Flacco', 'Joe Webb', 'John Skelton', 'Johnny Manziel', 'Josh Allen', 'Josh Freeman', 'Josh Johnson', 'Josh McCown', 'Josh Rosen', 'Joshua Dobbs', 'Kellen Clemens', 'Kellen Moore', 'Kevin Hogan', 'Kevin Kolb', 'Kirk Cousins', 'Kyle Orton', 'Lamar Jackson', 'Landry Jones', 'Luke McCown', 'Marcus Mariota', 'Mark Sanchez', 'Matt Barkley', 'Matt Cassel', 'Matt Flynn', 'Matt Hasselbeck', 'Matt Leinart', 'Matt McGloin', 'Matt Moore', 'Matt Ryan', 'Matt Schaub', 'Matthew Stafford', 'Michael Vick', 'Mike Glennon', 'Mitch Trubisky', 'Nathan Peterman', 'Nick Foles', 'Patrick Mahomes', 'Paxton Lynch', 'Peyton Manning', 'Philip Rivers', 'Robert Griffin III', 'Russell Wilson', 'Rusty Smith', 'Ryan Fitzpatrick', 'Ryan Lindley', 'Ryan Mallett', 'Ryan Tannehill', 'Sam Bradford', 'Sam Darnold', 'Scott Tolzien', 'Shaun Hill', 'TJ Yates', 'Tarvaris Jackson', 'Taysom Hill', 'Teddy Bridgewater', 'Thaddeus Lewis', 'Tim Tebow', 'Tom Brady', 'Tom Savage', 'Tony Romo', 'Trent Edwards', 'Trevor Siemian', 'Tyrod Taylor', 'Zach Mettenberger'])

In [140]:
# Create a data frame to investigate the points attribute of the dataset. 


def get_points_df(df):
    total_points = df['points'].sum()
    total_games = df['points'].count()

    val_lst = []
    sal_lst = []
    games_lst = []
    wght_avg=[]
    players = []
    avg_lst=[]

    for name in list(df['Name'].unique()):
        players.append(name)
        player_games = df[df['Name'] ==name].describe().loc['count'][0]
        games_lst.append(player_games)
        avg_points = round(df[df['Name'] ==name].describe()['points'].mean(),2)
        avg_lst.append(avg_points)
        wght_avg.append((round(avg_points + (avg_points* (player_games/total_games)),2)))
        sal_avg= round(df[df['Name'] ==name].describe()['salary'].mean(),2)
        sal_lst.append(sal_avg)
        val = round(sal_avg/avg_points,2)
        val_lst.append(val)
     
    df_eng = pd.DataFrame()
    df_eng['player'] = (df['Name'].unique())
    df_eng['games'] = games_lst
    df_eng['avg_points']= avg_lst
    df_eng['wght_avg'] = wght_avg
    df_eng['sal_avg'] = sal_lst
    df_eng['val'] = val_lst
    df_eng.head()
    
    return df_eng

In [191]:
te_points = get_points_df(te)

## Group Dataframes

In [10]:
# A function to create a dictonary of grouped data frames

def grouped_dict(csv):
    
    df= pd.read_csv(csv)
    

    yearly_dict = {}
    for year in list(df['year'].unique()):
        yearly_dict['player_{}'.format(year)] = (df[df['year']==year]).drop('year',axis=1).groupby(['Name','Week','Opponent']).sum()
        


    return yearly_dict

In [11]:
def conv_atts(grouped_dict):
    for group in grouped_dict:
        grouped_dict['{}'.format(group)]['h/a_1'] = grouped_dict['{}'.format(group)]['h/a_1'].astype('category')
        grouped_dict['{}'.format(group)]['surface_0'] = grouped_dict['{}'.format(group)]['surface_0'].astype('category')
    
    return grouped_dict

In [24]:
qb_group = grouped_dict('input/qb/qb_loc_cleaned.csv')

In [25]:
qb_group = conv_atts(qb_group)

In [26]:
qb_group['player_2013'].dtypes

games           int64
att             int64
comp%         float64
yds             int64
td              int64
def_rk          int64
h/a_1        category
surface_0    category
points        float64
dtype: object

In [27]:
qb_group

{'player_2012':                              games  att  comp%  yds  td  def_rk h/a_1  \
 Name          Week Opponent
 Aaron Rodgers 1    SF            1   44   68.0  303   2       5   1.0
               2    CHI           2   32   69.0  219   1      31   1.0
               3    SEA           3   39   67.0  223   0       1   0.0
               4    NO            4   41   76.0  319   4      29   1.0
               5    IND           5   32   63.0  235   3      13   0.0
               6    HOU           6   37   65.0  338   6      10   0.0
               7    LAR           7   37   81.0  342   3      11   0.0
               8    JAX           8   35   63.0  186   2      14   1.0
               9    ARI           9   30   47.0  218   4      23   1.0
               11   DET          10   27   70.0  236   2       7   0.0
               12   NYG          11   25   56.0  219   1      27   0.0
               13   MIN          12   35   77.0  286   1       9   1.0
               14   DET          13   24   58.0  173   0       7   1.0
               15   CHI          14   36   64.0  291   3      31   0.0
               16   TEN          15   38   71.0  342   3      18   1.0
               17   MIN          16   40   70.0  365   4       9   0.0
 Alex Smith    1    GB            1   26   77.0  211   2      17   0.0
               2    DET           2   31   65.0  226   2       7   1.0
               3    MIN           3   35   69.0  204   1       9   0.0
               4    NYJ           4   21   57.0  143   0      25   0.0
               5    BUF           5   24   75.0  303   3       2   1.0
               6    NYG           6   30   63.0  200   0      27   1.0
               7    SEA           7   23   61.0  140   1       1   1.0
               8    ARI           8   19   95.0  232   3      23   0.0
               10   LAR           9    8   88.0   72   1      11   1.0
               11   CHI          10    0    0.0    0   0      31   1.0
               12   NO           11    0    0.0    0   0      29   0.0
               13   LAR          12    0    0.0    0   0      11   0.0
               14   MIA          13    0    0.0    0   0       8   1.0
               15   NE           14    0    0.0    0   0      12   0.0
 ...                            ...  ...    ...  ...  ..     ...   ...
 Tom Brady     11   IND          10   35   69.0  331   3      13   1.0
               12   NYJ          11   27   67.0  323   3      25   0.0
               13   MIA          12   40   60.0  238   1       8   0.0
               14   HOU          13   35   60.0  296   4      10   1.0
               15   SF           14   65   55.0  443   1       5   1.0
               16   JAX          15   41   59.0  267   2      14   0.0
               17   MIA          16   36   61.0  284   2       8   1.0
 Tony Romo     1    NYG           1   29   76.0  307   3      27   0.0
               2    SEA           2   40   58.0  251   1       1   0.0
               3    TB            3   39   64.0  283   0      22   1.0
               4    CHI           4   43   72.0  307   1      31   1.0
               6    BAL           5   36   69.0  261   2      19   0.0
               7    CAR           6   34   71.0  227   1      16   0.0
               8    NYG           7   62   58.0  437   1      27   1.0
               9    ATL           8   35   71.0  321   1      26   0.0
               10   PHI           9   26   73.0  209   2      30   0.0
               11   CLE          10   50   70.0  313   1       6   1.0
               12   WAS          11   62   60.0  441   3      32   1.0
               13   PHI          12   27   82.0  303   3      30   1.0
               14   CIN          13   43   58.0  268   1       4   0.0
               15   PIT          14   42   71.0  341   2      28   1.0
               16   NO           15   43   61.0  416   4      29   1.0
               17   WAS          16   37   54.0  218   2      32   0.0
 Trent Edwards 17   NYG           1    2  100.0   14   0      27   0.0
 Tyrod Taylor  1    CIN           1    3   67.0   30   0       4   1.0
               4    CLE           2    0    0.0    0   0       6   1.0
               5    KC            3    0    0.0    0   0       3   0.0
               9    CLE           4    0    0.0    0   0       6   0.0
               10   OAK           5    1    0.0    0   0      20   1.0
               17   CIN           6   25   60.0  149   0       4   0.0

                             surface_0  points
 Name          Week Opponent
 Aaron Rodgers 1    SF             1.0   22.82
               2    CHI            1.0   10.16
               3    SEA            0.0   10.62
               4    NO             1.0   28.06
               5    IND            0.0   25.10
               6    HOU            0.0   39.22
               7    LAR            1.0   25.68
               8    JAX            1.0   13.84
               9    ARI            1.0   26.02
               11   DET            0.0   15.74
               12   NYG            0.0   10.96
               13   MIN            1.0   14.94
               14   DET            1.0   14.12
               15   CHI            1.0   25.94
               16   TEN            1.0   32.78
               17   MIN            0.0   28.60
 Alex Smith    1    GB             1.0   17.74
               2    DET            1.0   17.74
               3    MIN            0.0   10.76
               4    NYJ            0.0    6.92
               5    BUF            1.0   29.02
               6    NYG            1.0    2.50
               7    SEA            1.0    8.70
               8    ARI            1.0   21.88
               10   LAR            1.0    7.38
               11   CHI            1.0    0.00
               12   NO             0.0    0.00
               13   LAR            1.0    0.00
               14   MIA            1.0    0.00
               15   NE             0.0    0.00
 ...                               ...     ...
 Tom Brady     11   IND            0.0   25.24
               12   NYJ            0.0   31.42
               13   MIA            1.0   11.42
               14   HOU            0.0   28.44
               15   SF             0.0   24.82
               16   JAX            1.0   14.68
               17   MIA            0.0   19.36
 Tony Romo     1    NYG            0.0   23.48
               2    SEA            0.0   11.94
               3    TB             0.0    5.32
               4    CHI            0.0    6.28
               6    BAL            1.0   16.44
               7    CAR            1.0   14.18
               8    NYG            0.0   19.48
               9    ATL            0.0   16.84
               10   PHI            1.0   16.26
               11   CLE            0.0   15.52
               12   WAS            0.0   28.34
               13   PHI            0.0   25.52
               14   CIN            0.0   12.72
               15   PIT            0.0   21.24
               16   NO             0.0   32.64
               17   WAS            1.0   12.72
 Trent Edwards 17   NYG            0.0    0.56
 Tyrod Taylor  1    CIN            1.0    1.90
               4    CLE            1.0    0.00
               5    KC             1.0    0.00
               9    CLE            1.0    0.40
               10   OAK            1.0    0.00
               17   CIN            0.0   16.46

 [629 rows x 9 columns],
 'player_2013':                                 games  att  comp%  yds  td  def_rk h/a_1  \
 Name             Week Opponent
 Aaron Rodgers    1    SF           18   37   56.8  333   3       8   0.0
                  2    WAS          17   42   81.0  480   4      29   1.0
                  5    DET          23   30   66.7  274   1      20   1.0
                  6    BAL          22   32   53.1  315   1       9   0.0
                  7    CLE          19   36   69.4  260   3      23   1.0
                  8    MIN          20   29   82.8  285   2      30   0.0
                  17   CHI          21   39   64.1  318   2       4   0.0
 Alex Smith       1    JAX          25   34   61.8  173   2      16   0.0
                  2    DAL          20   36   58.3  223   2      13   1.0
                  4    NYG          18   41   58.5  288   3      24   1.0
                  7    HOU          24   34   67.6  240   0      18   0.0
                  8    CLE          23   36   66.7  225   2      23   1.0
                  11   DEN          22   45   46.7  230   2       7   0.0
                  12   LAC          21   38   68.4  294   3      19   1.0
                  13   DEN          19   42   61.9  293   2       7   1.0
                  15   OAK          17   20   85.0  287   5      25   0.0
 Andrew Luck      1    OAK          19   23   78.3  178   2      25   1.0
                  2    MIA          21   43   58.1  321   1      15   1.0
                  3    SF           28   26   65.4  159   0       8   0.0
                  4    JAX          23   35   60.0  257   2      16   0.0
                  5    SEA          24   29   55.2  229   2       2   1.0
                  7    DEN          18   38   55.3  228   3       7   0.0
                  9    HOU          20   40   45.0  271   3      18   0.0
                  10   LAR          22   47   61.7  353   1      17   1.0
                  11   TEN          25   36   63.9  232   0      22   0.0
                  14   CIN          17   46   63.0  326   4       6   0.0
                  15   HOU          26   32   59.4  180   2      18   1.0
                  17   JAX          27   37   70.3  282   1      16   1.0
 Andy Dalton      1    CHI          25   33   78.8  282   2       4   0.0
                  2    PIT          26   45   55.6  280   1       1   1.0
 ...                               ...  ...    ...  ...  ..     ...   ...
 Ryan Tannehill   15   NE           17   37   67.6  312   3      27   1.0
 Sam Bradford     1    ARI          19   38   71.1  299   2       3   0.0
                  2    ATL          17   55   58.2  352   3      10   0.0
                  5    JAX          18   34   55.9  222   3      16   0.0
                  6    HOU          20   16   75.0  117   3      18   0.0
 Scott Tolzien    10   PHI           1   39   61.5  280   1      28   1.0
 Tarvaris Jackson 3    JAX           1    8   87.5  129   1      16   1.0
 Thaddeus Lewis   6    CIN           2   32   59.4  216   2       6   1.0
 Tom Brady        1    BUF          23   52   55.8  288   2      26   0.0
                  3    TB           24   36   69.4  225   2      31   1.0
                  4    ATL          22   31   64.5  316   2      10   0.0
                  6    NO           25   43   58.1  269   1      32   1.0
                  9    PIT          17   33   69.7  432   4       1   1.0
                  11   CAR          26   40   72.5  296   1      12   0.0
                  12   DEN          19   50   68.0  344   3       7   1.0
                  13   HOU          20   41   70.7  371   2      18   0.0
                  14   CLE          18   52   61.5  418   2      23   1.0
                  15   MIA          21   55   61.8  364   2      15   0.0
 Tony Romo        1    NYG          24   49   73.5  263   2      24   1.0
                  2    KC           28   42   71.4  298   1      21   0.0
                  3    LAR          21   24   70.8  210   3      17   1.0
                  4    LAC          22   37   73.0  246   2      19   0.0
                  5    DEN          17   36   69.4  506   5       7   1.0
                  7    PHI          23   47   59.6  317   1      28   0.0
                  8    DET          20   30   46.7  206   3      20   0.0
                  9    MIN          18   51   66.7  337   2      30   1.0
                  12   NYG          25   38   60.5  234   2      24   0.0
                  14   CHI          26   20   55.0  104   3       4   0.0
                  15   GB           19   48   60.4  358   2      14   1.0
                  16   WAS          27   27   63.0  226   2      29   0.0

                                surface_0  points
 Name             Week Opponent
 Aaron Rodgers    1    SF             1.0   28.62
                  2    WAS            1.0   37.90
                  5    DET            1.0   15.76
                  6    BAL            1.0   20.70
                  7    CLE            1.0   23.60
                  8    MIN            0.0   22.50
                  17   CHI            1.0   22.22
 Alex Smith       1    JAX            1.0   17.42
                  2    DAL            1.0   22.62
                  4    NYG            1.0   25.22
                  7    HOU            0.0   18.00
                  8    CLE            1.0   21.00
                  11   DEN            1.0   22.40
                  12   LAC            1.0   22.46
                  13   DEN            1.0   23.32
                  15   OAK            1.0   32.18
 Andrew Luck      1    OAK            0.0   24.92
                  2    MIA            0.0   22.64
                  3    SF             1.0   14.76
                  4    JAX            1.0   19.88
                  5    SEA            0.0   19.06
                  7    DEN            1.0   30.02
                  9    HOU            0.0   24.84
                  10   LAR            0.0   20.82
                  11   TEN            1.0   18.38
                  14   CIN            0.0   35.24
                  15   HOU            0.0   17.10
                  17   JAX            0.0   15.98
 Andy Dalton      1    CHI            1.0   17.48
                  2    PIT            0.0   16.20
 ...                                  ...     ...
 Ryan Tannehill   15   NE             1.0   27.38
 Sam Bradford     1    ARI            1.0   21.06
                  2    ATL            0.0   30.58
                  5    JAX            1.0   21.28
                  6    HOU            0.0   17.08
 Scott Tolzien    10   PHI            1.0   15.10
 Tarvaris Jackson 3    JAX            0.0   15.36
 Thaddeus Lewis   6    CIN            0.0   23.34
 Tom Brady        1    BUF            0.0   17.12
                  3    TB             0.0   16.50
                  4    ATL            0.0   23.44
                  6    NO             0.0   15.36
                  9    PIT            0.0   36.18
                  11   CAR            1.0   15.14
                  12   DEN            0.0   27.76
                  13   HOU            0.0   24.84
                  14   CLE            0.0   27.82
                  15   MIA            1.0   24.56
 Tony Romo        1    NYG            0.0   17.42
                  2    KC             1.0   15.22
                  3    LAR            0.0   20.40
                  4    LAC            1.0   19.34
                  5    DEN            0.0   44.94
                  7    PHI            1.0   17.88
                  8    DET            0.0   20.84
                  9    MIN            0.0   24.28
                  12   NYG            0.0   16.46
                  14   CHI            1.0   16.06
                  15   GB             0.0   23.32
                  16   WAS            1.0   15.94

 [300 rows x 9 columns],
 'player_2014':                                  games  att  comp%  yds  td  def_rk h/a_1  \
 Name              Week Opponent
 Aaron Rodgers     2    NYJ          24   42   59.5  346   3      18   1.0
                   4    CHI          25   28   78.6  302   4      10   1.0
                   5    MIN          26   17   70.6  156   3      32   1.0
                   6    MIA          27   42   57.1  264   3       7   0.0
                   7    CAR          28   22   86.4  255   3       2   1.0
                   8    NO           29   39   71.8  418   1       4   0.0
                   10   CHI          30   27   66.7  315   6      10   1.0
                   11   PHI          31   36   61.1  341   3      30   1.0
                   12   MIN          32   29   65.5  209   2      32   1.0
                   13   NE           33   38   63.2  368   2      20   1.0
                   14   ATL          34   36   66.7  327   3      28   1.0
                   16   TB           35   40   77.5  318   1      26   1.0
                   17   DET          36   22   77.3  226   2      15   1.0
 Alex Smith        3    MIA          26   25   76.0  186   3       7   0.0
                   4    NE           27   26   76.9  248   3      20   1.0
                   7    LAC          28   28   67.9  221   1      23   0.0
                   9    NYJ          29   31   67.7  199   2      18   1.0
                   10   BUF          30   29   58.6  177   0       8   0.0
                   12   OAK          31   36   55.6  234   2      29   1.0
                   14   ARI          32   39   66.7  293   1      22   0.0
                   15   OAK          33   30   60.0  297   2      29   1.0
                   16   PIT          34   45   68.9  311   0       9   1.0
 Andrew Luck       1    DEN          29   53   66.0  370   2      25   1.0
                   2    PHI          30   34   58.8  172   3      30   1.0
                   3    JAX          31   39   79.5  370   4      27   0.0
                   4    TEN          32   41   70.7  393   4       3   1.0
                   5    BAL          33   49   65.3  312   1      13   1.0
                   6    HOU          34   44   56.8  370   3      12   0.0
                   7    CIN          35   42   64.3  344   2       6   1.0
                   8    PIT          36   45   57.8  400   3       9   1.0
 ...                                ...  ...    ...  ...  ..     ...   ...
 Teddy Bridgewater 4    ATL           1   30   63.3  317   0      28   1.0
                   9    WAS           2   42   61.9  268   1      21   1.0
                   12   GB            3   37   56.8  210   2      24   1.0
                   14   NYJ           4   27   70.4  309   2      18   1.0
                   15   DET           5   41   75.6  315   1      15   1.0
                   16   MIA           6   26   73.1  259   2       7   0.0
 Tom Brady         5    CIN          27   35   65.7  292   2       6   1.0
                   6    BUF          28   37   73.0  361   4       8   1.0
                   7    NYJ          29   37   54.1  261   3      18   1.0
                   8    CHI          30   35   85.7  354   5      10   1.0
                   9    DEN          31   53   62.3  333   4      25   1.0
                   11   IND          32   30   63.3  257   2      19   0.0
                   12   DET          33   53   71.7  349   2      15   1.0
                   13   GB           34   35   62.9  245   2      24   0.0
                   14   LAC          35   44   63.6  317   2      23   1.0
                   15   MIA          36   35   60.0  287   2       7   1.0
 Tony Romo         3    LAR          29   23   78.3  217   2      14   1.0
                   4    NO           30   29   75.9  262   3       4   1.0
                   5    HOU          31   41   68.3  324   2      12   1.0
                   6    SEA          32   32   65.6  250   2       1   1.0
                   7    NYG          33   23   73.9  279   3      11   1.0
                   10   JAX          34   27   74.1  246   3      27   0.0
                   12   NYG          35   26   69.2  275   4      11   0.0
                   14   CHI          36   26   80.8  205   3      10   0.0
                   15   PHI          37   31   71.0  265   3      30   1.0
                   16   IND          38   20   90.0  218   4      19   1.0
                   17   WAS          39   34   64.7  299   2      21   1.0
 Zach Mettenberger 8    HOU           1   41   65.9  299   2      12   1.0
                   11   PIT           2   24   62.5  263   2       9   1.0
                   12   PHI           3   39   51.3  345   2      30   1.0

                                 surface_0  points

In [30]:
def drop_col (grouped_df):
    for group in grouped_df:
        grouped_df[group].drop('h/a_1', axis=1, inplace=True)
        grouped_df[group].drop('surface_0',axis=1, inplace=True)
        grouped_df[group].drop('points',axis=1, inplace=True)
    return grouped_df

In [31]:
qb_group= drop_col(qb_group)

In [32]:
qb_group['player_2015'].columns

Index(['games', 'att', 'comp%', 'yds', 'td', 'def_rk'], dtype='object')

In [35]:
rb_group['player_2015'].isnull().sum()

games      0
att        0
yds        0
td         0
tar        0
rec_yds    0
def_rk     0
dtype: int64

## Current Stats
Weekly moving average for every year from 2015 through 2018

In [85]:
# Week 1 stats are player's career average through 2014 season
# Populate current dataframe with current year averages of players

def insert_data (grouped_df):
    new_df = pd.DataFrame(index=grouped_df.index)
    for col in grouped_df: # Iterate through every attribute in the team_stats dataframe
        points=[]  # Create an empty list to hold the season average of the current attribute

        for player in grouped_df.index.levels[0]:  # Iterate through every player in the team_stats df
            total =[]# create an empty list to hold the weekly attributes valu3

            for week in grouped_df.loc[player].index: # Iterate throough every week for the current player
                total.append(grouped_df.loc[player].loc[week][col]) # Add player's value for the current week's attribute to the total list
                points.append(round(np.mean(total),2))  # Add the average of the total list to the season average list

        new_df['{}_avg'.format(col.lower())] = points # Insert season average list for current attribute into the current stats dataframe
    return new_df

In [187]:
weekly_2012 = insert_data(qb_group['player_2012'])
weekly_2013 = insert_data(qb_group['player_2013'])
weekly_2014 = insert_data(qb_group['player_2014'])
weekly_2015 = insert_data(qb_group['player_2015'])
weekly_2016 = insert_data(qb_group['player_2016'])
weekly_2017 = insert_data(qb_group['player_2017'])
weekly_2018 = insert_data(qb_group['player_2018'])

In [183]:
weekly_2018.head()

                             games_avg  att_avg  comp%_avg  yds_avg  td_avg  \
Name          Week Opponent
Aaron Rodgers 1    CHI           70.00    30.00      66.70   286.00    3.00
              2    MIN           71.50    36.00      69.05   283.50    2.00
              3    WAS           71.33    38.67      66.50   277.33    2.00
              4    BUF           71.50    39.00      63.63   282.50    1.75
              5    DET           70.80    41.60      63.20   314.40    2.00

                             def_rk_avg
Name          Week Opponent
Aaron Rodgers 1    CHI            16.00
              2    MIN            20.00
              3    WAS            19.67
              4    BUF            15.50
              5    DET            14.80

In [186]:
def shift_dict(df):

    shift_dict = {}
    df.reset_index(inplace=True)
    for player in df['Name'].unique():
        shift_dict[player]=df[df['Name']==player].shift(1).fillna(0)
    df_shifted = pd.concat(shift_dict)
    df_shifted.drop('Name', axis=1, inplace=True)
    df_shifted['Week'] = df_shifted['Week'] + 1
    
    
    
    return df_shifted

In [188]:
player_2012_shifted = shift_dict(weekly_2012)
player_2013_shifted = shift_dict(weekly_2013)
player_2014_shifted = shift_dict(weekly_2014)
player_2015_shifted = shift_dict(weekly_2015)
player_2016_shifted = shift_dict(weekly_2016)
player_2017_shifted = shift_dict(weekly_2017)
player_2018_shifted = shift_dict(weekly_2018)

In [206]:
player_2012_shifted['year']=2012
player_2013_shifted['year']=2013
player_2014_shifted['year']=2014
player_2015_shifted['year']=2015
player_2016_shifted['year']=2016
player_2017_shifted['year']=2017
player_2018_shifted['year']=2018

In [215]:
player_weekly_avg = pd.concat([player_2012_shifted,player_2013_shifted, player_2014_shifted,player_2015_shifted, player_2016_shifted, player_2017_shifted, player_2018_shifted])

player_weekly_avg.head()

                 Week Opponent  games_avg  att_avg  comp%_avg  yds_avg  \
Aaron Rodgers 0   1.0        0        0.0     0.00        0.0     0.00
              1   2.0       SF        1.0    44.00       68.0   303.00
              2   3.0      CHI        1.5    38.00       68.5   261.00
              3   4.0      SEA        2.0    38.33       68.0   248.33
              4   5.0       NO        2.5    39.00       70.0   266.00

                 td_avg  def_rk_avg  year
Aaron Rodgers 0    0.00        0.00  2012
              1    2.00        5.00  2012
              2    1.50       18.00  2012
              3    1.00       12.33  2012
              4    1.75       16.50  2012

In [191]:
player_weekly_avg.reset_index(inplace=True)

In [192]:
player_weekly_avg.sort_values(['level_0','games_avg'], inplace=True)

In [194]:
player_weekly_avg.drop(['level_0','level_1','Week','Opponent','games_avg'],axis=1, inplace=True)
player_weekly_avg.shape

(2354, 5)

In [ ]:
temp_week = player_weekly_avg.set_index()

## Recent Player Stats
Calculate the 4 game moving average of all attributes for each player and insert resluts into positional dataframe

In [45]:
# A function designed to calcuate a player's 4 game moving average in seasons 2015,2016,2017,2018

def moving_average(grouped_df, games):
    new_grouped_df = pd.DataFrame(index = grouped_df.index)
    for col in grouped_df:  # Iterate through every attribute in the team_stats dataframe
        ma4 = []  # Create an empty list to hold the season average of the current attribute
        for player in grouped_df.index.levels[0]:  # Iterate through every player in the team_stats df
            total = [] # INstantiate a deque container with a max length of 3 to hold the three most current games for player
            count = 0 # Counter to track week number 
            for week in grouped_df.loc[player].index: # Iterate through every week for relevant player d
                if count < games: # check count value to start 3 game moving average
                    ma4.append(0)  # week 1 through 3 have 3 game movong average of 0
                    total.append(grouped_df.loc[player].loc[week][col])  # Add the value current player's attribute total from the left
                    count += 1  # Increase count
                else:  # Once 3 game moving average is avaliable
                    ma4.append(np.mean(total))  # Add the average of the 3 games held in totals 3 game moivng average list
                    total.append(grouped_df.loc[player].loc[week][col]) # Replace 3 set block with a first in first out process
        new_grouped_df['{}_ma'.format(col.lower())] = ma4  # Populate databse with 3 game moving average list
       

    return new_grouped_df

In [211]:
player_ma_2012 = moving_average(qb_group['player_2012'],4)
player_ma_2013 = moving_average(qb_group['player_2013'],4)
player_ma_2014 = moving_average(qb_group['player_2014'],4)
player_ma_2015 = moving_average(qb_group['player_2015'],4)
player_ma_2016 = moving_average(qb_group['player_2016'],4)
player_ma_2017 = moving_average(qb_group['player_2017'],4)
player_ma_2018 = moving_average(qb_group['player_2018'],4)

In [212]:
yearly_ma_grp = pd.concat([player_ma_2012, player_ma_2013])
yearly_ma_grp = pd.concat([yearly_ma_grp, player_ma_2014])
yearly_ma_grp = pd.concat([yearly_ma_grp, player_ma_2015])
yearly_ma_grp = pd.concat([yearly_ma_grp, player_ma_2016])
yearly_ma_grp = pd.concat([yearly_ma_grp,player_ma_2017])
yearly_ma_grp = pd.concat([yearly_ma_grp,player_ma_2018])
yearly_ma_grp.head()

                             games_ma  att_ma  comp%_ma  yds_ma  td_ma  \
Name          Week Opponent
Aaron Rodgers 1    SF             0.0     0.0       0.0     0.0   0.00
              2    CHI            0.0     0.0       0.0     0.0   0.00
              3    SEA            0.0     0.0       0.0     0.0   0.00
              4    NO             0.0     0.0       0.0     0.0   0.00
              5    IND            2.5    39.0      70.0   266.0   1.75

                             def_rk_ma
Name          Week Opponent
Aaron Rodgers 1    SF              0.0
              2    CHI             0.0
              3    SEA             0.0
              4    NO              0.0
              5    IND            16.5

In [217]:
aaron  = pd.concat([player_weekly_avg.loc['Aaron Rodgers'].reset_index(),yearly_ma_grp.loc['Aaron Rodgers'].reset_index()], axis=1)
aaron

,index,Week,Opponent,games_avg,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,year,Week,Opponent,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma
0,0,1.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2012,1,SF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1,2.0,SF,1.00,44.00,68.00,303.00,2.00,5.00,2012,2,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2,3.0,CHI,1.50,38.00,68.50,261.00,1.50,18.00,2012,3,SEA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,3,4.0,SEA,2.00,38.33,68.00,248.33,1.00,12.33,2012,4,NO,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,4,5.0,NO,2.50,39.00,70.00,266.00,1.75,16.50,2012,5,IND,2.500000,39.000000,70.000000,266.000000,1.750000,16.500000
5,5,6.0,IND,3.00,37.60,68.60,259.80,2.00,15.80,2012,6,HOU,3.000000,37.600000,68.600000,259.800000,2.000000,15.800000
6,6,7.0,HOU,3.50,37.50,68.00,272.83,2.67,14.83,2012,7,LAR,3.500000,37.500000,68.000000,272.833333,2.666667,14.833333
7,7,8.0,LAR,4.00,37.43,69.86,282.71,2.71,14.29,2012,8,JAX,4.000000,37.428571,69.857143,282.714286,2.714286,14.285714
8,8,9.0,JAX,4.50,37.12,69.00,270.62,2.62,14.25,2012,9,ARI,4.500000,37.125000,69.000000,270.625000,2.625000,14.250000
9,9,10.0,ARI,5.00,36.33,66.56,264.78,2.78,15.22,2012,11,DET,5.000000,36.333333,66.555556,264.777778,2.777778,15.222222
10,10,12.0,DET,5.50,35.40,66.90,261.90,2.70,14.40,2012,12,NYG,5.500000,35.400000,66.900000,261.900000,2.700000,14.400000
11,11,13.0,NYG,6.00,34.45,65.91,258.00,2.55,15.55,2012,13,MIN,6.000000,34.454545,65.909091,258.000000,2.545455,15.545455
12,12,14.0,MIN,6.50,34.50,66.83,260.33,2.42,15.00,2012,14,DET,6.500000,34.500000,66.833333,260.333333,2.416667,15.000000
13,13,15.0,DET,7.00,33.69,66.15,253.62,2.23,14.38,2012,15,CHI,7.000000,33.692308,66.153846,253.615385,2.230769,14.384615
14,14,16.0,CHI,7.50,33.86,66.00,256.29,2.29,15.57,2012,16,TEN,7.500000,33.857143,66.000000,256.285714,2.285714,15.571429
15,15,17.0,TEN,8.00,34.13,66.33,262.00,2.33,15.73,2012,17,MIN,8.000000,34.133333,66.333333,262.000000,2.333333,15.733333
16,0,1.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2013,1,SF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,1,2.0,SF,18.00,37.00,56.80,333.00,3.00,8.00,2013,2,WAS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,2,3.0,WAS,17.50,39.50,68.90,406.50,3.50,18.50,2013,5,DET,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,3,6.0,DET,19.33,36.33,68.17,362.33,2.67,19.00,2013,6,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,4,7.0,BAL,20.00,35.25,64.40,350.50,2.25,16.50,2013,7,CLE,20.000000,35.250000,64.400000,350.500000,2.250000,16.500000
21,5,8.0,CLE,19.80,35.40,65.40,332.40,2.40,17.80,2013,8,MIN,19.800000,35.400000,65.400000,332.400000,2.400000,17.800000
22,6,9.0,MIN,19.83,34.33,68.30,324.50,2.33,19.83,2013,17,CHI,19.833333,34.333333,68.300000,324.500000,2.333333,19.833333
23,0,1.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2014,2,NYJ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,1,3.0,NYJ,24.00,42.00,59.50,346.00,3.00,18.00,2014,4,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,2,5.0,CHI,24.50,35.00,69.05,324.00,3.50,14.00,2014,5,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,3,6.0,MIN,25.00,29.00,69.57,268.00,3.33,20.00,2014,6,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,4,7.0,MIA,25.50,32.25,66.45,267.00,3.25,16.75,2014,7,CAR,25.500000,32.250000,66.450000,267.000000,3.250000,16.750000
28,5,8.0,CAR,26.00,30.20,70.44,264.60,3.20,13.80,2014,8,NO,26.000000,30.200000,70.440000,264.600000,3.200000,13.800000
29,6,9.0,NO,26.50,31.67,70.67,290.17,2.83,12.17,2014,10,CHI,26.500000,31.666667,70.666667,290.166667,2.833333,12.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,8,10.0,CAR,42.00,32.86,66.01,265.71,2.71,11.57,2015,10,DET,42.000000,32.857143,66.014286,265.714286,2.714286,11.571429
44,9,11.0,DET,41.75,36.38,64.94,274.12,2.62,13.00,2015,11,MIN,41.750000,36.375000,64.937500,274.125000,2.625000,13.000000
45,10,12.0,MIN,42.11,36.11,62.96,267.22,2.56,12.78,2015,13,DET,42.111111,36.111111,62.955556,267.222222,2.555556,12.777778
46,11,14.0,DET,41.80,36.10,63.33,267.80,2.50,13.80,2015,14,DAL,41.800000,36.100000,63.330000,267.800000,2.500000,13.800000
47,0,1.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2016,1,JAX,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,1,2.0,JAX,57.00,34.00,58.80,199.00,2.00,5.00,2016,2,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
49,2,3.0,MIN,58.00,35.00,57.20,206.00,1.50,5.50,2016,3,DET,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50,3,4.0,DET,57.00,31.33,58.97,205.67,2.33,14.00,2016,5,NYG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
51,4,6.0,NYG,57.75,34.75,57.00,219.00,2.25,11.00,2016,7,CHI,57.750000,34.750000,57.000000,219.000000,2.250000,11.000000
52,5,8.0,CHI,56.80,39.00,59.52,240.40,2.40,11.80,2016,8,ATL,56.800000,39.000000,59.520000,240.400000,2.400000,11.800000
53,6,9.0,ATL,55.67,38.83,61.88,241.33,2.67,14.83,2016,9,IND,55.666667,38.833333,61.883333,241.333333,2.666667,14.833333
54,7,10.0,IND,55.43,39.43,61.69,249.29,2.71,16.14,2016,10,TEN,55.428571,39.428571,61.685714,249.285714,2.714286,16.142857
55,8,11.0,TEN,54.88,40.88,61.58,264.50,2.62,17.75,2016,11,WAS,54.875000,40.875000,61.575000,264.500000,2.625000,17.750000
56,9,12.0,WAS,54.56,40.89,61.78,274.11,2.67,18.22,2016,12,PHI,54.555556,40.888889,61.777778,274.111111,2.666667,18.222222
57,10,13.0,PHI,54.70,40.70,63.29,278.00,2.60,17.40,2016,13,HOU,54.700000,40.700000,63.290000,278.000000,2.600000,17.400000
58,11,14.0,HOU,55.27,39.73,63.60,271.73,2.55,16.09,2016,14,SEA,55.272727,39.727273,63.600000,271.727273,2.545455,16.090909
59,12,15.0,SEA,55.50,38.33,64.82,269.58,2.58,15.08,2016,16,MIN,55.500000,38.333333,64.825000,269.583333,2.583333,15.083333
60,13,17.0,MIN,54.92,38.31,65.51,275.54,2.69,14.38,2016,17,DET,54.923077,38.307692,65.507692,275.538462,2.692308,14.384615
61,0,1.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2017,1,SEA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
62,1,2.0,SEA,67.00,42.00,66.70,311.00,1.00,7.00,2017,2,ATL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
63,2,3.0,ATL,66.00,46.00,66.35,327.00,1.50,12.00,2017,3,CIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
64,3,4.0,CIN,64.67,44.67,66.47,322.33,2.00,11.67,2017,4,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
65,4,5.0,CHI,65.00,40.00,67.15,286.50,2.50,10.00,2017,5,DAL,65.000000,40.000000,67.150000,286.500000,2.500000,10.000000
66,5,6.0,DAL,64.80,37.80,66.82,273.40,2.60,11.20,2017,15,CAR,64.800000,37.800000,66.820000,273.400000,2.600000,11.200000
67,0,1.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2018,1,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
68,1,2.0,CHI,70.00,30.00,66.70,286.00,3.00,16.00,2018,2,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
69,2,3.0,MIN,71.50,36.00,69.05,283.50,2.00,20.00,2018,3,WAS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
70,3,4.0,WAS,71.33,38.67,66.50,277.33,2.00,19.67,2018,4,BUF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
71,4,5.0,BUF,71.50,39.00,63.63,282.50,1.75,15.50,2018,5,DET,71.500000,39.000000,63.625000,282.500000,1.750000,15.500000
72,5,6.0,DET,70.80,41.60,63.20,314.40,2.00,14.80,2018,6,SF,70.800000,41.600000,63.200000,314.400000,2.000000,14.800000

In [197]:
yearly_ma_grp.reset_index(inplace=True)
yearly_ma_grp.head()

,Name,Week,Opponent,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma
0,Aaron Rodgers,1,SF,0.0,0.0,0.0,0.0,0.00,0.0
1,Aaron Rodgers,2,CHI,0.0,0.0,0.0,0.0,0.00,0.0
2,Aaron Rodgers,3,SEA,0.0,0.0,0.0,0.0,0.00,0.0
3,Aaron Rodgers,4,NO,0.0,0.0,0.0,0.0,0.00,0.0
4,Aaron Rodgers,5,IND,2.5,39.0,70.0,266.0,1.75,16.5

In [205]:
yearly_ma_grp.sort_values(['Name','year','Week'],inplace=True)
yearly_ma_grp

KeyError: 'year'

In [202]:
yearly_ma_grp.reset_index(drop=True)

,Name,Week,Opponent,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma
0,AJ McCarron,14,PIT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Aaron Rodgers,1,SF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Aaron Rodgers,2,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Aaron Rodgers,3,SEA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Aaron Rodgers,4,NO,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,Aaron Rodgers,1,SF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Aaron Rodgers,2,WAS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Aaron Rodgers,5,DET,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,Aaron Rodgers,6,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,Aaron Rodgers,2,NYJ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,Aaron Rodgers,4,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,Aaron Rodgers,5,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,Aaron Rodgers,6,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
13,Aaron Rodgers,1,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,Aaron Rodgers,2,SEA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,Aaron Rodgers,3,KC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,Aaron Rodgers,4,SF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,Aaron Rodgers,1,JAX,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,Aaron Rodgers,2,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,Aaron Rodgers,3,DET,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,Aaron Rodgers,5,NYG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,Aaron Rodgers,1,SEA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,Aaron Rodgers,2,ATL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,Aaron Rodgers,3,CIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,Aaron Rodgers,4,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,Aaron Rodgers,1,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,Aaron Rodgers,2,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
27,Aaron Rodgers,3,WAS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,Aaron Rodgers,4,BUF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,Aaron Rodgers,5,IND,2.500000,39.000000,70.000000,266.000000,1.750000,16.500000
...,...,...,...,...,...,...,...,...,...
2324,Tyrod Taylor,5,LAR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2325,Tyrod Taylor,1,NYJ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2326,Tyrod Taylor,3,DEN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2327,Tyrod Taylor,7,TB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2328,Tyrod Taylor,8,OAK,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2329,Tyrod Taylor,1,PIT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2330,Tyrod Taylor,2,NO,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2331,Tyrod Taylor,3,NYJ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2332,Tyrod Taylor,10,OAK,2.500000,0.750000,16.750000,7.500000,0.000000,4.750000
2333,Tyrod Taylor,17,CIN,3.000000,0.800000,13.400000,6.000000,0.000000,7.800000
2334,Tyrod Taylor,14,PHI,9.600000,27.000000,63.120000,226.000000,2.600000,14.600000
2335,Tyrod Taylor,17,NYJ,10.000000,28.285714,61.100000,233.285714,2.285714,17.714286
2336,Tyrod Taylor,15,WAS,10.166667,28.500000,61.400000,233.000000,2.333333,17.166667
2337,Tyrod Taylor,13,HOU,10.250000,28.500000,65.800000,229.750000,2.500000,17.250000
2338,Tyrod Taylor,14,PIT,20.222222,29.444444,60.066667,202.666667,1.222222,14.111111
2339,Tyrod Taylor,12,JAX,20.250000,30.875000,59.237500,207.250000,1.250000,15.250000
2340,Tyrod Taylor,15,CLE,20.600000,29.000000,60.060000,205.200000,1.300000,13.400000
2341,Tyrod Taylor,8,NE,20.833333,28.500000,58.800000,197.666667,1.500000,18.166667
2342,Tyrod Taylor,9,SEA,20.857143,29.857143,57.542857,195.571429,1.285714,16.857143
2343,Tyrod Taylor,16,MIA,21.000000,28.545455,61.036364,202.363636,1.272727,15.090909
2344,Tyrod Taylor,7,MIA,21.400000,28.600000,60.560000,193.000000,1.600000,16.200000
2345,Tyrod Taylor,6,SF,22.000000,29.250000,59.350000,196.500000,1.500000,15.250000
2346,Tyrod Taylor,17,MIA,30.000000,29.714286,65.685714,219.571429,1.428571,19.142857
2347,Tyrod Taylor,11,LAC,30.200000,30.800000,68.240000,231.000000,1.600000,22.400000
2348,Tyrod Taylor,15,MIA,30.333333,29.833333,66.866667,218.833333,1.500000,19.333333
2349,Tyrod Taylor,9,NYJ,31.000000,28.500000,67.175000,217.500000,1.500000,21.000000
2350,Zach Mettenberger,8,HOU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2351,Zach Mettenberger,11,PIT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2352,Zach Mettenberger,12,PHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2353,Zach Mettenberger,15,NE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [175]:
player_weekly_avg.shape, yearly_ma_grp.shape

((2354, 5), (2354, 9))

In [309]:
yearly_ma.to_csv('input/qb_yearly_ma.csv', index=True)

In [199]:
qb_stats= pd.concat([player_weekly_avg, yearly_ma_grp], axis=1)
qb_stats.head()

,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,Name,Week,Opponent,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma
0,0.00,0.0,0.00,0.00,0.00,Aaron Rodgers,1,SF,0.0,0.0,0.0,0.0,0.00,0.0
1,44.00,68.0,303.00,2.00,5.00,Aaron Rodgers,2,CHI,0.0,0.0,0.0,0.0,0.00,0.0
2,38.00,68.5,261.00,1.50,18.00,Aaron Rodgers,3,SEA,0.0,0.0,0.0,0.0,0.00,0.0
3,38.33,68.0,248.33,1.00,12.33,Aaron Rodgers,4,NO,0.0,0.0,0.0,0.0,0.00,0.0
4,39.00,70.0,266.00,1.75,16.50,Aaron Rodgers,5,IND,2.5,39.0,70.0,266.0,1.75,16.5

In [200]:
qb_stats[qb_stats['Name']=='AJ McCarron']

,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,Name,Week,Opponent,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma
1229,0.0,0.0,0.0,0.0,0.0,AJ McCarron,14,PIT,0.0,0.0,0.0,0.0,0.0,0.0

In [142]:
cols = temp.columns.tolist()
cols = cols[5:8] +cols[:5] +cols[8:]
temp = temp[cols]
temp.columns

Index(['Name', 'Week', 'Opponent', 'att_avg', 'comp%_avg', 'yds_avg', 'td_avg',
       'def_rk_avg', 'games_ma', 'att_ma', 'comp%_ma', 'yds_ma', 'td_ma',
       'def_rk_ma'],
      dtype='object')

In [143]:
temp.isnull().sum()

Name          0
Week          0
Opponent      0
att_avg       0
comp%_avg     0
yds_avg       0
td_avg        0
def_rk_avg    0
games_ma      0
att_ma        0
comp%_ma      0
yds_ma        0
td_ma         0
def_rk_ma     0
dtype: int64

In [144]:
qb_stats = temp
qb_stats.isnull().sum()

Name          0
Week          0
Opponent      0
att_avg       0
comp%_avg     0
yds_avg       0
td_avg        0
def_rk_avg    0
games_ma      0
att_ma        0
comp%_ma      0
yds_ma        0
td_ma         0
def_rk_ma     0
dtype: int64

In [145]:
qb_stats.sort_values(['Name','games_ma'], inplace=True)
qb_stats

,Name,Week,Opponent,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma
1229,AJ McCarron,14,PIT,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
0,Aaron Rodgers,1,SF,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,Aaron Rodgers,2,CHI,44.00,68.00,303.00,2.00,5.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Aaron Rodgers,3,SEA,38.00,68.50,261.00,1.50,18.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Aaron Rodgers,4,NO,38.33,68.00,248.33,1.00,12.33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
629,Aaron Rodgers,1,SF,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
630,Aaron Rodgers,2,WAS,37.00,56.80,333.00,3.00,8.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
631,Aaron Rodgers,5,DET,39.50,68.90,406.50,3.50,18.50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
632,Aaron Rodgers,6,BAL,36.33,68.17,362.33,2.67,19.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
929,Aaron Rodgers,2,NYJ,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
930,Aaron Rodgers,4,CHI,42.00,59.50,346.00,3.00,18.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
931,Aaron Rodgers,5,MIN,35.00,69.05,324.00,3.50,14.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
932,Aaron Rodgers,6,MIA,29.00,69.57,268.00,3.33,20.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1230,Aaron Rodgers,1,CHI,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1231,Aaron Rodgers,2,SEA,23.00,78.30,189.00,3.00,25.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1232,Aaron Rodgers,3,KC,28.00,77.05,219.00,2.50,13.50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1233,Aaron Rodgers,4,SF,30.33,74.23,257.00,3.33,12.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1529,Aaron Rodgers,1,JAX,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1530,Aaron Rodgers,2,MIN,34.00,58.80,199.00,2.00,5.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1531,Aaron Rodgers,3,DET,35.00,57.20,206.00,1.50,5.50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1532,Aaron Rodgers,5,NYG,31.33,58.97,205.67,2.33,14.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1829,Aaron Rodgers,1,SEA,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1830,Aaron Rodgers,2,ATL,42.00,66.70,311.00,1.00,7.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1831,Aaron Rodgers,3,CIN,46.00,66.35,327.00,1.50,12.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1832,Aaron Rodgers,4,CHI,44.67,66.47,322.33,2.00,11.67,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2129,Aaron Rodgers,1,CHI,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2130,Aaron Rodgers,2,MIN,30.00,66.70,286.00,3.00,16.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2131,Aaron Rodgers,3,WAS,36.00,69.05,283.50,2.00,20.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2132,Aaron Rodgers,4,BUF,38.67,66.50,277.33,2.00,19.67,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Aaron Rodgers,5,IND,39.00,70.00,266.00,1.75,16.50,2.500000,39.000000,70.000000,266.000000,1.750000,16.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1820,Tyrod Taylor,5,LAR,31.33,61.73,220.67,1.33,13.33,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2121,Tyrod Taylor,1,NYJ,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2122,Tyrod Taylor,3,DEN,28.00,57.10,224.00,2.00,28.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2123,Tyrod Taylor,7,TB,27.00,67.00,218.50,2.00,19.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2124,Tyrod Taylor,8,OAK,29.00,64.87,235.00,1.67,20.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2351,Tyrod Taylor,1,PIT,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2352,Tyrod Taylor,2,NO,40.00,37.50,197.00,1.00,28.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2353,Tyrod Taylor,3,NYJ,35.00,55.40,221.50,1.00,29.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
627,Tyrod Taylor,10,OAK,0.75,16.75,7.50,0.00,4.75,2.500000,0.750000,16.750000,7.500000,0.000000,4.750000
628,Tyrod Taylor,17,CIN,0.80,13.40,6.00,0.00,7.80,3.000000,0.800000,13.400000,6.000000,0.000000,7.800000
1525,Tyrod Taylor,14,PHI,27.00,63.12,226.00,2.60,14.60,9.600000,27.000000,63.120000,226.000000,2.600000,14.600000
1527,Tyrod Taylor,17,NYJ,28.29,61.10,233.29,2.29,17.71,10.000000,28.285714,61.100000,233.285714,2.285714,17.714286
1526,Tyrod Taylor,15,WAS,28.50,61.40,233.00,2.33,17.17,10.166667,28.500000,61.400000,233.000000,2.333333,17.166667
1524,Tyrod Taylor,13,HOU,28.50,65.80,229.75,2.50,17.25,10.250000,28.500000,65.800000,229.750000,2.500000,17.250000
1826,Tyrod Taylor,14,PIT,29.44,60.07,202.67,1.22,14.11,20.222222,29.444444,60.066667,202.666667,1.222222,14.111111
1825,Tyrod Taylor,12,JAX,30.88,59.24,207.25,1.25,15.25,20.250000,30.875000,59.237500,207.250000,1.250000,15.250000
1827,Tyrod Taylor,15,CLE,29.00,60.06,205.20,1.30,13.40,20.600000,29.000000,60.060000,205.200000,1.300000,13.400000
1823,Tyrod Taylor,8,NE,28.50,58.80,197.67,1.50,18.17,20.833333,28.500000,58.800000,197.666667,1.500000,18.166667
1824,Tyrod Taylor,9,SEA,29.86,57.54,195.57,1.29,16.86,20.857143,29.857143,57.542857,195.571429,1.285714,16.857143
1828,Tyrod Taylor,16,MIA,28.55,61.04,202.36,1.27,15.09,21.000000,28.545455,61.036364,202.363636,1.272727,15.090909
1822,Tyrod Taylor,7,MIA,28.60,60.56,193.00,1.60,16.20,21.400000,28.600000,60.560000,193.000000,1.600000,16.200000
1821,Tyrod Taylor,6,SF,29.25,59.35,196.50,1.50,15.25,22.000000,29.250000,59.350000,196.500000,1.500000,15.250000
2128,Tyrod Taylor,17,MIA,29.71,65.69,219.57,1.43,19.14,30.000000,29.714286,65.685714,219.571429,1.428571,19.142857
2126,Tyrod Taylor,11,LAC,30.80,68.24,231.00,1.60,22.40,30.200000,30.800000,68.240000,231.000000,1.600000,22.400000
2127,Tyrod Taylor,15,MIA,29.83,66.87,218.83,1.50,19.33,30.333333,29.833333,66.866667,218.833333,1.500000,19.333333
2125,Tyrod Taylor,9,NYJ,28.50,67.18,217.50,1.50,21.00,31.000000,28.500000,67.175000,217.500000,1.500000,21.000000
1226,Zach Mettenberger,8,HOU,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1227,Zach Mettenberger,11,PIT,41.00,65.90,299.00,2.00,12.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1228,Zach Mettenberger,12,PHI,32.50,64.20,281.00,2.00,10.50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1528,Zach Mettenberger,15,NE,0.00,0.00,0.00,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

## Career Average

In [110]:
# Week 1 stats are player's career average through 2014 season
# Populate current dataframe with current year averages of players

def career_average (grouped_df1, grouped_df2=None):
    new_grouped_df1 = pd.DataFrame(index= grouped_df1.index)
    for col in grouped_df1: # Iterate through every attribute in the team_stats dataframe
        points=[]  # Create an empty list to hold the season average of the current attribute

        try:
            for player in grouped_df1.index.levels[0]:  # Iterate through every player in the team_stats df
                if player in list(grouped_df2.index.levels[0].unique()):
                    total =[grouped_df2.loc[player][col][-1]] # If player not a rookie, use final average from 2015
                else:
                    total =[]  # create an empty list to hold the weekly attributes value
                
                for week in grouped_df1.loc[player].index: # Iterate throough every week for the current player
                    total.append(grouped_df1.loc[player].loc[week][col]) # Add player's value for the current week's attribute to the total list
                    points.append(round(np.mean(total),2))  # Add the average of the total list to the season average list
                    
            new_grouped_df1['{}_car'.format(col.lower())] = points # Insert season average list for current attribute into the current stats dataframe


                                
        except:
            for player in grouped_df1.index.levels[0]:  # Iterate through every player in the team_stats df
                total = []

                for week in grouped_df1.loc[player].index: # Iterate throough every week for the current player
                    total.append(grouped_df1.loc[player].loc[week][col]) # Add player's value for the current week's attribute to the total list
                    points.append(round(np.mean(total),2))  # Add the average of the total list to the season average list

            new_grouped_df1['{}_car'.format(col.lower())] = points # Insert season average list for current attribute into the current stats dataframe
    return new_grouped_df1

In [112]:
df_career_2012 = career_average(qb_group['player_2012'])
df_career_2013 = career_average(qb_group['player_2013'], qb_group['player_2012'])
df_career_2014 = career_average(qb_group['player_2014'], qb_group['player_2013'])
df_career_2015 = career_average(qb_group['player_2015'], qb_group['player_2014'])
df_career_2016 = career_average(qb_group['player_2016'],qb_group['player_2015'])
df_career_2017 = career_average(qb_group['player_2017'],qb_group['player_2016'])
df_career_2018 = career_average(qb_group['player_2018'], qb_group['player_2017'])

In [146]:
player_career_grp = pd.concat([df_career_2012, df_career_2013])
player_career_grp = pd.concat([player_career_grp, df_career_2014])
player_career_grp = pd.concat([player_career_grp, df_career_2015])
player_career_grp = pd.concat([player_career_grp, df_career_2016])
player_career_grp = pd.concat([player_career_grp, df_career_2017])
player_career_grp = pd.concat([player_career_grp, df_career_2018])
player_career_grp.head()

                             games_car  att_car  comp%_car  yds_car  td_car  \
Name          Week Opponent
Aaron Rodgers 1    SF              1.0    44.00       68.0   303.00    2.00
              2    CHI             1.5    38.00       68.5   261.00    1.50
              3    SEA             2.0    38.33       68.0   248.33    1.00
              4    NO              2.5    39.00       70.0   266.00    1.75
              5    IND             3.0    37.60       68.6   259.80    2.00

                             def_rk_car
Name          Week Opponent
Aaron Rodgers 1    SF              5.00
              2    CHI            18.00
              3    SEA            12.33
              4    NO             16.50
              5    IND            15.80

In [147]:
career_shifted = shift_dict(player_career_grp)
career_shifted.head()

                    Week Opponent  games_car  att_car  comp%_car  yds_car  \
AJ McCarron   1229   0.0        0        0.0     0.00        0.0     0.00
Aaron Rodgers 0      0.0        0        0.0     0.00        0.0     0.00
              1      1.0       SF        1.0    44.00       68.0   303.00
              2      2.0      CHI        1.5    38.00       68.5   261.00
              3      3.0      SEA        2.0    38.33       68.0   248.33

                    td_car  def_rk_car
AJ McCarron   1229     0.0        0.00
Aaron Rodgers 0        0.0        0.00
              1        2.0        5.00
              2        1.5       18.00
              3        1.0       12.33

In [151]:
#qb_stats.reset_index(inplace=True)
qb_stats.drop('level_0', axis=1, inplace=True)
qb_stats.head()

,Name,Week,Opponent,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma
0,AJ McCarron,14,PIT,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
1,Aaron Rodgers,1,SF,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0
2,Aaron Rodgers,2,CHI,44.00,68.0,303.00,2.0,5.00,0.0,0.0,0.0,0.0,0.0,0.0
3,Aaron Rodgers,3,SEA,38.00,68.5,261.00,1.5,18.00,0.0,0.0,0.0,0.0,0.0,0.0
4,Aaron Rodgers,4,NO,38.33,68.0,248.33,1.0,12.33,0.0,0.0,0.0,0.0,0.0,0.0

In [152]:
career_shifted.reset_index(inplace=True)
career_shifted.head()

,level_0,level_1,Week,Opponent,games_car,att_car,comp%_car,yds_car,td_car,def_rk_car
0,AJ McCarron,1229,0.0,0,0.0,0.00,0.0,0.00,0.0,0.00
1,Aaron Rodgers,0,0.0,0,0.0,0.00,0.0,0.00,0.0,0.00
2,Aaron Rodgers,1,1.0,SF,1.0,44.00,68.0,303.00,2.0,5.00
3,Aaron Rodgers,2,2.0,CHI,1.5,38.00,68.5,261.00,1.5,18.00
4,Aaron Rodgers,3,3.0,SEA,2.0,38.33,68.0,248.33,1.0,12.33

In [153]:
career_shifted = career_shifted.sort_values(['level_0','games_car']).drop(['level_0','level_1','Week','Opponent'], axis=1)
career_shifted.head()

   games_car  att_car  comp%_car  yds_car  td_car  def_rk_car
0        0.0     0.00        0.0     0.00     0.0        0.00
1        0.0     0.00        0.0     0.00     0.0        0.00
2        1.0    44.00       68.0   303.00     2.0        5.00
3        1.5    38.00       68.5   261.00     1.5       18.00
4        2.0    38.33       68.0   248.33     1.0       12.33

In [154]:
qb_stats = pd.concat([qb_stats, career_shifted], axis=1)
qb_stats.isnull().sum()

Name          0
Week          0
Opponent      0
att_avg       0
comp%_avg     0
yds_avg       0
td_avg        0
def_rk_avg    0
games_ma      0
att_ma        0
comp%_ma      0
yds_ma        0
td_ma         0
def_rk_ma     0
games_car     0
att_car       0
comp%_car     0
yds_car       0
td_car        0
def_rk_car    0
dtype: int64

In [155]:
qb_stats.sort_values(['Name','games_ma'], inplace=True)
qb_stats.head()

,Name,Week,Opponent,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma,games_car,att_car,comp%_car,yds_car,td_car,def_rk_car
0,AJ McCarron,14,PIT,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00
1,Aaron Rodgers,1,SF,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.00
2,Aaron Rodgers,2,CHI,44.00,68.0,303.00,2.0,5.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44.00,68.0,303.00,2.0,5.00
3,Aaron Rodgers,3,SEA,38.00,68.5,261.00,1.5,18.00,0.0,0.0,0.0,0.0,0.0,0.0,1.5,38.00,68.5,261.00,1.5,18.00
4,Aaron Rodgers,4,NO,38.33,68.0,248.33,1.0,12.33,0.0,0.0,0.0,0.0,0.0,0.0,2.0,38.33,68.0,248.33,1.0,12.33

In [65]:
#A function that will covert a time series database into a supervised learning database

def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
    n_vars = 1 if type(data) is list else data.shape[1]
    df = pd.DataFrame(data)
    cols, names = list(), list()
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -1):
            cols.append(df.shift(i))
            names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
    # forecast sequence (t, t+1, ... t+n)
    for i in range(0, n_out):
        cols.append(df.shift(-i))
        if i == 0:
            names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
        else:
            names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
    # put it all together
    agg = pd.concat(cols, axis=1)
    agg.columns = names
    # drop rows with NaN values
    if dropnan:
        agg.dropna(inplace=True)
    return agg

In [102]:
temp = rb_stats.groupby(['Name','games_ma']).sum()

In [138]:
qb_stats = qb_stats.set_index('Name')
qb_stats.head()

,Week,Opponent,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma,games_car,att_car,comp%_car,yds_car,td_car,def_rk_car
Name,,,,,,,,,,,,,,,,,,,
AJ McCarron,14,PIT,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,33.0,41.25,62.95,317.0,1.75,16.75
Aaron Rodgers,1,SF,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00
Aaron Rodgers,2,CHI,44.00,68.0,303.00,2.0,5.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.00,0.00
Aaron Rodgers,3,SEA,38.00,68.5,261.00,1.5,18.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,44.00,68.00,303.0,2.00,5.00
Aaron Rodgers,4,NO,38.33,68.0,248.33,1.0,12.33,0.0,0.0,0.0,0.0,0.0,0.0,1.5,38.00,68.50,261.0,1.50,18.00

In [139]:
qb_stats.index

Index(['AJ McCarron', 'Aaron Rodgers', 'Aaron Rodgers', 'Aaron Rodgers',
       'Aaron Rodgers', 'Aaron Rodgers', 'Aaron Rodgers', 'Aaron Rodgers',
       'Aaron Rodgers', 'Aaron Rodgers',
       ...
       'Tyrod Taylor', 'Tyrod Taylor', 'Tyrod Taylor', 'Tyrod Taylor',
       'Tyrod Taylor', 'Tyrod Taylor', 'Zach Mettenberger',
       'Zach Mettenberger', 'Zach Mettenberger', 'Zach Mettenberger'],
      dtype='object', name='Name', length=2354)

In [156]:
reframed_dict = {}
for player in qb_stats['Name'].unique():
    reframed_dict['{}_reframed'.format(player)]= qb_stats[qb_stats['Name']==player]

In [157]:
reframed_dict

{'AJ McCarron_reframed':           Name  Week Opponent  att_avg  comp%_avg  yds_avg  td_avg  \
 0  AJ McCarron    14      PIT      0.0        0.0      0.0     0.0

    def_rk_avg  games_ma  att_ma  comp%_ma  yds_ma  td_ma  def_rk_ma  \
 0         0.0       0.0     0.0       0.0     0.0    0.0        0.0

    games_car  att_car  comp%_car  yds_car  td_car  def_rk_car
 0        0.0      0.0        0.0      0.0     0.0         0.0  ,
 'Aaron Rodgers_reframed':              Name  Week Opponent  att_avg  comp%_avg  yds_avg  td_avg  \
 1   Aaron Rodgers     1       SF     0.00       0.00     0.00    0.00
 2   Aaron Rodgers     2      CHI    44.00      68.00   303.00    2.00
 3   Aaron Rodgers     3      SEA    38.00      68.50   261.00    1.50
 4   Aaron Rodgers     4       NO    38.33      68.00   248.33    1.00
 5   Aaron Rodgers     1       SF     0.00       0.00     0.00    0.00
 6   Aaron Rodgers     2      WAS    37.00      56.80   333.00    3.00
 7   Aaron Rodgers     5      DET    39.50      68.90   406.50    3.50
 8   Aaron Rodgers     6      BAL    36.33      68.17   362.33    2.67
 9   Aaron Rodgers     2      NYJ     0.00       0.00     0.00    0.00
 10  Aaron Rodgers     4      CHI    42.00      59.50   346.00    3.00
 11  Aaron Rodgers     5      MIN    35.00      69.05   324.00    3.50
 12  Aaron Rodgers     6      MIA    29.00      69.57   268.00    3.33
 13  Aaron Rodgers     1      CHI     0.00       0.00     0.00    0.00
 14  Aaron Rodgers     2      SEA    23.00      78.30   189.00    3.00
 15  Aaron Rodgers     3       KC    28.00      77.05   219.00    2.50
 16  Aaron Rodgers     4       SF    30.33      74.23   257.00    3.33
 17  Aaron Rodgers     1      JAX     0.00       0.00     0.00    0.00
 18  Aaron Rodgers     2      MIN    34.00      58.80   199.00    2.00
 19  Aaron Rodgers     3      DET    35.00      57.20   206.00    1.50
 20  Aaron Rodgers     5      NYG    31.33      58.97   205.67    2.33
 21  Aaron Rodgers     1      SEA     0.00       0.00     0.00    0.00
 22  Aaron Rodgers     2      ATL    42.00      66.70   311.00    1.00
 23  Aaron Rodgers     3      CIN    46.00      66.35   327.00    1.50
 24  Aaron Rodgers     4      CHI    44.67      66.47   322.33    2.00
 25  Aaron Rodgers     1      CHI     0.00       0.00     0.00    0.00
 26  Aaron Rodgers     2      MIN    30.00      66.70   286.00    3.00
 27  Aaron Rodgers     3      WAS    36.00      69.05   283.50    2.00
 28  Aaron Rodgers     4      BUF    38.67      66.50   277.33    2.00
 29  Aaron Rodgers     5      IND    39.00      70.00   266.00    1.75
 30  Aaron Rodgers     6      HOU    37.60      68.60   259.80    2.00
 ..            ...   ...      ...      ...        ...      ...     ...
 44  Aaron Rodgers     7      CAR    32.25      66.45   267.00    3.25
 45  Aaron Rodgers     8       NO    30.20      70.44   264.60    3.20
 46  Aaron Rodgers    10      CHI    31.67      70.67   290.17    2.83
 47  Aaron Rodgers    11      PHI    31.00      70.10   293.71    3.29
 48  Aaron Rodgers    12      MIN    31.62      68.97   299.62    3.25
 49  Aaron Rodgers    13       NE    31.33      68.59   289.56    3.11
 50  Aaron Rodgers    14      ATL    32.00      68.05   297.40    3.00
 51  Aaron Rodgers    16       TB    32.36      67.93   300.09    3.00
 52  Aaron Rodgers    17      DET    33.00      68.73   301.58    2.83
 53  Aaron Rodgers     5      LAR    30.75      72.88   248.75    2.75
 54  Aaron Rodgers    11      MIN    36.38      64.94   274.12    2.62
 55  Aaron Rodgers    14      DAL    36.10      63.33   267.80    2.50
 56  Aaron Rodgers    10      DET    32.86      66.01   265.71    2.71
 57  Aaron Rodgers    13      DET    36.11      62.96   267.22    2.56
 58  Aaron Rodgers     6      LAC    30.60      70.96   247.20    2.60
 59  Aaron Rodgers     9      CAR    30.33      68.33   248.50    2.50
 60  Aaron Rodgers    12      PHI    40.89      61.78   274.11    2.67
 61  Aaron Rodgers    13      HOU    40.70      63.29   278.00    2.60
 62  Aaron Rodgers    11      WAS    40.88      61.58   264.50    2.62
 63  Aaron Rodgers    17      DET    38.31      65.51   275.54    2.69
 64  Aaron Rodgers    14      SEA    39.73      63.60   271.73    2.55
 65  Aaron Rodgers    10      TEN    39.43      61.69   249.29    2.71
 66  Aaron Rodgers    16      MIN    38.33      64.82   269.58    2.58
 67  Aaron Rodgers     9      IND    38.83      61.88   241.33    2.67
 68  Aaron Rodgers     8      ATL    39.00      59.52   240.40    2.40
 69  Aaron Rodgers     7      CHI    34.75      57.00   219.00    2.25
 70  Aaron Rodgers    15      CAR    37.80      66.82   273.40    2.60
 71  Aaron Rodgers     5      DAL    40.00      67.15   286.50    2.50
 72  Aaron Rodgers     6       SF    41.60      63.20   314.40    2.00
 73  Aaron Rodgers     5      DET    39.00      63.63   282.50    1.75

     def_rk_avg   games_ma     att_ma   comp%_ma      yds_ma     td_ma  \
 1         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 2         5.00   0.000000   0.000000   0.000000    0.000000  0.000000
 3        18.00   0.000000   0.000000   0.000000    0.000000  0.000000
 4        12.33   0.000000   0.000000   0.000000    0.000000  0.000000
 5         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 6         8.00   0.000000   0.000000   0.000000    0.000000  0.000000
 7        18.50   0.000000   0.000000   0.000000    0.000000  0.000000
 8        19.00   0.000000   0.000000   0.000000    0.000000  0.000000
 9         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 10       18.00   0.000000   0.000000   0.000000    0.000000  0.000000
 11       14.00   0.000000   0.000000   0.000000    0.000000  0.000000
 12       20.00   0.000000   0.000000   0.000000    0.000000  0.000000
 13        0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 14       25.00   0.000000   0.000000   0.000000    0.000000  0.000000
 15       13.50   0.000000   0.000000   0.000000    0.000000  0.000000
 16       12.00   0.000000   0.000000   0.000000    0.000000  0.000000
 17        0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 18        5.00   0.000000   0.000000   0.000000    0.000000  0.000000
 19        5.50   0.000000   0.000000   0.000000    0.000000  0.000000
 20       14.00   0.000000   0.000000   0.000000    0.000000  0.000000
 21        0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 22        7.00   0.000000   0.000000   0.000000    0.000000  0.000000
 23       12.00   0.000000   0.000000   0.000000    0.000000  0.000000
 24       11.67   0.000000   0.000000   0.000000    0.000000  0.000000
 25        0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 26       16.00   0.000000   0.000000   0.000000    0.000000  0.000000
 27       20.00   0.000000   0.000000   0.000000    0.000000  0.000000
 28       19.67   0.000000   0.000000   0.000000    0.000000  0.000000
 29       16.50   2.500000  39.000000  70.000000  266.000000  1.750000
 30       15.80   3.000000  37.600000  68.600000  259.800000  2.000000
 ..         ...        ...        ...        ...         ...       ...
 44       16.75  25.500000  32.250000  66.450000  267.000000  3.250000
 45       13.80  26.000000  30.200000  70.440000  264.600000  3.200000
 46       12.17  26.500000  31.666667  70.666667  290.166667  2.833333
 47       11.86  27.000000  31.000000  70.100000  293.714286  3.285714
 48       14.12  27.500000  31.625000  68.975000  299.625000  3.250000
 49       16.11  28.000000  31.333333  68.588889  289.555556  3.111111
 50       16.50  28.500000  32.000000  68.050000  297.400000  3.000000
 51       17.55  29.000000  32.363636  67.927273  300.090909  3.000000
 52       18.25  29.500000  33.000000  68.725000  301.583333  2.833333
 53       13.00  41.750000  30.750000  72.875000  248.750000  2.750000
 54       13.00  41.750000  36.375000  64.937500  274.125000  2.625000
 55       13.80  41.800000  36.100000  63.330000  267.800000  2.500000
 56       11.57  42.000000  32.857143  66.014286  265.714286  2.714286
 57       12.78  42.111111  36.111111  62.955556  267.222222  2.555556
 58       12.40  42.600000  30.600000  70.960000  247.200000  2.600000
 59       12.50  42.666667  30.333333  68.333333  248.500000  2.500000
 60       18.22  54.555556  40.888889  61.777778  274.111111  2.666667
 61       17.40  54.700000  40.700000  63.290000  278.000000  2.600000
 62       17.75  54.875000  40.875000  61.575000  264.500000  2.625000
 63       14.38  54.923077  38.307692  65.507692  275.538462  2.692308
 64       16.09  55.272727  39.727273  63.600000  271.727273  2.545455
 65       16.14  55.428571  39.428571  61.685714  249.285714  2.714286
 66       15.08  55.500000  38.333333  64.825000  269.583333  2.583333
 67       14.83  55.666667  38.833333  61.883333  241.333333  2.666667
 68       11.80  56.800000  39.000000  59.520000  240.400000  2.400000
 69       11.00  57.750000  34.750000  57.000000  219.000000  2.250000
 70       11.20  64.800000  37.800000  66.820000  273.400000  2.600000
 71       10.00  65.000000  40.000000  67.150000  286.500000  2.500000
 72       14.80  70.800000  41.600000  63.200000  314.400000  2.000000
 73       15.50  71.500000  39.000000  63.625000  282.500000  1.750000

     def_rk_ma  games_car  att_car  comp%_car  yds_car  td_car  def_rk_car
 1    0.000000       0.00     0.00       0.00     0.00    0.00        0.00
 2    0.000000       1.00    44.00      68.00   303.00    2.00        5.00
 3    0.000000       1.50    38.00      68.50   261.00    1.50       18.00
 4    0.000000       2.00    38.33      68.00   248.33    1.00       12.33
 5    0.000000       2.50    39.00      70.00   266.00    1.75       16.50
 6    0.000000       3.00    37.60      68.60   259.80    2.00       15.80
 7    0.000000       3.50    37.50      68.00   272.83    2.67       14.83
 8    0.000000       4.00    37.43      69.86   282.71    2.71       14.29
 9    0.000000       4.50    37.12      69.00   270.62    2.62       14.25
 10   0.000000       5.00    36.33      66.56   264.78    2.78       15.22
 11   0.000000       5.50    35.40      66.90   261.90    2.70       14.40
 12   0.000000       6.00    34.45      65.91   258.00    2.55       15.55
 13   0.000000       6.50    34.50      66.83   260.33    2.42       15.00
 14   0.000000       7.00    33.69      66.15   253.62    2.23       14.38
 15   0.000000       7.50    33.86      66.00   256.29    2.29       15.57
 16   0.000000       8.00    34.13      66.33   262.00    2.33       15.73
 17   0.000000       8.50    34.50      66.56   268.44    2.44       15.31
 18   0.000000      17.00    38.50      63.40   349.00    3.50        8.50
 19   0.000000      17.00    39.67      69.27   392.67    3.67       15.33
 20   0.000000      18.50    37.25      68.62   363.00    3.00       16.50
 21   0.000000      19.20    36.20      65.52   353.40    2.60       15.00
 22   0.000000      19.17    36.17      66.17   337.83    2.67       16.33
 23   0.000000      19.29    35.14      68.54   330.29    2.57       18.29
 24   0.000000      19.50    35.62      67.99   328.75    2.50       16.50
 25   0.000000      22.50    40.50      61.80   332.00    2.50       11.00
 26   0.000000      23.33    36.33      67.40   322.00    3.00       10.67
 27   0.000000      24.00    31.50      68.20   280.50    3.00       16.00
 28   0.000000      24.60    33.60      65.98   277.20    3.00       14.20
 29  16.500000      25.17    31.67      69.38   273.50    3.00       12.17
 30  15.800000      25.71    32.71      69.73   294.14    2.71       11.00
 ..        ...        ...      ...        ...      ...     ...         ...
 44  16.750000      41.25    31.50      67.42   260.75    2.62       12.00
 45  13.800000      41.11    34.78      66.31   268.78    2.56       13.22
 46  12.166667      41.50    34.70      64.39   263.10    2.50       13.00
 47  11.857143      41.27    34.82      64.60   264.00    2.45       13.91
 48  14.125000      41.50    34.83      64.46   260.17    2.42       13.17
 49  16.111111      50.50    34.50      60.85   208.50    2.00        5.00
 50  16.500000      53.33    35.00      59.10   210.00    1.67        5.33
 51  17.545455      53.75    32.25      59.95   208.75    2.25       11.75
 52  18.250000      55.00    34.80      58.18   218.80    2.20        9.80
 53  13.000000      54.67    38.33      60.08   236.67    2.33       10.67
 54  13.000000      54.00    38.29      62.03   238.00    2.57       13.43
 55  13.800000      54.00    38.88      61.84   245.38    2.62       14.75
 56  11.571429      53.67    40.22      61.72   259.33    2.56       16.33
 57  12.777778      53.50    40.30      61.89   268.50    2.60       16.90
 58  12.400000      53.73    40.18      63.25   272.55    2.55       16.27
 59  12.500000      54.33    39.33      63.54   267.25    2.50       15.17
 60  18.222222      54.62    38.08      64.68   265.62    2.54       14.31
 61  17.400000      54.14    38.07      65.32   271.43    2.64       13.71
 62  17.750000      53.80    38.13      65.58   273.33    2.73       14.87
 63  14.384615      58.00    40.50      67.95   305.50    2.50       19.00
 64  16.090909      60.33    43.67      67.30   318.00    2.33       18.33
 65  16.142857      60.75    43.25      67.15   316.75    2.50       16.50
 66  15.083333      61.80    39.80      67.56   289.20    2.80       14.20
 67  14.833333      62.17    38.00      67.22   277.83    2.83       14.50
 68  11.800000      62.29    39.00      65.87   279.57    2.86       14.57
 69  11.000000      66.50    37.50      62.25   288.00    3.00       15.50
 70  11.200000      68.67    39.00      65.30   285.67    2.33       18.33
 71  10.000000      69.25    40.25      64.32   280.50    2.25       18.50
 72  14.800000      69.80    40.20      62.46   284.00    2.00       15.40
 73  15.500000      69.50    42.17      62.30   310.33    2.17       14.83

 [73 rows x 20 columns],
 'Alex Smith_reframed':            Name  Week Opponent  att_avg  comp%_avg  yds_avg  td_avg  \
 74   Alex Smith     1       GB     0.00       0.00     0.00    0.00
 75   Alex Smith     2      DET    26.00      77.00   211.00    2.00
 76   Alex Smith     3      MIN    28.50      71.00   218.50    2.00
 77   Alex Smith     4      NYJ    30.67      70.33   213.67    1.67
 78   Alex Smith     1      JAX     0.00       0.00     0.00    0.00
 79   Alex Smith     2      DAL    34.00      61.80   173.00    2.00
 80   Alex Smith     4      NYG    35.00      60.05   198.00    2.00
 81   Alex Smith     7      HOU    37.00      59.53   228.00    2.33
 82   Alex Smith     3      MIA     0.00       0.00     0.00    0.00
 83   Alex Smith     4       NE    25.00      76.00   186.00    3.00
 84   Alex Smith     7      LAC    25.50      76.45   217.00    3.00
 85   Alex Smith     9      NYJ    26.33      73.60   218.33    2.33
 86   Alex Smith     1      HOU     0.00       0.00     0.00    0.00
 87   Alex Smith     3       GB    33.00      66.70   243.00    3.00
 88   Alex Smith     4      CIN    36.50      63.35   266.50    2.00
 89   Alex Smith     6      MIN    39.33      65.20   306.33    1.33
 90   Alex Smith     1      LAC     0.00       0.00     0.00    0.00
 91   Alex Smith     4      PIT    48.00      70.80   363.00    2.00
 92   Alex Smith     7       NO    49.00      65.40   325.00    2.00
 93   Alex Smith    11       TB    40.67      67.20   288.00    2.00
 94   Alex Smith     1       NE     0.00       0.00     0.00    0.00
 95   Alex Smith     2      PHI    35.00      80.00   368.00    4.00
 96   Alex Smith     3      LAC    31.50      77.50   309.50    2.50
 97   Alex Smith     4      WAS    28.00      77.07   258.00    2.33
 98   Alex Smith     1      ARI     0.00       0.00     0.00    0.00
 99   Alex Smith     2      IND    30.00      70.00   255.00    2.00
 100  Alex Smith     3       GB    38.00      70.85   273.50    1.00
 101  Alex Smith     5       NO    32.00      67.23   255.67    1.33
 102  Alex Smith     5      BUF    28.25      67.00   196.00    1.25
 103  Alex Smith     6      NYG    27.40      68.60   217.40    1.60
 ..          ...   ...      ...      ...        ...      ...     ...
 109  Alex Smith    13      LAR    19.73      59.09   157.36    1.18
 110  Alex Smith    14      MIA    18.08      54.17   144.25    1.08
 111  Alex Smith    15       NE    16.69      50.00   133.15    1.00
 112  Alex Smith    16      SEA    15.50      46.43   123.64    0.93
 113  Alex Smith    17      ARI    14.47      43.33   115.40    0.87
 114  Alex Smith    15      OAK    38.25      61.24   245.75    2.00
 115  Alex Smith     8      CLE    36.25      61.55   231.00    1.75
 116  Alex Smith    13      DEN    37.71      61.14   239.00    2.00
 117  Alex Smith    11      DEN    36.20      62.58   229.80    1.80
 118  Alex Smith    12      LAC    37.67      59.93   229.83    1.83
 119  Alex Smith    10      BUF    27.50      72.12   213.50    2.25
 120  Alex Smith    12      OAK    27.80      69.42   206.20    1.80
 121  Alex Smith    14      ARI    29.17      67.12   210.83    1.83
 122  Alex Smith    15      OAK    30.57      67.06   222.57    1.71
 123  Alex Smith    16      PIT    30.50      66.18   231.88    1.75
 124  Alex Smith    16      CLE    33.29      65.76   251.86    1.57
 125  Alex Smith    13      OAK    35.17      64.60   266.83    1.50
 126  Alex Smith    17      OAK    31.88      66.06   236.00    1.62
 127  Alex Smith    12      BUF    36.20      64.86   269.20    1.40
 128  Alex Smith     8      DET    38.75      63.78   300.25    1.25
 129  Alex Smith    17      LAC    37.80      69.68   273.80    1.60
 130  Alex Smith    16      DEN    38.25      69.75   281.25    1.75
 131  Alex Smith    15      LAC    32.78      71.00   289.78    2.33
 132  Alex Smith     6      PIT    31.60      76.52   278.20    2.20
 133  Alex Smith    16      MIA    32.50      71.57   283.90    2.30
 134  Alex Smith     9      DAL    32.57      72.56   282.71    2.14
 135  Alex Smith    13      NYJ    32.75      72.68   280.25    2.12
 136  Alex Smith     7      OAK    32.00      73.08   272.83    2.00
 137  Alex Smith     5      HOU    30.25      76.05   266.75    2.00
 138  Alex Smith     6      CAR    33.75      65.18   260.50    1.00

      def_rk_avg   games_ma     att_ma   comp%_ma      yds_ma     td_ma  \
 74         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 75        17.00   0.000000   0.000000   0.000000    0.000000  0.000000
 76        12.00   0.000000   0.000000   0.000000    0.000000  0.000000
 77        11.00   0.000000   0.000000   0.000000    0.000000  0.000000
 78         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 79        16.00   0.000000   0.000000   0.000000    0.000000  0.000000
 80        14.50   0.000000   0.000000   0.000000    0.000000  0.000000
 81        17.67   0.000000   0.000000   0.000000    0.000000  0.000000
 82         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 83         7.00   0.000000   0.000000   0.000000    0.000000  0.000000
 84        13.50   0.000000   0.000000   0.000000    0.000000  0.000000
 85        16.67   0.000000   0.000000   0.000000    0.000000  0.000000
 86         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 87         4.00   0.000000   0.000000   0.000000    0.000000  0.000000
 88         5.50   0.000000   0.000000   0.000000    0.000000  0.000000
 89         4.67   0.000000   0.000000   0.000000    0.000000  0.000000
 90         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 91        18.00   0.000000   0.000000   0.000000    0.000000  0.000000
 92        12.50   0.000000   0.000000   0.000000    0.000000  0.000000
 93        17.33   0.000000   0.000000   0.000000    0.000000  0.000000
 94         0.00   0.000000   0.000000   0.000000    0.000000  0.000000
 95        27.00   0.000000   0.000000   0.000000    0.000000  0.000000
 96        19.50   0.000000   0.000000   0.000000    0.000000  0.000000

In [159]:
reframed_dict['AJ McCarron_reframed']

,Name,Week,Opponent,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,games_ma,att_ma,comp%_ma,yds_ma,td_ma,def_rk_ma,games_car,att_car,comp%_car,yds_car,td_car,def_rk_car
0,AJ McCarron,14,PIT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [118]:
rb_stats.head()

,Name,Week,Opponent,att_avg,yds_avg,td_avg,tar_avg,rec_yds_avg,def_rk_avg,att_ma,...,tar_ma,rec_yds_ma,def_rk_ma,index,att_car,yds_car,td_car,tar_car,rec_yds_car,def_rk_car
0,Adrian Peterson,1,SF,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,Adrian Peterson,2,DET,10.00,31.0,0.00,3.00,21.00,32.00,0.00,...,0.00,0.0,0.00,2612.0,13.0,49.00,1.00,0.00,0.00,11.00
2,Adrian Peterson,3,LAC,19.50,82.5,0.00,2.50,39.50,24.50,0.00,...,0.00,0.0,0.00,2613.0,16.0,87.00,1.00,0.50,4.50,9.50
3,Adrian Peterson,4,DEN,19.67,97.0,0.67,1.67,26.33,25.00,0.00,...,0.00,0.0,0.00,2614.0,15.0,71.67,0.67,1.67,3.33,6.67
4,Adrian Peterson,6,KC,18.75,93.0,0.75,2.75,23.00,22.25,18.75,...,2.75,23.0,22.25,2615.0,15.5,86.50,0.75,2.50,4.25,9.25

In [160]:
# A function to insert the non reframed columns back into the stats dataframe 

def insert_non_reframed(df, col_dict):
    non_reframed = ['games','year','Opponent','def_rk','h/a_1','surface_0','points']
    for player in df['Name'].unique():
        for col in non_reframed:
            reframed_dict['{}_reframed'.format(player)][col] = col_dict['{}'.format(player)][col].values
            
    return reframed_dict

In [112]:
rb_sorted_dict['Aaron Jones']['points'].shape

(12,)

In [161]:
qb_stats = insert_non_reframed(qb_stats,qb_sorted_dict)

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [162]:
qb_stats = pd.concat(qb_stats)

In [163]:
qb_stats

                                              Name  Week Opponent  att_avg  \
AJ McCarron_reframed       0           AJ McCarron    14      PIT     0.00
Aaron Rodgers_reframed     1         Aaron Rodgers     1       SF     0.00
                           2         Aaron Rodgers     2       SF    44.00
                           3         Aaron Rodgers     3      CHI    38.00
                           4         Aaron Rodgers     4      JAX    38.33
                           5         Aaron Rodgers     1      SEA     0.00
                           6         Aaron Rodgers     2      CHI    37.00
                           7         Aaron Rodgers     5      CHI    39.50
                           8         Aaron Rodgers     6      WAS    36.33
                           9         Aaron Rodgers     2      NYJ     0.00
                           10        Aaron Rodgers     4      SEA    42.00
                           11        Aaron Rodgers     5      MIN    35.00
                           12        Aaron Rodgers     6      ATL    29.00
                           13        Aaron Rodgers     1      MIN     0.00
                           14        Aaron Rodgers     2      SEA    23.00
                           15        Aaron Rodgers     3       KC    28.00
                           16        Aaron Rodgers     4      DET    30.33
                           17        Aaron Rodgers     1      CIN     0.00
                           18        Aaron Rodgers     2      WAS    34.00
                           19        Aaron Rodgers     3       NO    35.00
                           20        Aaron Rodgers     5      CHI    31.33
                           21        Aaron Rodgers     1       SF     0.00
                           22        Aaron Rodgers     2      CHI    42.00
                           23        Aaron Rodgers     3      BUF    46.00
                           24        Aaron Rodgers     4      IND    44.67
                           25        Aaron Rodgers     1      DET     0.00
                           26        Aaron Rodgers     2      MIN    30.00
                           27        Aaron Rodgers     3      LAR    36.00
                           28        Aaron Rodgers     4      NYG    38.67
                           29        Aaron Rodgers     5      DAL    39.00
...                                            ...   ...      ...      ...
Tyrod Taylor_reframed      2324       Tyrod Taylor     5       NE    31.33
                           2325       Tyrod Taylor     1       KC     0.00
                           2326       Tyrod Taylor     3      TEN    28.00
                           2327       Tyrod Taylor     7      LAR    27.00
                           2328       Tyrod Taylor     8       SF    29.00
                           2329       Tyrod Taylor     1      MIA     0.00
                           2330       Tyrod Taylor     2       TB    40.00
                           2331       Tyrod Taylor     3       NE    35.00
                           2332       Tyrod Taylor    10      OAK     0.75
                           2333       Tyrod Taylor    17      CLE     0.80
                           2334       Tyrod Taylor    14      SEA    27.00
                           2335       Tyrod Taylor    17      NYJ    28.29
                           2336       Tyrod Taylor    15      OAK    28.50
                           2337       Tyrod Taylor    13      LAC    28.50
                           2338       Tyrod Taylor    14       KC    29.44
                           2339       Tyrod Taylor    12      JAX    30.88
                           2340       Tyrod Taylor    15      HOU    29.00
                           2341       Tyrod Taylor     8      PHI    28.50
                           2342       Tyrod Taylor     9      PIT    29.86
                           2343       Tyrod Taylor    16      WAS    28.55
                           2344       Tyrod Taylor     7      CLE    28.60
                           2345       Tyrod Taylor     6      MIA    29.25
                           2346       Tyrod Taylor    17      MIA    29.71
                           2347       Tyrod Taylor    11      CIN    30.80
                           2348       Tyrod Taylor    15      NYJ    29.83
                           2349       Tyrod Taylor     9      MIA    28.50
Zach Mettenberger_reframed 2350  Zach Mettenberger     8      HOU     0.00
                           2351  Zach Mettenberger    11      PIT    41.00
                           2352  Zach Mettenberger    12      PHI    32.50
                           2353  Zach Mettenberger    15       NE     0.00

                                 comp%_avg  yds_avg  td_avg  def_rk_avg  \
AJ McCarron_reframed       0          0.00     0.00    0.00        0.00
Aaron Rodgers_reframed     1          0.00     0.00    0.00        0.00
                           2         68.00   303.00    2.00        5.00
                           3         68.50   261.00    1.50       18.00
                           4         68.00   248.33    1.00       12.33
                           5          0.00     0.00    0.00        0.00
                           6         56.80   333.00    3.00        8.00
                           7         68.90   406.50    3.50       18.50
                           8         68.17   362.33    2.67       19.00
                           9          0.00     0.00    0.00        0.00
                           10        59.50   346.00    3.00       18.00
                           11        69.05   324.00    3.50       14.00
                           12        69.57   268.00    3.33       20.00
                           13         0.00     0.00    0.00        0.00
                           14        78.30   189.00    3.00       25.00
                           15        77.05   219.00    2.50       13.50
                           16        74.23   257.00    3.33       12.00
                           17         0.00     0.00    0.00        0.00
                           18        58.80   199.00    2.00        5.00
                           19        57.20   206.00    1.50        5.50
                           20        58.97   205.67    2.33       14.00
                           21         0.00     0.00    0.00        0.00
                           22        66.70   311.00    1.00        7.00
                           23        66.35   327.00    1.50       12.00
                           24        66.47   322.33    2.00       11.67
                           25         0.00     0.00    0.00        0.00
                           26        66.70   286.00    3.00       16.00
                           27        69.05   283.50    2.00       20.00
                           28        66.50   277.33    2.00       19.67
                           29        70.00   266.00    1.75       16.50
...                                    ...      ...     ...         ...
Tyrod Taylor_reframed      2324      61.73   220.67    1.33       13.33
                           2325       0.00     0.00    0.00        0.00
                           2326      57.10   224.00    2.00       28.00
                           2327      67.00   218.50    2.00       19.00
                           2328      64.87   235.00    1.67       20.00
                           2329       0.00     0.00    0.00        0.00
                           2330      37.50   197.00    1.00       28.00
                           2331      55.40   221.50    1.00       29.00
                           2332      16.75     7.50    0.00        4.75
                           2333      13.40     6.00    0.00        7.80
                           2334      63.12   226.00    2.60       14.60
                           2335      61.10   233.29    2.29       17.71
                           2336      61.40   233.00    2.33       17.17
                           2337      65.80   229.75    2.50       17.25
                           2338      60.07   202.67    1.22       14.11
                           2339      59.24   207.25    1.25       15.25
                           2340      60.06   205.20    1.30       13.40
                           2341      58.80   197.67    1.50       18.17
                           2342      57.54   195.57    1.29       16.86
                           2343      61.04   202.36    1.27       15.09
                           2344      60.56   193.00    1.60       16.20
                           2345      59.35   196.50    1.50       15.25
                           2346      65.69   219.57    1.43       19.14
                           2347      68.24   231.00    1.60       22.40
                           2348      66.87   218.83    1.50       19.33
                           2349      67.18   217.50    1.50       21.00
Zach Mettenberger_reframed 2350       0.00     0.00    0.00        0.00
                           2351      65.90   299.00    2.00       12.00
                           2352      64.20   281.00    2.00       10.50
                           2353       0.00     0.00    0.00        0.00

                                  games_ma     att_ma   ...    comp%_car  \
AJ McCarron_reframed       0      0.000000   0.000000   ...         0.00
Aaron Rodgers_reframed     1      0.000000   0.000000   ...         0.00
                           2      0.000000   0.000000   ...        68.00
                           3      0.000000   0.000000   ...        68.50
                           4      0.000000   0.000000   ...        68.00
                           5      0.000000   0.000000   ...        70.00
                           6      0.000000   0.000000   ...        68.60
                           7      0.000000   0.000000   ...        68.00
                           8      0.000000   0.000000   ...        69.86
                           9      0.000000   0.000000   ...        69.00
                           10     0.000000   0.000000   ...        66.56
                           11     0.000000   0.000000   ...        66.90
                           12     0.000000   0.000000   ...        65.91
                           13     0.000000   0.000000   ...        66.83
                           14     0.000000   0.000000   ...        66.15
                           15     0.000000   0.000000   ...        66.00
                           16     0.000000   0.000000   ...        66.33
                           17     0.000000   0.000000   ...        66.56
                           18     0.000000   0.000000   ...        63.40
                           19     0.000000   0.000000   ...        69.27
                           20     0.000000   0.000000   ...        68.62
                           21     0.000000   0.000000   ...        65.52
                           22     0.000000   0.000000   ...        66.17
                           23     0.000000   0.000000   ...        68.54
                           24     0.000000   0.000000   ...        67.99
                           25     0.000000   0.000000   ...        61.80
                           26     0.000000   0.000000   ...        67.40
                           27     0.000000   0.000000   ...        68.20
                           28     0.000000   0.000000   ...        65.98
                           29     2.500000  39.000000   ...        69.38
...                                    ...        ...   ...          ...
Tyrod Taylor_reframed      2324   0.000000   0.000000   ...        63.12
                           2325   0.000000   0.000000   ...        61.40
                           2326   0.000000   0.000000   ...        61.10
                           2327   0.000000   0.000000   ...        61.50
                           2328   0.000000   0.000000   ...        62.15
                           2329   0.000000   0.000000   ...        60.10
                           2330   0.000000   0.000000   ...        62.38
                           2331   0.000000   0.000000   ...        60.34
                           2332   2.500000   0.750000   ...        61.18
                           2333   3.000000   0.800000   ...        59.59
                           2334   9.600000  27.000000   ...        58.39
                           2335  10.000000  28.285714   ...        59.80
                           2336  10.166667  28.500000   ...        60.49
                           2337  10.250000  28.500000   ...        60.45
                           2338  20.222222  29.444444   ...        61.31
                           2339  20.250000  30.875000   ...        61.72
                           2340  20.600000  29.000000   ...        61.90
                           2341  20.833333  28.500000   ...        66.90
                           2342  20.857143  29.857143   ...        65.32
                           2343  21.000000  28.545455   ...        67.08
                           2344  21.400000  28.600000   ...        67.98
                           2345  22.000000  29.250000   ...        66.84
                           2346  30.000000  29.714286   ...        65.81
                           2347  30.200000  30.800000   ...        66.32
                           2348  30.333333  29.833333   ...        53.95
                           2349  31.000000  28.500000   ...        60.40
Zach Mettenberger_reframed 2350   0.000000   0.000000   ...         0.00
                           2351   0.000000   0.000000   ...        65.90
                           2352   0.000000   0.000000   ...        64.20
                           2353   0.000000   0.000000   ...        59.90

                                 yds_car  td_car  def_rk_car  games  year  \
AJ McCarron_reframed       0        0.00    0.00        0.00      1  2015
Aaron Rodgers_reframed     1        0.00    0.00        0.00      1  2012
                           2      303.00    2.00        5.00     18  2013
                           3      261.00    1.50       18.00     41  2015
                           4      248.33    1.00       12.33     57  2016
                           5      266.00    1.75       16.50     67  2017
                           6      259.80    2.00       15.80     70  2018
                           7      272.83    2.67       14.83      2  2012
                           8      282.71    2.71       14.29     17  2013
                           9      270.62    2.62       14.25     24  2014
                           10     264.78    2.78       15.22     42  2015
                           11     261.90    2.70       14.40     59  2016
                           12     258.00    2.55       15.55     65  2017
                           13     260.33    2.42       15.00     73  2018
                           14     253.62    2.23       14.38      3  2012
                           15     256.29    2.29       15.57     37  2015
                           16     262.00    2.33       15.73     55  2016
                           17     268.44    2.44       15.31     62  2017
                           18     349.00    3.50        8.50     71  2018
                           19     392.67    3.67       15.33      4  2012
                           20     363.00    3.00       16.50     25  2014
                           21     353.40    2.60       15.00     47  2015
                           22     337.83    2.67       16.33     66  2017
                           23     330.29    2.57       18.29     72  2018
                           24     328.75    2.50       16.50      5  2012
                           25     332.00    2.50       11.00     23  2013
                           26     322.00    3.00       10.67     26  2014
                           27     280.50    3.00       16.00     46  2015
                           28     277.20    3.00       14.20     60  2016
                           29     273.50    3.00       12.17     64  2017
...                                  ...     ...         ...    ...   ...
Tyrod Taylor_reframed      2324   226.00    2.60       14.60     23  2016
                           2325   233.00    2.33       17.17      3  2012
                           2326   233.29    2.29       17.71     12  2015
                           2327   226.88    2.00       17.25     26  2016
                           2328   239.50    1.50       16.50     19  2016
                           2329   199.33    1.00       15.00     18  2016
                           2330   211.00    1.00       13.50     29  2017
                           2331   193.60    1.20       15.00     21  2016
                           2332   191.17    1.33       15.83     33  2017
                           2333   195.43    1.29       17.57      4  2012
                           2334   193.88    1.12       16.50     16  2016
                           2335   204.44    1.11       15.11     27  2017
                           2336   200.60    1.10       14.10      5  2012
                           2337   203.09    1.18       13.45     31  2017
                           2338   200.67    1.17       15.00     10  2015
                           2339   210.54    1.31       16.00     20  2016
                           2340   276.50    2.50       28.00      7  2015
                           2341   255.33    2.33       22.00     13  2015
                           2342   258.50    2.00       22.00     24  2016
                           2343   239.80    1.80       22.40      9  2015
                           2344   247.33    1.83       23.33     25  2016
                           2345   234.57    1.71       20.57     28  2017
                           2346   233.25    1.62       20.25     15  2016
                           2347   230.00    1.56       20.00      6  2012
                           2348   200.50    1.00       23.00     14  2015
                           2349   215.67    1.00       25.33     34  2017
Zach Mettenberger_reframed 2350     0.00    0.00        0.00      1  2014
                           2351   299.00    2.00       12.00      2  2014
                           2352   281.00    2.00       10.50      3  2014
                           2353   302.33    2.00       17.00      4  2015

                                 def_rk  h/a_1  surface_0  points
AJ McCarron_reframed       0         24    1.0        0.0   18.00
Aaron Rodgers_reframed     1          5    1.0        1.0   22.82
                           2          8    0.0        1.0   28.62
                           3         25    0.0        1.0   23.06
                           4          5    0.0        1.0   23.56
                           5          7    1.0        1.0   20.54
                           6         16    1.0        1.0   24.94
                           7         31    1.0        1.0   10.16
                           8         29    1.0        1.0   37.90
                           9         18    1.0        1.0   32.64
                           10         2    1.0        1.0   22.26
                           11         6    0.0        0.0   19.42
                           12        17    0.0        0.0   23.52
                           13        24    1.0        1.0   16.04
                           14         1    0.0        0.0   10.62
                           15         9    1.0        1.0   37.92
                           16        31    1.0        1.0   26.40
                           17        11    1.0        1.0   28.82
                           18        19    0.0        1.0   19.90
                           19        29    1.0        1.0   28.06
                           20        10    1.0        1.0   31.88
                           21        16    0.0        1.0   16.26
                           22         5    1.0        1.0   23.06
                           23         3    1.0        1.0   17.02
                           24        13    0.0        0.0   25.10

In [164]:
qb_stats.shape

(2354, 26)

In [164]:
rb_stats.drop(0, axis=1, inplace=True)

In [165]:
print(rb_stats[rb_stats.isnull().any(axis=1)][null_columns]).nunique()

                                     Week Opponent  att_avg  yds_avg  td_avg  \
                        Name
Brandon Burks_reframed  Week          NaN      NaN      NaN      NaN     NaN
                        Opponent      NaN      NaN      NaN      NaN     NaN
                        att_avg       NaN      NaN      NaN      NaN     NaN
                        yds_avg       NaN      NaN      NaN      NaN     NaN
                        td_avg        NaN      NaN      NaN      NaN     NaN
                        tar_avg       NaN      NaN      NaN      NaN     NaN
                        rec_yds_avg   NaN      NaN      NaN      NaN     NaN
                        def_rk_avg    NaN      NaN      NaN      NaN     NaN
                        games_ma      NaN      NaN      NaN      NaN     NaN
                        att_ma        NaN      NaN      NaN      NaN     NaN
                        yds_ma        NaN      NaN      NaN      NaN     NaN
                        td_ma         NaN      NaN      NaN      NaN     NaN
                        tar_ma        NaN      NaN      NaN      NaN     NaN
                        rec_yds_ma    NaN      NaN      NaN      NaN     NaN
                        def_rk_ma     NaN      NaN      NaN      NaN     NaN
                        games_car     NaN      NaN      NaN      NaN     NaN
                        att_car       NaN      NaN      NaN      NaN     NaN
                        yds_car       NaN      NaN      NaN      NaN     NaN
                        td_car        NaN      NaN      NaN      NaN     NaN
                        tar_car       NaN      NaN      NaN      NaN     NaN
                        rec_yds_car   NaN      NaN      NaN      NaN     NaN
                        def_rk_car    NaN      NaN      NaN      NaN     NaN
                        games         NaN      NaN      NaN      NaN     NaN
                        year          NaN      NaN      NaN      NaN     NaN
                        def_rk        NaN      NaN      NaN      NaN     NaN
                        h/a_1         NaN      NaN      NaN      NaN     NaN
                        surface_0     NaN      NaN      NaN      NaN     NaN
                        points        NaN      NaN      NaN      NaN     NaN
Cedric Peerman_reframed Week          NaN      NaN      NaN      NaN     NaN
                        Opponent      NaN      NaN      NaN      NaN     NaN
...                                   ...      ...      ...      ...     ...
Tyler Varga_reframed    surface_0     NaN      NaN      NaN      NaN     NaN
                        points        NaN      NaN      NaN      NaN     NaN
Will Johnson_reframed   Week          NaN      NaN      NaN      NaN     NaN
                        Opponent      NaN      NaN      NaN      NaN     NaN
                        att_avg       NaN      NaN      NaN      NaN     NaN
                        yds_avg       NaN      NaN      NaN      NaN     NaN
                        td_avg        NaN      NaN      NaN      NaN     NaN
                        tar_avg       NaN      NaN      NaN      NaN     NaN
                        rec_yds_avg   NaN      NaN      NaN      NaN     NaN
                        def_rk_avg    NaN      NaN      NaN      NaN     NaN
                        games_ma      NaN      NaN      NaN      NaN     NaN
                        att_ma        NaN      NaN      NaN      NaN     NaN
                        yds_ma        NaN      NaN      NaN      NaN     NaN
                        td_ma         NaN      NaN      NaN      NaN     NaN
                        tar_ma        NaN      NaN      NaN      NaN     NaN
                        rec_yds_ma    NaN      NaN      NaN      NaN     NaN
                        def_rk_ma     NaN      NaN      NaN      NaN     NaN
                        games_car     NaN      NaN      NaN      NaN     NaN
                        att_car       NaN      NaN      NaN      NaN     NaN
                        yds_car       NaN      NaN      NaN      NaN     NaN
                        td_car        NaN      NaN      NaN      NaN     NaN
                        tar_car       NaN      NaN      NaN      NaN     NaN
                        rec_yds_car   NaN      NaN      NaN      NaN     NaN
                        def_rk_car    NaN      NaN      NaN      NaN     NaN
                        games         NaN      NaN      NaN      NaN     NaN
                        year          NaN      NaN      NaN      NaN     NaN
                        def_rk        NaN      NaN      NaN      NaN     NaN
                        h/a_1         NaN      NaN      NaN      NaN     NaN
                        surface_0     NaN      NaN      NaN      NaN     NaN
                        points        NaN      NaN      NaN      NaN     NaN

                                     tar_avg  rec_yds_avg  def_rk_avg  \
                        Name
Brandon Burks_reframed  Week             NaN          NaN         NaN
                        Opponent         NaN          NaN         NaN
                        att_avg          NaN          NaN         NaN
                        yds_avg          NaN          NaN         NaN
                        td_avg           NaN          NaN         NaN
                        tar_avg          NaN          NaN         NaN
                        rec_yds_avg      NaN          NaN         NaN
                        def_rk_avg       NaN          NaN         NaN
                        games_ma         NaN          NaN         NaN
                        att_ma           NaN          NaN         NaN
                        yds_ma           NaN          NaN         NaN
                        td_ma            NaN          NaN         NaN
                        tar_ma           NaN          NaN         NaN
                        rec_yds_ma       NaN          NaN         NaN
                        def_rk_ma        NaN          NaN         NaN
                        games_car        NaN          NaN         NaN
                        att_car          NaN          NaN         NaN
                        yds_car          NaN          NaN         NaN
                        td_car           NaN          NaN         NaN
                        tar_car          NaN          NaN         NaN
                        rec_yds_car      NaN          NaN         NaN
                        def_rk_car       NaN          NaN         NaN
                        games            NaN          NaN         NaN
                        year             NaN          NaN         NaN
                        def_rk           NaN          NaN         NaN
                        h/a_1            NaN          NaN         NaN
                        surface_0        NaN          NaN         NaN
                        points           NaN          NaN         NaN
Cedric Peerman_reframed Week             NaN          NaN         NaN
                        Opponent         NaN          NaN         NaN
...                                      ...          ...         ...
Tyler Varga_reframed    surface_0        NaN          NaN         NaN
                        points           NaN          NaN         NaN
Will Johnson_reframed   Week             NaN          NaN         NaN
                        Opponent         NaN          NaN         NaN
                        att_avg          NaN          NaN         NaN
                        yds_avg          NaN          NaN         NaN
                        td_avg           NaN          NaN         NaN
                        tar_avg          NaN          NaN         NaN
                        rec_yds_avg      NaN          NaN         NaN
                        def_rk_avg       NaN          NaN         NaN
                        games_ma         NaN          NaN         NaN
                        att_ma           NaN          NaN         NaN
                        yds_ma           NaN          NaN         NaN
                        td_ma            NaN          NaN         NaN
                        tar_ma           NaN          NaN         NaN
                        rec_yds_ma       NaN          NaN         NaN
                        def_rk_ma        NaN          NaN         NaN
                        games_car        NaN          NaN         NaN
                        att_car          NaN          NaN         NaN
                        yds_car          NaN          NaN         NaN
                        td_car           NaN          NaN         NaN
                        tar_car          NaN          NaN         NaN
                        rec_yds_car      NaN          NaN         NaN
                        def_rk_car       NaN          NaN         NaN
                        games            NaN          NaN         NaN
                        year             NaN          NaN         NaN
                        def_rk           NaN          NaN         NaN
                        h/a_1            NaN          NaN         NaN
                        surface_0        NaN          NaN         NaN
                        points           NaN          NaN         NaN

                                     games_ma  att_ma   ...    td_car  \
                        Name                            ...
Brandon Burks_reframed  Week              NaN     NaN   ...       NaN
                        Opponent          NaN     NaN   ...       NaN
                        att_avg           NaN     NaN   ...       NaN
                        yds_avg           NaN     NaN   ...       NaN
                        td_avg            NaN     NaN   ...       NaN
                        tar_avg           NaN     NaN   ...       NaN
                        rec_yds_avg       NaN     NaN   ...       NaN
                        def_rk_avg        NaN     NaN   ...       NaN
                        games_ma          NaN     NaN   ...       NaN
                        att_ma            NaN     NaN   ...       NaN
                        yds_ma            NaN     NaN   ...       NaN
                        td_ma             NaN     NaN   ...       NaN
                        tar_ma            NaN     NaN   ...       NaN
                        rec_yds_ma        NaN     NaN   ...       NaN
                        def_rk_ma         NaN     NaN   ...       NaN
                        games_car         NaN     NaN   ...       NaN
                        att_car           NaN     NaN   ...       NaN
                        yds_car           NaN     NaN   ...       NaN
                        td_car            NaN     NaN   ...       NaN
                        tar_car           NaN     NaN   ...       NaN
                        rec_yds_car       NaN     NaN   ...       NaN
                        def_rk_car        NaN     NaN   ...       NaN
                        games             NaN     NaN   ...       NaN
                        year              NaN     NaN   ...       NaN
                        def_rk            NaN     NaN   ...       NaN
                        h/a_1             NaN     NaN   ...       NaN
                        surface_0         NaN     NaN   ...       NaN
                        points            NaN     NaN   ...       NaN
Cedric Peerman_reframed Week              NaN     NaN   ...       NaN
                        Opponent          NaN     NaN   ...       NaN
...                                       ...     ...   ...       ...
Tyler Varga_reframed    surface_0         NaN     NaN   ...       NaN
                        points            NaN     NaN   ...       NaN
Will Johnson_reframed   Week              NaN     NaN   ...       NaN
                        Opponent          NaN     NaN   ...       NaN
                        att_avg           NaN     NaN   ...       NaN
                        yds_avg           NaN     NaN   ...       NaN
                        td_avg            NaN     NaN   ...       NaN
                        tar_avg           NaN     NaN   ...       NaN
                        rec_yds_avg       NaN     NaN   ...       NaN
                        def_rk_avg        NaN     NaN   ...       NaN
                        games_ma          NaN     NaN   ...       NaN
                        att_ma            NaN     NaN   ...       NaN
                        yds_ma            NaN     NaN   ...       NaN
                        td_ma             NaN     NaN   ...       NaN
                        tar_ma            NaN     NaN   ...       NaN
                        rec_yds_ma        NaN     NaN   ...       NaN
                        def_rk_ma         NaN     NaN   ...       NaN
                        games_car         NaN     NaN   ...       NaN
                        att_car           NaN     NaN   ...       NaN
                        yds_car           NaN     NaN   ...       NaN
                        td_car            NaN     NaN   ...       NaN
                        tar_car           NaN     NaN   ...       NaN
                        rec_yds_car       NaN     NaN   ...       NaN
                        def_rk_car        NaN     NaN   ...       NaN
                        games             NaN     NaN   ...       NaN
                        year              NaN     NaN   ...       NaN
                        def_rk            NaN     NaN   ...       NaN
                        h/a_1             NaN     NaN   ...       NaN
                        surface_0         NaN     NaN   ...       NaN
                        points            NaN     NaN   ...       NaN

                                     tar_car  rec_yds_car  def_rk_car  games  \
                        Name
Brandon Burks_reframed  Week             NaN          NaN         NaN    NaN
                        Opponent         NaN          NaN         NaN    NaN
                        att_avg          NaN          NaN         NaN    NaN
                        yds_avg          NaN          NaN         NaN    NaN
                        td_avg           NaN          NaN         NaN    NaN
                        tar_avg          NaN          NaN         NaN    NaN
                        rec_yds_avg      NaN          NaN         NaN    NaN
                        def_rk_avg       NaN          NaN         NaN    NaN
                        games_ma         NaN          NaN         NaN    NaN
                        att_ma           NaN          NaN         NaN    NaN
                        yds_ma           NaN          NaN         NaN    NaN
                        td_ma            NaN          NaN         NaN    NaN
                        tar_ma           NaN          NaN         NaN    NaN
                        rec_yds_ma       NaN          NaN         NaN    NaN
                        def_rk_ma        NaN          NaN         NaN    NaN
                        games_car        NaN          NaN         NaN    NaN
                        att_car          NaN          NaN         NaN    NaN
                        yds_car          NaN          NaN         NaN    NaN
                        td_car           NaN          NaN         NaN    NaN
                        tar_car          NaN          NaN         NaN    NaN
                        rec_yds_car      NaN          NaN         NaN    NaN
                        def_rk_car       NaN          NaN         NaN    NaN
                        games            NaN          NaN         NaN    NaN
                        year             NaN          NaN         NaN    NaN
                        def_rk           NaN          NaN         NaN    NaN
                        h/a_1            NaN          NaN         NaN    NaN
                        surface_0        NaN          NaN         NaN    NaN
                        points           NaN          NaN         NaN    NaN
Cedric Peerman_reframed Week             NaN          NaN         NaN    NaN
                        Opponent         NaN          NaN         NaN    NaN
...                                      ...          ...         ...    ...
Tyler Varga_reframed    surface_0        NaN          NaN         NaN    NaN
                        points           NaN          NaN         NaN    NaN
Will Johnson_reframed   Week             NaN          NaN         NaN    NaN
                        Opponent         NaN          NaN         NaN    NaN
                        att_avg          NaN          NaN         NaN    NaN
                        yds_avg          NaN          NaN         NaN    NaN
                        td_avg           NaN          NaN         NaN    NaN
                        tar_avg          NaN          NaN         NaN    NaN
                        rec_yds_avg      NaN          NaN         NaN    NaN
                        def_rk_avg       NaN          NaN         NaN    NaN
                        games_ma         NaN          NaN         NaN    NaN
                        att_ma           NaN          NaN         NaN    NaN
                        yds_ma           NaN          NaN         NaN    NaN
                        td_ma            NaN          NaN         NaN    NaN
                        tar_ma           NaN          NaN         NaN    NaN
                        rec_yds_ma       NaN          NaN         NaN    NaN
                        def_rk_ma        NaN          NaN         NaN    NaN
                        games_car        NaN          NaN         NaN    NaN
                        att_car          NaN          NaN         NaN    NaN
                        yds_car          NaN          NaN         NaN    NaN
                        td_car           NaN          NaN         NaN    NaN
                        tar_car          NaN          NaN         NaN    NaN
                        rec_yds_car      NaN          NaN         NaN    NaN
                        def_rk_car       NaN          NaN         NaN    NaN
                        games            NaN          NaN         NaN    NaN
                        year             NaN          NaN         NaN    NaN
                        def_rk           NaN          NaN         NaN    NaN
                        h/a_1            NaN          NaN         NaN    NaN
                        surface_0        NaN          NaN         NaN    NaN
                        points           NaN          NaN         NaN    NaN

                                     year  def_rk  h/a_1  surface_0  points
                        Name
Brandon Burks_reframed  Week          NaN     NaN    NaN        NaN     NaN
                        Opponent      NaN     NaN    NaN        NaN     NaN
                        att_avg       NaN     NaN    NaN        NaN     NaN
                        yds_avg       NaN     NaN    NaN        NaN     NaN
                        td_avg        NaN     NaN    NaN        NaN     NaN
                        tar_avg       NaN     NaN    NaN        NaN     NaN
                        rec_yds_avg   NaN     NaN    NaN        NaN     NaN
                        def_rk_avg    NaN     NaN    NaN        NaN     NaN
                        games_ma      NaN     NaN    NaN        NaN     NaN
                        att_ma        NaN     NaN    NaN        NaN     NaN
                        yds_ma        NaN     NaN    NaN        NaN     NaN
                        td_ma         NaN     NaN    NaN        NaN     NaN
                        tar_ma        NaN     NaN    NaN        NaN     NaN
                        rec_yds_ma    NaN     NaN    NaN        NaN     NaN
                        def_rk_ma     NaN     NaN    NaN        NaN     NaN
                        games_car     NaN     NaN    NaN        NaN     NaN
                        att_car       NaN     NaN    NaN        NaN     NaN
                        yds_car       NaN     NaN    NaN        NaN     NaN
                        td_car        NaN     NaN    NaN        NaN     NaN

AttributeError: 'NoneType' object has no attribute 'nunique'

In [167]:
rb_stats.dropna(axis=0, inplace=True)
rb_stats.shape

(4193, 28)

In [168]:
rb_stats.isnull().sum()

Week           0
Opponent       0
att_avg        0
yds_avg        0
td_avg         0
tar_avg        0
rec_yds_avg    0
def_rk_avg     0
games_ma       0
att_ma         0
yds_ma         0
td_ma          0
tar_ma         0
rec_yds_ma     0
def_rk_ma      0
games_car      0
att_car        0
yds_car        0
td_car         0
tar_car        0
rec_yds_car    0
def_rk_car     0
games          0
year           0
def_rk         0
h/a_1          0
surface_0      0
points         0
dtype: int64

In [162]:
temp.loc['Tyler Varga_reframed']

Empty DataFrame
Columns: [Week, Opponent, att_avg, yds_avg, td_avg, tar_avg, rec_yds_avg, def_rk_avg, games_ma, att_ma, yds_ma, td_ma, tar_ma, rec_yds_ma, def_rk_ma, games_car, att_car, yds_car, td_car, tar_car, rec_yds_car, def_rk_car, games, year, def_rk, h/a_1, surface_0, points]
Index: []

[0 rows x 28 columns]

In [165]:
qb_sorted_dict['Aaron Rodgers']['points']

0       22.82
629     28.62
1229    23.06
1529    23.56
1829    20.54
2129    24.94
39      10.16
652     37.90
947     32.64
1245    22.26
1548    19.42
1845    23.52
2168    16.04
74      10.62
1268    37.92
1570    26.40
1862    28.82
2205    19.90
113     28.06
985     31.88
1288    16.26
1885    23.06
2245    17.02
151     25.10
709     15.76
1002    18.24
1306    18.54
1602    17.86
1902    24.04
2282    33.68
        ...
287     26.02
1372    36.96
1668    27.18
1099    39.60
1390    25.12
1686    32.54
357     15.74
1112    31.84
1406    19.08
1705    32.34
392     10.96
1128    19.76
1722    26.12
430     14.94
1144    27.92
1440    26.62
1747    16.96
465     14.12
1161    30.88
1460    19.42
1762    21.24
507     25.94
2080    24.90
547     32.78
1195    18.72
1790    40.18
587     28.60
912     22.22
1215    24.44
1812    37.20
Name: points, Length: 73, dtype: float64

In [167]:
qb_stats.loc['Aaron Rodgers_reframed']['points']

1     22.82
2     28.62
3     23.06
4     23.56
5     20.54
6     24.94
7     10.16
8     37.90
9     32.64
10    22.26
11    19.42
12    23.52
13    16.04
14    10.62
15    37.92
16    26.40
17    28.82
18    19.90
19    28.06
20    31.88
21    16.26
22    23.06
23    17.02
24    25.10
25    15.76
26    18.24
27    18.54
28    17.86
29    24.04
30    33.68
      ...
44    26.02
45    36.96
46    27.18
47    39.60
48    25.12
49    32.54
50    15.74
51    31.84
52    19.08
53    32.34
54    10.96
55    19.76
56    26.12
57    14.94
58    27.92
59    26.62
60    16.96
61    14.12
62    30.88
63    19.42
64    21.24
65    25.94
66    24.90
67    32.78
68    18.72
69    40.18
70    28.60
71    22.22
72    24.44
73    37.20
Name: points, Length: 73, dtype: float64

In [115]:
non_reframed = ['year','def_rk','h/a_1','surface_0','salary','points']

for player in te_stats['Name']:
    for col in non_reframed:
        if len(reframed_dict['{}_reframed'.format(player)]['points']) != len(te_sorted_dict['{}'.format(player)][col][1:].values):
            print(player)

NameError: name 'reframed_dict' is not defined

In [168]:
qb_stats.isnull().sum()

Name          0
Week          0
Opponent      0
att_avg       0
comp%_avg     0
yds_avg       0
td_avg        0
def_rk_avg    0
games_ma      0
att_ma        0
comp%_ma      0
yds_ma        0
td_ma         0
def_rk_ma     0
games_car     0
att_car       0
comp%_car     0
yds_car       0
td_car        0
def_rk_car    0
games         0
year          0
def_rk        0
h/a_1         0
surface_0     0
points        0
dtype: int64

In [170]:
qb_stats.to_csv('input/qb/qb_stats.csv', index=False)

In [170]:
wr = pd.read_csv('input/wr/wr_stats.csv')
wr.head()

,Unnamed: 0,Name,Week,Opponent,tar_avg,rec_avg,yds_avg,td_avg,yds/tar_avg,yds/rec_avg,...,yds/tar_car,yds/rec_car,def_rk_car,games,year,def_rk,h/a_1,surface_0,points,0
0,AJ Green_reframed,AJ Green,1.0,OAK,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,1.0,2015.0,22.0,0.0,1.0,11.3,NaN
1,AJ Green_reframed,AJ Green,2.0,NYJ,8.00,5.00,63.00,0.00,7.90,12.60,...,7.90,12.60,22.00,17.0,2016.0,15.0,0.0,0.0,39.0,NaN
2,AJ Green_reframed,AJ Green,3.0,BAL,6.00,4.00,54.00,0.50,9.55,13.80,...,9.55,13.80,18.00,27.0,2017.0,5.0,1.0,0.0,12.4,NaN
3,AJ Green_reframed,AJ Green,4.0,IND,8.33,6.00,111.67,1.00,12.20,16.77,...,12.20,16.77,17.67,43.0,2018.0,1.0,0.0,0.0,20.2,NaN
4,AJ Green_reframed,AJ Green,5.0,LAC,8.75,6.25,104.25,0.75,11.20,15.50,...,11.20,15.50,15.00,2.0,2015.0,14.0,1.0,0.0,13.5,NaN

In [204]:
te_stats=te_stats.iloc[:,:-1]
te_stats.isnull().sum()

Name          0.0
Week          0.0
Opponent      0.0
tar_avg       0.0
rec_avg       0.0
yds_avg       0.0
td_avg        0.0
fum_avg       0.0
def_rk_avg    0.0
tar_ma        0.0
rec_ma        0.0
yds_ma        0.0
td_ma         0.0
fum_ma        0.0
def_rk_ma     0.0
tar_car       0.0
rec_car       0.0
yds_car       0.0
td_car        0.0
fum_car       0.0
def_rk_car    0.0
def_rk        0.0
h/a_1         0.0
surface_0     0.0
points        0.0
games         0.0
year          0.0
dtype: float64

In [205]:
te_stats.to_csv('input/te/te_stats.csv', index=True)

In [202]:
te_stats.dropna(axis=0, inplace=True)

In [203]:
te_stats.drop('Unnamed: 0', axis=1, inplace=True)

In [135]:
rb_stats.columns

Index(['Week', 'games_avg', 'att_avg', 'yds_avg', 'td_avg', 'tar_avg',
       'rec_yds_avg', 'def_rk_avg', 'games_ma', 'att_ma', 'yds_ma', 'td_ma',
       'tar_ma', 'rec_yds_ma', 'def_rk_ma', 'games_car', 'att_car', 'yds_car',
       'td_car', 'tar_car', 'rec_yds_car', 'def_rk_car', 'year', 'def_rk',
       'h/a_1', 'surface_0', 'salary', 'points'],
      dtype='object')

In [200]:
te_stats = pd.read_csv('input/te/te_stats.csv')

In [201]:
te_stats.isnull().sum()

Unnamed: 0       0
Name             0
Week           416
Opponent       416
tar_avg        416
rec_avg        416
yds_avg        416
td_avg         416
fum_avg        416
def_rk_avg     416
tar_ma         416
rec_ma         416
yds_ma         416
td_ma          416
fum_ma         416
def_rk_ma      416
tar_car        416
rec_car        416
yds_car        416
td_car         416
fum_car        416
def_rk_car     416
def_rk         416
h/a_1          416
surface_0      416
points         416
games          416
year           416
0             3167
dtype: int64