## Location Dataframe

In [633]:
"""This is a program designed to add the location and surface type the DraftKings historical stats dataframe.
for every players game and a home or away attribute and the whether the game was played on grass or turf surface"""

'This is a program designed to add the location and surface type the DraftKings historical stats dataframe.\nfor every players game and a home or away attribute and the whether the game was played on grass or turf surface'

In [1]:
# Import packages

import pandas as pd
import numpy as np
import http.client, urllib.request, urllib.parse, urllib.error, base64
import json
from bs4 import BeautifulSoup
import requests
import re

In [573]:
# ead in the original DraftKings dataframe

qb = pd.read_csv('input/qb/dk_stas_sal.csv')

qb.tail()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
1795,18525,Joe Callahan,GB,17,DET,5,7,71.4,11,1.6,...,0,74.11,0,0,0.0,0,0.44,4400,2017,21
1796,18811,Mitch Trubisky,CHI,17,MIN,20,36,55.6,178,4.9,...,0,68.98,1,2,2.0,0,7.32,4700,2017,1
1797,18868,Deshone Kizer,CLE,17,PIT,16,30,53.3,314,10.5,...,1,98.47,6,61,10.2,0,28.66,4400,2017,6
1798,18890,Patrick Mahomes,KC,17,DEN,22,35,62.9,284,8.1,...,1,76.37,7,10,1.4,0,11.36,4800,2017,5
1799,19238,Taysom Hill,NO,17,TB,0,0,0.0,0,0.0,...,0,0.00,0,0,0.0,0,0.00,4500,2017,31

# Create a list of urls from Pro Football Reference.com which contain the location of every game in the 2015, 2016, 2-17 seasons

In [116]:
url1 ='https://www.pro-football-reference.com/years/2015/games.htm'

In [207]:
url2 =  'https://www.pro-football-reference.com/years/2016/games.htm'

In [240]:
url3 = 'https://www.pro-football-reference.com/years/2017/games.htm'

In [241]:
page = requests.get(url3)

page

In [242]:
# Use BeautifulSoup to retreive data the data from Pro Footbal Reference.com 

soup = BeautifulSoup(page.text,'html.parser')

weeks = []  
for tr in soup.find_all('tr'):
    weeks.append(tr.text)

In [243]:
# Remove any lines that dont describe weekly game

for val in weeks:
    try:
        weeks.remove('\nWeek\nDay\nDate\nTime\nWinner/tie\n\nLoser/tie\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n')
    except:
        None

In [244]:
weeks

['1ThuSeptember 78:30PMKansas City Chiefs@New England Patriotsboxscore422753713710',
 '1SunSeptember 101:00PMPittsburgh Steelers@Cleveland Brownsboxscore211829012371',
 '1SunSeptember 101:00PMBaltimore Ravens@Cincinnati Bengalsboxscore20026812215',
 '1SunSeptember 101:00PMPhiladelphia Eagles@Washington Redskinsboxscore301735622644',
 '1SunSeptember 101:00PMDetroit LionsArizona Cardinalsboxscore352336713084',
 '1SunSeptember 101:00PMJacksonville Jaguars@Houston Texansboxscore29728002034',
 '1SunSeptember 101:00PMOakland Raiders@Tennessee Titansboxscore261635903500',
 '1SunSeptember 101:00PMAtlanta Falcons@Chicago Bearsboxscore231737203010',
 '1SunSeptember 101:00PMBuffalo BillsNew York Jetsboxscore211240812142',
 '1SunSeptember 104:05PMLos Angeles RamsIndianapolis Coltsboxscore46937312253',
 '1SunSeptember 104:25PMCarolina Panthers@San Francisco 49ersboxscore23328722172',
 '1SunSeptember 104:25PMGreen Bay PackersSeattle Seahawksboxscore17937012251',
 '1SunSeptember 108:30PMDallas CowboysNew York Giantsboxscore19339202331',
 '1MonSeptember 117:10PMMinnesota VikingsNew Orleans Saintsboxscore291947003440',
 '1MonSeptember 1110:20PMDenver BroncosLos Angeles Chargersboxscore242132122491',
 '2ThuSeptember 148:25PMHouston Texans@Cincinnati Bengalsboxscore13926602951',
 '2SunSeptember 171:00PMPittsburgh SteelersMinnesota Vikingsboxscore26933502371',
 '2SunSeptember 171:00PMTampa Bay BuccaneersChicago Bearsboxscore29731113104',
 '2SunSeptember 171:00PMBaltimore RavensCleveland Brownsboxscore241033723865',
 '2SunSeptember 171:00PMTennessee Titans@Jacksonville Jaguarsboxscore371639013103',
 '2SunSeptember 171:00PMKansas City ChiefsPhiladelphia Eaglesboxscore272034404062',
 '2SunSeptember 171:00PMArizona Cardinals@Indianapolis Coltsboxscore161338912661',
 '2SunSeptember 171:00PMCarolina PanthersBuffalo Billsboxscore9325501760',
 '2SunSeptember 171:00PMNew England Patriots@New Orleans Saintsboxscore362055504290',
 '2SunSeptember 174:05PMMiami Dolphins@Los Angeles Chargersboxscore191733603670',
 '2SunSeptember 174:05PMOakland RaidersNew York Jetsboxscore452041002712',
 '2SunSeptember 174:25PMSeattle SeahawksSan Francisco 49ersboxscore12931202481',
 '2SunSeptember 174:25PMDenver BroncosDallas Cowboysboxscore421738022682',
 '2SunSeptember 174:25PMWashington Redskins@Los Angeles Ramsboxscore272038503322',
 '2SunSeptember 178:30PMAtlanta FalconsGreen Bay Packersboxscore342336403672',
 '2MonSeptember 188:30PMDetroit Lions@New York Giantsboxscore241025712701',
 '3ThuSeptember 218:25PMLos Angeles Rams@San Francisco 49ersboxscore413941824212',
 '3SunSeptember 249:30AMJacksonville JaguarsBaltimore Ravensboxscore44741001863',
 '3SunSeptember 241:00PMNew York JetsMiami Dolphinsboxscore20633612252',
 '3SunSeptember 241:00PMAtlanta Falcons@Detroit Lionsboxscore302642833240',
 '3SunSeptember 241:00PMBuffalo BillsDenver Broncosboxscore261627203662',
 '3SunSeptember 241:00PMMinnesota VikingsTampa Bay Buccaneersboxscore341749403423',
 '3SunSeptember 241:00PMChicago BearsPittsburgh Steelersboxscore231730622822',
 '3SunSeptember 241:00PMNew Orleans Saints@Carolina Panthersboxscore341336202883',
 '3SunSeptember 241:00PMIndianapolis ColtsCleveland Brownsboxscore312833513463',
 '3SunSeptember 241:00PMNew England PatriotsHouston Texansboxscore363339614172',
 '3SunSeptember 241:00PMPhiladelphia EaglesNew York Giantsboxscore272435414152',
 '3SunSeptember 244:05PMTennessee TitansSeattle Seahawksboxscore332742004330',
 '3SunSeptember 244:25PMKansas City Chiefs@Los Angeles Chargersboxscore241031103303',
 '3SunSeptember 244:25PMGreen Bay PackersCincinnati Bengalsboxscore272434413011',
 '3SunSeptember 248:30PMWashington RedskinsOakland Raidersboxscore271047221283',
 '3MonSeptember 258:30PMDallas Cowboys@Arizona Cardinalsboxscore281727303320',
 '4ThuSeptember 288:25PMGreen Bay PackersChicago Bearsboxscore351426003084',
 '4SunOctober 19:30AMNew Orleans Saints@Miami Dolphinsboxscore20034701861',
 '4SunOctober 11:00PMNew York JetsJacksonville Jaguarsboxscore232047123111',
 '4SunOctober 11:00PMLos Angeles Rams@Dallas Cowboysboxscore353041204402',
 '4SunOctober 11:00PMDetroit Lions@Minnesota Vikingsboxscore14725102843',
 '4SunOctober 11:00PMPittsburgh Steelers@Baltimore Ravensboxscore26938112883',
 '4SunOctober 11:00PMBuffalo Bills@Atlanta Falconsboxscore231728103893',
 '4SunOctober 11:00PMCarolina Panthers@New England Patriotsboxscore333044423730',
 '4SunOctober 11:00PMCincinnati Bengals@Cleveland Brownsboxscore31735012151',
 '4SunOctober 11:00PMHouston TexansTennessee Titansboxscore571444511955',
 '4SunOctober 14:05PMTampa Bay BuccaneersNew York Giantsboxscore252343403790',
 '4SunOctober 14:05PMPhiladelphia Eagles@Los Angeles Chargersboxscore262445404001',
 '4SunOctober 14:05PMArizona CardinalsSan Francisco 49ersboxscore181536813051',
 '4SunOctober 14:25PMDenver BroncosOakland Raidersboxscore161029802541',
 '4SunOctober 18:30PMSeattle SeahawksIndianapolis Coltsboxscore461847722372',
 '4MonOctober 28:30PMKansas City ChiefsWashington Redskinsboxscore292042903311',
 '5ThuOctober 58:25PMNew England Patriots@Tampa Bay Buccaneersboxscore191440224090',
 '5SunOctober 81:00PMMiami DolphinsTennessee Titansboxscore161017821882',
 '5SunOctober 81:00PMCarolina Panthers@Detroit Lionsboxscore272436202421',
 '5SunOctober 81:00PMPhiladelphia EaglesArizona Cardinalsboxscore34741913071',
 '5SunOctober 81:00PMJacksonville Jaguars@Pittsburgh Steelersboxscore30931313715',
 '5SunOctober 81:00PMLos Angeles Chargers@New York Giantsboxscore272238213352',
 '5SunOctober 81:00PMIndianapolis ColtsSan Francisco 49ersboxscore262344714020',
 '5SunOctober 81:00PMCincinnati BengalsBuffalo Billsboxscore201638832211',
 '5SunOctober 81:00PMNew York Jets@Cleveland Brownsboxscore171421214193',
 '5SunOctober 84:05PMBaltimore Ravens@Oakland Raidersboxscore301736502451',
 '5SunOctober 84:05PMSeattle Seahawks@Los Angeles Ramsboxscore161024123755',
 '5SunOctober 84:25PMGreen Bay Packers@Dallas Cowboysboxscore353134214083',
 '5SunOctober 88:30PMKansas City Chiefs@Houston Texansboxscore423445003921',
 '5MonOctober 98:30PMMinnesota Vikings@Chicago Bearsboxscore201730002742',
 '6ThuOctober 128:25PMPhiladelphia Eagles@Carolina Panthersboxscore282331013053',
 '6SunOctober 151:00PMMiami Dolphins@Atlanta Falconsboxscore201728913391',
 '6SunOctober 151:00PMHouston TexansCleveland Brownsboxscore331734012473',
 '6SunOctober 151:00PMChicago Bears@Baltimore Ravensboxscore272434222913',
 '6SunOctober 151:00PMNew Orleans SaintsDetroit Lionsboxscore523837933475',
 '6SunOctober 151:00PMWashington RedskinsSan Francisco 49ersboxscore262441923351',
 '6SunOctober 151:00PMMinnesota VikingsGreen Bay Packersboxscore231035122273',
 '6SunOctober 151:00PMNew England Patriots@New York Jetsboxscore241737524083',
 '6SunOctober 154:05PMArizona CardinalsTampa Bay Buccaneersboxscore383343224122',
 '6SunOctober 154:05PMLos Angeles Rams@Jacksonville Jaguarsboxscore271724913891',
 '6SunOctober 154:25PMLos Angeles Chargers@Oakland Raidersboxscore171634312742',
 '6SunOctober 154:25PMPittsburgh Steelers@Kansas City Chiefsboxscore191343912510',
 '6SunOctober 158:30PMNew York Giants@Denver Broncosboxscore231026604123',
 '6MonOctober 168:30PMTennessee TitansIndianapolis Coltsboxscore362247312971',
 '7ThuOctober 198:25PMOakland RaidersKansas City Chiefsboxscore313050504250',
 '7SunOctober 221:00PMMiami DolphinsNew York Jetsboxscore312835722722',
 '7SunOctober 221:00PMBuffalo BillsTampa Bay Buccaneersboxscore302743414473',
 '7SunOctober 221:00PMJacksonville Jaguars@Indianapolis Coltsboxscore27051822320',
 '7SunOctober 221:00PMTennessee Titans@Cleveland Brownsboxscore12926912843',
 '7SunOctober 221:00PMMinnesota VikingsBaltimore Ravensboxscore241635712080',
 '7SunOctober 221:00PMChicago BearsCarolina Panthersboxscore17315302933',
 '7SunOctober 221:00PMLos Angeles RamsArizona Cardinalsboxscore33042511962',
 '7SunOctober 221:00PMNew Orleans Saints@Green Bay Packersboxscore261748522601',
 '7SunOctober 224:05PMDallas Cowboys@San Francisco 49ersboxscore401050102903',
 '7SunOctober 224:25PMPittsburgh SteelersCincinnati Bengalsboxscore291442001792',
 '7SunOctober 224:25PMLos Angeles ChargersDenver Broncosboxscore21024202513',
 '7SunOctober 224:25PMSeattle Seahawks@New York Giantsboxscore24742511771',
 '7SunOctober 228:30PMNew England PatriotsAtlanta Falconsboxscore23740303430',
 '7MonOctober 238:30PMPhiladelphia EaglesWashington Redskinsboxscore342437113441',
 '8ThuOctober 268:25PMBaltimore RavensMiami Dolphinsboxscore40029501962',
 '8SunOctober 299:30AMMinnesota Vikings@Cleveland Brownsboxscore331637512762',
 '8SunOctober 291:00PMBuffalo BillsOakland Raidersboxscore341433103674',
 '8SunOctober 291:00PMAtlanta Falcons@New York Jetsboxscore252038622791',
 '8SunOctober 291:00PMCincinnati BengalsIndianapolis Coltsboxscore242327623311',
 '8SunOctober 291:00PMPhiladelphia EaglesSan Francisco 49ersboxscore331030412382',
 '8SunOctober 291:00PMNew England PatriotsLos Angeles Chargersboxscore211341403491',
 '8SunOctober 291:00PMNew Orleans SaintsChicago Bearsboxscore201238723071',
 '8SunOctober 291:00PMCarolina Panthers@Tampa Bay Buccaneersboxscore17325412793',
 '8SunOctober 294:05PMSeattle SeahawksHouston Texansboxscore413847915093',
 '8SunOctober 294:25PMDallas Cowboys@Washington Redskinsboxscore331930712853',
 '8SunOctober 298:30PMPittsburgh Steelers@Detroit Lionsboxscore201539224821',
 '8MonOctober 308:30PMKansas City ChiefsDenver Broncosboxscore291927623645',
 '9ThuNovember 28:25PMNew York JetsBuffalo Billsboxscore342133103073',
 '9SunNovember 51:00PMLos Angeles Rams@New York Giantsboxscore511747303193',
 '9SunNovember 51:00PMTennessee TitansBaltimore Ravensboxscore232025713412',
 '9SunNovember 51:00PMNew Orleans SaintsTampa Bay Buccaneersboxscore301040722001',
 '9SunNovember 51:00PMCarolina PanthersAtlanta Falconsboxscore201733023551',
 '9SunNovember 51:00PMJacksonville JaguarsCincinnati Bengalsboxscore23740811480',
 '9SunNovember 51:00PMPhiladelphia EaglesDenver Broncosboxscore512341912262',
 '9SunNovember 51:00PMIndianapolis Colts@Houston Texansboxscore201437112881',
 '9SunNovember 54:05PMArizona Cardinals@San Francisco 49ersboxscore201036823292',
 '9SunNovember 54:05PMWashington Redskins@Seattle Seahawksboxscore171424414372',
 '9SunNovember 54:25PMDallas CowboysKansas City Chiefsboxscore281737503231',
 '9SunNovember 58:30PMOakland Raiders@Miami Dolphinsboxscore272437923951',
 '9MonNovember 68:30PMDetroit Lions@Green Bay Packersboxscore301741713110',
 '10ThuNovember 98:25PMSeattle Seahawks@Arizona Cardinalsboxscore221628702901',
 '10SunNovember 121:00PMTennessee TitansCincinnati Bengalsboxscore242041623082',
 '10SunNovember 121:00PMNew Orleans Saints@Buffalo Billsboxscore471048211981',
 '10SunNovember 121:00PMGreen Bay Packers@Chicago Bearsboxscore231634203231',
 '10SunNovember 121:00PMJacksonville JaguarsLos Angeles Chargersboxscore201739823222',
 '10SunNovember 121:00PMMinnesota Vikings@Washington Redskinsboxscore383040623941',
 '10SunNovember 121:00PMDetroit LionsCleveland Brownsboxscore382434514132',
 '10SunNovember 121:00PMTampa Bay BuccaneersNew York Jetsboxscore151027112752',
 '10SunNovember 121:00PMPittsburgh Steelers@Indianapolis Coltsboxscore201731612671',
 '10SunNovember 124:05PMLos Angeles RamsHouston Texansboxscore33744302834',
 '10SunNovember 124:25PMSan Francisco 49ersNew York Giantsboxscore312147423741',
 '10SunNovember 124:25PMAtlanta FalconsDallas Cowboysboxscore27733612332',
 '10SunNovember 128:30PMNew England Patriots@Denver Broncosboxscore411639603392',
 '10MonNovember 138:30PMCarolina PanthersMiami Dolphinsboxscore452154803131',
 '11ThuNovember 168:25PMPittsburgh SteelersTennessee Titansboxscore401734903164',
 '11SunNovember 191:00PMDetroit Lions@Chicago Bearsboxscore272435213981',
 '11SunNovember 191:00PMMinnesota VikingsLos Angeles Ramsboxscore24745102541',
 '11SunNovember 191:00PMBaltimore Ravens@Green Bay Packersboxscore23021912655',
 '11SunNovember 191:00PMNew York GiantsKansas City Chiefsboxscore12931713633',
 '11SunNovember 191:00PMJacksonville Jaguars@Cleveland Brownsboxscore19728411845',
 '11SunNovember 191:00PMNew Orleans SaintsWashington Redskinsboxscore343153514560',
 '11SunNovember 191:00PMHouston TexansArizona Cardinalsboxscore312135722922',
 '11SunNovember 191:00PMTampa Bay Buccaneers@Miami Dolphinsboxscore302032104485',
 '11SunNovember 194:05PMLos Angeles ChargersBuffalo Billsboxscore542442903936',
 '11SunNovember 194:25PMCincinnati Bengals@Denver Broncosboxscore201719003412',
 '11SunNovember 194:25PMNew England Patriots@Oakland Raidersboxscore33842103442',
 '11SunNovember 198:30PMPhiladelphia Eagles@Dallas Cowboysboxscore37938302254',
 '11MonNovember 208:30PMAtlanta Falcons@Seattle Seahawksboxscore343127913602',
 '12ThuNovember 2312:30PMMinnesota Vikings@Detroit Lionsboxscore302340802892',
 '12ThuNovember 234:30PMLos Angeles Chargers@Dallas Cowboysboxscore28651502472',
 '12ThuNovember 238:30PMWashington RedskinsNew York Giantsboxscore201032311701',
 '12SunNovember 261:00PMBuffalo Bills@Kansas City Chiefsboxscore161026802361',
 '12SunNovember 261:00PMPhiladelphia EaglesChicago Bearsboxscore31342031402',
 '12SunNovember 261:00PMAtlanta FalconsTampa Bay Buccaneersboxscore342051613730',
 '12SunNovember 261:00PMCarolina Panthers@New York Jetsboxscore352729903911',
 '12SunNovember 261:00PMCincinnati BengalsCleveland Brownsboxscore301636104050',
 '12SunNovember 261:00PMTennessee Titans@Indianapolis Coltsboxscore201627622541',
 '12SunNovember 261:00PMNew England PatriotsMiami Dolphinsboxscore351741722213',
 '12SunNovember 264:05PMSeattle Seahawks@San Francisco 49ersboxscore241331812801',
 '12SunNovember 264:25PMOakland RaidersDenver Broncosboxscore211434812161',
 '12SunNovember 264:25PMLos Angeles RamsNew Orleans Saintsboxscore262041513460',
 '12SunNovember 264:25PMArizona CardinalsJacksonville Jaguarsboxscore272434422193',
 '12SunNovember 268:30PMPittsburgh SteelersGreen Bay Packersboxscore312846233070',
 '12MonNovember 278:30PMBaltimore RavensHouston Texansboxscore231629403033',
 '13ThuNovember 308:25PMDallas CowboysWashington Redskinsboxscore381427502804',
 '13SunDecember 31:00PMJacksonville JaguarsIndianapolis Coltsboxscore301042602902',
 '13SunDecember 31:00PMTennessee TitansHouston Texansboxscore241334413841',
 '13SunDecember 31:00PMNew England Patriots@Buffalo Billsboxscore23343512681',
 '13SunDecember 31:00PMNew York JetsKansas City Chiefsboxscore383148804740',
 '13SunDecember 31:00PMBaltimore RavensDetroit Lionsboxscore442037003723',
 '13SunDecember 31:00PMSan Francisco 49ers@Chicago Bearsboxscore151438811470',
 '13SunDecember 31:00PMMiami DolphinsDenver Broncosboxscore35936732703',
 '13SunDecember 31:00PMMinnesota Vikings@Atlanta Falconsboxscore14931202750',
 '13SunDecember 31:00PMGreen Bay PackersTampa Bay Buccaneersboxscore262027613951',
 '13SunDecember 34:05PMLos Angeles ChargersCleveland Brownsboxscore191042902912',
 '13SunDecember 34:25PMLos Angeles Rams@Arizona Cardinalsboxscore321630313052',
 '13SunDecember 34:25PMNew Orleans SaintsCarolina Panthersboxscore312140012791',
 '13SunDecember 34:25PMOakland RaidersNew York Giantsboxscore241740112652',
 '13SunDecember 38:30PMSeattle SeahawksPhiladelphia Eaglesboxscore241031004252',
 '13MonDecember 48:30PMPittsburgh Steelers@Cincinnati Bengalsboxscore232037413530',
 '14ThuDecember 78:25PMAtlanta FalconsNew Orleans Saintsboxscore201734333061',
 '14SunDecember 101:00PMCarolina PanthersMinnesota Vikingsboxscore312434513563',
 '14SunDecember 101:00PMDallas Cowboys@New York Giantsboxscore301045403302',
 '14SunDecember 101:00PMSan Francisco 49ers@Houston Texansboxscore261641613111',
 '14SunDecember 101:00PMBuffalo BillsIndianapolis Coltsboxscore13731922270',
 '14SunDecember 101:00PMKansas City ChiefsOakland Raidersboxscore261540812683',
 '14SunDecember 101:00PMDetroit Lions@Tampa Bay Buccaneersboxscore242143434005',
 '14SunDecember 101:00PMGreen Bay Packers@Cleveland Brownsboxscore272134103452',
 '14SunDecember 101:00PMChicago Bears@Cincinnati Bengalsboxscore33748202342',
 '14SunDecember 104:05PMDenver BroncosNew York Jetsboxscore23027301002',
 '14SunDecember 104:05PMLos Angeles ChargersWashington Redskinsboxscore301348812011',
 '14SunDecember 104:05PMArizona CardinalsTennessee Titansboxscore12726102042',
 '14SunDecember 104:25PMJacksonville JaguarsSeattle Seahawksboxscore302442414013',
 '14SunDecember 104:25PMPhiladelphia Eagles@Los Angeles Ramsboxscore433545513072',
 '14SunDecember 108:30PMPittsburgh SteelersBaltimore Ravensboxscore393854504131',
 '14MonDecember 118:30PMMiami DolphinsNew England Patriotsboxscore272036202482',
 '15ThuDecember 148:25PMDenver Broncos@Indianapolis Coltsboxscore251346212280',
 '15SatDecember 164:30PMDetroit LionsChicago Bearsboxscore201029313493',
 '15SatDecember 168:25PMKansas City ChiefsLos Angeles Chargersboxscore301339703074',
 '15SunDecember 171:00PMBuffalo BillsMiami Dolphinsboxscore241632803493',
 '15SunDecember 171:00PMNew Orleans SaintsNew York Jetsboxscore311941232942',
 '15SunDecember 171:00PMBaltimore Ravens@Cleveland Brownsboxscore271037602664',
 '15SunDecember 171:00PMMinnesota VikingsCincinnati Bengalsboxscore34734611612',
 '15SunDecember 171:00PMPhiladelphia Eagles@New York Giantsboxscore342934105041',
 '15SunDecember 171:00PMCarolina PanthersGreen Bay Packersboxscore312438703844',
 '15SunDecember 171:00PMWashington RedskinsArizona Cardinalsboxscore201521812862',
 '15SunDecember 171:00PMJacksonville JaguarsHouston Texansboxscore45746401861',
 '15SunDecember 174:05PMLos Angeles Rams@Seattle Seahawksboxscore42735211492',
 '15SunDecember 174:25PMSan Francisco 49ersTennessee Titansboxscore252341403281',
 '15SunDecember 174:25PMNew England Patriots@Pittsburgh Steelersboxscore272436014131',
 '15SunDecember 178:30PMDallas Cowboys@Oakland Raidersboxscore201733022931',
 '15MonDecember 188:30PMAtlanta Falcons@Tampa Bay Buccaneersboxscore242141003731',
 '16SatDecember 234:30PMBaltimore RavensIndianapolis Coltsboxscore231632302960',
 '16SatDecember 238:30PMMinnesota Vikings@Green Bay Packersboxscore16023602392',
 '16SunDecember 241:00PMWashington RedskinsDenver Broncosboxscore271138623303',
 '16SunDecember 241:00PMLos Angeles Chargers@New York Jetsboxscore14737902953',
 '16SunDecember 241:00PMNew England PatriotsBuffalo Billsboxscore371641113260',
 '16SunDecember 241:00PMKansas City ChiefsMiami Dolphinsboxscore291340403452',
 '16SunDecember 241:00PMCincinnati BengalsDetroit Lionsboxscore261736412761',
 '16SunDecember 241:00PMChicago BearsCleveland Brownsboxscore20325802543',
 '16SunDecember 241:00PMNew Orleans SaintsAtlanta Falconsboxscore231331513312',
 '16SunDecember 241:00PMCarolina PanthersTampa Bay Buccaneersboxscore221925513923',
 '16SunDecember 241:00PMLos Angeles Rams@Tennessee Titansboxscore272340213661',
 '16SunDecember 244:05PMSan Francisco 49ersJacksonville Jaguarsboxscore443336914723',
 '16SunDecember 244:25PMSeattle Seahawks@Dallas Cowboysboxscore211213602823',
 '16SunDecember 244:25PMArizona CardinalsNew York Giantsboxscore23028922933',
 '16MonDecember 254:30PMPittsburgh Steelers@Houston Texansboxscore34633002272',
 '16MonDecember 258:30PMPhiladelphia EaglesOakland Raidersboxscore191021622745',
 '17SunDecember 311:00PMIndianapolis ColtsHouston Texansboxscore221325002091',
 '17SunDecember 311:00PMNew England PatriotsNew York Jetsboxscore26633002470',
 '17SunDecember 311:00PMDetroit LionsGreen Bay Packersboxscore351135602564',
 '17SunDecember 311:00PMDallas Cowboys@Philadelphia Eaglesboxscore6030112192',
 '17SunDecember 311:00PMPittsburgh SteelersCleveland Brownsboxscore282434823742',
 '17SunDecember 311:00PMNew York GiantsWashington Redskinsboxscore181038111973',
 '17SunDecember 311:00PMMinnesota VikingsChicago Bearsboxscore231032702010',
 '17SunDecember 314:25PMSan Francisco 49ers@Los Angeles Ramsboxscore341346132512',
 '17SunDecember 314:25PMArizona Cardinals@Seattle Seahawksboxscore262425912960',
 '17SunDecember 314:25PMTampa Bay BuccaneersNew Orleans Saintsboxscore312445533231',
 '17SunDecember 314:25PMKansas City Chiefs@Denver Broncosboxscore272437923363',

In [245]:
weeks = weeks[0:-12]

weeks

['1ThuSeptember 78:30PMKansas City Chiefs@New England Patriotsboxscore422753713710',
 '1SunSeptember 101:00PMPittsburgh Steelers@Cleveland Brownsboxscore211829012371',
 '1SunSeptember 101:00PMBaltimore Ravens@Cincinnati Bengalsboxscore20026812215',
 '1SunSeptember 101:00PMPhiladelphia Eagles@Washington Redskinsboxscore301735622644',
 '1SunSeptember 101:00PMDetroit LionsArizona Cardinalsboxscore352336713084',
 '1SunSeptember 101:00PMJacksonville Jaguars@Houston Texansboxscore29728002034',
 '1SunSeptember 101:00PMOakland Raiders@Tennessee Titansboxscore261635903500',
 '1SunSeptember 101:00PMAtlanta Falcons@Chicago Bearsboxscore231737203010',
 '1SunSeptember 101:00PMBuffalo BillsNew York Jetsboxscore211240812142',
 '1SunSeptember 104:05PMLos Angeles RamsIndianapolis Coltsboxscore46937312253',
 '1SunSeptember 104:25PMCarolina Panthers@San Francisco 49ersboxscore23328722172',
 '1SunSeptember 104:25PMGreen Bay PackersSeattle Seahawksboxscore17937012251',
 '1SunSeptember 108:30PMDallas CowboysNew York Giantsboxscore19339202331',
 '1MonSeptember 117:10PMMinnesota VikingsNew Orleans Saintsboxscore291947003440',
 '1MonSeptember 1110:20PMDenver BroncosLos Angeles Chargersboxscore242132122491',
 '2ThuSeptember 148:25PMHouston Texans@Cincinnati Bengalsboxscore13926602951',
 '2SunSeptember 171:00PMPittsburgh SteelersMinnesota Vikingsboxscore26933502371',
 '2SunSeptember 171:00PMTampa Bay BuccaneersChicago Bearsboxscore29731113104',
 '2SunSeptember 171:00PMBaltimore RavensCleveland Brownsboxscore241033723865',
 '2SunSeptember 171:00PMTennessee Titans@Jacksonville Jaguarsboxscore371639013103',
 '2SunSeptember 171:00PMKansas City ChiefsPhiladelphia Eaglesboxscore272034404062',
 '2SunSeptember 171:00PMArizona Cardinals@Indianapolis Coltsboxscore161338912661',
 '2SunSeptember 171:00PMCarolina PanthersBuffalo Billsboxscore9325501760',
 '2SunSeptember 171:00PMNew England Patriots@New Orleans Saintsboxscore362055504290',
 '2SunSeptember 174:05PMMiami Dolphins@Los Angeles Chargersboxscore191733603670',
 '2SunSeptember 174:05PMOakland RaidersNew York Jetsboxscore452041002712',
 '2SunSeptember 174:25PMSeattle SeahawksSan Francisco 49ersboxscore12931202481',
 '2SunSeptember 174:25PMDenver BroncosDallas Cowboysboxscore421738022682',
 '2SunSeptember 174:25PMWashington Redskins@Los Angeles Ramsboxscore272038503322',
 '2SunSeptember 178:30PMAtlanta FalconsGreen Bay Packersboxscore342336403672',
 '2MonSeptember 188:30PMDetroit Lions@New York Giantsboxscore241025712701',
 '3ThuSeptember 218:25PMLos Angeles Rams@San Francisco 49ersboxscore413941824212',
 '3SunSeptember 249:30AMJacksonville JaguarsBaltimore Ravensboxscore44741001863',
 '3SunSeptember 241:00PMNew York JetsMiami Dolphinsboxscore20633612252',
 '3SunSeptember 241:00PMAtlanta Falcons@Detroit Lionsboxscore302642833240',
 '3SunSeptember 241:00PMBuffalo BillsDenver Broncosboxscore261627203662',
 '3SunSeptember 241:00PMMinnesota VikingsTampa Bay Buccaneersboxscore341749403423',
 '3SunSeptember 241:00PMChicago BearsPittsburgh Steelersboxscore231730622822',
 '3SunSeptember 241:00PMNew Orleans Saints@Carolina Panthersboxscore341336202883',
 '3SunSeptember 241:00PMIndianapolis ColtsCleveland Brownsboxscore312833513463',
 '3SunSeptember 241:00PMNew England PatriotsHouston Texansboxscore363339614172',
 '3SunSeptember 241:00PMPhiladelphia EaglesNew York Giantsboxscore272435414152',
 '3SunSeptember 244:05PMTennessee TitansSeattle Seahawksboxscore332742004330',
 '3SunSeptember 244:25PMKansas City Chiefs@Los Angeles Chargersboxscore241031103303',
 '3SunSeptember 244:25PMGreen Bay PackersCincinnati Bengalsboxscore272434413011',
 '3SunSeptember 248:30PMWashington RedskinsOakland Raidersboxscore271047221283',
 '3MonSeptember 258:30PMDallas Cowboys@Arizona Cardinalsboxscore281727303320',
 '4ThuSeptember 288:25PMGreen Bay PackersChicago Bearsboxscore351426003084',
 '4SunOctober 19:30AMNew Orleans Saints@Miami Dolphinsboxscore20034701861',
 '4SunOctober 11:00PMNew York JetsJacksonville Jaguarsboxscore232047123111',
 '4SunOctober 11:00PMLos Angeles Rams@Dallas Cowboysboxscore353041204402',
 '4SunOctober 11:00PMDetroit Lions@Minnesota Vikingsboxscore14725102843',
 '4SunOctober 11:00PMPittsburgh Steelers@Baltimore Ravensboxscore26938112883',
 '4SunOctober 11:00PMBuffalo Bills@Atlanta Falconsboxscore231728103893',
 '4SunOctober 11:00PMCarolina Panthers@New England Patriotsboxscore333044423730',
 '4SunOctober 11:00PMCincinnati Bengals@Cleveland Brownsboxscore31735012151',
 '4SunOctober 11:00PMHouston TexansTennessee Titansboxscore571444511955',
 '4SunOctober 14:05PMTampa Bay BuccaneersNew York Giantsboxscore252343403790',
 '4SunOctober 14:05PMPhiladelphia Eagles@Los Angeles Chargersboxscore262445404001',
 '4SunOctober 14:05PMArizona CardinalsSan Francisco 49ersboxscore181536813051',
 '4SunOctober 14:25PMDenver BroncosOakland Raidersboxscore161029802541',
 '4SunOctober 18:30PMSeattle SeahawksIndianapolis Coltsboxscore461847722372',
 '4MonOctober 28:30PMKansas City ChiefsWashington Redskinsboxscore292042903311',
 '5ThuOctober 58:25PMNew England Patriots@Tampa Bay Buccaneersboxscore191440224090',
 '5SunOctober 81:00PMMiami DolphinsTennessee Titansboxscore161017821882',
 '5SunOctober 81:00PMCarolina Panthers@Detroit Lionsboxscore272436202421',
 '5SunOctober 81:00PMPhiladelphia EaglesArizona Cardinalsboxscore34741913071',
 '5SunOctober 81:00PMJacksonville Jaguars@Pittsburgh Steelersboxscore30931313715',
 '5SunOctober 81:00PMLos Angeles Chargers@New York Giantsboxscore272238213352',
 '5SunOctober 81:00PMIndianapolis ColtsSan Francisco 49ersboxscore262344714020',
 '5SunOctober 81:00PMCincinnati BengalsBuffalo Billsboxscore201638832211',
 '5SunOctober 81:00PMNew York Jets@Cleveland Brownsboxscore171421214193',
 '5SunOctober 84:05PMBaltimore Ravens@Oakland Raidersboxscore301736502451',
 '5SunOctober 84:05PMSeattle Seahawks@Los Angeles Ramsboxscore161024123755',
 '5SunOctober 84:25PMGreen Bay Packers@Dallas Cowboysboxscore353134214083',
 '5SunOctober 88:30PMKansas City Chiefs@Houston Texansboxscore423445003921',
 '5MonOctober 98:30PMMinnesota Vikings@Chicago Bearsboxscore201730002742',
 '6ThuOctober 128:25PMPhiladelphia Eagles@Carolina Panthersboxscore282331013053',
 '6SunOctober 151:00PMMiami Dolphins@Atlanta Falconsboxscore201728913391',
 '6SunOctober 151:00PMHouston TexansCleveland Brownsboxscore331734012473',
 '6SunOctober 151:00PMChicago Bears@Baltimore Ravensboxscore272434222913',
 '6SunOctober 151:00PMNew Orleans SaintsDetroit Lionsboxscore523837933475',
 '6SunOctober 151:00PMWashington RedskinsSan Francisco 49ersboxscore262441923351',
 '6SunOctober 151:00PMMinnesota VikingsGreen Bay Packersboxscore231035122273',
 '6SunOctober 151:00PMNew England Patriots@New York Jetsboxscore241737524083',
 '6SunOctober 154:05PMArizona CardinalsTampa Bay Buccaneersboxscore383343224122',
 '6SunOctober 154:05PMLos Angeles Rams@Jacksonville Jaguarsboxscore271724913891',
 '6SunOctober 154:25PMLos Angeles Chargers@Oakland Raidersboxscore171634312742',
 '6SunOctober 154:25PMPittsburgh Steelers@Kansas City Chiefsboxscore191343912510',
 '6SunOctober 158:30PMNew York Giants@Denver Broncosboxscore231026604123',
 '6MonOctober 168:30PMTennessee TitansIndianapolis Coltsboxscore362247312971',
 '7ThuOctober 198:25PMOakland RaidersKansas City Chiefsboxscore313050504250',
 '7SunOctober 221:00PMMiami DolphinsNew York Jetsboxscore312835722722',
 '7SunOctober 221:00PMBuffalo BillsTampa Bay Buccaneersboxscore302743414473',
 '7SunOctober 221:00PMJacksonville Jaguars@Indianapolis Coltsboxscore27051822320',
 '7SunOctober 221:00PMTennessee Titans@Cleveland Brownsboxscore12926912843',
 '7SunOctober 221:00PMMinnesota VikingsBaltimore Ravensboxscore241635712080',
 '7SunOctober 221:00PMChicago BearsCarolina Panthersboxscore17315302933',
 '7SunOctober 221:00PMLos Angeles RamsArizona Cardinalsboxscore33042511962',
 '7SunOctober 221:00PMNew Orleans Saints@Green Bay Packersboxscore261748522601',
 '7SunOctober 224:05PMDallas Cowboys@San Francisco 49ersboxscore401050102903',
 '7SunOctober 224:25PMPittsburgh SteelersCincinnati Bengalsboxscore291442001792',
 '7SunOctober 224:25PMLos Angeles ChargersDenver Broncosboxscore21024202513',
 '7SunOctober 224:25PMSeattle Seahawks@New York Giantsboxscore24742511771',
 '7SunOctober 228:30PMNew England PatriotsAtlanta Falconsboxscore23740303430',
 '7MonOctober 238:30PMPhiladelphia EaglesWashington Redskinsboxscore342437113441',
 '8ThuOctober 268:25PMBaltimore RavensMiami Dolphinsboxscore40029501962',
 '8SunOctober 299:30AMMinnesota Vikings@Cleveland Brownsboxscore331637512762',
 '8SunOctober 291:00PMBuffalo BillsOakland Raidersboxscore341433103674',
 '8SunOctober 291:00PMAtlanta Falcons@New York Jetsboxscore252038622791',
 '8SunOctober 291:00PMCincinnati BengalsIndianapolis Coltsboxscore242327623311',
 '8SunOctober 291:00PMPhiladelphia EaglesSan Francisco 49ersboxscore331030412382',
 '8SunOctober 291:00PMNew England PatriotsLos Angeles Chargersboxscore211341403491',
 '8SunOctober 291:00PMNew Orleans SaintsChicago Bearsboxscore201238723071',
 '8SunOctober 291:00PMCarolina Panthers@Tampa Bay Buccaneersboxscore17325412793',
 '8SunOctober 294:05PMSeattle SeahawksHouston Texansboxscore413847915093',
 '8SunOctober 294:25PMDallas Cowboys@Washington Redskinsboxscore331930712853',
 '8SunOctober 298:30PMPittsburgh Steelers@Detroit Lionsboxscore201539224821',
 '8MonOctober 308:30PMKansas City ChiefsDenver Broncosboxscore291927623645',
 '9ThuNovember 28:25PMNew York JetsBuffalo Billsboxscore342133103073',
 '9SunNovember 51:00PMLos Angeles Rams@New York Giantsboxscore511747303193',
 '9SunNovember 51:00PMTennessee TitansBaltimore Ravensboxscore232025713412',
 '9SunNovember 51:00PMNew Orleans SaintsTampa Bay Buccaneersboxscore301040722001',
 '9SunNovember 51:00PMCarolina PanthersAtlanta Falconsboxscore201733023551',
 '9SunNovember 51:00PMJacksonville JaguarsCincinnati Bengalsboxscore23740811480',
 '9SunNovember 51:00PMPhiladelphia EaglesDenver Broncosboxscore512341912262',
 '9SunNovember 51:00PMIndianapolis Colts@Houston Texansboxscore201437112881',
 '9SunNovember 54:05PMArizona Cardinals@San Francisco 49ersboxscore201036823292',
 '9SunNovember 54:05PMWashington Redskins@Seattle Seahawksboxscore171424414372',
 '9SunNovember 54:25PMDallas CowboysKansas City Chiefsboxscore281737503231',
 '9SunNovember 58:30PMOakland Raiders@Miami Dolphinsboxscore272437923951',
 '9MonNovember 68:30PMDetroit Lions@Green Bay Packersboxscore301741713110',
 '10ThuNovember 98:25PMSeattle Seahawks@Arizona Cardinalsboxscore221628702901',
 '10SunNovember 121:00PMTennessee TitansCincinnati Bengalsboxscore242041623082',
 '10SunNovember 121:00PMNew Orleans Saints@Buffalo Billsboxscore471048211981',
 '10SunNovember 121:00PMGreen Bay Packers@Chicago Bearsboxscore231634203231',
 '10SunNovember 121:00PMJacksonville JaguarsLos Angeles Chargersboxscore201739823222',
 '10SunNovember 121:00PMMinnesota Vikings@Washington Redskinsboxscore383040623941',
 '10SunNovember 121:00PMDetroit LionsCleveland Brownsboxscore382434514132',
 '10SunNovember 121:00PMTampa Bay BuccaneersNew York Jetsboxscore151027112752',
 '10SunNovember 121:00PMPittsburgh Steelers@Indianapolis Coltsboxscore201731612671',
 '10SunNovember 124:05PMLos Angeles RamsHouston Texansboxscore33744302834',
 '10SunNovember 124:25PMSan Francisco 49ersNew York Giantsboxscore312147423741',
 '10SunNovember 124:25PMAtlanta FalconsDallas Cowboysboxscore27733612332',
 '10SunNovember 128:30PMNew England Patriots@Denver Broncosboxscore411639603392',
 '10MonNovember 138:30PMCarolina PanthersMiami Dolphinsboxscore452154803131',
 '11ThuNovember 168:25PMPittsburgh SteelersTennessee Titansboxscore401734903164',
 '11SunNovember 191:00PMDetroit Lions@Chicago Bearsboxscore272435213981',
 '11SunNovember 191:00PMMinnesota VikingsLos Angeles Ramsboxscore24745102541',
 '11SunNovember 191:00PMBaltimore Ravens@Green Bay Packersboxscore23021912655',
 '11SunNovember 191:00PMNew York GiantsKansas City Chiefsboxscore12931713633',
 '11SunNovember 191:00PMJacksonville Jaguars@Cleveland Brownsboxscore19728411845',
 '11SunNovember 191:00PMNew Orleans SaintsWashington Redskinsboxscore343153514560',
 '11SunNovember 191:00PMHouston TexansArizona Cardinalsboxscore312135722922',
 '11SunNovember 191:00PMTampa Bay Buccaneers@Miami Dolphinsboxscore302032104485',
 '11SunNovember 194:05PMLos Angeles ChargersBuffalo Billsboxscore542442903936',
 '11SunNovember 194:25PMCincinnati Bengals@Denver Broncosboxscore201719003412',
 '11SunNovember 194:25PMNew England Patriots@Oakland Raidersboxscore33842103442',
 '11SunNovember 198:30PMPhiladelphia Eagles@Dallas Cowboysboxscore37938302254',
 '11MonNovember 208:30PMAtlanta Falcons@Seattle Seahawksboxscore343127913602',
 '12ThuNovember 2312:30PMMinnesota Vikings@Detroit Lionsboxscore302340802892',
 '12ThuNovember 234:30PMLos Angeles Chargers@Dallas Cowboysboxscore28651502472',
 '12ThuNovember 238:30PMWashington RedskinsNew York Giantsboxscore201032311701',
 '12SunNovember 261:00PMBuffalo Bills@Kansas City Chiefsboxscore161026802361',
 '12SunNovember 261:00PMPhiladelphia EaglesChicago Bearsboxscore31342031402',
 '12SunNovember 261:00PMAtlanta FalconsTampa Bay Buccaneersboxscore342051613730',
 '12SunNovember 261:00PMCarolina Panthers@New York Jetsboxscore352729903911',
 '12SunNovember 261:00PMCincinnati BengalsCleveland Brownsboxscore301636104050',
 '12SunNovember 261:00PMTennessee Titans@Indianapolis Coltsboxscore201627622541',
 '12SunNovember 261:00PMNew England PatriotsMiami Dolphinsboxscore351741722213',
 '12SunNovember 264:05PMSeattle Seahawks@San Francisco 49ersboxscore241331812801',
 '12SunNovember 264:25PMOakland RaidersDenver Broncosboxscore211434812161',
 '12SunNovember 264:25PMLos Angeles RamsNew Orleans Saintsboxscore262041513460',
 '12SunNovember 264:25PMArizona CardinalsJacksonville Jaguarsboxscore272434422193',
 '12SunNovember 268:30PMPittsburgh SteelersGreen Bay Packersboxscore312846233070',
 '12MonNovember 278:30PMBaltimore RavensHouston Texansboxscore231629403033',
 '13ThuNovember 308:25PMDallas CowboysWashington Redskinsboxscore381427502804',
 '13SunDecember 31:00PMJacksonville JaguarsIndianapolis Coltsboxscore301042602902',
 '13SunDecember 31:00PMTennessee TitansHouston Texansboxscore241334413841',
 '13SunDecember 31:00PMNew England Patriots@Buffalo Billsboxscore23343512681',
 '13SunDecember 31:00PMNew York JetsKansas City Chiefsboxscore383148804740',
 '13SunDecember 31:00PMBaltimore RavensDetroit Lionsboxscore442037003723',
 '13SunDecember 31:00PMSan Francisco 49ers@Chicago Bearsboxscore151438811470',
 '13SunDecember 31:00PMMiami DolphinsDenver Broncosboxscore35936732703',
 '13SunDecember 31:00PMMinnesota Vikings@Atlanta Falconsboxscore14931202750',
 '13SunDecember 31:00PMGreen Bay PackersTampa Bay Buccaneersboxscore262027613951',
 '13SunDecember 34:05PMLos Angeles ChargersCleveland Brownsboxscore191042902912',
 '13SunDecember 34:25PMLos Angeles Rams@Arizona Cardinalsboxscore321630313052',
 '13SunDecember 34:25PMNew Orleans SaintsCarolina Panthersboxscore312140012791',
 '13SunDecember 34:25PMOakland RaidersNew York Giantsboxscore241740112652',
 '13SunDecember 38:30PMSeattle SeahawksPhiladelphia Eaglesboxscore241031004252',
 '13MonDecember 48:30PMPittsburgh Steelers@Cincinnati Bengalsboxscore232037413530',
 '14ThuDecember 78:25PMAtlanta FalconsNew Orleans Saintsboxscore201734333061',
 '14SunDecember 101:00PMCarolina PanthersMinnesota Vikingsboxscore312434513563',
 '14SunDecember 101:00PMDallas Cowboys@New York Giantsboxscore301045403302',
 '14SunDecember 101:00PMSan Francisco 49ers@Houston Texansboxscore261641613111',
 '14SunDecember 101:00PMBuffalo BillsIndianapolis Coltsboxscore13731922270',
 '14SunDecember 101:00PMKansas City ChiefsOakland Raidersboxscore261540812683',
 '14SunDecember 101:00PMDetroit Lions@Tampa Bay Buccaneersboxscore242143434005',
 '14SunDecember 101:00PMGreen Bay Packers@Cleveland Brownsboxscore272134103452',
 '14SunDecember 101:00PMChicago Bears@Cincinnati Bengalsboxscore33748202342',
 '14SunDecember 104:05PMDenver BroncosNew York Jetsboxscore23027301002',
 '14SunDecember 104:05PMLos Angeles ChargersWashington Redskinsboxscore301348812011',
 '14SunDecember 104:05PMArizona CardinalsTennessee Titansboxscore12726102042',
 '14SunDecember 104:25PMJacksonville JaguarsSeattle Seahawksboxscore302442414013',
 '14SunDecember 104:25PMPhiladelphia Eagles@Los Angeles Ramsboxscore433545513072',
 '14SunDecember 108:30PMPittsburgh SteelersBaltimore Ravensboxscore393854504131',
 '14MonDecember 118:30PMMiami DolphinsNew England Patriotsboxscore272036202482',
 '15ThuDecember 148:25PMDenver Broncos@Indianapolis Coltsboxscore251346212280',
 '15SatDecember 164:30PMDetroit LionsChicago Bearsboxscore201029313493',
 '15SatDecember 168:25PMKansas City ChiefsLos Angeles Chargersboxscore301339703074',
 '15SunDecember 171:00PMBuffalo BillsMiami Dolphinsboxscore241632803493',
 '15SunDecember 171:00PMNew Orleans SaintsNew York Jetsboxscore311941232942',
 '15SunDecember 171:00PMBaltimore Ravens@Cleveland Brownsboxscore271037602664',
 '15SunDecember 171:00PMMinnesota VikingsCincinnati Bengalsboxscore34734611612',
 '15SunDecember 171:00PMPhiladelphia Eagles@New York Giantsboxscore342934105041',
 '15SunDecember 171:00PMCarolina PanthersGreen Bay Packersboxscore312438703844',
 '15SunDecember 171:00PMWashington RedskinsArizona Cardinalsboxscore201521812862',
 '15SunDecember 171:00PMJacksonville JaguarsHouston Texansboxscore45746401861',
 '15SunDecember 174:05PMLos Angeles Rams@Seattle Seahawksboxscore42735211492',
 '15SunDecember 174:25PMSan Francisco 49ersTennessee Titansboxscore252341403281',
 '15SunDecember 174:25PMNew England Patriots@Pittsburgh Steelersboxscore272436014131',
 '15SunDecember 178:30PMDallas Cowboys@Oakland Raidersboxscore201733022931',
 '15MonDecember 188:30PMAtlanta Falcons@Tampa Bay Buccaneersboxscore242141003731',
 '16SatDecember 234:30PMBaltimore RavensIndianapolis Coltsboxscore231632302960',
 '16SatDecember 238:30PMMinnesota Vikings@Green Bay Packersboxscore16023602392',
 '16SunDecember 241:00PMWashington RedskinsDenver Broncosboxscore271138623303',
 '16SunDecember 241:00PMLos Angeles Chargers@New York Jetsboxscore14737902953',
 '16SunDecember 241:00PMNew England PatriotsBuffalo Billsboxscore371641113260',
 '16SunDecember 241:00PMKansas City ChiefsMiami Dolphinsboxscore291340403452',
 '16SunDecember 241:00PMCincinnati BengalsDetroit Lionsboxscore261736412761',
 '16SunDecember 241:00PMChicago BearsCleveland Brownsboxscore20325802543',
 '16SunDecember 241:00PMNew Orleans SaintsAtlanta Falconsboxscore231331513312',
 '16SunDecember 241:00PMCarolina PanthersTampa Bay Buccaneersboxscore221925513923',
 '16SunDecember 241:00PMLos Angeles Rams@Tennessee Titansboxscore272340213661',
 '16SunDecember 244:05PMSan Francisco 49ersJacksonville Jaguarsboxscore443336914723',
 '16SunDecember 244:25PMSeattle Seahawks@Dallas Cowboysboxscore211213602823',
 '16SunDecember 244:25PMArizona CardinalsNew York Giantsboxscore23028922933',
 '16MonDecember 254:30PMPittsburgh Steelers@Houston Texansboxscore34633002272',
 '16MonDecember 258:30PMPhiladelphia EaglesOakland Raidersboxscore191021622745',
 '17SunDecember 311:00PMIndianapolis ColtsHouston Texansboxscore221325002091',
 '17SunDecember 311:00PMNew England PatriotsNew York Jetsboxscore26633002470',
 '17SunDecember 311:00PMDetroit LionsGreen Bay Packersboxscore351135602564',
 '17SunDecember 311:00PMDallas Cowboys@Philadelphia Eaglesboxscore6030112192',
 '17SunDecember 311:00PMPittsburgh SteelersCleveland Brownsboxscore282434823742',
 '17SunDecember 311:00PMNew York GiantsWashington Redskinsboxscore181038111973',
 '17SunDecember 311:00PMMinnesota VikingsChicago Bearsboxscore231032702010',
 '17SunDecember 314:25PMSan Francisco 49ers@Los Angeles Ramsboxscore341346132512',
 '17SunDecember 314:25PMArizona Cardinals@Seattle Seahawksboxscore262425912960',
 '17SunDecember 314:25PMTampa Bay BuccaneersNew Orleans Saintsboxscore312445533231',
 '17SunDecember 314:25PMKansas City Chiefs@Denver Broncosboxscore272437923363',

In [246]:
# Split string a first non digit and append to week list

week =[] 
for row in weeks:
    week.append(int(re.split(r'(\d+)', row)[1]))

In [214]:
week

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 14,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17]

In [247]:
game =[]
for td in soup.find_all('td'):
    game.append(td.text)

In [248]:
game

['Thu',
 'September 7',
 '8:30PM',
 'Kansas City Chiefs',
 '@',
 'New England Patriots',
 'boxscore',
 '42',
 '27',
 '537',
 '1',
 '371',
 '0',
 'Sun',
 'September 10',
 '1:00PM',
 'Pittsburgh Steelers',
 '@',
 'Cleveland Browns',
 'boxscore',
 '21',
 '18',
 '290',
 '1',
 '237',
 '1',
 'Sun',
 'September 10',
 '1:00PM',
 'Baltimore Ravens',
 '@',
 'Cincinnati Bengals',
 'boxscore',
 '20',
 '0',
 '268',
 '1',
 '221',
 '5',
 'Sun',
 'September 10',
 '1:00PM',
 'Philadelphia Eagles',
 '@',
 'Washington Redskins',
 'boxscore',
 '30',
 '17',
 '356',
 '2',
 '264',
 '4',
 'Sun',
 'September 10',
 '1:00PM',
 'Detroit Lions',
 '',
 'Arizona Cardinals',
 'boxscore',
 '35',
 '23',
 '367',
 '1',
 '308',
 '4',
 'Sun',
 'September 10',
 '1:00PM',
 'Jacksonville Jaguars',
 '@',
 'Houston Texans',
 'boxscore',
 '29',
 '7',
 '280',
 '0',
 '203',
 '4',
 'Sun',
 'September 10',
 '1:00PM',
 'Oakland Raiders',
 '@',
 'Tennessee Titans',
 'boxscore',
 '26',
 '16',
 '359',
 '0',
 '350',
 '0',
 'Sun',
 'September 10',
 '1:00PM',
 'Atlanta Falcons',
 '@',
 'Chicago Bears',
 'boxscore',
 '23',
 '17',
 '372',
 '0',
 '301',
 '0',
 'Sun',
 'September 10',
 '1:00PM',
 'Buffalo Bills',
 '',
 'New York Jets',
 'boxscore',
 '21',
 '12',
 '408',
 '1',
 '214',
 '2',
 'Sun',
 'September 10',
 '4:05PM',
 'Los Angeles Rams',
 '',
 'Indianapolis Colts',
 'boxscore',
 '46',
 '9',
 '373',
 '1',
 '225',
 '3',
 'Sun',
 'September 10',
 '4:25PM',
 'Carolina Panthers',
 '@',
 'San Francisco 49ers',
 'boxscore',
 '23',
 '3',
 '287',
 '2',
 '217',
 '2',
 'Sun',
 'September 10',
 '4:25PM',
 'Green Bay Packers',
 '',
 'Seattle Seahawks',
 'boxscore',
 '17',
 '9',
 '370',
 '1',
 '225',
 '1',
 'Sun',
 'September 10',
 '8:30PM',
 'Dallas Cowboys',
 '',
 'New York Giants',
 'boxscore',
 '19',
 '3',
 '392',
 '0',
 '233',
 '1',
 'Mon',
 'September 11',
 '7:10PM',
 'Minnesota Vikings',
 '',
 'New Orleans Saints',
 'boxscore',
 '29',
 '19',
 '470',
 '0',
 '344',
 '0',
 'Mon',
 'September 11',
 '10:20PM',
 'Denver Broncos',
 '',
 'Los Angeles Chargers',
 'boxscore',
 '24',
 '21',
 '321',
 '2',
 '249',
 '1',
 'Thu',
 'September 14',
 '8:25PM',
 'Houston Texans',
 '@',
 'Cincinnati Bengals',
 'boxscore',
 '13',
 '9',
 '266',
 '0',
 '295',
 '1',
 'Sun',
 'September 17',
 '1:00PM',
 'Pittsburgh Steelers',
 '',
 'Minnesota Vikings',
 'boxscore',
 '26',
 '9',
 '335',
 '0',
 '237',
 '1',
 'Sun',
 'September 17',
 '1:00PM',
 'Tampa Bay Buccaneers',
 '',
 'Chicago Bears',
 'boxscore',
 '29',
 '7',
 '311',
 '1',
 '310',
 '4',
 'Sun',
 'September 17',
 '1:00PM',
 'Baltimore Ravens',
 '',
 'Cleveland Browns',
 'boxscore',
 '24',
 '10',
 '337',
 '2',
 '386',
 '5',
 'Sun',
 'September 17',
 '1:00PM',
 'Tennessee Titans',
 '@',
 'Jacksonville Jaguars',
 'boxscore',
 '37',
 '16',
 '390',
 '1',
 '310',
 '3',
 'Sun',
 'September 17',
 '1:00PM',
 'Kansas City Chiefs',
 '',
 'Philadelphia Eagles',
 'boxscore',
 '27',
 '20',
 '344',
 '0',
 '406',
 '2',
 'Sun',
 'September 17',
 '1:00PM',
 'Arizona Cardinals',
 '@',
 'Indianapolis Colts',
 'boxscore',
 '16',
 '13',
 '389',
 '1',
 '266',
 '1',
 'Sun',
 'September 17',
 '1:00PM',
 'Carolina Panthers',
 '',
 'Buffalo Bills',
 'boxscore',
 '9',
 '3',
 '255',
 '0',
 '176',
 '0',
 'Sun',
 'September 17',
 '1:00PM',
 'New England Patriots',
 '@',
 'New Orleans Saints',
 'boxscore',
 '36',
 '20',
 '555',
 '0',
 '429',
 '0',
 'Sun',
 'September 17',
 '4:05PM',
 'Miami Dolphins',
 '@',
 'Los Angeles Chargers',
 'boxscore',
 '19',
 '17',
 '336',
 '0',
 '367',
 '0',
 'Sun',
 'September 17',
 '4:05PM',
 'Oakland Raiders',
 '',
 'New York Jets',
 'boxscore',
 '45',
 '20',
 '410',
 '0',
 '271',
 '2',
 'Sun',
 'September 17',
 '4:25PM',
 'Seattle Seahawks',
 '',
 'San Francisco 49ers',
 'boxscore',
 '12',
 '9',
 '312',
 '0',
 '248',
 '1',
 'Sun',
 'September 17',
 '4:25PM',
 'Denver Broncos',
 '',
 'Dallas Cowboys',
 'boxscore',
 '42',
 '17',
 '380',
 '2',
 '268',
 '2',
 'Sun',
 'September 17',
 '4:25PM',
 'Washington Redskins',
 '@',
 'Los Angeles Rams',
 'boxscore',
 '27',
 '20',
 '385',
 '0',
 '332',
 '2',
 'Sun',
 'September 17',
 '8:30PM',
 'Atlanta Falcons',
 '',
 'Green Bay Packers',
 'boxscore',
 '34',
 '23',
 '364',
 '0',
 '367',
 '2',
 'Mon',
 'September 18',
 '8:30PM',
 'Detroit Lions',
 '@',
 'New York Giants',
 'boxscore',
 '24',
 '10',
 '257',
 '1',
 '270',
 '1',
 'Thu',
 'September 21',
 '8:25PM',
 'Los Angeles Rams',
 '@',
 'San Francisco 49ers',
 'boxscore',
 '41',
 '39',
 '418',
 '2',
 '421',
 '2',
 'Sun',
 'September 24',
 '9:30AM',
 'Jacksonville Jaguars',
 '',
 'Baltimore Ravens',
 'boxscore',
 '44',
 '7',
 '410',
 '0',
 '186',
 '3',
 'Sun',
 'September 24',
 '1:00PM',
 'New York Jets',
 '',
 'Miami Dolphins',
 'boxscore',
 '20',
 '6',
 '336',
 '1',
 '225',
 '2',
 'Sun',
 'September 24',
 '1:00PM',
 'Atlanta Falcons',
 '@',
 'Detroit Lions',
 'boxscore',
 '30',
 '26',
 '428',
 '3',
 '324',
 '0',
 'Sun',
 'September 24',
 '1:00PM',
 'Buffalo Bills',
 '',
 'Denver Broncos',
 'boxscore',
 '26',
 '16',
 '272',
 '0',
 '366',
 '2',
 'Sun',
 'September 24',
 '1:00PM',
 'Minnesota Vikings',
 '',
 'Tampa Bay Buccaneers',
 'boxscore',
 '34',
 '17',
 '494',
 '0',
 '342',
 '3',
 'Sun',
 'September 24',
 '1:00PM',
 'Chicago Bears',
 '',
 'Pittsburgh Steelers',
 'boxscore',
 '23',
 '17',
 '306',
 '2',
 '282',
 '2',
 'Sun',
 'September 24',
 '1:00PM',
 'New Orleans Saints',
 '@',
 'Carolina Panthers',
 'boxscore',
 '34',
 '13',
 '362',
 '0',
 '288',
 '3',
 'Sun',
 'September 24',
 '1:00PM',
 'Indianapolis Colts',
 '',
 'Cleveland Browns',
 'boxscore',
 '31',
 '28',
 '335',
 '1',
 '346',
 '3',
 'Sun',
 'September 24',
 '1:00PM',
 'New England Patriots',
 '',
 'Houston Texans',
 'boxscore',
 '36',
 '33',
 '396',
 '1',
 '417',
 '2',
 'Sun',
 'September 24',
 '1:00PM',
 'Philadelphia Eagles',
 '',
 'New York Giants',
 'boxscore',
 '27',
 '24',
 '354',
 '1',
 '415',
 '2',
 'Sun',
 'September 24',
 '4:05PM',
 'Tennessee Titans',
 '',
 'Seattle Seahawks',
 'boxscore',
 '33',
 '27',
 '420',
 '0',
 '433',
 '0',
 'Sun',
 'September 24',
 '4:25PM',
 'Kansas City Chiefs',
 '@',
 'Los Angeles Chargers',
 'boxscore',
 '24',
 '10',
 '311',
 '0',
 '330',
 '3',
 'Sun',
 'September 24',
 '4:25PM',
 'Green Bay Packers',
 '',
 'Cincinnati Bengals',
 'boxscore',
 '27',
 '24',
 '344',
 '1',
 '301',
 '1',
 'Sun',
 'September 24',
 '8:30PM',
 'Washington Redskins',
 '',
 'Oakland Raiders',
 'boxscore',
 '27',
 '10',
 '472',
 '2',
 '128',
 '3',
 'Mon',
 'September 25',
 '8:30PM',
 'Dallas Cowboys',
 '@',
 'Arizona Cardinals',
 'boxscore',
 '28',
 '17',
 '273',
 '0',
 '332',
 '0',
 'Thu',
 'September 28',
 '8:25PM',
 'Green Bay Packers',
 '',
 'Chicago Bears',
 'boxscore',
 '35',
 '14',
 '260',
 '0',
 '308',
 '4',
 'Sun',
 'October 1',
 '9:30AM',
 'New Orleans Saints',
 '@',
 'Miami Dolphins',
 'boxscore',
 '20',
 '0',
 '347',
 '0',
 '186',
 '1',
 'Sun',
 'October 1',
 '1:00PM',
 'New York Jets',
 '',
 'Jacksonville Jaguars',
 'boxscore',
 '23',
 '20',
 '471',
 '2',
 '311',
 '1',
 'Sun',
 'October 1',
 '1:00PM',
 'Los Angeles Rams',
 '@',
 'Dallas Cowboys',
 'boxscore',
 '35',
 '30',
 '412',
 '0',
 '440',
 '2',
 'Sun',
 'October 1',
 '1:00PM',
 'Detroit Lions',
 '@',
 'Minnesota Vikings',
 'boxscore',
 '14',
 '7',
 '251',
 '0',
 '284',
 '3',
 'Sun',
 'October 1',
 '1:00PM',
 'Pittsburgh Steelers',
 '@',
 'Baltimore Ravens',
 'boxscore',
 '26',
 '9',
 '381',
 '1',
 '288',
 '3',
 'Sun',
 'October 1',
 '1:00PM',
 'Buffalo Bills',
 '@',
 'Atlanta Falcons',
 'boxscore',
 '23',
 '17',
 '281',
 '0',
 '389',
 '3',
 'Sun',
 'October 1',
 '1:00PM',
 'Carolina Panthers',
 '@',
 'New England Patriots',
 'boxscore',
 '33',
 '30',
 '444',
 '2',
 '373',
 '0',
 'Sun',
 'October 1',
 '1:00PM',
 'Cincinnati Bengals',
 '@',
 'Cleveland Browns',
 'boxscore',
 '31',
 '7',
 '350',
 '1',
 '215',
 '1',
 'Sun',
 'October 1',
 '1:00PM',
 'Houston Texans',
 '',
 'Tennessee Titans',
 'boxscore',
 '57',
 '14',
 '445',
 '1',
 '195',
 '5',
 'Sun',
 'October 1',
 '4:05PM',
 'Tampa Bay Buccaneers',
 '',
 'New York Giants',
 'boxscore',
 '25',
 '23',
 '434',
 '0',
 '379',
 '0',
 'Sun',
 'October 1',
 '4:05PM',
 'Philadelphia Eagles',
 '@',
 'Los Angeles Chargers',
 'boxscore',
 '26',
 '24',
 '454',
 '0',
 '400',
 '1',
 'Sun',
 'October 1',
 '4:05PM',
 'Arizona Cardinals',
 '',
 'San Francisco 49ers',
 'boxscore',
 '18',
 '15',
 '368',
 '1',
 '305',
 '1',
 'Sun',
 'October 1',
 '4:25PM',
 'Denver Broncos',
 '',
 'Oakland Raiders',
 'boxscore',
 '16',
 '10',
 '298',
 '0',
 '254',
 '1',
 'Sun',
 'October 1',
 '8:30PM',
 'Seattle Seahawks',
 '',
 'Indianapolis Colts',
 'boxscore',
 '46',
 '18',
 '477',
 '2',
 '237',
 '2',
 'Mon',
 'October 2',
 '8:30PM',
 'Kansas City Chiefs',
 '',
 'Washington Redskins',
 'boxscore',
 '29',
 '20',
 '429',
 '0',
 '331',
 '1',
 'Thu',
 'October 5',
 '8:25PM',
 'New England Patriots',
 '@',
 'Tampa Bay Buccaneers',
 'boxscore',
 '19',
 '14',
 '402',
 '2',
 '409',
 '0',
 'Sun',
 'October 8',
 '1:00PM',
 'Miami Dolphins',
 '',
 'Tennessee Titans',
 'boxscore',
 '16',
 '10',
 '178',
 '2',
 '188',
 '2',
 'Sun',
 'October 8',
 '1:00PM',
 'Carolina Panthers',
 '@',
 'Detroit Lions',
 'boxscore',
 '27',
 '24',
 '362',
 '0',
 '242',
 '1',
 'Sun',
 'October 8',
 '1:00PM',
 'Philadelphia Eagles',
 '',
 'Arizona Cardinals',
 'boxscore',
 '34',
 '7',
 '419',
 '1',
 '307',
 '1',
 'Sun',
 'October 8',
 '1:00PM',
 'Jacksonville Jaguars',
 '@',
 'Pittsburgh Steelers',
 'boxscore',
 '30',
 '9',
 '313',
 '1',
 '371',
 '5',
 'Sun',
 'October 8',
 '1:00PM',
 'Los Angeles Chargers',
 '@',
 'New York Giants',
 'boxscore',
 '27',
 '22',
 '382',
 '1',
 '335',
 '2',
 'Sun',
 'October 8',
 '1:00PM',
 'Indianapolis Colts',
 '',
 'San Francisco 49ers',
 'boxscore',
 '26',
 '23',
 '447',
 '1',
 '402',
 '0',
 'Sun',
 'October 8',
 '1:00PM',
 'Cincinnati Bengals',
 '',
 'Buffalo Bills',
 'boxscore',
 '20',
 '16',
 '388',
 '3',
 '221',
 '1',
 'Sun',
 'October 8',
 '1:00PM',
 'New York Jets',
 '@',
 'Cleveland Browns',
 'boxscore',
 '17',
 '14',
 '212',
 '1',
 '419',
 '3',
 'Sun',
 'October 8',
 '4:05PM',
 'Baltimore Ravens',
 '@',
 'Oakland Raiders',
 'boxscore',
 '30',
 '17',
 '365',
 '0',
 '245',
 '1',
 'Sun',
 'October 8',
 '4:05PM',
 'Seattle Seahawks',
 '@',
 'Los Angeles Rams',
 'boxscore',
 '16',
 '10',
 '241',
 '2',
 '375',
 '5',
 'Sun',
 'October 8',
 '4:25PM',
 'Green Bay Packers',
 '@',
 'Dallas Cowboys',
 'boxscore',
 '35',
 '31',
 '342',
 '1',
 '408',
 '3',
 'Sun',
 'October 8',
 '8:30PM',
 'Kansas City Chiefs',
 '@',
 'Houston Texans',
 'boxscore',
 '42',
 '34',
 '450',
 '0',
 '392',
 '1',
 'Mon',
 'October 9',
 '8:30PM',
 'Minnesota Vikings',
 '@',
 'Chicago Bears',
 'boxscore',
 '20',
 '17',
 '300',
 '0',
 '274',
 ...]

In [221]:
away[:256]

['Carolina Panthers',
 'Green Bay Packers',
 'Buffalo Bills',
 'Cleveland Browns',
 'Chicago Bears',
 'San Diego Chargers',
 'Tampa Bay Buccaneers',
 'Minnesota Vikings',
 'Oakland Raiders',
 'Cincinnati Bengals',
 'Miami Dolphins',
 'New York Giants',
 'Detroit Lions',
 'New England Patriots',
 'Pittsburgh Steelers',
 'Los Angeles Rams',
 'New York Jets',
 'Cincinnati Bengals',
 'Baltimore Ravens',
 'Kansas City Chiefs',
 'Miami Dolphins',
 'Tennessee Titans',
 'New Orleans Saints',
 'San Francisco 49ers',
 'Dallas Cowboys',
 'Tampa Bay Buccaneers',
 'Seattle Seahawks',
 'Indianapolis Colts',
 'Jacksonville Jaguars',
 'Atlanta Falcons',
 'Green Bay Packers',
 'Philadelphia Eagles',
 'Houston Texans',
 'Minnesota Vikings',
 'Detroit Lions',
 'Washington Redskins',
 'Denver Broncos',
 'Arizona Cardinals',
 'Cleveland Browns',
 'Oakland Raiders',
 'Baltimore Ravens',
 'Los Angeles Rams',
 'San Francisco 49ers',
 'Pittsburgh Steelers',
 'San Diego Chargers',
 'New York Jets',
 'Chicago Bears',
 'Atlanta Falcons',
 'Miami Dolphins',
 'Indianapolis Colts',
 'Detroit Lions',
 'Tennessee Titans',
 'Oakland Raiders',
 'Buffalo Bills',
 'Seattle Seahawks',
 'Carolina Panthers',
 'Cleveland Browns',
 'Denver Broncos',
 'Dallas Cowboys',
 'New Orleans Saints',
 'Los Angeles Rams',
 'Kansas City Chiefs',
 'New York Giants',
 'Arizona Cardinals',
 'New England Patriots',
 'Philadelphia Eagles',
 'Chicago Bears',
 'New York Jets',
 'Tennessee Titans',
 'Washington Redskins',
 'Houston Texans',
 'Atlanta Falcons',
 'Cincinnati Bengals',
 'Buffalo Bills',
 'San Diego Chargers',
 'New York Giants',
 'Tampa Bay Buccaneers',
 'Denver Broncos',
 'Pittsburgh Steelers',
 'Cincinnati Bengals',
 'San Francisco 49ers',
 'Cleveland Browns',
 'Baltimore Ravens',
 'Los Angeles Rams',
 'Jacksonville Jaguars',
 'Philadelphia Eagles',
 'Carolina Panthers',
 'Kansas City Chiefs',
 'Dallas Cowboys',
 'Atlanta Falcons',
 'Indianapolis Colts',
 'New York Jets',
 'Chicago Bears',
 'New York Giants',
 'Oakland Raiders',
 'Minnesota Vikings',
 'Washington Redskins',
 'Indianapolis Colts',
 'Cleveland Browns',
 'Buffalo Bills',
 'New Orleans Saints',
 'Baltimore Ravens',
 'San Diego Chargers',
 'Tampa Bay Buccaneers',
 'New England Patriots',
 'Seattle Seahawks',
 'Houston Texans',
 'Jacksonville Jaguars',
 'Washington Redskins',
 'Arizona Cardinals',
 'Oakland Raiders',
 'Kansas City Chiefs',
 'New York Jets',
 'New England Patriots',
 'Seattle Seahawks',
 'Detroit Lions',
 'San Diego Chargers',
 'Green Bay Packers',
 'Philadelphia Eagles',
 'Minnesota Vikings',
 'Atlanta Falcons',
 'Philadelphia Eagles',
 'New York Jets',
 'Jacksonville Jaguars',
 'Pittsburgh Steelers',
 'Dallas Cowboys',
 'Detroit Lions',
 'Carolina Panthers',
 'New Orleans Saints',
 'Indianapolis Colts',
 'Tennessee Titans',
 'Denver Broncos',
 'Buffalo Bills',
 'Cleveland Browns',
 'Kansas City Chiefs',
 'Green Bay Packers',
 'Minnesota Vikings',
 'Houston Texans',
 'Chicago Bears',
 'Denver Broncos',
 'Los Angeles Rams',
 'Atlanta Falcons',
 'Miami Dolphins',
 'Dallas Cowboys',
 'San Francisco 49ers',
 'Seattle Seahawks',
 'Cincinnati Bengals',
 'New Orleans Saints',
 'Tennessee Titans',
 'Baltimore Ravens',
 'Buffalo Bills',
 'Tampa Bay Buccaneers',
 'Jacksonville Jaguars',
 'Chicago Bears',
 'Arizona Cardinals',
 'Pittsburgh Steelers',
 'Miami Dolphins',
 'New England Patriots',
 'Philadelphia Eagles',
 'Green Bay Packers',
 'Houston Texans',
 'Minnesota Vikings',
 'Washington Redskins',
 'Pittsburgh Steelers',
 'San Diego Chargers',
 'Tennessee Titans',
 'Los Angeles Rams',
 'San Francisco 49ers',
 'Cincinnati Bengals',
 'Arizona Cardinals',
 'Jacksonville Jaguars',
 'New York Giants',
 'Seattle Seahawks',
 'Carolina Panthers',
 'New England Patriots',
 'Kansas City Chiefs',
 'Green Bay Packers',
 'Dallas Cowboys',
 'Los Angeles Rams',
 'Houston Texans',
 'San Francisco 49ers',
 'Detroit Lions',
 'Denver Broncos',
 'Miami Dolphins',
 'Philadelphia Eagles',
 'Kansas City Chiefs',
 'Buffalo Bills',
 'Washington Redskins',
 'Tampa Bay Buccaneers',
 'New York Giants',
 'Carolina Panthers',
 'Indianapolis Colts',
 'Oakland Raiders',
 'Cincinnati Bengals',
 'Washington Redskins',
 'Pittsburgh Steelers',
 'Arizona Cardinals',
 'San Diego Chargers',
 'Chicago Bears',
 'Denver Broncos',
 'Houston Texans',
 'Minnesota Vikings',
 'New York Jets',
 'Atlanta Falcons',
 'New Orleans Saints',
 'Seattle Seahawks',
 'Dallas Cowboys',
 'Baltimore Ravens',
 'Los Angeles Rams',
 'Miami Dolphins',
 'Green Bay Packers',
 'Indianapolis Colts',
 'Pittsburgh Steelers',
 'Philadelphia Eagles',
 'Jacksonville Jaguars',
 'Tennessee Titans',
 'Cleveland Browns',
 'Detroit Lions',
 'San Francisco 49ers',
 'New Orleans Saints',
 'New England Patriots',
 'Oakland Raiders',
 'Tampa Bay Buccaneers',
 'Carolina Panthers',
 'New York Giants',
 'San Diego Chargers',
 'Tennessee Titans',
 'Washington Redskins',
 'Atlanta Falcons',
 'New York Jets',
 'Minnesota Vikings',
 'Miami Dolphins',
 'Indianapolis Colts',
 'Arizona Cardinals',
 'San Francisco 49ers',
 'Tampa Bay Buccaneers',
 'Cincinnati Bengals',
 'Baltimore Ravens',
 'Denver Broncos',
 'Detroit Lions',
 'Dallas Cowboys',
 'Carolina Panthers',
 'New England Patriots',
 'Buffalo Bills',
 'Cleveland Browns',
 'Chicago Bears',
 'Houston Texans',
 'Jacksonville Jaguars',
 'Baltimore Ravens',
 'New York Giants',
 'Seattle Seahawks',
 'Arizona Cardinals',
 'Oakland Raiders',
 'Kansas City Chiefs',
 'New Orleans Saints',
 'Green Bay Packers']

In [249]:
home = []
away =[]
for idx,val in enumerate(game):
    if val == '':
        home.append(game[idx-1])
        away.append(game[idx+1])
    elif val =='@':
        home.append(game[idx+1])
        away.append(game[idx-1])

In [250]:
location_17 = pd.DataFrame(columns = ['week','home','away'])

In [251]:
location_17.head()

Empty DataFrame
Columns: [week, home, away]
Index: []

In [258]:
location_17['year'] = 2017

In [254]:
away

['Kansas City Chiefs',
 'Pittsburgh Steelers',
 'Baltimore Ravens',
 'Philadelphia Eagles',
 'Arizona Cardinals',
 'Jacksonville Jaguars',
 'Oakland Raiders',
 'Atlanta Falcons',
 'New York Jets',
 'Indianapolis Colts',
 'Carolina Panthers',
 'Seattle Seahawks',
 'New York Giants',
 'New Orleans Saints',
 'Los Angeles Chargers',
 'Houston Texans',
 'Minnesota Vikings',
 'Chicago Bears',
 'Cleveland Browns',
 'Tennessee Titans',
 'Philadelphia Eagles',
 'Arizona Cardinals',
 'Buffalo Bills',
 'New England Patriots',
 'Miami Dolphins',
 'New York Jets',
 'San Francisco 49ers',
 'Dallas Cowboys',
 'Washington Redskins',
 'Green Bay Packers',
 'Detroit Lions',
 'Los Angeles Rams',
 'Baltimore Ravens',
 'Miami Dolphins',
 'Atlanta Falcons',
 'Denver Broncos',
 'Tampa Bay Buccaneers',
 'Pittsburgh Steelers',
 'New Orleans Saints',
 'Cleveland Browns',
 'Houston Texans',
 'New York Giants',
 'Seattle Seahawks',
 'Kansas City Chiefs',
 'Cincinnati Bengals',
 'Oakland Raiders',
 'Dallas Cowboys',
 'Chicago Bears',
 'New Orleans Saints',
 'Jacksonville Jaguars',
 'Los Angeles Rams',
 'Detroit Lions',
 'Pittsburgh Steelers',
 'Buffalo Bills',
 'Carolina Panthers',
 'Cincinnati Bengals',
 'Tennessee Titans',
 'New York Giants',
 'Philadelphia Eagles',
 'San Francisco 49ers',
 'Oakland Raiders',
 'Indianapolis Colts',
 'Washington Redskins',
 'New England Patriots',
 'Tennessee Titans',
 'Carolina Panthers',
 'Arizona Cardinals',
 'Jacksonville Jaguars',
 'Los Angeles Chargers',
 'San Francisco 49ers',
 'Buffalo Bills',
 'New York Jets',
 'Baltimore Ravens',
 'Seattle Seahawks',
 'Green Bay Packers',
 'Kansas City Chiefs',
 'Minnesota Vikings',
 'Philadelphia Eagles',
 'Miami Dolphins',
 'Cleveland Browns',
 'Chicago Bears',
 'Detroit Lions',
 'San Francisco 49ers',
 'Green Bay Packers',
 'New England Patriots',
 'Tampa Bay Buccaneers',
 'Los Angeles Rams',
 'Los Angeles Chargers',
 'Pittsburgh Steelers',
 'New York Giants',
 'Indianapolis Colts',
 'Kansas City Chiefs',
 'New York Jets',
 'Tampa Bay Buccaneers',
 'Jacksonville Jaguars',
 'Tennessee Titans',
 'Baltimore Ravens',
 'Carolina Panthers',
 'Arizona Cardinals',
 'New Orleans Saints',
 'Dallas Cowboys',
 'Cincinnati Bengals',
 'Denver Broncos',
 'Seattle Seahawks',
 'Atlanta Falcons',
 'Washington Redskins',
 'Miami Dolphins',
 'Minnesota Vikings',
 'Oakland Raiders',
 'Atlanta Falcons',
 'Indianapolis Colts',
 'San Francisco 49ers',
 'Los Angeles Chargers',
 'Chicago Bears',
 'Carolina Panthers',
 'Houston Texans',
 'Dallas Cowboys',
 'Pittsburgh Steelers',
 'Denver Broncos',
 'Buffalo Bills',
 'Los Angeles Rams',
 'Baltimore Ravens',
 'Tampa Bay Buccaneers',
 'Atlanta Falcons',
 'Cincinnati Bengals',
 'Denver Broncos',
 'Indianapolis Colts',
 'Arizona Cardinals',
 'Washington Redskins',
 'Kansas City Chiefs',
 'Oakland Raiders',
 'Detroit Lions',
 'Seattle Seahawks',
 'Cincinnati Bengals',
 'New Orleans Saints',
 'Green Bay Packers',
 'Los Angeles Chargers',
 'Minnesota Vikings',
 'Cleveland Browns',
 'New York Jets',
 'Pittsburgh Steelers',
 'Houston Texans',
 'New York Giants',
 'Dallas Cowboys',
 'New England Patriots',
 'Miami Dolphins',
 'Tennessee Titans',
 'Detroit Lions',
 'Los Angeles Rams',
 'Baltimore Ravens',
 'Kansas City Chiefs',
 'Jacksonville Jaguars',
 'Washington Redskins',
 'Arizona Cardinals',
 'Tampa Bay Buccaneers',
 'Buffalo Bills',
 'Cincinnati Bengals',
 'New England Patriots',
 'Philadelphia Eagles',
 'Atlanta Falcons',
 'Minnesota Vikings',
 'Los Angeles Chargers',
 'New York Giants',
 'Buffalo Bills',
 'Chicago Bears',
 'Tampa Bay Buccaneers',
 'Carolina Panthers',
 'Cleveland Browns',
 'Tennessee Titans',
 'Miami Dolphins',
 'Seattle Seahawks',
 'Denver Broncos',
 'New Orleans Saints',
 'Jacksonville Jaguars',
 'Green Bay Packers',
 'Houston Texans',
 'Washington Redskins',
 'Indianapolis Colts',
 'Houston Texans',
 'New England Patriots',
 'Kansas City Chiefs',
 'Detroit Lions',
 'San Francisco 49ers',
 'Denver Broncos',
 'Minnesota Vikings',
 'Tampa Bay Buccaneers',
 'Cleveland Browns',
 'Los Angeles Rams',
 'Carolina Panthers',
 'New York Giants',
 'Philadelphia Eagles',
 'Pittsburgh Steelers',
 'New Orleans Saints',
 'Minnesota Vikings',
 'Dallas Cowboys',
 'San Francisco 49ers',
 'Indianapolis Colts',
 'Oakland Raiders',
 'Detroit Lions',
 'Green Bay Packers',
 'Chicago Bears',
 'New York Jets',
 'Washington Redskins',
 'Tennessee Titans',
 'Seattle Seahawks',
 'Philadelphia Eagles',
 'Baltimore Ravens',
 'New England Patriots',
 'Denver Broncos',
 'Chicago Bears',
 'Los Angeles Chargers',
 'Miami Dolphins',
 'New York Jets',
 'Baltimore Ravens',
 'Cincinnati Bengals',
 'Philadelphia Eagles',
 'Green Bay Packers',
 'Arizona Cardinals',
 'Houston Texans',
 'Los Angeles Rams',
 'Tennessee Titans',
 'New England Patriots',
 'Dallas Cowboys',
 'Atlanta Falcons',
 'Indianapolis Colts',
 'Minnesota Vikings',
 'Denver Broncos',
 'Los Angeles Chargers',
 'Buffalo Bills',
 'Miami Dolphins',
 'Detroit Lions',
 'Cleveland Browns',
 'Atlanta Falcons',
 'Tampa Bay Buccaneers',
 'Los Angeles Rams',
 'Jacksonville Jaguars',
 'Seattle Seahawks',
 'New York Giants',
 'Pittsburgh Steelers',
 'Oakland Raiders',
 'Houston Texans',
 'New York Jets',
 'Green Bay Packers',
 'Dallas Cowboys',
 'Cleveland Browns',
 'Washington Redskins',
 'Chicago Bears',
 'San Francisco 49ers',
 'Arizona Cardinals',
 'New Orleans Saints',
 'Kansas City Chiefs',
 'Oakland Raiders',
 'Buffalo Bills',
 'Jacksonville Jaguars',
 'Cincinnati Bengals',
 'Carolina Panthers',
 'Playoffs',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 'Sat',
 'Tennessee Titans',
 'Atlanta Falcons',
 'Buffalo Bills',
 'Carolina Panthers',
 'Atlanta Falcons',
 'Tennessee Titans',
 'Jacksonville Jaguars',
 'New Orleans Saints',
 'Jacksonville Jaguars',
 'Minnesota Vikings']

In [256]:
location_17['home']=home[:256]

In [259]:
location_17.head()

  week                  home                 away  year
0  NaN  New England Patriots   Kansas City Chiefs  2017
1  NaN      Cleveland Browns  Pittsburgh Steelers  2017
2  NaN    Cincinnati Bengals     Baltimore Ravens  2017
3  NaN   Washington Redskins  Philadelphia Eagles  2017
4  NaN         Detroit Lions    Arizona Cardinals  2017

In [166]:
loc_15 = location
loc_15['year']=2015

In [191]:
location_15

     week                  home                  away  year
0       1  New England Patriots   Pittsburgh Steelers  2015
1       1        St. Louis Rams      Seattle Seahawks  2015
2       1         Chicago Bears     Green Bay Packers  2015
3       1   Washington Redskins        Miami Dolphins  2015
4       1        Houston Texans    Kansas City Chiefs  2015
5       1         Buffalo Bills    Indianapolis Colts  2015
6       1  Jacksonville Jaguars     Carolina Panthers  2015
7       1         New York Jets      Cleveland Browns  2015
8       1     Arizona Cardinals    New Orleans Saints  2015
9       1    San Diego Chargers         Detroit Lions  2015
10      1        Denver Broncos      Baltimore Ravens  2015
11      1  Tampa Bay Buccaneers      Tennessee Titans  2015
12      1       Oakland Raiders    Cincinnati Bengals  2015
13      1        Dallas Cowboys       New York Giants  2015
14      1       Atlanta Falcons   Philadelphia Eagles  2015
15      1   San Francisco 49ers     Minnesota Vikings  2015
16      2    Kansas City Chiefs        Denver Broncos  2015
17      2         Chicago Bears     Arizona Cardinals  2015
18      2    New Orleans Saints  Tampa Bay Buccaneers  2015
19      2   Pittsburgh Steelers   San Francisco 49ers  2015
20      2         Buffalo Bills  New England Patriots  2015
21      2      Cleveland Browns      Tennessee Titans  2015
22      2       New York Giants       Atlanta Falcons  2015
23      2     Carolina Panthers        Houston Texans  2015
24      2    Cincinnati Bengals    San Diego Chargers  2015
25      2   Washington Redskins        St. Louis Rams  2015
26      2     Minnesota Vikings         Detroit Lions  2015
27      2       Oakland Raiders      Baltimore Ravens  2015
28      2  Jacksonville Jaguars        Miami Dolphins  2015
29      2   Philadelphia Eagles        Dallas Cowboys  2015
..    ...                   ...                   ...   ...
226    16         Buffalo Bills        Dallas Cowboys  2015
227    16        Miami Dolphins    Indianapolis Colts  2015
228    16         New York Jets  New England Patriots  2015
229    16       Atlanta Falcons     Carolina Panthers  2015
230    16      Tennessee Titans        Houston Texans  2015
231    16      Baltimore Ravens   Pittsburgh Steelers  2015
232    16  Tampa Bay Buccaneers         Chicago Bears  2015
233    16         Detroit Lions   San Francisco 49ers  2015
234    16    Kansas City Chiefs      Cleveland Browns  2015
235    16    New Orleans Saints  Jacksonville Jaguars  2015
236    16     Arizona Cardinals     Green Bay Packers  2015
237    16      Seattle Seahawks        St. Louis Rams  2015
238    16     Minnesota Vikings       New York Giants  2015
239    16        Denver Broncos    Cincinnati Bengals  2015
240    17      Cleveland Browns   Pittsburgh Steelers  2015
241    17         Buffalo Bills         New York Jets  2015
242    17         Chicago Bears         Detroit Lions  2015
243    17    Indianapolis Colts      Tennessee Titans  2015
244    17    Cincinnati Bengals      Baltimore Ravens  2015
245    17       Atlanta Falcons    New Orleans Saints  2015
246    17        Miami Dolphins  New England Patriots  2015
247    17        Houston Texans  Jacksonville Jaguars  2015
248    17        Dallas Cowboys   Washington Redskins  2015
249    17       New York Giants   Philadelphia Eagles  2015
250    17     Carolina Panthers  Tampa Bay Buccaneers  2015
251    17     Arizona Cardinals      Seattle Seahawks  2015
252    17        Denver Broncos    San Diego Chargers  2015
253    17   San Francisco 49ers        St. Louis Rams  2015
254    17    Kansas City Chiefs       Oakland Raiders  2015
255    17     Green Bay Packers     Minnesota Vikings  2015

[256 rows x 4 columns]

In [273]:

team_dict = {'New England Patriots':'NE',
            'Green Bay Packers':'GB',
            'Tampa Bay Buccaneers':'TB',
            'Kansas City Chiefs':'KC',
            'San Diego Chargers':'SD',
            'St. Louis Rams':'STL',
            'New Orleans Saints':'NO',
            'New York Jets':'NYJ',
            'New York Giants':'NYG',
            'San Francisco 49ers':'SF',
            'LOS':'LAR',
            'Jacksonville Jaguars':'JAX'}

In [276]:
location_17 = location_17.replace({"home": team_dict})

In [265]:
location_17['week']=week

In [280]:
location_16[0:17]

    week home away  year
0      1  DEN  CAR  2016
1      1  JAX   GB  2016
2      1  BAL  BUF  2016
3      1  PHI  CLE  2016
4      1  HOU  CHI  2016
5      1   KC   SD  2016
6      1  ATL   TB  2016
7      1  TEN  MIN  2016
8      1   NO  OAK  2016
9      1  NYJ  CIN  2016
10     1  SEA  MIA  2016
11     1  DAL  NYG  2016
12     1  IND  DET  2016
13     1  ARI   NE  2016
14     1  WAS  PIT  2016
15     1   SF  LAR  2016
16     2  BUF  NYJ  2016

In [274]:
try:
    location_17['home'] = location_17['home'].apply(lambda x: x[0:3].upper())
    location_17['away'] = location_17['away'].apply(lambda x: x[0:3].upper())
except:
    None

In [272]:
location_17[:17]

    week home away  year
0      1   NE   KC  2017
1      1  CLE  PIT  2017
2      1  CIN  BAL  2017
3      1  WAS  PHI  2017
4      1  DET  ARI  2017
5      1  HOU  JAX  2017
6      1  TEN  OAK  2017
7      1  CHI  ATL  2017
8      1  BUF  NYJ  2017
9      1  LOS  IND  2017
10     1   SF  CAR  2017
11     1   GB  SEA  2017
12     1  DAL  NYG  2017
13     1  MIN   NO  2017
14     1  DEN  LOS  2017
15     2  CIN  HOU  2017
16     2  PIT  MIN  2017

In [105]:
location_17.head()

   week home away  year
0     1   NE   KC  2017
1     1  CLE  PIT  2017
2     1  CIN  BAL  2017
3     1  WAS  PHI  2017
4     1  DET  ARI  2017

In [106]:
location_16.head()

   week home away  year
0     1  DEN  CAR  2016
1     1  JAC   GB  2016
2     1  BAL  BUF  2016
3     1  PHI  CLE  2016
4     1  HOU  CHI  2016

In [112]:
location_15['year']=2015
location_16['year']=2016
location_17['year']=2017

In [281]:
location = pd.concat([location_15,location_16])
location = pd.concat([location,location_17])

In [282]:
location.head()

   week home away  year
0     1   NE  PIT  2015
1     1  STL  SEA  2015
2     1  CHI   GB  2015
3     1  WAS  MIA  2015
4     1  HOU   KC  2015

In [104]:
location_15 =pd.read_csv('.../../input/location.csv')

In [283]:
location.to_csv('../../my_git/draftkings/input/location.csv',index=False)

In [35]:
location.index = location['home']
location[0:100]

      week home away
home
NE       1   NE  PIT
STL      1  STL  SEA
CHI      1  CHI   GB
WAS      1  WAS  MIA
HOU      1  HOU   KC
BUF      1  BUF  IND
JAC      1  JAC  CAR
NE       1   NE  CLE
ARI      1  ARI   NE
SD       1   SD  DET
DEN      1  DEN  BAL
TB       1   TB  TEN
OAK      1  OAK  CIN
DAL      1  DAL   NE
ATL      1  ATL  PHI
SD       1   SD  MIN
KC       2   KC  DEN
CHI      2  CHI  ARI
NE       2   NE   TB
PIT      2  PIT   SD
BUF      2  BUF   NE
CLE      2  CLE  TEN
NE       2   NE  ATL
CAR      2  CAR  HOU
CIN      2  CIN   SD
WAS      2  WAS  STL
MIN      2  MIN  DET
OAK      2  OAK  BAL
JAC      2  JAC  MIA
PHI      2  PHI  DAL
...    ...  ...  ...
TEN      5  TEN  BUF
PHI      5  PHI   NE
DET      5  DET  ARI
OAK      5  OAK  DEN
DAL      5  DAL   NE
NE       5   NE   SD
SD       5   SD  PIT
NE       6   NE  ATL
NE       6   NE  WAS
JAC      6  JAC  HOU
MIN      6  MIN   KC
BUF      6  BUF  CIN
CLE      6  CLE  DEN
DET      6  DET  CHI
TEN      6  TEN  MIA
PIT      6  PIT  ARI
SEA      6  SEA  CAR
GB       6   GB   SD
SD       6   SD  BAL
IND      6  IND   NE
PHI      6  PHI   NE
SD       7   SD  SEA
JAC      7  JAC  BUF
STL      7  STL  CLE
NE       7   NE   NE
MIA      7  MIA  HOU
TEN      7  TEN  ATL
DET      7  DET  MIN
KC       7   KC  PIT
IND      7  IND   NE

[100 rows x 3 columns]

In [5]:
location.to_csv('inpout/location.csv', undex=False)

NameError: name 'location' is not defined

In [575]:
temp = qb[qb['year']==2017]

In [576]:
temp.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
1200,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,1,70.96,0,0,0.0,0,7.84,5500,2017,12
1201,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,0,116.11,3,11,3.7,0,20.94,6900,2017,7
1202,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,3,53.12,1,2,2.0,0,11.92,4300,2017,21
1203,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,1,86.51,7,21,3.0,0,20.54,6000,2017,8
1204,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,1,95.02,3,-8,-2.7,0,16.72,7000,2017,24

In [578]:
week1 = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [468]:
qb_stats = ['week1',
'week2',
'week3',
'week4',
'week5',
'week6',
'week7',
'week8',
'week9',
'week10',
'week11',
'week12',
'week13',
'week14',
'week15',
'week16',
'week17']

In [476]:
for row in qb_stats:
    print(int(row[4:]))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17

In [395]:
loc_df

     week home away
240    17  CHI  DET
241    17  IND  TEN
242    17  ATL  NEW
243    17  MIA  NEW
244    17  CIN  BAL
245    17  HOU  JAC
246    17  CLE  PIT
247    17  BUF  NEW
248    17  DAL  WAS
249    17   NE  PHI
250    17  DEN  SAN
251    17   SD  ST.
252    17  CAR  TAM
253    17  ARI  SEA
254    17   KC  OAK
255    17   GB  MIN

In [480]:
for row in qb_stats:
    loc_df = location[location['week']==int(row[4:])]
loc_df.shape

home_list = []
for team in '{}'['Team'].format(row):
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

TypeError: string indices must be integers

In [612]:
location[location['week']==17]
loc_df.shape

home_list = []
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')


week17['h/a'] = home_list


week17.head()

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
1762,611,Joe Flacco,BAL,17,CIN,25,47,53.2,203,4.3,...,69.73,0,0,0.0,0,15.12,6300,2017,12,away
1763,732,Matt Ryan,ATL,17,CAR,28,45,62.2,317,7.0,...,90.69,3,14,4.7,0,21.08,5300,2017,14,home
1764,4314,Tom Brady,NE,17,NYJ,18,37,48.6,190,5.1,...,82.04,0,0,0.0,0,15.60,4600,2017,24,home
1765,4737,Drew Stanton,ARI,17,SEA,15,34,44.1,145,4.3,...,54.17,1,-1,-1.0,0,8.70,4500,2017,8,away
1766,4932,Eli Manning,NYG,17,WAS,10,28,35.7,132,4.7,...,48.51,3,-4,-1.3,0,7.88,4400,2017,16,away

In [613]:
qb_2017=pd.concat([qb_2017,week17])

qb_2017.tail()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
1795,18525,Joe Callahan,GB,17,DET,5,7,71.4,11,1.6,...,74.11,0,0,0.0,0,0.44,4400,2017,21,away
1796,18811,Mitch Trubisky,CHI,17,MIN,20,36,55.6,178,4.9,...,68.98,1,2,2.0,0,7.32,4700,2017,1,away
1797,18868,Deshone Kizer,CLE,17,PIT,16,30,53.3,314,10.5,...,98.47,6,61,10.2,0,28.66,4400,2017,6,away
1798,18890,Patrick Mahomes,KC,17,DEN,22,35,62.9,284,8.1,...,76.37,7,10,1.4,0,11.36,4800,2017,5,away
1799,19238,Taysom Hill,NO,17,TB,0,0,0.0,0,0.0,...,0.00,0,0,0.0,0,0.00,4500,2017,31,away

In [531]:

qb_2016.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
600,611,Joe Flacco,BAL,1,BUF,22,33,66.7,258,7.8,...,100.32,4,-3,-0.8,0,13.02,6700,2016,10,away
601,732,Matt Ryan,ATL,1,TB,27,39,69.2,334,8.6,...,112.55,3,10,3.3,0,27.36,7100,2016,17,home
602,2428,Carson Palmer,ARI,1,NE,24,37,64.9,271,7.3,...,104.67,2,1,0.5,0,18.94,7100,2016,6,away
603,2593,Aaron Rodgers,GB,1,JAX,20,34,58.8,199,5.9,...,95.10,4,16,4.0,1,23.56,8500,2016,8,away
604,3807,Ben Roethlisberger,PIT,1,WAS,27,37,73.0,300,8.1,...,112.44,1,-2,-2.0,0,25.80,7800,2016,27,home

In [583]:
qb_2017= pd.concat([week1,week2])
qb_2017.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
1200,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,70.96,0,0,0.0,0,7.84,5500,2017,12,away
1201,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,116.11,3,11,3.7,0,20.94,6900,2017,7,home
1202,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,53.12,1,2,2.0,0,11.92,4300,2017,21,away
1203,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,86.51,7,21,3.0,0,20.54,6000,2017,8,away
1204,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,95.02,3,-8,-2.7,0,16.72,7000,2017,24,home

In [402]:
surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'
              
             }

In [614]:
surface = []
for idx, team in enumerate(qb_2017['Team']):
    if qb_2017.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[qb_2017.iloc[idx]['Opponent']])


qb_2017['surface'] = surface

In [615]:
qb_2017.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
1200,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,0,0,0.0,0,7.84,5500,2017,12,away,turf
1201,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,3,11,3.7,0,20.94,6900,2017,7,home,turf
1202,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,1,2,2.0,0,11.92,4300,2017,21,away,turf
1203,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,7,21,3.0,0,20.54,6000,2017,8,away,turf
1204,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,3,-8,-2.7,0,16.72,7000,2017,24,home,grass

In [617]:
qb_df=pd.concat([qb_df,qb_2017])

In [618]:
qb_df.tail()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
1795,18525,Joe Callahan,GB,17,DET,5,7,71.4,11,1.6,...,0,0,0.0,0,0.44,4400,2017,21,away,turf
1796,18811,Mitch Trubisky,CHI,17,MIN,20,36,55.6,178,4.9,...,1,2,2.0,0,7.32,4700,2017,1,away,turf
1797,18868,Deshone Kizer,CLE,17,PIT,16,30,53.3,314,10.5,...,6,61,10.2,0,28.66,4400,2017,6,away,grass
1798,18890,Patrick Mahomes,KC,17,DEN,22,35,62.9,284,8.1,...,7,10,1.4,0,11.36,4800,2017,5,away,grass
1799,19238,Taysom Hill,NO,17,TB,0,0,0.0,0,0.0,...,0,0,0.0,0,0.00,4500,2017,31,away,grass

In [619]:
qb_df.shape

(1796, 23)

In [620]:
qb.shape

(1800, 21)

In [628]:
for player in qb_df['Name']:
    if player not in list(qb['Name'].unique()):
        print(player)

In [629]:
qb_df.reset_index(inplace=True,drop=True)

In [631]:
qb_df.to_csv('input/qb/dk_stats_loc.csv')

In [3]:
wr = pd.read_csv('input/wr/dk_wr_stats.csv')

In [4]:
wr.head()

,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,ReceivingLong,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,points,year
0,Kevin Ogletree,DAL,1,NYG,11,8,72.7,114,2,NaN,10.4,14.2,0,0,0.0,0,0,0,23.4,2012
1,Julio Jones,ATL,1,KC,9,6,66.7,108,2,NaN,12.0,18.0,0,0,0.0,0,0,0,22.8,2012
2,Stephen Hill,NYJ,1,BUF,6,5,83.3,89,2,NaN,14.8,17.8,0,0,0.0,0,0,0,20.9,2012
3,Lance Moore,NO,1,WAS,10,6,60.0,120,1,NaN,12.0,20.0,0,0,0.0,0,0,0,18.0,2012
4,Brandon Marshall,CHI,1,IND,15,9,60.0,119,1,NaN,7.9,13.2,0,0,0.0,0,0,0,17.9,2012