In [2]:
import pandas as pd
import numpy as np
import json
from bs4 import BeautifulSoup
import requests
import re

In [ ]:
url = 'https://www.pro-football-reference.com/years/2018/games.htm'
page = requests.get(url)

In [ ]:
# Use BeautifulSoup to retreive data the data from Pro Footbal Reference.com 

soup = BeautifulSoup(page.text,'html.parser')

weeks = []  
for tr in soup.find_all('tr'):
    weeks.append(tr.text)

In [585]:
def_2015 = pd.read_csv('input/def/def_2015.csv')
def_2017 = pd.read_csv('input/def/def_2017.csv')
def_2016 = pd.read_csv('input/def/def_2016.csv')

In [13]:
    def read_concat(csv1, csv2):
        data=pd.read_csv(csv1)
        data2=pd.read_csv(csv2)
        df = pd.concat([data, data2])
        df.reset_index(inplace=True, drop=True)

        return df

In [17]:
df1= read_concat('input/wr/2015wk1_2.csv','input/wr/2015wk3_4.csv')


#df2 = read_concat('input/wr/2015_sal_1_9.csv','input/wr/2015_sal_10_17.csv')

In [ ]:
df1 = pd.concat([df1,(pd.read_csv('input/wr/2015wk5_6.csv'))])
df1.reset_index(inplace=True, drop=True)

In [16]:
df1.shape

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
736,111,14368,Nick Toon,LAR,WR,17,SF,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
737,111,7857,Jerome Simpson,SF,WR,17,LAR,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
738,111,16480,Jeff Janis,GB,WR,17,MIN,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
739,111,16469,Jared Abbrederis,GB,WR,17,MIN,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
740,155,15150,Cordarrelle Patterson,MIN,WR,17,GB,0,0,0.0,...,0.0,0.0,0,0,0.0,0,1,1,-1.0,-1.0

In [257]:
data1 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool.csv')
data2 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (1).csv')
data3 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (2).csv')
data4 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (3).csv')
data5 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (4).csv')
data6 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (5).csv')
#data7 = pd.read_csv('input/rb/daily-fantasy-football-salary-and-projection-tool (6).csv')
#data8 = pd.read_csv('input/rb/daily-fantasy-football-salary-and-projection-tool (7).csv')
#data9 = pd.read_csv('input/rb/daily-fantasy-football-salary-and-projection-tool (8).csv')

In [259]:
data6.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,UpcomingOpponentRank,UpcomingOpponentPositionRank,DraftKingsSalary,FantasyPointsDraftKings
0,1,10974,Rob Gronkowski,NE,TE,16,NYJ,6,3,7600,19.4
1,2,1658,Greg Olsen,CAR,TE,16,ATL,11,28,7000,18.9
2,3,7175,Delanie Walker,TEN,TE,17,IND,26,19,5600,18.3
3,4,15100,Jordan Reed,WAS,TE,16,PHI,28,2,6500,18.0
4,5,10974,Rob Gronkowski,NE,TE,17,MIA,29,10,7400,17.5

In [198]:
#data1 = pd.read_csv('input/rb/fantasy-football-leaders.csv')
data2 = pd.read_csv('input/rb/fantasy-football-leaders (1).csv')
data3 = pd.read_csv('input/rb/fantasy-football-leaders (2).csv')
data4 = pd.read_csv('input/rb/fantasy-football-leaders (3).csv')
data5 = pd.read_csv('input/rb/fantasy-football-leaders (4).csv')
data6 = pd.read_csv('input/rb/fantasy-football-leaders (5).csv')
data7 = pd.read_csv('input/rb/fantasy-football-leaders (6).csv')
data8 = pd.read_csv('input/rb/fantasy-football-leaders (7).csv')
data9 = pd.read_csv('input/rb/fantasy-football-leaders (8).csv')
data10 = pd.read_csv('input/rb/fantasy-football-leaders (9).csv')

## Tight Ends

In [571]:
data1 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool.csv')
data2 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (1).csv')
data3 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (2).csv')
data4 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (3).csv')
data5 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (4).csv')
data6 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (5).csv')

In [579]:
data2 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (1).csv')
data3 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (2).csv')
data4 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (3).csv')
data5 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (4).csv')
data6 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (5).csv')
data7 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (6).csv')

In [572]:
data5.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,UpcomingOpponentRank,UpcomingOpponentPositionRank,DraftKingsSalary,FantasyPointsDraftKings
0,1,15048,Travis Kelce,KC,TE,13,ATL,30,28,4700,14.56
1,2,1658,Greg Olsen,CAR,TE,15,WAS,25,26,5000,14.39
2,3,11488,Jimmy Graham,SEA,TE,14,GB,17,23,5500,14.28
3,4,11488,Jimmy Graham,SEA,TE,13,CAR,25,31,5500,14.11
4,5,1658,Greg Olsen,CAR,TE,13,SEA,5,8,5100,13.95

In [504]:
te_2016.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
0,722,Jason Witten,DAL,1,NYG,14,9,64.3,66,0,...,0,0,0,0,15.6,4100,20,away,turf,2016
1,852,Jacob Tamme,ATL,1,TB,8,6,75.0,51,0,...,0,0,0,0,11.1,2800,14,away,grass,2016
2,1181,Martellus Bennett,NE,1,ARI,5,3,60.0,14,0,...,0,0,0,0,4.4,3400,1,away,grass,2016
3,1545,Anthony Fasano,TEN,1,MIN,0,0,0.0,0,0,...,0,0,0,0,0.0,2500,11,away,turf,2016
4,1658,Greg Olsen,CAR,1,DEN,9,7,77.8,73,0,...,0,0,0,0,14.3,5100,19,away,grass,2016

In [584]:
te_2016 = pd.concat([te_2016,data7])
te_2016.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
162,103,15305,Demetrius Harris,KC,TE,17,LAC,1,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
163,103,16933,James O'Shaughnessy,KC,TE,17,LAC,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
164,103,11555,Jim Dray,SF,TE,17,SEA,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
165,103,9671,Matthew Mulligan,DET,TE,17,GB,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
166,103,11317,Clay Harbor,DET,TE,17,GB,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0

In [578]:
te_2016_sal = te_2016

In [639]:
te_2016 = add_salary(te_2016,te_2016_sal)

te_2016.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,def_rk,h/a,surface,year,salary
0,722,Jason Witten,DAL,1,NYG,14,9,64.3,66,0,...,0,0,0,0,15.6,20,away,turf,2016,4100
1,852,Jacob Tamme,ATL,1,TB,8,6,75.0,51,0,...,0,0,0,0,11.1,14,away,grass,2016,2800
2,1181,Martellus Bennett,NE,1,ARI,5,3,60.0,14,0,...,0,0,0,0,4.4,1,away,grass,2016,3400
3,1545,Anthony Fasano,TEN,1,MIN,0,0,0.0,0,0,...,0,0,0,0,0.0,11,away,turf,2016,2500
4,1658,Greg Olsen,CAR,1,DEN,9,7,77.8,73,0,...,0,0,0,0,14.3,19,away,grass,2016,5100

In [586]:
def_2015.sort_values('DraftKingsTightEndFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsTightEndFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsTightEndFantasyPointsAllowedAverage', inplace=True)

In [587]:
def_2016.reset_index(inplace=True)

In [588]:
def_2016['Rank'] =def_2016.index+1

In [589]:
def_2016.index = def_2016['Team']

In [590]:
# Add defensive rankings to dataframe

#te_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], te_2015['Opponent']))
te_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], te_2016['Opponent']))
#te_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], te_2017['Opponent']))

In [592]:
te_2016.shape

(1415, 24)

In [593]:
temp = te_2016

In [594]:
week1  = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [595]:
loc_df = location[location['year']==2016]

In [627]:
loc_df[loc_df['week']==17]

home_list = []

for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

week17['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [628]:
te_2016 = pd.concat([te_2016,week17])
te_2016.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk,h/a
162,103,15305,Demetrius Harris,KC,TE,17,LAC,1,0,0.0,...,0,0,0,0,0,0,0.0,0.0,12,away
163,103,16933,James O'Shaughnessy,KC,TE,17,LAC,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,12,away
164,103,11555,Jim Dray,SF,TE,17,SEA,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,4,away
165,103,9671,Matthew Mulligan,DET,TE,17,GB,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,21,away
166,103,11317,Clay Harbor,DET,TE,17,GB,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,21,away

In [629]:
surface = []
for idx, team in enumerate(te_2016['Team']):
    if te_2016.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[te_2016.iloc[idx]['Opponent']])


te_2016['surface'] = surface
te_2016.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk,h/a,surface
10,11,15602,Jack Doyle,IND,TE,1,DET,4,3,75.0,...,0,0,0,0,0,18.5,18.5,27,away,turf
12,13,13027,Julius Thomas,JAX,TE,1,GB,5,5,100.0,...,0,0,0,0,0,17.4,17.4,21,away,grass
13,14,13987,Dwayne Allen,IND,TE,1,DET,6,4,66.7,...,0,0,0,0,0,17.3,17.3,27,away,turf
17,18,16451,Eric Ebron,DET,TE,1,IND,5,5,100.0,...,0,0,0,0,0,15.6,15.6,23,away,turf
18,18,722,Jason Witten,DAL,TE,1,NYG,14,9,64.3,...,0,0,0,0,0,15.6,15.6,20,away,turf

In [630]:
te_2017['year']=2017
te_2016['year'] = 2016

In [637]:
te_2017.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets',
       'Receptions', 'ReceptionPercentage', 'ReceivingYards',
       'ReceivingTouchdowns', 'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'salary', 'def_rk', 'h/a', 'surface',
       'year'],
      dtype='object')

In [667]:
te_2017.shape

(1485, 25)

In [662]:
cols = te_2016.columns.tolist()
cols = cols[:-5] + cols[-1:] +cols[-5:-1]
te_2016 = te_2016[cols]

In [663]:
te_2016.shape

(1415, 25)

In [669]:
te=pd.concat([te,te_2017])
te.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
0,3,Craig Stevens,TEN,1,TB,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,21,away,grass,2015
1,722,Jason Witten,DAL,1,NYG,9,8,88.9,60,2,...,0.0,0,0,0,26.0,4000,31,away,turf,2015
2,852,Jacob Tamme,ATL,1,PHI,3,3,100.0,19,0,...,0.0,0,0,0,4.9,2600,11,away,grass,2015
3,1181,Martellus Bennett,CHI,1,GB,7,5,71.4,55,1,...,0.0,0,0,0,16.5,4300,14,away,grass,2015
4,1545,Anthony Fasano,TEN,1,TB,1,1,100.0,18,0,...,0.0,0,0,0,2.8,2500,21,away,grass,2015

In [670]:
te.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
1480,19304,Pharaoh Brown,OAK,17,LAC,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,8,home,grass,2017
1481,19335,Antony Auclair,TB,17,NO,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,2,away,turf,2017
1482,19390,Emanuel Byrd,GB,17,DET,2,2,100.0,31,0,...,0.0,0,0,0,5.1,3500,16,away,turf,2017
1483,19410,Ricky Seals-Jones,ARI,17,SEA,1,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,9,home,grass,2017
1484,19579,Tyrone Swoopes,SEA,17,ARI,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,17,home,turf,2017

In [671]:
te.to_csv('input/te/dk_stats_loc.csv', index=False)

## Running Backs

In [206]:
rb_2015= pd.concat([rb_2015,data10])
rb_2015.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
115,88,13255,Matt Asiata,MIN,RB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
116,88,15555,Zach Line,MIN,FB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
117,118,15018,Denard Robinson,JAX,RB,17,HOU,5,9,1.8,0,1,0,0,0,1,1,-0.1,-0.1
118,119,17217,Raheem Mostert,CLE,RB,17,PIT,0,0,0.0,0,0,0,0,0,1,1,-1.0,-1.0
119,119,13852,Bobby Rainey,TB,RB,17,CAR,0,0,0.0,0,0,0,0,0,1,1,-1.0,-1.0

In [142]:
rb_2016 = pd.concat([rb_2016,data10])
rb_2016.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
108,87,12323,Joique Bell,DET,RB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
109,87,18152,Dwayne Washington,DET,RB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
110,87,18452,Joe Kerridge,GB,FB,17,DET,1,0,0.0,0,0,0,0,0,0,0,0.0,0.0
111,112,18626,Brandon Burks,NYJ,RB,17,BUF,2,-4,-2.0,0,0,0,0,0,0,0,-0.4,-0.4
112,113,12985,DuJuan Harris,SF,RB,17,SEA,4,-1,-0.2,0,0,0,0,0,1,1,-1.1,-1.1

In [208]:
rb_2015 = add_salary(rb_2015,rb_2015_sal)

In [209]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary
0,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000
1,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,3000
2,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,3000
3,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,7800
4,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000

In [145]:
def_2016.head()

,Rank,Name,Team,Position,Played,DraftKingsQuarterbackFantasyPointsAllowedAverage,DraftKingsRunningbackFantasyPointsAllowedAverage,DraftKingsWideReceiverFantasyPointsAllowedAverage,DraftKingsTightEndFantasyPointsAllowedAverage,DraftKingsKickerFantasyPointsAllowedAverage,DraftKingsFantasyPointsAllowedAverage
6,7,Arizona Cardinals,ARI,DST,16,17.59,18.91,40.28,6.30,0.0,83.07
21,22,Tennessee Titans,TEN,DST,16,20.68,19.09,44.60,11.48,0.0,95.85
17,18,Dallas Cowboys,DAL,DST,16,18.22,19.23,36.69,18.12,0.0,92.26
3,4,Seattle Seahawks,SEA,DST,16,15.73,19.99,37.16,9.02,0.0,81.90
13,14,Chicago Bears,CHI,DST,16,18.20,20.71,40.41,10.42,0.0,89.74

In [385]:
def_2015.sort_values('DraftKingsRunningbackFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsRunningbackFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsRunningbackFantasyPointsAllowedAverage', inplace=True)

In [386]:
def_2017.reset_index(inplace=True)
def_2017['Rank']= def_2016.index +1

In [210]:
rb_2015.index = rb_2015['Team']

In [370]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,...,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
Team,,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,...,0,0,0,0,0.0,3000,28,away,turf,2015
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,...,0,0,0,0,0.0,3000,15,away,grass,2015
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,...,25,0,0,0,30.6,3000,5,away,grass,2015
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,...,26,2,0,0,17.6,7800,9,away,turf,2015
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,...,0,0,0,0,0.8,3000,11,away,turf,2015

In [387]:
def_2017.index=def_2017.Team

In [388]:
# Add defensive rankings to dataframe

#rb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], rb_2015['Opponent']))
#rb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], rb_2016['Opponent']))
rb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], rb_2017['Opponent']))

In [374]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,...,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
Team,,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,...,0,0,0,0,0.0,3000,18,away,turf,2015
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,...,0,0,0,0,0.0,3000,22,away,grass,2015
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,...,25,0,0,0,30.6,3000,13,away,grass,2015
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,...,26,2,0,0,17.6,7800,15,away,turf,2015
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,...,0,0,0,0,0.8,3000,9,away,turf,2015

In [213]:
temp=rb_2015

In [214]:
week1  = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [53]:
location = pd.read_csv('input/location.csv')

In [215]:
loc_df=location[location['year']==2015]

In [247]:
loc_df[loc_df['week']==17]

home_list = []
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

week17['h/a'] = home_list


week17.head()

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,17,NYJ,0,0,0.0,0,0,0,0,0,0,0,0.0,3500,6,away
WAS,957,Pierre Thomas,WAS,17,DAL,7,30,4.3,0,2,1,5,0,0,0,4.5,3600,8,away
GB,1589,John Kuhn,GB,17,MIN,1,3,3.0,0,2,2,14,0,0,0,3.7,3000,11,away
NE,1652,Steven Jackson,NE,17,MIA,14,35,2.5,1,1,1,20,0,0,0,12.5,3800,26,away
NO,2262,Tim Hightower,NO,17,ATL,16,66,4.1,1,5,5,41,0,0,0,21.7,3000,12,away

In [155]:
rb_2016 = pd.concat([rb_2015,week2]) 
rb_2016.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
NO,1589,John Kuhn,NO,1,OAK,2,4,2.0,0,1,0,0,0,0,0,0.4,3000,21,away
NO,2262,Tim Hightower,NO,1,OAK,4,9,2.2,0,1,1,1,0,0,0,2.0,null,21,away
NYJ,2699,Matt Forte,NYJ,1,CIN,22,96,4.4,0,7,5,59,0,0,0,20.5,4300,11,away
BUF,4640,Reggie Bush,BUF,1,BAL,3,-4,-1.3,0,1,0,0,0,0,0,-0.4,6100,12,away
CAR,4738,Mike Tolbert,CAR,1,DEN,2,6,3.0,0,1,1,1,0,0,0,1.7,3000,1,away

In [248]:
rb_2015 = pd.concat([rb_2015, week17])
rb_2015.tail()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
LAC,17120,Dreamius Smith,LAC,17,DEN,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,2,away
HOU,17199,Akeem Hunt,HOU,17,JAX,3,28,9.3,0,3,1,27,0,0,0,6.5,4500,29,away
CLE,17217,Raheem Mostert,CLE,17,PIT,0,0,0.0,0,0,0,0,0,1,1,-1.0,3000,23,away
SF,17254,Jarryd Hayne,SF,17,LAR,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,16,away
DAL,17360,Rod Smith,DAL,17,WAS,0,0,0.0,0,0,0,0,0,0,0,0.0,4600,27,away

In [613]:
rb_2016.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000,25,home
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,null,8,away
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,4300,16,home
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,6100,18,home
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000,17,away

In [523]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000,28,home
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,15,away
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,3000,5,home
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,7800,9,home
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000,11,away

In [249]:
surface = []
for idx, team in enumerate(rb_2015['Team']):
    if rb_2015.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[rb_2015.iloc[idx]['Opponent']])


rb_2015['surface'] = surface
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface
Team,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000,28,away,turf
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,15,away,grass
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,3000,5,away,grass
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,7800,9,away,turf
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000,11,away,turf

In [250]:
rb_2017['year']=2017
rb_2016['year']=2016
rb_2015['year']=2015

In [389]:
rb = pd.concat([rb_2015,rb_2016])
rb.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,...,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
Team,,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,...,0,0,0,0,0.0,3000,18,away,turf,2015
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,...,0,0,0,0,0.0,3000,22,away,grass,2015
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,...,25,0,0,0,30.6,3000,13,away,grass,2015
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,...,26,2,0,0,17.6,7800,15,away,turf,2015
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,...,0,0,0,0,0.8,3000,9,away,turf,2015

In [390]:
rb = pd.concat([rb,rb_2017])

In [391]:
rb.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'RushingAttempts',
       'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns',
       'ReceivingTargets', 'Receptions', 'ReceivingYards',
       'ReceivingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'salary', 'def_rk', 'h/a', 'surface',
       'year'],
      dtype='object')

In [392]:
rb.to_csv('input/rb/dk_stats_loc.csv', index=False)

# Wide Receivers

In [281]:
wr_2016_df = pd.concat([wr_2016_df, data9])
wr_2016_df.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,13.8,15.0,0,0,0.0,0,0,0,39.0,39.0
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,15.9,23.8,1,11,11.0,0,0,0,36.4,36.4
2,3,16906,Stefon Diggs,MIN,WR,2,GB,11,9,81.8,...,16.5,20.2,0,0,0.0,0,0,0,36.2,36.2
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,11.5,15.8,0,0,0.0,0,0,0,35.6,35.6
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,19.1,19.1,0,0,0.0,0,1,0,35.2,35.2

In [77]:
wr_2017 = wr_2017[0:600]

In [44]:
df2.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,UpcomingOpponentRank,UpcomingOpponentPositionRank,DraftKingsSalary,FantasyPointsDraftKings
0,1,4314,Tom Brady,NE,QB,9,WAS,16,15,8500,26.92
1,2,8244,Philip Rivers,LAC,QB,8,BAL,31,32,6600,26.72
2,3,4314,Tom Brady,NE,QB,5,DAL,18,10,7800,26.46
3,4,2428,Carson Palmer,ARI,QB,7,BAL,30,32,6700,26.30
4,5,13320,Cam Newton,CAR,QB,7,PHI,9,9,6600,26.22

In [111]:
wr_2015['year'] = 2015
wr_2016['year']=2016
wr_2017['year'] = 2017

In [40]:
def add_salary(df,df2):
    df = df.sort_values(['Week','PlayerID'])
    df = df.drop(['FantasyPointsPerGameDraftKings','Rank','Position'], axis=1)
    df.reset_index(inplace=True, drop=True)
    df2 = df2.sort_values(['Week','PlayerID'])
    df2 = df2.drop(['Rank','Position'], axis=1)
    df2.reset_index(inplace=True, drop=True)
    df['salary'] = df2['DraftKingsSalary']
    
    return df

In [331]:
wr_2016 = add_salary(wr_2016,wr_2016_sal)
wr_2016.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,def_rk,h/a,salary
0,2429,Andre Johnson,TEN,1,MIN,7,3,42.9,30,0,...,0,0,0.0,0,0,0,6.0,17,home,3900
1,3519,Vincent Jackson,TB,1,ATL,7,2,28.6,18,0,...,0,0,0.0,0,0,0,3.8,11,away,4400
2,3601,Eric Weems,ATL,1,TB,0,0,0.0,0,0,...,0,0,0.0,0,0,0,0.0,24,home,3000
3,3943,DeSean Jackson,WAS,1,PIT,10,6,60.0,102,0,...,0,0,0.0,0,0,0,19.2,22,home,6100
4,4358,Steve Smith,BAL,1,BUF,8,5,62.5,19,0,...,0,0,0.0,0,0,0,6.9,29,home,4900

In [383]:
cols =wr_2016.columns.tolist()
cols = cols[:-4] + cols[-1:] +cols[-3:-2] +cols[-4:-3] +cols[-2:-1]
df = wr_2016[cols]

In [385]:
df

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
0,2429,Andre Johnson,TEN,1,MIN,7,3,42.9,30,0,...,0,0.0,0,0,0,6.0,2016,3900,17,home
1,3519,Vincent Jackson,TB,1,ATL,7,2,28.6,18,0,...,0,0.0,0,0,0,3.8,2016,4400,11,away
2,3601,Eric Weems,ATL,1,TB,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,24,home
3,3943,DeSean Jackson,WAS,1,PIT,10,6,60.0,102,0,...,0,0.0,0,0,0,19.2,2016,6100,22,home
4,4358,Steve Smith,BAL,1,BUF,8,5,62.5,19,0,...,0,0.0,0,0,0,6.9,2016,4900,29,home
5,4556,Jordy Nelson,GB,1,JAX,9,6,66.7,32,1,...,0,0.0,0,0,0,15.2,2016,7700,19,away
6,5571,Larry Fitzgerald,ARI,1,NE,10,8,80.0,81,2,...,0,0.0,0,0,0,28.1,2016,6300,26,home
7,6211,Harry Douglas,TEN,1,MIN,5,2,40.0,21,0,...,0,0.0,0,0,0,4.1,2016,3400,17,home
8,6767,Pierre Garcon,WAS,1,PIT,6,6,100.0,51,0,...,0,0.0,0,0,0,11.1,2016,4400,22,home
9,7082,Devin Hester,BAL,1,BUF,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,null,29,home
10,7389,Eddie Royal,CHI,1,HOU,6,4,66.7,57,1,...,0,0.0,0,0,0,15.7,2016,3200,5,home
11,7651,Matthew Slater,NE,1,ARI,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,6100,6,away
12,8355,Julian Edelman,NE,1,ARI,7,7,100.0,66,0,...,16,5.3,0,0,0,15.2,2016,4200,6,away
13,8373,Brandon Tate,BUF,1,BAL,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3900,9,home
14,8529,Mike Wallace,BAL,1,BUF,6,3,50.0,91,1,...,11,11.0,0,0,0,19.2,2016,3600,29,home
15,8532,Kenny Britt,LAR,1,SF,6,4,66.7,67,0,...,0,0.0,0,0,0,10.7,2016,6500,32,away
16,8771,Darrius Heyward-Bey,PIT,1,WAS,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,5500,14,home
17,8914,Jeremy Maclin,KC,1,LAC,7,5,71.4,63,1,...,-1,-1.0,0,0,0,17.2,2016,4200,2,away
18,9331,Michael Crabtree,OAK,1,NO,9,7,77.8,87,0,...,0,0.0,0,0,0,17.7,2016,9800,12,home
19,9906,Danny Amendola,NE,1,ARI,4,3,75.0,48,0,...,0,0.0,0,0,0,7.8,2016,5700,6,away
20,11056,Antonio Brown,PIT,1,WAS,11,8,72.7,126,2,...,0,0.0,0,0,0,35.6,2016,3000,14,home
21,11063,Emmanuel Sanders,DEN,1,CAR,8,5,62.5,49,0,...,0,0.0,0,0,0,9.9,2016,6600,10,home
22,11084,Marc Mariani,TEN,1,MIN,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,7000,17,home
23,11182,Eric Decker,NYJ,1,CIN,7,2,28.6,37,1,...,0,0.0,0,0,0,11.7,2016,8500,18,away
24,11197,Demaryius Thomas,DEN,1,CAR,6,4,66.7,48,0,...,0,0.0,0,0,0,8.8,2016,3900,10,home
25,11270,Dez Bryant,DAL,1,NYG,5,1,20.0,8,0,...,0,0.0,0,0,0,1.8,2016,3000,7,home
26,11463,Brandon LaFell,CIN,1,NYJ,4,4,100.0,91,0,...,0,0.0,0,0,0,13.1,2016,7300,30,home
27,11501,Arrelious Benn,JAX,1,GB,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,7800,16,away
28,11565,Andre Roberts,DET,1,IND,1,1,100.0,8,0,...,0,0.0,0,0,0,1.8,2016,4500,25,home
29,11611,Golden Tate,DET,1,IND,7,7,100.0,41,0,...,2,2.0,0,0,0,11.3,2016,4100,25,home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2480,18036,Ricardo Louis,CLE,17,PIT,2,2,100.0,22,0,...,0,0.0,0,0,0,4.2,2016,3500,22,home
2481,18039,Pharoh Cooper,LAR,17,ARI,6,4,66.7,36,0,...,0,0.0,0,0,0,6.6,2016,null,6,away
2482,18047,Demarcus Robinson,KC,17,LAC,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,2,away
2483,18058,Tajae Sharpe,TEN,17,HOU,2,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3200,5,home
2484,18080,Trevor Davis,GB,17,DET,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3400,21,away
2485,18082,Tyreek Hill,KC,17,LAC,7,5,71.4,46,0,...,15,5.0,0,0,0,17.1,2016,3900,2,away
2486,18089,Rashard Higgins,CLE,17,PIT,1,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,4300,22,home
2487,18103,Jakeem Grant,MIA,17,NE,0,0,0.0,0,0,...,1,1.0,0,1,0,0.1,2016,null,26,home
2488,18116,Cody Core,CIN,17,BAL,5,4,80.0,82,0,...,0,0.0,0,0,0,12.2,2016,null,9,home
2489,18129,Aaron Burbridge,SF,17,SEA,2,1,50.0,24,0,...,0,0.0,0,0,0,3.4,2016,3000,3,away
2490,18145,Demarcus Ayers,PIT,17,CLE,12,5,41.7,44,1,...,-12,-6.0,0,0,0,14.2,2016,null,20,home
2491,18157,Charone Peake,NYJ,17,BUF,5,2,40.0,22,0,...,0,0.0,0,0,0,4.2,2016,null,29,away
2492,18187,Robby Anderson,NYJ,17,BUF,7,4,57.1,43,0,...,0,0.0,0,0,0,8.3,2016,null,29,away
2493,18197,Alex Erickson,CIN,17,BAL,0,0,0.0,0,0,...,0,0.0,0,1,0,0.0,2016,5600,9,home
2494,18221,Rashawn Scott,MIA,17,NE,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,null,26,home
2495,18234,Paul McRoberts,LAR,17,ARI,1,1,100.0,6,0,...,0,0.0,0,0,0,1.6,2016,3000,6,away
2496,18241,Johnny Holton,OAK,17,DEN,1,0,0.0,0,0,...,0,0.0,0,1,1,-1.0,2016,3000,1,home
2497,18257,Jalin Marshall,NYJ,17,BUF,4,3,75.0,22,1,...,0,0.0,0,0,0,11.2,2016,3000,29,away
2498,18269,Geronimo Allison,GB,17,DET,6,4,66.7,91,1,...,0,0.0,0,0,0,19.1,2016,4700,21,away
2499,18285,Roger Lewis,NYG,17,WAS,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,5800,14,away
2500,18323,Wendall Williams,HOU,17,TEN,4,2,50.0,41,0,...,0,0.0,0,0,0,6.1,2016,5000,13,home
2501,18361,Chester Rogers,IND,17,JAX,7,4,57.1,72,0,...,0,0.0,0,0,0,11.2,2016,3800,19,home
2502,18401,Tommylee Lewis,NO,17,ATL,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,11,away
2503,18407,Bralon Addison,CHI,17,MIN,1,1,100.0,11,0,...,4,4.0,0,1,1,1.5,2016,3000,17,home
2504,18422,Khalif Raymond,DEN,17,OAK,1,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,27,home
2505,18443,Maurice Harris,WAS,17,NYG,2,1,50.0,15,0,...,0,0.0,0,0,0,2.5,2016,5100,7,home
2506,18445,Mike Thomas,LAR,17,ARI,1,1,100.0,15,0,...,0,0.0,0,0,0,2.5,2016,null,6,away
2507,18596,Paul Turner,PHI,17,DAL,4,2,50.0,30,0,...,0,0.0,0,0,0,5.0,2016,5400,15,home
2508,18602,Tanner McEvoy,SEA,17,SF,2,2,100.0,16,0,...,0,0.0,0,0,0,3.6,2016,null,32,home
2509,18611,Bryce Treggs,PHI,17,DAL,2,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,5100,15,home

In [400]:
wr = pd.read_csv('input/wr/dk_stats_loc.csv')

In [404]:
wr_2015 = wr[wr['year']==2015] 
wr_2016 = wr[wr['year']==2016]
wr_2017 = wr[wr['year']==2017]

In [371]:
wr_2016['year']=2016

In [386]:
wr_2016 = df

In [394]:
def_2015.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)

In [409]:
def_2017.reset_index(inplace=True)
def_2017['Rank'] = def_2017.index+1

In [410]:
#def_2015.index=def_2015['Team']
#def_2016.index=def_2016['Team']
def_2017.index=def_2017['Team']

In [285]:
wr_2016 = wr_2016_df

In [412]:
# Add defensive rankings to dataframe

#wr_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], wr_2015['Opponent']))
#wr_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], wr_2016['Opponent']))
wr_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], wr_2017['Opponent']))

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [287]:
wr_2016.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,15.0,0,0,0.0,0,0,0,39.0,39.0,30
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,23.8,1,11,11.0,0,0,0,36.4,36.4,27
2,3,16906,Stefon Diggs,MIN,WR,2,GB,11,9,81.8,...,20.2,0,0,0.0,0,0,0,36.2,36.2,16
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,15.8,0,0,0.0,0,0,0,35.6,35.6,14
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,19.1,0,0,0.0,0,1,0,35.2,35.2,27

# Quarterbacks

In [74]:
df1= read_concat('input/qb/2016wk1_9.csv','input/qb/2016wk_10_17.csv')

df2 = read_concat('input/qb/2016_sal_wk1_9.csv','input/qb/2016_sal_wk10_17.csv')

df1= read_concat('input/qb/2017wk1_9.csv','input/qb/2017wk10_17.csv')

df2 = read_concat('input/qb/2017_sal_wk1_9.csv','input/qb/2017_sal_wk10_17.csv')

In [ ]:
# Add defensive rankings to dataframe

qb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], qb_2015['Opponent']))
qb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], qb_2016['Opponent']))
qb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], qb_2017['Opponent']))

In [76]:
qb.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,PassingTouchdowns,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary
0,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,1,1,70.96,0,0,0.0,0,7.84,5500
1,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,1,0,116.11,3,11,3.7,0,20.94,6900
2,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,1,3,53.12,1,2,2.0,0,11.92,4300
3,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,1,1,86.51,7,21,3.0,0,20.54,6000
4,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,2,1,95.02,3,-8,-2.7,0,16.72,7000

In [421]:
qb=pd.read_csv('input/qb/dk_stats_loc.csv')

In [422]:
qb_2015 = qb[qb['year']==2015]
qb_2016 = qb[qb['year']==2016]
qb_2017 = qb[qb['year']==2017]

In [426]:
def_2015.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)

In [436]:
def_2017.reset_index(inplace=True)
def_2017['Rank'] = def_2017.index +1

In [437]:
#def_2015.index=def_2015['Team']

#def_2016.index=def_2016['Team']

def_2017.index = def_2017['Team']

In [58]:
qb_2015['year'] = 2015

In [68]:
qb_2016['year']=2016

In [78]:
qb_2017['year'] = 2017

In [438]:
# Map defensive rankings fron defense df to qb_df by yer and opponent

#qb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], qb_2015['Opponent']))
#qb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], qb_2016['Opponent']))
qb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], qb_2017['Opponent']))

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [439]:
qb=pd.concat([qb_2015,qb_2016])

In [440]:
qb= pd.concat([qb, qb_2017])

In [441]:
qb.to_csv('input/qb/dk_stats_loc.csv')

In [73]:
qb_2016.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,BUF,22,33,66.7,258,7.8,...,0,100.32,4,-3,-0.8,0,13.02,6700,2016,10
1,732,Matt Ryan,ATL,1,TB,27,39,69.2,334,8.6,...,0,112.55,3,10,3.3,0,27.36,7100,2016,17
2,2428,Carson Palmer,ARI,1,NE,24,37,64.9,271,7.3,...,0,104.67,2,1,0.5,0,18.94,7100,2016,6
3,2593,Aaron Rodgers,GB,1,JAX,20,34,58.8,199,5.9,...,0,95.10,4,16,4.0,1,23.56,8500,2016,8
4,3807,Ben Roethlisberger,PIT,1,WAS,27,37,73.0,300,8.1,...,1,112.44,1,-2,-2.0,0,25.80,7800,2016,27

In [80]:
qb_2017.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,1,70.96,0,0,0.0,0,7.84,5500,2017,12
1,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,0,116.11,3,11,3.7,0,20.94,6900,2017,7
2,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,3,53.12,1,2,2.0,0,11.92,4300,2017,21
3,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,1,86.51,7,21,3.0,0,20.54,6000,2017,8
4,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,1,95.02,3,-8,-2.7,0,16.72,7000,2017,24

## Merge Dataframes

In [ ]:
data_qb = [qb_2015,qb_2016,qb_2017]

In [413]:
data_wr= [wr_2015,wr_2016,wr_2017]

In [82]:
qb= pd.concat(data)

In [414]:
wr= pd.concat(data_wr)

In [417]:
wr['ReceivingTargets'].max()

23

In [129]:
wr.shape

(5501, 23)

In [416]:
#qb.to_csv('input/qb/dk_stas_sal.csv', index=False)
wr.to_csv('input/wr/dk_stats_loc.csv', index=False)

In [ ]:
pd.read_

In [130]:
# add location to dataframes by mapping location of game from completed qb dataframe

qb = pd.read_csv('input/qb/dk_stats_loc.csv')

In [131]:
qb.head()

,Unnamed: 0,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
0,0,611,Joe Flacco,BAL,1,DEN,18,32,56.2,117,...,0,0,0.0,0,2.68,6700,2015,2,away,grass
1,1,732,Matt Ryan,ATL,1,PHI,23,34,67.6,298,...,5,7,1.4,0,18.62,7500,2015,30,home,turf
2,2,2428,Carson Palmer,ARI,1,NO,19,32,59.4,307,...,3,14,4.7,0,28.68,6500,2015,32,home,grass
3,3,2593,Aaron Rodgers,GB,1,CHI,18,23,78.3,189,...,8,35,4.4,0,23.06,8600,2015,15,away,grass
4,4,3807,Ben Roethlisberger,PIT,1,NE,26,38,68.4,351,...,0,0,0.0,0,22.04,7300,2015,13,away,turf

In [263]:
wr.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk
0,204,Roddy White,ATL,1,PHI,8,4,50.0,84,0,...,0,0,0.0,0,0,0,12.4,2015,6500,30
1,1986,Jason Avant,KC,1,HOU,0,0,0.0,0,0,...,0,0,0.0,0,0,0,0.0,2015,3000,3
2,2429,Andre Johnson,IND,1,BUF,10,4,40.0,24,0,...,0,0,0.0,0,0,0,6.4,2015,6100,18
3,2950,Steve Johnson,LAC,1,DET,6,6,100.0,82,1,...,0,0,0.0,0,0,0,20.2,2015,3700,20
4,3330,Miles Austin,PHI,1,ATL,3,2,66.7,22,0,...,0,0,0.0,0,0,0,4.2,2015,3000,12

In [139]:
qb_2015 = qb[qb['year']==2015]
qb_2015.index = qb_2015['Team']
wr_2015.index = wr_2015['Team']

In [145]:
wr_2015.reset_index(inplace=True, drop =True)

In [148]:
location = pd.read_csv('input/location.csv')
location.drop('Unnamed: 0', axis=1,inplace=True)

In [143]:
wr_2015['h/a'] = home

In [401]:
temp = wr_2017

In [395]:
week1  = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [393]:
loc_df = location[location['year']==2017]

In [402]:
week1.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets',
       'Receptions', 'ReceptionPercentage', 'ReceivingYards',
       'ReceivingTouchdowns', 'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'year', 'salary', 'def_rk', 'h/a'],
      dtype='object')

In [403]:
week2.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets',
       'Receptions', 'ReceptionPercentage', 'ReceivingYards',
       'ReceivingTouchdowns', 'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'year', 'salary', 'def_rk'],
      dtype='object')

In [434]:
loc_df[loc_df['week']==17]

home_list = []
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')


week17['h/a'] = home_list


week17.head()

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
2329,3601,Eric Weems,TEN,17,JAX,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,3400,23,home
2330,5571,Larry Fitzgerald,ARI,17,SEA,13,8,61.5,55,0,...,0,0.0,0,0,0,13.5,2017,6600,5,home
2331,7651,Matthew Slater,NE,17,NYJ,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,4100,24,away
2332,8373,Brandon Tate,BUF,17,MIA,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,null,21,home
2333,8529,Mike Wallace,BAL,17,CIN,13,5,38.5,40,1,...,0,0.0,0,0,0,15.0,2017,3000,11,home

In [435]:
wr_2017 = pd.concat([wr_2017,week17])
wr_2017.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
2476,19501,Justin Hardee,NO,17,TB,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,null,20,away
2477,19514,Keelan Cole,JAX,17,TEN,8,4,50.0,33,0,...,0,0.0,0,1,1,6.3,2017,3200,15,away
2478,19539,Travis Rudolph,NYG,17,WAS,4,1,25.0,29,0,...,0,0.0,0,0,0,3.9,2017,3000,14,away
2479,19627,Chris Thompson,HOU,17,IND,3,3,100.0,54,0,...,0,0.0,0,0,0,8.4,2017,3500,26,home
2480,19668,Lance Lenoir,DAL,17,PHI,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,6200,22,home

In [405]:
wr_2017 = pd.concat([week1,week2])
wr_2017.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
0,3601,Eric Weems,TEN,1,OAK,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,3000,7,home
1,4556,Jordy Nelson,GB,1,SEA,8,7,87.5,79,1,...,0,0.0,0,0,0,20.9,2017,7600,5,away
2,5571,Larry Fitzgerald,ARI,1,DET,13,6,46.2,74,0,...,0,0.0,0,0,0,13.4,2017,5900,24,home
3,6767,Pierre Garcon,SF,1,CAR,10,6,60.0,81,0,...,0,0.0,0,0,0,14.1,2017,3000,17,away
4,8373,Brandon Tate,BUF,1,NYJ,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,5300,24,home

In [217]:
wr_2015.shape

(2420, 24)

In [109]:
# Surface dictionary consisting of every team and the type of field they play on

surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'
              
             }

In [387]:
wr_2016.index = wr_2016['Team']

In [436]:
# Add the tyep of field the player palyed on by mapping the field on which the game was played to the surface dictionary

surface = []
for idx, team in enumerate(wr_2017['Team']):
    if wr_2017.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[wr_2017.iloc[idx]['Opponent']])


wr_2017['surface'] = surface

In [437]:
wr_2017.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a,surface
0,3601,Eric Weems,TEN,1,OAK,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,3000,7,home,grass
1,4556,Jordy Nelson,GB,1,SEA,8,7,87.5,79,1,...,0.0,0,0,0,20.9,2017,7600,5,away,turf
2,5571,Larry Fitzgerald,ARI,1,DET,13,6,46.2,74,0,...,0.0,0,0,0,13.4,2017,5900,24,home,grass
3,6767,Pierre Garcon,SF,1,CAR,10,6,60.0,81,0,...,0.0,0,0,0,14.1,2017,3000,17,away,grass
4,8373,Brandon Tate,BUF,1,NYJ,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,5300,24,home,turf

In [438]:
wr = pd.concat([wr,wr_2017])

In [439]:

wr.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a,surface
2476,19501,Justin Hardee,NO,17,TB,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,null,20,away,grass
2477,19514,Keelan Cole,JAX,17,TEN,8,4,50.0,33,0,...,0.0,0,1,1,6.3,2017,3200,15,away,grass
2478,19539,Travis Rudolph,NYG,17,WAS,4,1,25.0,29,0,...,0.0,0,0,0,3.9,2017,3000,14,away,grass
2479,19627,Chris Thompson,HOU,17,IND,3,3,100.0,54,0,...,0.0,0,0,0,8.4,2017,3500,26,home,turf
2480,19668,Lance Lenoir,DAL,17,PHI,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,6200,22,home,turf

In [441]:
wr.to_csv('input/wr/dk_stats_loc.csv', index=False)