In [1]:
import pandas as pd
import numpy as np

In [13]:
df= pd.read_csv('input/2012/rb/weekly_stats.csv')
df.drop(['Unnamed: 0','Rank', 'FantasyPointsPerGameDraftKings'], axis=1, inplace=True)
df=df.rename(columns={'FantasyPointsDraftKings':'points'})

team_stats = df.groupby(['Name','Week','Opponent']).sum()
team_stats.head(), team_stats.shape

(                               RushingAttempts  RushingYards  \
 Name            Week Opponent
 Adrian Peterson 1    JAX                    17            84
                 2    IND                    16            60
                 3    SF                     25            86
                 4    DET                    21           102
                 5    TEN                    17            88

                                RushingYardsPerAttempt  RushingTouchdowns  \
 Name            Week Opponent
 Adrian Peterson 1    JAX                          4.9                  2
                 2    IND                          3.8                  0
                 3    SF                           3.4                  0
                 4    DET                          4.9                  0
                 5    TEN                          5.2                  0

                                ReceivingTargets  Receptions  ReceivingYards  \
 Name            Week Opponent
 Adrian Peterson 1    JAX                      1           1               3
                 2    IND                      3           3              20
                 3    SF                       4           2              21
                 4    DET                      4           4              20
                 5    TEN                      3           3              15

                                ReceivingTouchdowns  Fumbles  FumblesLost  \
 Name            Week Opponent
 Adrian Peterson 1    JAX                         0        0            0
                 2    IND                         0        0            0
                 3    SF                          0        1            0
                 4    DET                         0        0            0
                 5    TEN                         0        0            0

                                points
 Name            Week Opponent
 Adrian Peterson 1    JAX         21.7
                 2    IND         11.0
                 3    SF          12.7
                 4    DET         19.2
                 5    TEN         13.3  , (2083, 11))

In [14]:
# Define a dataframe to contain the current year 3 game moving averages of all 2012 QBs
def create_recent_dataframe(df):
    columns = []
    for col in df.columns:
        columns.append('{}_ma'.format(col.lower()))
    new_df = pd.DataFrame(columns=columns, index =df.index)
    return new_df

In [15]:
# Create recent and current dataframes for all 2012 QBs
rb_recent_2012= create_recent_dataframe(team_stats)

In [16]:
#Populate recent dataframe with 3 game moving average for all qb's in 2012 season
# DO NOT CHANGE !!!!!!!!
for col in team_stats:  # Iterate through every attribute in the team_stats dataframe
    ma3 = []  # Create an empty list to hold the season average of the current attribute
    for player in team_stats.index.levels[0]:  # Iterate through every player in the team_stats df
        total = [] # INstantiate a deque container with a max length of 3 to hold the three most current games for player
        count = 0 # Counter to track week number 
        for week in team_stats.loc[player].index: # Iterate through every week for relevant player d
            if count < 3: # check count value to start 3 game moving average
                ma3.append(0)  # week 1 through 3 have 3 game movong average of 0
                total.append(team_stats.loc[player].loc[week][col])  # Add the value current player's attribute total from the left
                count += 1  # Increase count
            else:  # Once 3 game moving average is avaliable
                ma3.append(np.mean(total))  # Add the average of the 3 games held in totals 3 game moivng average list
                total.append(team_stats.loc[player].loc[week][col]) # Replace 3 set block with a first in first out process
    rb_recent_2012['{}_ma'.format(col.lower())] = ma3  # Populate databse with 3 game moving average list

In [17]:
rb_recent_2012.shape

(2083, 11)

In [18]:
rb_recent_2012[0:100]

                               rushingattempts_ma  rushingyards_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                 0.000000         0.000000
                2    IND                 0.000000         0.000000
                3    SF                  0.000000         0.000000
                4    DET                19.333333        76.666667
                5    TEN                19.750000        83.000000
                6    WAS                19.200000        84.000000
                7    ARI                18.833333        83.166667
                8    TB                 19.428571        93.142857
                9    SEA                18.875000        96.875000
                10   DET                18.666667       106.333333
                12   CHI                19.500000       112.800000
                13   GB                 19.363636       112.363636
                14   CHI                19.500000       120.500000
                15   LAR                20.384615       123.076923
                16   HOU                20.642857       129.428571
                17   GB                 20.933333       126.533333
Ahmad Bradshaw  1    DAL                 0.000000         0.000000
                2    TB                  0.000000         0.000000
                4    PHI                 0.000000         0.000000
                5    CLE                11.666667        44.333333
                6    SF                 16.250000        83.250000
                7    WAS                18.400000        89.800000
                8    DAL                17.333333        82.000000
                9    PIT                18.000000        81.428571
                10   CIN                17.625000        77.250000
                12   GB                 16.777778        75.000000
                13   WAS                16.100000        73.300000
                14   NO                 16.818182        76.000000
                16   BAL                16.333333        72.416667
                17   PHI                15.769231        69.846154
...                                           ...              ...
Andre Brown     2    TB                  0.000000         0.000000
                3    CAR                 0.000000         0.000000
                4    PHI                11.000000        61.333333
                5    CLE                 9.500000        49.500000
                7    WAS                 7.600000        39.600000
                8    DAL                 7.166667        35.833333
                9    PIT                 6.571429        33.714286
                10   CIN                 6.625000        32.000000
                12   GB                  6.666667        35.666667
Anthony Allen   1    CIN                 0.000000         0.000000
                2    PHI                 0.000000         0.000000
                3    NE                  0.000000         0.000000
                4    CLE                 1.333333         4.333333
                5    KC                  1.000000         3.250000
                6    DAL                 1.000000         2.600000
                7    HOU                 0.833333         2.166667
                9    CLE                 0.714286         1.857143
                10   OAK                 0.625000         1.625000
                11   PIT                 0.555556         1.444444
                12   LAC                 0.500000         1.300000
                13   PIT                 0.454545         1.181818
                14   WAS                 0.416667         1.083333
                15   DEN                 0.384615         1.000000
                16   NYG                 0.357143         0.928571
                17   CIN                 0.400000         1.333333
Anthony Dixon   1    GB                  0.000000         0.000000
                2    DET                 0.000000         0.000000
                3    MIN                 0.000000         0.000000
                4    NYJ                 0.000000         0.000000
                5    BUF                 1.000000         4.000000

                               rushingyardsperattempt_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                        0.000000
                2    IND                        0.000000
                3    SF                         0.000000
                4    DET                        4.033333
                5    TEN                        4.250000
                6    WAS                        4.440000
                7    ARI                        4.466667
                8    TB                         4.785714
                9    SEA                        5.212500
                10   DET                        5.822222
                12   CHI                        5.870000
                13   GB                         5.881818
                14   CHI                        6.225000
                15   LAR                        6.130769
                16   HOU                        6.321429
                17   GB                         6.126667
Ahmad Bradshaw  1    DAL                        0.000000
                2    TB                         0.000000
                4    PHI                        0.000000
                5    CLE                        3.600000
                6    SF                         4.375000
                7    WAS                        4.360000
                8    DAL                        4.233333
                9    PIT                        4.128571
                10   CIN                        4.012500
                12   GB                         4.200000
                13   WAS                        4.360000
                14   NO                         4.354545
                16   BAL                        4.241667
                17   PHI                        4.246154
...                                                  ...
Andre Brown     2    TB                         0.000000
                3    CAR                        0.000000
                4    PHI                        3.700000
                5    CLE                        3.475000
                7    WAS                        2.780000
                8    DAL                        2.883333
                9    PIT                        3.471429
                10   CIN                        3.400000
                12   GB                         4.055556
Anthony Allen   1    CIN                        0.000000
                2    PHI                        0.000000
                3    NE                         0.000000
                4    CLE                        1.066667
                5    KC                         0.800000
                6    DAL                        0.640000
                7    HOU                        0.533333
                9    CLE                        0.457143
                10   OAK                        0.400000
                11   PIT                        0.355556
                12   LAC                        0.320000
                13   PIT                        0.290909
                14   WAS                        0.266667
                15   DEN                        0.246154
                16   NYG                        0.228571
                17   CIN                        0.680000
Anthony Dixon   1    GB                         0.000000
                2    DET                        0.000000
                3    MIN                        0.000000
                4    NYJ                        0.000000
                5    BUF                        1.000000

                               rushingtouchdowns_ma  receivingtargets_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                   0.000000             0.000000
                2    IND                   0.000000             0.000000
                3    SF                    0.000000             0.000000
                4    DET                   0.666667             2.666667
                5    TEN                   0.500000             3.000000
                6    WAS                   0.400000             3.000000
                7    ARI                   0.333333             3.833333
                8    TB                    0.428571             3.857143
                9    SEA                   0.500000             3.500000
                10   DET                   0.666667             3.555556
                12   CHI                   0.700000             3.600000
                13   GB                    0.636364             3.909091
                14   CHI                   0.666667             3.750000
                15   LAR                   0.769231             3.615385
                16   HOU                   0.785714             3.357143
                17   GB                    0.733333             3.266667
Ahmad Bradshaw  1    DAL                   0.000000             0.000000
                2    TB                    0.000000             0.000000
                4    PHI                   0.000000             0.000000
                5    CLE                   0.333333             2.000000
                6    SF                    0.500000             3.000000
                7    WAS                   0.600000             2.600000
                8    DAL                   0.666667             3.000000
                9    PIT                   0.571429             2.571429
                10   CIN                   0.500000             2.250000
                12   GB                    0.444444             2.444444
                13   WAS                   0.500000             2.500000
                14   NO                    0.454545             2.454545
                16   BAL                   0.416667             2.333333
                17   PHI                   0.384615             2.230769
...                                             ...                  ...
Andre Brown     2    TB                    0.000000             0.000000
                3    CAR                   0.000000             0.000000
                4    PHI                   1.000000             2.333333
                5    CLE                   0.750000             2.000000
                7    WAS                   0.600000             1.600000
                8    DAL                   0.666667             1.500000
                9    PIT                   0.714286             1.571429
                10   CIN                   0.750000             1.375000
                12   GB                    0.777778             1.888889
Anthony Allen   1    CIN                   0.000000             0.000000
                2    PHI                   0.000000             0.000000
                3    NE                    0.000000             0.000000
                4    CLE                   0.000000             0.000000
                5    KC                    0.000000             0.000000
                6    DAL                   0.000000             0.000000
                7    HOU                   0.000000             0.000000
                9    CLE                   0.000000             0.000000
                10   OAK                   0.000000             0.000000
                11   PIT                   0.000000             0.111111
                12   LAC                   0.000000             0.100000
                13   PIT                   0.000000             0.090909
                14   WAS                   0.000000             0.083333
                15   DEN                   0.000000             0.076923
                16   NYG                   0.000000             0.142857
                17   CIN                   0.000000             0.200000
Anthony Dixon   1    GB                    0.000000             0.000000
                2    DET                   0.000000             0.000000
                3    MIN                   0.000000             0.000000
                4    NYJ                   0.000000             0.000000
                5    BUF                   0.000000             0.000000

                               receptions_ma  receivingyards_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX            0.000000           0.000000
                2    IND            0.000000           0.000000
                3    SF             0.000000           0.000000
                4    DET            2.000000          14.666667
                5    TEN            2.500000          16.000000
                6    WAS            2.600000          15.800000
                7    ARI            3.333333          21.500000
                8    TB             3.142857          19.285714
                9    SEA            2.875000          17.375000
                10   DET            2.888889          16.666667
                12   CHI            2.900000          15.500000
                13   GB             3.181818          16.818182
                14   CHI            3.000000          16.250000
                15   LAR            2.923077          16.230769
                16   HOU            2.714286          15.071429
                17   GB             2.600000          14.333333
Ahmad Bradshaw  1    DAL            0.000000           0.000000
                2    TB             0.000000           0.000000
                4    PHI            0.000000           0.000000
                5    CLE            1.666667          17.666667
                6    SF             2.250000          20.500000
                7    WAS            2.000000          17.200000
                8    DAL            2.333333          18.000000
                9    PIT            2.000000          15.428571
                10   CIN            1.750000          13.500000
                12   GB             1.888889          13.555556
                13   WAS            1.900000          18.300000
                14   NO             1.909091          17.818182
                16   BAL            1.750000          16.333333
                17   PHI            1.692308          15.692308
...                                      ...                ...
Andre Brown     2    TB             0.000000           0.000000
                3    CAR            0.000000           0.000000
                4    PHI            1.666667          12.000000
                5    CLE            1.500000          10.000000
                7    WAS            1.200000           8.000000
                8    DAL            1.166667           9.500000
                9    PIT            1.000000           8.142857
                10   CIN            0.875000           7.125000
                12   GB             1.333333           9.555556
Anthony Allen   1    CIN            0.000000           0.000000
                2    PHI            0.000000           0.000000
                3    NE             0.000000           0.000000
                4    CLE            0.000000           0.000000
                5    KC             0.000000           0.000000
                6    DAL            0.000000           0.000000
                7    HOU            0.000000           0.000000
                9    CLE            0.000000           0.000000
                10   OAK            0.000000           0.000000
                11   PIT            0.000000           0.000000
                12   LAC            0.000000           0.000000
                13   PIT            0.000000           0.000000
                14   WAS            0.000000           0.000000
                15   DEN            0.000000           0.000000
                16   NYG            0.000000           0.000000
                17   CIN            0.066667           0.333333
Anthony Dixon   1    GB             0.000000           0.000000
                2    DET            0.000000           0.000000
                3    MIN            0.000000           0.000000
                4    NYJ            0.000000           0.000000
                5    BUF            0.000000           0.000000

                               receivingtouchdowns_ma  fumbles_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                          0.0    0.000000
                2    IND                          0.0    0.000000
                3    SF                           0.0    0.000000
                4    DET                          0.0    0.333333
                5    TEN                          0.0    0.250000
                6    WAS                          0.0    0.200000
                7    ARI                          0.0    0.166667
                8    TB                           0.0    0.142857
                9    SEA                          0.0    0.250000
                10   DET                          0.0    0.222222
                12   CHI                          0.0    0.200000
                13   GB                           0.0    0.272727
                14   CHI                          0.0    0.250000
                15   LAR                          0.0    0.307692
                16   HOU                          0.0    0.285714
                17   GB                           0.0    0.266667
Ahmad Bradshaw  1    DAL                          0.0    0.000000
                2    TB                           0.0    0.000000
                4    PHI                          0.0    0.000000
                5    CLE                          0.0    0.000000
                6    SF                           0.0    0.250000
                7    WAS                          0.0    0.200000
                8    DAL                          0.0    0.166667
                9    PIT                          0.0    0.285714
                10   CIN                          0.0    0.250000
                12   GB                           0.0    0.333333
                13   WAS                          0.0    0.300000
                14   NO                           0.0    0.272727
                16   BAL                          0.0    0.250000
                17   PHI                          0.0    0.230769
...                                               ...         ...
Andre Brown     2    TB                           0.0    0.000000
                3    CAR                          0.0    0.000000
                4    PHI                          0.0    0.000000
                5    CLE                          0.0    0.000000
                7    WAS                          0.0    0.000000
                8    DAL                          0.0    0.000000
                9    PIT                          0.0    0.000000
                10   CIN                          0.0    0.000000
                12   GB                           0.0    0.000000
Anthony Allen   1    CIN                          0.0    0.000000
                2    PHI                          0.0    0.000000
                3    NE                           0.0    0.000000
                4    CLE                          0.0    0.000000
                5    KC                           0.0    0.000000
                6    DAL                          0.0    0.000000
                7    HOU                          0.0    0.000000
                9    CLE                          0.0    0.000000
                10   OAK                          0.0    0.000000
                11   PIT                          0.0    0.000000
                12   LAC                          0.0    0.000000
                13   PIT                          0.0    0.000000
                14   WAS                          0.0    0.000000
                15   DEN                          0.0    0.000000

In [19]:
rb_recent_2012.head()

                               rushingattempts_ma  rushingyards_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                 0.000000         0.000000
                2    IND                 0.000000         0.000000
                3    SF                  0.000000         0.000000
                4    DET                19.333333        76.666667
                5    TEN                19.750000        83.000000

                               rushingyardsperattempt_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                        0.000000
                2    IND                        0.000000
                3    SF                         0.000000
                4    DET                        4.033333
                5    TEN                        4.250000

                               rushingtouchdowns_ma  receivingtargets_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                   0.000000             0.000000
                2    IND                   0.000000             0.000000
                3    SF                    0.000000             0.000000
                4    DET                   0.666667             2.666667
                5    TEN                   0.500000             3.000000

                               receptions_ma  receivingyards_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                 0.0           0.000000
                2    IND                 0.0           0.000000
                3    SF                  0.0           0.000000
                4    DET                 2.0          14.666667
                5    TEN                 2.5          16.000000

                               receivingtouchdowns_ma  fumbles_ma  \
Name            Week Opponent
Adrian Peterson 1    JAX                          0.0    0.000000
                2    IND                          0.0    0.000000
                3    SF                           0.0    0.000000
                4    DET                          0.0    0.333333
                5    TEN                          0.0    0.250000

                               fumbleslost_ma  points_ma
Name            Week Opponent
Adrian Peterson 1    JAX                  0.0   0.000000
                2    IND                  0.0   0.000000
                3    SF                   0.0   0.000000
                4    DET                  0.0  15.133333
                5    TEN                  0.0  16.150000

In [20]:
rb_recent_2012.tail()

                              rushingattempts_ma  rushingyards_ma  \
Name           Week Opponent
Willis McGahee 6    LAC                16.600000        75.200000
               8    NO                 16.666667        72.000000
               9    CIN                17.571429        79.142857
               10   CAR                18.250000        77.500000
               11   LAC                17.777778        75.111111

                              rushingyardsperattempt_ma  rushingtouchdowns_ma  \
Name           Week Opponent
Willis McGahee 6    LAC                        4.320000              0.600000
               8    NO                         4.150000              0.500000
               9    CIN                        4.314286              0.571429
               10   CAR                        4.137500              0.500000
               11   LAC                        4.122222              0.444444

                              receivingtargets_ma  receptions_ma  \
Name           Week Opponent
Willis McGahee 6    LAC                  3.400000       2.800000
               8    NO                   3.666667       3.000000
               9    CIN                  3.428571       2.857143
               10   CAR                  3.125000       2.625000
               11   LAC                  3.444444       2.777778

                              receivingyards_ma  receivingtouchdowns_ma  \
Name           Week Opponent
Willis McGahee 6    LAC               18.200000                     0.0
               8    NO                22.166667                     0.0
               9    CIN               23.714286                     0.0
               10   CAR               21.250000                     0.0
               11   LAC               22.555556                     0.0

                              fumbles_ma  fumbleslost_ma  points_ma
Name           Week Opponent
Willis McGahee 6    LAC         0.400000        0.400000  16.940000
               8    NO          0.333333        0.333333  16.416667
               9    CIN         0.428571        0.428571  17.714286
               10   CAR         0.375000        0.375000  16.500000
               11   LAC         0.555556        0.444444  15.988889

In [21]:
rb_recent_2012.to_csv('input/2012/rb/rb_recent_2012.csv', index=True)