In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [2]:
wr= pd.read_csv('input/wr/wr_loc_cleaned.csv')
wr.head()

,year,games,Name,Week,Opponent,Team,tar,rec,yds,yds/rec,yds/tar,td,def_rk,h/a_1,surface_0,points
0,2012.0,1,AJ Green,1,BAL,CIN,11,5,70,14.0,6.4,0,30,0.0,1.0,7.0
1,2012.0,1,Aldrick Robinson,1,NO,WAS,6,4,52,13.0,8.7,1,25,0.0,0.0,11.2
2,2012.0,1,Alshon Jeffery,1,IND,CHI,5,3,80,26.7,16.0,1,2,1.0,1.0,14.0
3,2012.0,1,Andre Holmes,1,NYG,DAL,0,0,0,0.0,0.0,0,11,0.0,0.0,0.0
4,2012.0,1,Andre Johnson,1,MIA,HOU,10,8,119,14.9,11.9,1,22,1.0,0.0,17.9

In [3]:
wr['year'].unique()

array([2012., 2014., 2015., 2016., 2017., 2018., 2013.])

In [4]:
wr_18=wr[wr['year']==2018]
wr_18['Week'].unique()

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [5]:
wr_18[wr_18['Name']=='AJ Green']

,year,games,Name,Week,Opponent,Team,tar,rec,yds,yds/rec,yds/tar,td,def_rk,h/a_1,surface_0,points
12544,2018.0,88,AJ Green,1,IND,CIN,8,6,92,15.3,11.5,1,17,0.0,0.0,20.2
12707,2018.0,89,AJ Green,2,BAL,CIN,9,5,69,13.8,7.7,3,3,1.0,0.0,29.9
12844,2018.0,90,AJ Green,3,CAR,CIN,8,5,58,11.6,7.2,0,16,0.0,1.0,10.8
13006,2018.0,91,AJ Green,4,ATL,CIN,8,4,78,19.5,9.8,1,29,0.0,0.0,17.8
13144,2018.0,92,AJ Green,5,MIA,CIN,10,6,112,18.7,11.2,0,11,1.0,0.0,20.2
13294,2018.0,93,AJ Green,6,PIT,CIN,12,7,85,12.1,7.1,0,30,1.0,0.0,15.5
13452,2018.0,94,AJ Green,7,KC,CIN,14,7,117,16.7,8.4,0,20,0.0,1.0,21.7
15846,2018.0,95,AJ Green,8,TB,CIN,7,5,76,15.2,10.9,1,25,1.0,0.0,18.6

In [6]:
wr.sort_values(['Name','games'], inplace=True)
wr.head()

,year,games,Name,Week,Opponent,Team,tar,rec,yds,yds/rec,yds/tar,td,def_rk,h/a_1,surface_0,points
0,2012.0,1,AJ Green,1,BAL,CIN,11,5,70,14.0,6.4,0,30,0.0,1.0,7.0
152,2012.0,2,AJ Green,2,CLE,CIN,12,7,58,8.3,4.8,1,16,1.0,0.0,11.8
303,2012.0,3,AJ Green,3,WAS,CIN,11,9,183,20.3,16.6,1,28,0.0,1.0,25.4
456,2012.0,4,AJ Green,4,JAX,CIN,9,6,117,19.5,13.0,1,15,0.0,1.0,17.7
601,2012.0,5,AJ Green,5,MIA,CIN,13,9,65,7.2,5.0,1,22,1.0,0.0,12.5

In [7]:
wr.reset_index(drop=True, inplace=True)
wr.tail()

,year,games,Name,Week,Opponent,Team,tar,rec,yds,yds/rec,yds/tar,td,def_rk,h/a_1,surface_0,points
15965,2018.0,19,Zay Jones,4,GB,BUF,7,4,38,9.5,5.4,0,13,0.0,1.0,7.8
15966,2018.0,20,Zay Jones,5,TEN,BUF,4,3,20,6.7,5.0,0,18,1.0,0.0,5.0
15967,2018.0,21,Zay Jones,6,HOU,BUF,8,3,35,11.7,4.4,1,7,0.0,0.0,12.5
15968,2018.0,22,Zay Jones,7,IND,BUF,5,3,27,9.0,5.4,0,13,0.0,0.0,5.7
15969,2018.0,23,Zay Jones,8,NE,BUF,8,6,55,9.2,6.9,0,8,1.0,0.0,11.5

In [8]:
wr.shape

(15970, 16)

In [7]:
def create_sorted_dict (df):
    df_sorted = df.sort_values(['Name','games'])
    sorted_dict = {}
    for player in df_sorted['Name']:
        sorted_dict['{}'.format(player)] = {'year':df_sorted[df_sorted['Name']==player]['year'],
                                            'Opponent':df_sorted[df_sorted['Name']==player]['Opponent'],
                                            'points':df_sorted[df_sorted['Name']==player]['points'],
                                            'def_rk':df_sorted[df_sorted['Name']==player]['def_rk'],
                                            'surface_0':df_sorted[df_sorted['Name']==player]['surface_0'],
                                            'h/a_1':df_sorted[df_sorted['Name']== player]['h/a_1'],
                                            'games': df_sorted[df_sorted['Name']==player]['games']
                                           }
       
    return sorted_dict

In [8]:
wr_sorted_dict = create_sorted_dict(wr)

In [140]:
# Create a data frame to investigate the points attribute of the dataset. 


def get_points_df(df):
    total_points = df['points'].sum()
    total_games = df['points'].count()

    val_lst = []
    sal_lst = []
    games_lst = []
    wght_avg=[]
    players = []
    avg_lst=[]

    for name in list(df['Name'].unique()):
        players.append(name)
        player_games = df[df['Name'] ==name].describe().loc['count'][0]
        games_lst.append(player_games)
        avg_points = round(df[df['Name'] ==name].describe()['points'].mean(),2)
        avg_lst.append(avg_points)
        wght_avg.append((round(avg_points + (avg_points* (player_games/total_games)),2)))
        sal_avg= round(df[df['Name'] ==name].describe()['salary'].mean(),2)
        sal_lst.append(sal_avg)
        val = round(sal_avg/avg_points,2)
        val_lst.append(val)
     
    df_eng = pd.DataFrame()
    df_eng['player'] = (df['Name'].unique())
    df_eng['games'] = games_lst
    df_eng['avg_points']= avg_lst
    df_eng['wght_avg'] = wght_avg
    df_eng['sal_avg'] = sal_lst
    df_eng['val'] = val_lst
    df_eng.head()
    
    return df_eng

## Group Dataframes

In [9]:
# A function to create a dictonary of grouped data frames

def grouped_dict(csv):
    
    df= pd.read_csv(csv)
    

    yearly_dict = {}
    for year in list(df['year'].unique()):
        yearly_dict['player_{}'.format(year)] = (df[df['year']==year]).drop('year',axis=1).groupby(['Name','games','Opponent']).sum()
        


    return yearly_dict

In [10]:
def conv_atts(grouped_dict):
    for group in grouped_dict:
        grouped_dict['{}'.format(group)]['h/a_1'] = grouped_dict['{}'.format(group)]['h/a_1'].astype('category')
        grouped_dict['{}'.format(group)]['surface_0'] = grouped_dict['{}'.format(group)]['surface_0'].astype('category')
    
    return grouped_dict

In [11]:
wr_group = grouped_dict('input/wr/wr_loc_cleaned.csv')

In [12]:
wr_group = conv_atts(wr_group)

In [13]:
wr_group['player_2013.0'].head()

                         Week  tar  rec  yds  yds/rec  yds/tar  td  def_rk  \
Name     games Opponent
AJ Green 17    CHI          1   13    9  162     18.0     12.5   2      11
         18    GB           3    8    4   46     11.5      5.8   1      15
         19    CLE          4   15    7   51      7.3      3.4   0      28
         21    NE           5    8    5   61     12.2      7.6   0      23
         22    BUF          6   11    6  103     17.2      9.4   1      18

                        h/a_1 surface_0  points
Name     games Opponent
AJ Green 17    CHI        0.0       1.0    40.2
         18    GB         1.0       0.0    14.6
         19    CLE        0.0       1.0    12.1
         21    NE         1.0       0.0    11.1
         22    BUF        0.0       0.0    25.3

In [14]:
def drop_col (grouped_df):
    for group in grouped_df:
        grouped_df[group].drop('h/a_1', axis=1, inplace=True)
        grouped_df[group].drop('surface_0',axis=1, inplace=True)
        grouped_df[group].drop('points',axis=1, inplace=True)
        grouped_df[group].drop('def_rk',axis=1, inplace=True)
        grouped_df[group].drop('Week', axis=1, inplace=True)

    return grouped_df

In [15]:
wr_group= drop_col(wr_group)

In [17]:
wr_group['player_2015.0'].columns

Index(['tar', 'rec', 'yds', 'yds/rec', 'yds/tar', 'td'], dtype='object')

## Current Stats
Weekly moving average for every year from 2015 through 2018

In [18]:
# Week 1 stats are player's career average through 2014 season
# Populate current dataframe with current year averages of players

def insert_data (grouped_df):
    new_df = pd.DataFrame(index=grouped_df.index)
    for col in grouped_df: # Iterate through every attribute in the team_stats dataframe
        if col not in list(['def_rk','surface_0','h/a_1','games','points']):
            points=[]  # Create an empty list to hold the season average of the current attribute
            for player in grouped_df.index.levels[0]:  # Iterate through every player in the team_stats df
                total =[]# create an empty list to hold the weekly attributes valu3

                for week in grouped_df.loc[player].index: # Iterate throough every week for the current player
                    total.append(grouped_df.loc[player].loc[week][col]) # Add player's value for the current week's attribute to the total list
                    points.append(round(np.mean(total),2))  # Add the average of the total list to the season average list

            new_df['{}_avg'.format(col.lower())] = points # Insert season average list for current attribute into the current stats dataframe
        else:
            None
    return new_df

In [19]:
weekly_2012 = insert_data(wr_group['player_2012.0'])
weekly_2013 = insert_data(wr_group['player_2013.0'])
weekly_2014 = insert_data(wr_group['player_2014.0'])
weekly_2015 = insert_data(wr_group['player_2015.0'])
weekly_2016 = insert_data(wr_group['player_2016.0'])
weekly_2017 = insert_data(wr_group['player_2017.0'])
weekly_2018 = insert_data(wr_group['player_2018.0'])

In [20]:
weekly_2012.head()

                         tar_avg  rec_avg  yds_avg  yds/rec_avg  yds/tar_avg  \
Name     games Opponent
AJ Green 1     BAL         11.00     5.00    70.00        14.00         6.40
         2     CLE         11.50     6.00    64.00        11.15         5.60
         3     WAS         11.33     7.00   103.67        14.20         9.27
         4     JAX         10.75     6.75   107.00        15.52        10.20
         5     MIA         11.20     7.20    98.60        13.86         9.16

                         td_avg
Name     games Opponent
AJ Green 1     BAL         0.00
         2     CLE         0.50
         3     WAS         0.67
         4     JAX         0.75
         5     MIA         0.80

In [21]:
def shift_dict(df):

    shift_dict = {}
    df.reset_index(inplace=True)
    for player in df['Name'].unique():
        shift_dict[player]=df[df['Name']==player].shift(1).fillna(0)
    df_shifted = pd.concat(shift_dict)
    df_shifted.drop('Name', axis=1, inplace=True)
    
    
    
    return df_shifted

In [22]:
player_2012_shifted = shift_dict(weekly_2012)
player_2013_shifted = shift_dict(weekly_2013)
player_2014_shifted = shift_dict(weekly_2014)
player_2015_shifted = shift_dict(weekly_2015)
player_2016_shifted = shift_dict(weekly_2016)
player_2017_shifted = shift_dict(weekly_2017)
player_2018_shifted = shift_dict(weekly_2018)

In [23]:
player_2012_shifted['year']=2012
player_2013_shifted['year']=2013
player_2014_shifted['year']=2014
player_2015_shifted['year']=2015
player_2016_shifted['year']=2016
player_2017_shifted['year']=2017
player_2018_shifted['year']=2018

In [24]:
player_2012_shifted.head()

            games Opponent  tar_avg  rec_avg  yds_avg  yds/rec_avg  \
AJ Green 0    0.0        0     0.00     0.00     0.00         0.00
         1    1.0      BAL    11.00     5.00    70.00        14.00
         2    2.0      CLE    11.50     6.00    64.00        11.15
         3    3.0      WAS    11.33     7.00   103.67        14.20
         4    4.0      JAX    10.75     6.75   107.00        15.52

            yds/tar_avg  td_avg  year
AJ Green 0         0.00    0.00  2012
         1         6.40    0.00  2012
         2         5.60    0.50  2012
         3         9.27    0.67  2012
         4        10.20    0.75  2012

In [94]:
player_weekly_avg = pd.concat([player_2012_shifted,player_2013_shifted, player_2014_shifted,player_2015_shifted, player_2016_shifted, player_2017_shifted, player_2018_shifted])

player_weekly_avg.head()

            games Opponent  tar_avg  rec_avg  yds_avg  yds/rec_avg  \
AJ Green 0    0.0        0     0.00     0.00     0.00         0.00
         1    1.0      BAL    11.00     5.00    70.00        14.00
         2    2.0      CLE    11.50     6.00    64.00        11.15
         3    3.0      WAS    11.33     7.00   103.67        14.20
         4    4.0      JAX    10.75     6.75   107.00        15.52

            yds/tar_avg  td_avg  year
AJ Green 0         0.00    0.00  2012
         1         6.40    0.00  2012
         2         5.60    0.50  2012
         3         9.27    0.67  2012
         4        10.20    0.75  2012

In [26]:
temp = player_weekly_avg.drop(['games','Opponent'], axis=1)

In [27]:
temp.columns

Index(['tar_avg', 'rec_avg', 'yds_avg', 'yds/rec_avg', 'yds/tar_avg', 'td_avg',
       'year'],
      dtype='object')

In [96]:
player_weekly_avg.reset_index(inplace=True)
player_weekly_avg.head()

,level_0,level_1,games,Opponent,tar_avg,rec_avg,yds_avg,yds/rec_avg,yds/tar_avg,td_avg,year
0,AJ Green,0,0.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2012
1,AJ Green,1,1.0,BAL,11.00,5.00,70.00,14.00,6.40,0.00,2012
2,AJ Green,2,2.0,CLE,11.50,6.00,64.00,11.15,5.60,0.50,2012
3,AJ Green,3,3.0,WAS,11.33,7.00,103.67,14.20,9.27,0.67,2012
4,AJ Green,4,4.0,JAX,10.75,6.75,107.00,15.52,10.20,0.75,2012

In [102]:
player_weekly_avg.sort_values(['level_0','year', 'games'], inplace=True)
player_weekly_avg.head()

,level_0,level_1,games,Opponent,tar_avg,rec_avg,yds_avg,yds/rec_avg,yds/tar_avg,td_avg,year
0,AJ Green,0,0.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2012
67,AJ Green,1,1.0,BAL,11.00,5.00,70.00,14.00,6.40,0.00,2012
66,AJ Green,2,2.0,CLE,11.50,6.00,64.00,11.15,5.60,0.50,2012
65,AJ Green,3,3.0,WAS,11.33,7.00,103.67,14.20,9.27,0.67,2012
64,AJ Green,4,4.0,JAX,10.75,6.75,107.00,15.52,10.20,0.75,2012

In [104]:
player_weekly_avg.reset_index(inplace=True, drop=True)
player_weekly_avg.head()

,level_0,level_1,games,Opponent,tar_avg,rec_avg,yds_avg,yds/rec_avg,yds/tar_avg,td_avg,year
0,AJ Green,0,0.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2012
1,AJ Green,1,1.0,BAL,11.00,5.00,70.00,14.00,6.40,0.00,2012
2,AJ Green,2,2.0,CLE,11.50,6.00,64.00,11.15,5.60,0.50,2012
3,AJ Green,3,3.0,WAS,11.33,7.00,103.67,14.20,9.27,0.67,2012
4,AJ Green,4,4.0,JAX,10.75,6.75,107.00,15.52,10.20,0.75,2012

In [37]:
player_weekly_avg.reset_index(inplace=True, drop=True)

In [105]:
player_weekly_avg.drop(['Opponent','level_0','level_1','games'],axis=1, inplace=True)
player_weekly_avg.shape

(15970, 7)

In [106]:
player_weekly_avg.head()

   tar_avg  rec_avg  yds_avg  yds/rec_avg  yds/tar_avg  td_avg  year
0     0.00     0.00     0.00         0.00         0.00    0.00  2012
1    11.00     5.00    70.00        14.00         6.40    0.00  2012
2    11.50     6.00    64.00        11.15         5.60    0.50  2012
3    11.33     7.00   103.67        14.20         9.27    0.67  2012
4    10.75     6.75   107.00        15.52        10.20    0.75  2012

## Recent Player Stats
Calculate the 4 game moving average of all attributes for each player and insert resluts into positional dataframe

In [40]:
# A function designed to calcuate a player's 4 game moving average in seasons 2015,2016,2017,2018

def moving_average(grouped_df, games):
    new_grouped_df = pd.DataFrame(index = grouped_df.index)
    for col in grouped_df:  # Iterate through every attribute in the team_stats dataframe
        if col not in list(['def_rk','surface_0','h/a_1','games','points']):
            ma4 = []  # Create an empty list to hold the season average of the current attribute
            for player in grouped_df.index.levels[0]:  # Iterate through every player in the team_stats df
                total = [] # INstantiate a deque container with a max length of 3 to hold the three most current games for player
                count = 0 # Counter to track week number 
                for week in grouped_df.loc[player].index: # Iterate through every week for relevant player d
                    if count < games: # check count value to start 3 game moving average
                        ma4.append(0)  # week 1 through 3 have 3 game movong average of 0
                        total.append(grouped_df.loc[player].loc[week][col])  # Add the value current player's attribute total from the left
                        count += 1  # Increase count
                    else:  # Once 3 game moving average is avaliable
                        ma4.append(np.mean(total))  # Add the average of the 3 games held in totals 3 game moivng average list
                        total.append(grouped_df.loc[player].loc[week][col]) # Replace 3 set block with a first in first out process
        else:
            None
        new_grouped_df['{}_ma'.format(col.lower())] = ma4  # Populate databse with 3 game moving average list
       

    return new_grouped_df

In [41]:
player_ma_2012 = moving_average(wr_group['player_2012.0'],4)
player_ma_2013 = moving_average(wr_group['player_2013.0'],4)
player_ma_2014 = moving_average(wr_group['player_2014.0'],4)
player_ma_2015 = moving_average(wr_group['player_2015.0'],4)
player_ma_2016 = moving_average(wr_group['player_2016.0'],4)
player_ma_2017 = moving_average(wr_group['player_2017.0'],4)
player_ma_2018 = moving_average(wr_group['player_2018.0'],4)

In [116]:
yearly_ma_grp = pd.concat([player_ma_2012, player_ma_2013])
yearly_ma_grp = pd.concat([yearly_ma_grp, player_ma_2014])
yearly_ma_grp = pd.concat([yearly_ma_grp, player_ma_2015])
yearly_ma_grp = pd.concat([yearly_ma_grp, player_ma_2016])
yearly_ma_grp = pd.concat([yearly_ma_grp,player_ma_2017])
yearly_ma_grp = pd.concat([yearly_ma_grp,player_ma_2018])
yearly_ma_grp.head()

                         tar_ma  rec_ma  yds_ma  yds/rec_ma  yds/tar_ma  td_ma
Name     games Opponent
AJ Green 1     BAL         0.00    0.00     0.0       0.000         0.0   0.00
         2     CLE         0.00    0.00     0.0       0.000         0.0   0.00
         3     WAS         0.00    0.00     0.0       0.000         0.0   0.00
         4     JAX         0.00    0.00     0.0       0.000         0.0   0.00
         5     MIA        10.75    6.75   107.0      15.525        10.2   0.75

In [117]:
yearly_ma_grp.reset_index(inplace=True)

In [118]:
yearly_ma_grp.sort_values(['Name','games'],inplace=True)
yearly_ma_grp.head()

,Name,games,Opponent,tar_ma,rec_ma,yds_ma,yds/rec_ma,yds/tar_ma,td_ma
0,AJ Green,1,BAL,0.00,0.00,0.0,0.000,0.0,0.00
1,AJ Green,2,CLE,0.00,0.00,0.0,0.000,0.0,0.00
2,AJ Green,3,WAS,0.00,0.00,0.0,0.000,0.0,0.00
3,AJ Green,4,JAX,0.00,0.00,0.0,0.000,0.0,0.00
4,AJ Green,5,MIA,10.75,6.75,107.0,15.525,10.2,0.75

In [123]:
yearly_ma_grp.reset_index(inplace=True, drop=True)
yearly_ma_grp.head()

,Name,games,Opponent,tar_ma,rec_ma,yds_ma,yds/rec_ma,yds/tar_ma,td_ma
0,AJ Green,1,BAL,0.00,0.00,0.0,0.000,0.0,0.00
1,AJ Green,2,CLE,0.00,0.00,0.0,0.000,0.0,0.00
2,AJ Green,3,WAS,0.00,0.00,0.0,0.000,0.0,0.00
3,AJ Green,4,JAX,0.00,0.00,0.0,0.000,0.0,0.00
4,AJ Green,5,MIA,10.75,6.75,107.0,15.525,10.2,0.75

In [124]:
yearly_ma_grp

,Name,games,Opponent,tar_ma,rec_ma,yds_ma,yds/rec_ma,yds/tar_ma,td_ma
0,AJ Green,1,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,AJ Green,2,CLE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,AJ Green,3,WAS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,AJ Green,4,JAX,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,AJ Green,5,MIA,10.750000,6.750000,107.000000,15.525000,10.200000,0.750000
5,AJ Green,6,CLE,11.200000,7.200000,98.600000,13.860000,9.160000,0.800000
6,AJ Green,7,PIT,11.166667,7.166667,104.666667,14.766667,9.683333,1.000000
7,AJ Green,8,DEN,10.428571,6.285714,90.857143,13.800000,8.485714,1.000000
8,AJ Green,9,NYG,10.250000,6.375000,91.875000,13.837500,8.800000,1.000000
9,AJ Green,10,KC,10.222222,6.444444,91.111111,13.644444,8.766667,1.000000
10,AJ Green,11,OAK,10.400000,6.400000,91.100000,13.800000,8.650000,1.000000
11,AJ Green,12,LAC,10.272727,6.090909,92.909091,15.909091,8.981818,0.909091
12,AJ Green,13,DAL,10.500000,6.333333,92.250000,15.366667,8.775000,0.833333
13,AJ Green,14,PHI,10.307692,6.076923,88.538462,15.315385,8.523077,0.769231
14,AJ Green,15,PIT,10.285714,6.071429,86.285714,14.900000,8.321429,0.785714
15,AJ Green,16,BAL,10.800000,6.333333,88.266667,14.680000,8.193333,0.733333
16,AJ Green,17,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,AJ Green,18,GB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,AJ Green,19,CLE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,AJ Green,21,NE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,AJ Green,22,BUF,11.000000,6.250000,80.000000,12.250000,7.325000,0.750000
21,AJ Green,23,DET,11.000000,6.200000,84.600000,13.240000,7.740000,0.800000
22,AJ Green,24,NYJ,10.500000,6.166667,96.333333,15.333333,9.683333,0.833333
23,AJ Green,25,MIA,10.000000,5.714286,99.000000,18.614286,10.642857,0.714286
24,AJ Green,26,BAL,11.125000,6.375000,102.625000,17.737500,10.150000,0.625000
25,AJ Green,27,CLE,11.555556,6.555556,108.000000,17.866667,10.144444,0.666667
26,AJ Green,28,LAC,10.900000,6.100000,97.900000,16.430000,9.270000,0.600000
27,AJ Green,29,IND,10.545455,6.000000,96.545455,16.445455,9.509091,0.636364
28,AJ Green,30,PIT,10.333333,6.000000,94.500000,16.075000,9.466667,0.666667
29,AJ Green,31,MIN,10.923077,6.230769,94.384615,15.630769,9.138462,0.615385
...,...,...,...,...,...,...,...,...,...
15940,Zach Pascal,1,CIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15941,Zach Pascal,2,PHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15942,Zach Pascal,3,HOU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15943,Zach Pascal,4,NE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15944,Zach Pascal,5,NYJ,5.000000,2.250000,22.250000,10.575000,6.700000,0.250000
15945,Zach Pascal,6,BUF,5.400000,2.800000,24.800000,9.860000,6.360000,0.200000
15946,Zach Pascal,7,OAK,4.500000,2.333333,20.666667,8.216667,5.300000,0.166667
15947,Zay Jones,1,NYJ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15948,Zay Jones,2,CAR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15949,Zay Jones,3,DEN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15950,Zay Jones,4,ATL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15951,Zay Jones,5,CIN,4.250000,1.000000,14.250000,12.000000,2.950000,0.000000
15952,Zay Jones,6,TB,4.600000,1.000000,13.200000,11.400000,2.660000,0.000000
15953,Zay Jones,7,OAK,5.333333,1.166667,13.833333,10.916667,2.533333,0.000000
15954,Zay Jones,8,NYJ,5.285714,1.428571,16.428571,10.885714,3.085714,0.000000
15955,Zay Jones,9,LAC,5.500000,2.000000,21.000000,10.625000,3.650000,0.125000
15956,Zay Jones,10,KC,5.666667,2.222222,26.222222,11.333333,4.322222,0.111111
15957,Zay Jones,11,NE,6.100000,2.300000,26.900000,11.300000,4.220000,0.200000
15958,Zay Jones,12,IND,6.181818,2.272727,26.454545,11.272727,4.118182,0.181818
15959,Zay Jones,13,MIA,5.666667,2.083333,24.250000,10.333333,3.775000,0.166667
15960,Zay Jones,14,NE,5.384615,1.923077,22.384615,9.538462,3.484615,0.153846
15961,Zay Jones,15,MIA,5.071429,1.785714,20.785714,8.857143,3.235714,0.142857
15962,Zay Jones,16,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15963,Zay Jones,17,LAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15964,Zay Jones,18,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15965,Zay Jones,19,GB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15966,Zay Jones,20,TEN,4.250000,2.500000,36.000000,16.675000,11.925000,0.000000
15967,Zay Jones,21,HOU,4.200000,2.600000,32.800000,14.680000,10.540000,0.000000
15968,Zay Jones,22,IND,4.833333,2.666667,33.166667,14.183333,9.516667,0.166667
15969,Zay Jones,23,NE,4.857143,2.714286,32.285714,13.442857,8.928571,0.142857

In [116]:
yearly_ma_grp.drop(['def_rk_ma','surface_0_ma','h/a_1_ma','points_ma'],axis=1, inplace=True)

In [45]:
yearly_ma_grp.shape

(15970, 9)

In [46]:
player_weekly_avg.shape, yearly_ma_grp.shape

((15970, 8), (15970, 9))

In [125]:
temp= pd.concat([player_weekly_avg,yearly_ma_grp],axis=1)
temp.isnull().sum()

tar_avg        0
rec_avg        0
yds_avg        0
yds/rec_avg    0
yds/tar_avg    0
td_avg         0
year           0
Name           0
games          0
Opponent       0
tar_ma         0
rec_ma         0
yds_ma         0
yds/rec_ma     0
yds/tar_ma     0
td_ma          0
dtype: int64

In [126]:

temp

,tar_avg,rec_avg,yds_avg,yds/rec_avg,yds/tar_avg,td_avg,year,Name,games,Opponent,tar_ma,rec_ma,yds_ma,yds/rec_ma,yds/tar_ma,td_ma
0,0.00,0.00,0.00,0.00,0.00,0.00,2012,AJ Green,1,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,11.00,5.00,70.00,14.00,6.40,0.00,2012,AJ Green,2,CLE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,11.50,6.00,64.00,11.15,5.60,0.50,2012,AJ Green,3,WAS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,11.33,7.00,103.67,14.20,9.27,0.67,2012,AJ Green,4,JAX,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,10.75,6.75,107.00,15.52,10.20,0.75,2012,AJ Green,5,MIA,10.750000,6.750000,107.000000,15.525000,10.200000,0.750000
5,11.20,7.20,98.60,13.86,9.16,0.80,2012,AJ Green,6,CLE,11.200000,7.200000,98.600000,13.860000,9.160000,0.800000
6,11.17,7.17,104.67,14.77,9.68,1.00,2012,AJ Green,7,PIT,11.166667,7.166667,104.666667,14.766667,9.683333,1.000000
7,10.43,6.29,90.86,13.80,8.49,1.00,2012,AJ Green,8,DEN,10.428571,6.285714,90.857143,13.800000,8.485714,1.000000
8,10.25,6.38,91.88,13.84,8.80,1.00,2012,AJ Green,9,NYG,10.250000,6.375000,91.875000,13.837500,8.800000,1.000000
9,10.22,6.44,91.11,13.64,8.77,1.00,2012,AJ Green,10,KC,10.222222,6.444444,91.111111,13.644444,8.766667,1.000000
10,10.40,6.40,91.10,13.80,8.65,1.00,2012,AJ Green,11,OAK,10.400000,6.400000,91.100000,13.800000,8.650000,1.000000
11,10.27,6.09,92.91,15.91,8.98,0.91,2012,AJ Green,12,LAC,10.272727,6.090909,92.909091,15.909091,8.981818,0.909091
12,10.50,6.33,92.25,15.37,8.78,0.83,2012,AJ Green,13,DAL,10.500000,6.333333,92.250000,15.366667,8.775000,0.833333
13,10.31,6.08,88.54,15.32,8.52,0.77,2012,AJ Green,14,PHI,10.307692,6.076923,88.538462,15.315385,8.523077,0.769231
14,10.29,6.07,86.29,14.90,8.32,0.79,2012,AJ Green,15,PIT,10.285714,6.071429,86.285714,14.900000,8.321429,0.785714
15,10.80,6.33,88.27,14.68,8.19,0.73,2012,AJ Green,16,BAL,10.800000,6.333333,88.266667,14.680000,8.193333,0.733333
16,0.00,0.00,0.00,0.00,0.00,0.00,2013,AJ Green,17,CHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,13.00,9.00,162.00,18.00,12.50,2.00,2013,AJ Green,18,GB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,10.50,6.50,104.00,14.75,9.15,1.50,2013,AJ Green,19,CLE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,12.00,6.67,86.33,12.27,7.23,1.00,2013,AJ Green,21,NE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,11.00,6.25,80.00,12.25,7.32,0.75,2013,AJ Green,22,BUF,11.000000,6.250000,80.000000,12.250000,7.325000,0.750000
21,11.00,6.20,84.60,13.24,7.74,0.80,2013,AJ Green,23,DET,11.000000,6.200000,84.600000,13.240000,7.740000,0.800000
22,10.50,6.17,96.33,15.33,9.68,0.83,2013,AJ Green,24,NYJ,10.500000,6.166667,96.333333,15.333333,9.683333,0.833333
23,10.00,5.71,99.00,18.61,10.64,0.71,2013,AJ Green,25,MIA,10.000000,5.714286,99.000000,18.614286,10.642857,0.714286
24,11.12,6.38,102.62,17.74,10.15,0.62,2013,AJ Green,26,BAL,11.125000,6.375000,102.625000,17.737500,10.150000,0.625000
25,11.56,6.56,108.00,17.87,10.14,0.67,2013,AJ Green,27,CLE,11.555556,6.555556,108.000000,17.866667,10.144444,0.666667
26,10.90,6.10,97.90,16.43,9.27,0.60,2013,AJ Green,28,LAC,10.900000,6.100000,97.900000,16.430000,9.270000,0.600000
27,10.55,6.00,96.55,16.45,9.51,0.64,2013,AJ Green,29,IND,10.545455,6.000000,96.545455,16.445455,9.509091,0.636364
28,10.33,6.00,94.50,16.08,9.47,0.67,2013,AJ Green,30,PIT,10.333333,6.000000,94.500000,16.075000,9.466667,0.666667
29,10.92,6.23,94.38,15.63,9.14,0.62,2013,AJ Green,31,MIN,10.923077,6.230769,94.384615,15.630769,9.138462,0.615385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15940,0.00,0.00,0.00,0.00,0.00,0.00,2018,Zach Pascal,1,CIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15941,1.00,1.00,18.00,18.00,18.00,0.00,2018,Zach Pascal,2,PHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15942,1.50,1.00,10.50,10.50,9.75,0.00,2018,Zach Pascal,3,HOU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15943,4.33,2.67,25.67,10.10,8.37,0.33,2018,Zach Pascal,4,NE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15944,5.00,2.25,22.25,10.58,6.70,0.25,2018,Zach Pascal,5,NYJ,5.000000,2.250000,22.250000,10.575000,6.700000,0.250000
15945,5.40,2.80,24.80,9.86,6.36,0.20,2018,Zach Pascal,6,BUF,5.400000,2.800000,24.800000,9.860000,6.360000,0.200000
15946,4.50,2.33,20.67,8.22,5.30,0.17,2018,Zach Pascal,7,OAK,4.500000,2.333333,20.666667,8.216667,5.300000,0.166667
15947,0.00,0.00,0.00,0.00,0.00,0.00,2017,Zay Jones,1,NYJ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15948,4.00,1.00,21.00,21.00,5.20,0.00,2017,Zay Jones,2,CAR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15949,5.00,1.50,19.50,15.00,4.10,0.00,2017,Zay Jones,3,DEN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15950,4.00,1.00,13.00,10.00,2.73,0.00,2017,Zay Jones,4,ATL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15951,4.25,1.00,14.25,12.00,2.95,0.00,2017,Zay Jones,5,CIN,4.250000,1.000000,14.250000,12.000000,2.950000,0.000000
15952,4.60,1.00,13.20,11.40,2.66,0.00,2017,Zay Jones,6,TB,4.600000,1.000000,13.200000,11.400000,2.660000,0.000000
15953,5.33,1.17,13.83,10.92,2.53,0.00,2017,Zay Jones,7,OAK,5.333333,1.166667,13.833333,10.916667,2.533333,0.000000
15954,5.29,1.43,16.43,10.89,3.09,0.00,2017,Zay Jones,8,NYJ,5.285714,1.428571,16.428571,10.885714,3.085714,0.000000
15955,5.50,2.00,21.00,10.62,3.65,0.12,2017,Zay Jones,9,LAC,5.500000,2.000000,21.000000,10.625000,3.650000,0.125000
15956,5.67,2.22,26.22,11.33,4.32,0.11,2017,Zay Jones,10,KC,5.666667,2.222222,26.222222,11.333333,4.322222,0.111111
15957,6.10,2.30,26.90,11.30,4.22,0.20,2017,Zay Jones,11,NE,6.100000,2.300000,26.900000,11.300000,4.220000,0.200000
15958,6.18,2.27,26.45,11.27,4.12,0.18,2017,Zay Jones,12,IND,6.181818,2.272727,26.454545,11.272727,4.118182,0.181818
15959,5.67,2.08,24.25,10.33,3.77,0.17,2017,Zay Jones,13,MIA,5.666667,2.083333,24.250000,10.333333,3.775000,0.166667
15960,5.38,1.92,22.38,9.54,3.48,0.15,2017,Zay Jones,14,NE,5.384615,1.923077,22.384615,9.538462,3.484615,0.153846
15961,5.07,1.79,20.79,8.86,3.24,0.14,2017,Zay Jones,15,MIA,5.071429,1.785714,20.785714,8.857143,3.235714,0.142857
15962,0.00,0.00,0.00,0.00,0.00,0.00,2018,Zay Jones,16,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15963,6.00,3.00,26.00,8.70,4.30,0.00,2018,Zay Jones,17,LAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15964,4.50,2.50,44.50,20.10,12.65,0.00,2018,Zay Jones,18,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15965,3.33,2.00,35.33,19.07,14.10,0.00,2018,Zay Jones,19,GB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15966,4.25,2.50,36.00,16.68,11.92,0.00,2018,Zay Jones,20,TEN,4.250000,2.500000,36.000000,16.675000,11.925000,0.000000
15967,4.20,2.60,32.80,14.68,10.54,0.00,2018,Zay Jones,21,HOU,4.200000,2.600000,32.800000,14.680000,10.540000,0.000000
15968,4.83,2.67,33.17,14.18,9.52,0.17,2018,Zay Jones,22,IND,4.833333,2.666667,33.166667,14.183333,9.516667,0.166667
15969,4.86,2.71,32.29,13.44,8.93,0.14,2018,Zay Jones,23,NE,4.857143,2.714286,32.285714,13.442857,8.928571,0.142857

In [68]:
temp

,tar_avg,rec_avg,yds_avg,yds/rec_avg,yds/tar_avg,td_avg,year,Name,games,Opponent,tar_ma,rec_ma,yds_ma,yds/rec_ma,yds/tar_ma,td_ma
0,0.00,0.00,0.00,0.00,0.00,0.00,2012,AJ Green,1,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,11.00,5.00,70.00,14.00,6.40,0.00,2012,AJ Green,2,CLE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,11.50,6.00,64.00,11.15,5.60,0.50,2012,AJ Green,3,WAS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,11.33,7.00,103.67,14.20,9.27,0.67,2012,AJ Green,4,JAX,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,10.75,6.75,107.00,15.52,10.20,0.75,2012,AJ Green,5,MIA,10.750000,6.750000,107.000000,15.525000,10.200000,0.750000
5,11.20,7.20,98.60,13.86,9.16,0.80,2012,AJ Green,6,CLE,11.200000,7.200000,98.600000,13.860000,9.160000,0.800000
6,11.17,7.17,104.67,14.77,9.68,1.00,2012,AJ Green,7,PIT,11.166667,7.166667,104.666667,14.766667,9.683333,1.000000
7,10.43,6.29,90.86,13.80,8.49,1.00,2012,AJ Green,8,DEN,10.428571,6.285714,90.857143,13.800000,8.485714,1.000000
8,10.25,6.38,91.88,13.84,8.80,1.00,2012,AJ Green,9,NYG,10.250000,6.375000,91.875000,13.837500,8.800000,1.000000
9,10.22,6.44,91.11,13.64,8.77,1.00,2012,AJ Green,10,KC,10.222222,6.444444,91.111111,13.644444,8.766667,1.000000
10,10.40,6.40,91.10,13.80,8.65,1.00,2012,AJ Green,11,OAK,10.400000,6.400000,91.100000,13.800000,8.650000,1.000000
11,10.27,6.09,92.91,15.91,8.98,0.91,2012,AJ Green,12,LAC,10.272727,6.090909,92.909091,15.909091,8.981818,0.909091
12,10.50,6.33,92.25,15.37,8.78,0.83,2012,AJ Green,13,DAL,10.500000,6.333333,92.250000,15.366667,8.775000,0.833333
13,10.31,6.08,88.54,15.32,8.52,0.77,2012,AJ Green,14,PHI,10.307692,6.076923,88.538462,15.315385,8.523077,0.769231
14,10.29,6.07,86.29,14.90,8.32,0.79,2012,AJ Green,15,PIT,10.285714,6.071429,86.285714,14.900000,8.321429,0.785714
15,10.80,6.33,88.27,14.68,8.19,0.73,2012,AJ Green,16,BAL,10.800000,6.333333,88.266667,14.680000,8.193333,0.733333
16,0.00,0.00,0.00,0.00,0.00,0.00,2012,AJ Jenkins,1,MIA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
17,0.00,0.00,0.00,0.00,0.00,0.00,2012,AJ Jenkins,2,NE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.00,0.00,0.00,0.00,0.00,0.00,2012,AJ Jenkins,3,ARI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.00,0.00,0.00,0.00,0.00,0.00,2012,Aldrick Robinson,1,NO,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,6.00,4.00,52.00,13.00,8.70,1.00,2012,Aldrick Robinson,2,LAR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,4.50,3.00,46.00,16.50,11.00,0.50,2012,Aldrick Robinson,3,CIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,4.00,2.33,34.67,15.00,8.67,0.33,2012,Aldrick Robinson,4,ATL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,3.25,2.00,28.50,13.75,9.00,0.25,2012,Aldrick Robinson,5,MIN,3.250000,2.000000,28.500000,13.750000,9.000000,0.250000
24,2.60,1.60,22.80,11.00,7.20,0.20,2012,Aldrick Robinson,6,NYG,2.600000,1.600000,22.800000,11.000000,7.200000,0.200000
25,2.33,1.33,19.00,9.17,6.00,0.17,2012,Aldrick Robinson,7,PIT,2.333333,1.333333,19.000000,9.166667,6.000000,0.166667
26,2.14,1.14,16.29,7.86,5.14,0.14,2012,Aldrick Robinson,8,CAR,2.142857,1.142857,16.285714,7.857143,5.142857,0.142857
27,2.12,1.12,15.00,7.62,4.88,0.12,2012,Aldrick Robinson,9,PHI,2.125000,1.125000,15.000000,7.625000,4.875000,0.125000
28,2.00,1.11,18.78,12.22,9.78,0.22,2012,Aldrick Robinson,10,DAL,2.000000,1.111111,18.777778,12.222222,9.777778,0.222222
29,1.90,1.10,23.70,17.80,15.60,0.30,2012,Aldrick Robinson,11,NYG,1.900000,1.100000,23.700000,17.800000,15.600000,0.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15940,0.00,0.00,0.00,0.00,0.00,0.00,2018,Will Fuller,25,TEN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15941,9.00,8.00,113.00,14.10,12.60,1.00,2018,Will Fuller,26,NYG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15942,10.00,6.50,107.00,17.15,10.90,1.00,2018,Will Fuller,27,IND,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15943,8.33,5.67,87.67,15.50,10.53,1.00,2018,Will Fuller,28,DAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15944,7.00,4.75,69.50,13.50,9.15,0.75,2018,Will Fuller,29,BUF,7.000000,4.750000,69.500000,13.500000,9.150000,0.750000
15945,6.20,4.20,62.20,14.10,9.52,0.60,2018,Will Fuller,30,JAX,6.200000,4.200000,62.200000,14.100000,9.520000,0.600000
15946,6.50,4.50,63.17,13.63,9.35,0.50,2018,Will Fuller,31,MIA,6.500000,4.500000,63.166667,13.633333,9.350000,0.500000
15947,0.00,0.00,0.00,0.00,0.00,0.00,2018,Willie Snead,42,BUF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15948,6.00,4.00,49.00,12.20,8.20,1.00,2018,Willie Snead,43,CIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15949,7.00,4.50,51.50,11.50,7.50,0.50,2018,Willie Snead,44,DEN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15950,6.33,4.00,47.33,12.00,7.60,0.33,2018,Willie Snead,45,PIT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15951,6.50,4.50,49.50,11.32,7.70,0.25,2018,Willie Snead,46,CLE,6.500000,4.500000,49.500000,11.325000,7.700000,0.250000
15952,6.60,4.60,50.60,11.26,7.74,0.20,2018,Willie Snead,47,TEN,6.600000,4.600000,50.600000,11.260000,7.740000,0.200000
15953,7.17,5.00,52.17,10.82,7.45,0.17,2018,Willie Snead,48,NO,7.166667,5.000000,52.166667,10.816667,7.450000,0.166667
15954,7.14,4.71,48.00,10.37,6.86,0.14,2018,Willie Snead,49,CAR,7.142857,4.714286,48.000000,10.371429,6.857143,0.142857
15955,0.00,0.00,0.00,0.00,0.00,0.00,2018,Zach Pascal,1,CIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15956,1.00,1.00,18.00,18.00,18.00,0.00,2018,Zach Pascal,2,PHI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15957,1.50,1.00,10.50,10.50,9.75,0.00,2018,Zach Pascal,3,HOU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15958,4.33,2.67,25.67,10.10,8.37,0.33,2018,Zach Pascal,4,NE,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15959,5.00,2.25,22.25,10.58,6.70,0.25,2018,Zach Pascal,5,NYJ,5.000000,2.250000,22.250000,10.575000,6.700000,0.250000
15960,5.40,2.80,24.80,9.86,6.36,0.20,2018,Zach Pascal,6,BUF,5.400000,2.800000,24.800000,9.860000,6.360000,0.200000
15961,4.50,2.33,20.67,8.22,5.30,0.17,2018,Zach Pascal,7,OAK,4.500000,2.333333,20.666667,8.216667,5.300000,0.166667
15962,0.00,0.00,0.00,0.00,0.00,0.00,2018,Zay Jones,16,BAL,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15963,6.00,3.00,26.00,8.70,4.30,0.00,2018,Zay Jones,17,LAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15964,4.50,2.50,44.50,20.10,12.65,0.00,2018,Zay Jones,18,MIN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15965,3.33,2.00,35.33,19.07,14.10,0.00,2018,Zay Jones,19,GB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15966,4.25,2.50,36.00,16.68,11.92,0.00,2018,Zay Jones,20,TEN,4.250000,2.500000,36.000000,16.675000,11.925000,0.000000
15967,4.20,2.60,32.80,14.68,10.54,0.00,2018,Zay Jones,21,HOU,4.200000,2.600000,32.800000,14.680000,10.540000,0.000000
15968,4.83,2.67,33.17,14.18,9.52,0.17,2018,Zay Jones,22,IND,4.833333,2.666667,33.166667,14.183333,9.516667,0.166667
15969,4.86,2.71,32.29,13.44,8.93,0.14,2018,Zay Jones,23,NE,4.857143,2.714286,32.285714,13.442857,8.928571,0.142857

## Career Average

In [60]:
# Week 1 stats are player's career average through 2014 season
# Populate current dataframe with current year averages of players

def career_average (grouped_df1, grouped_df2=None):
    new_grouped_df1 = pd.DataFrame(index= grouped_df1.index)
    for col in grouped_df1: # Iterate through every attribute in the team_stats dataframe
        points=[]  # Create an empty list to hold the season average of the current attribute

        try:
            for player in grouped_df1.index.levels[0]:  # Iterate through every player in the team_stats df
                if player in list(grouped_df2.index.levels[0].unique()):
                    total =[grouped_df2.loc[player][col][-1]] # If player not a rookie, use final average from 2015
                else:
                    total =[]  # create an empty list to hold the weekly attributes value
                
                for week in grouped_df1.loc[player].index: # Iterate throough every week for the current player
                    total.append(grouped_df1.loc[player].loc[week][col]) # Add player's value for the current week's attribute to the total list
                    points.append(round(np.mean(total),2))  # Add the average of the total list to the season average list
                    
            new_grouped_df1['{}_car'.format(col.lower())] = points # Insert season average list for current attribute into the current stats dataframe


                                
        except:
            for player in grouped_df1.index.levels[0]:  # Iterate through every player in the team_stats df
                total = []

                for week in grouped_df1.loc[player].index: # Iterate throough every week for the current player
                    total.append(grouped_df1.loc[player].loc[week][col]) # Add player's value for the current week's attribute to the total list
                    points.append(round(np.mean(total),2))  # Add the average of the total list to the season average list

            new_grouped_df1['{}_car'.format(col.lower())] = points # Insert season average list for current attribute into the current stats dataframe
    return new_grouped_df1

In [61]:
df_career_2012 = career_average(wr_group['player_2012.0'])
df_career_2013 = career_average(wr_group['player_2013.0'], wr_group['player_2012.0'])
df_career_2014 = career_average(wr_group['player_2014.0'], wr_group['player_2013.0'])
df_career_2015 = career_average(wr_group['player_2015.0'], wr_group['player_2014.0'])
df_career_2016 = career_average(wr_group['player_2016.0'],wr_group['player_2015.0'])
df_career_2017 = career_average(wr_group['player_2017.0'],wr_group['player_2016.0'])
df_career_2018 = career_average(wr_group['player_2018.0'], wr_group['player_2017.0'])

In [69]:
df_career_2012['year'] = 2012
df_career_2013['year'] = 2013
df_career_2014['year'] = 2014
df_career_2015['year'] = 2015
df_career_2016['year'] = 2016
df_career_2017['year'] = 2017
df_career_2018['year'] = 2018

In [86]:
player_career_grp = pd.concat([df_career_2012, df_career_2013])
player_career_grp = pd.concat([player_career_grp, df_career_2014])
player_career_grp = pd.concat([player_career_grp, df_career_2015])
player_career_grp = pd.concat([player_career_grp, df_career_2016])
player_career_grp = pd.concat([player_career_grp, df_career_2017])
player_career_grp = pd.concat([player_career_grp, df_career_2018])
player_career_grp.head()

                         tar_car  rec_car  yds_car  yds/rec_car  yds/tar_car  \
Name     games Opponent
AJ Green 1     BAL         11.00     5.00    70.00        14.00         6.40
         2     CLE         11.50     6.00    64.00        11.15         5.60
         3     WAS         11.33     7.00   103.67        14.20         9.27
         4     JAX         10.75     6.75   107.00        15.52        10.20
         5     MIA         11.20     7.20    98.60        13.86         9.16

                         td_car  year
Name     games Opponent
AJ Green 1     BAL         0.00  2012
         2     CLE         0.50  2012
         3     WAS         0.67  2012
         4     JAX         0.75  2012
         5     MIA         0.80  2012

In [87]:
player_career_grp.loc['AJ Green']

,,tar_car,rec_car,yds_car,yds/rec_car,yds/tar_car,td_car,year
games,Opponent,,,,,,,
1,BAL,11.00,5.00,70.00,14.00,6.40,0.00,2012
2,CLE,11.50,6.00,64.00,11.15,5.60,0.50,2012
3,WAS,11.33,7.00,103.67,14.20,9.27,0.67,2012
4,JAX,10.75,6.75,107.00,15.52,10.20,0.75,2012
5,MIA,11.20,7.20,98.60,13.86,9.16,0.80,2012
6,CLE,11.17,7.17,104.67,14.77,9.68,1.00,2012
7,PIT,10.43,6.29,90.86,13.80,8.49,1.00,2012
8,DEN,10.25,6.38,91.88,13.84,8.80,1.00,2012
9,NYG,10.22,6.44,91.11,13.64,8.77,1.00,2012
10,KC,10.40,6.40,91.10,13.80,8.65,1.00,2012
11,OAK,10.27,6.09,92.91,15.91,8.98,0.91,2012
12,LAC,10.50,6.33,92.25,15.37,8.78,0.83,2012
13,DAL,10.31,6.08,88.54,15.32,8.52,0.77,2012
14,PHI,10.29,6.07,86.29,14.90,8.32,0.79,2012
15,PIT,10.80,6.33,88.27,14.68,8.19,0.73,2012
16,BAL,10.25,6.06,84.38,14.58,8.49,0.69,2012
17,CHI,7.50,5.50,94.00,15.50,12.75,1.00,2013
18,GB,7.67,5.00,78.00,14.17,10.43,1.00,2013
19,CLE,9.50,5.50,71.25,12.45,8.68,0.75,2013
21,NE,9.20,5.40,69.20,12.40,8.46,0.60,2013
22,BUF,9.50,5.50,74.83,13.20,8.62,0.67,2013
23,DET,9.29,5.57,86.29,15.00,10.16,0.71,2013
24,NYJ,9.00,5.25,89.88,17.91,10.94,0.62,2013
25,MIA,10.11,5.89,94.11,17.21,10.47,0.56,2013
26,BAL,10.60,6.10,99.80,17.38,10.43,0.60,2013
27,CLE,10.09,5.73,91.36,16.12,9.61,0.55,2013
28,LAC,9.83,5.67,90.67,16.16,9.80,0.58,2013
29,IND,9.69,5.69,89.23,15.84,9.74,0.62,2013
30,PIT,10.29,5.93,89.50,15.44,9.41,0.57,2013
31,MIN,10.40,6.00,90.00,15.34,9.33,0.67,2013
...,...,...,...,...,...,...,...,...
66,DAL,9.50,6.67,92.00,13.65,8.83,0.50,2016
67,NE,9.57,6.57,91.43,13.80,8.83,0.43,2016
68,CLE,9.38,6.75,101.12,14.71,10.36,0.50,2016
69,WAS,10.33,7.00,103.33,14.57,9.96,0.44,2016
70,NYG,10.40,7.00,99.80,14.08,9.58,0.50,2016
71,BUF,9.55,6.36,90.73,12.80,8.71,0.45,2016
72,BAL,5.50,2.50,37.00,7.40,3.70,0.00,2017
73,HOU,6.33,3.33,47.00,9.40,5.27,0.00,2017
74,GB,8.00,5.00,63.00,9.83,6.08,0.25,2017
75,CLE,7.80,5.00,63.00,10.38,6.66,0.40,2017
76,BUF,8.67,5.33,84.00,13.15,7.97,0.50,2017
77,PIT,8.29,5.00,77.86,13.23,7.80,0.43,2017
78,IND,8.25,4.75,71.50,12.70,7.25,0.50,2017
79,JAX,7.56,4.33,64.22,11.96,6.78,0.44,2017
80,TEN,7.50,4.40,69.30,13.06,7.74,0.50,2017
81,DEN,7.64,4.36,67.55,13.01,7.55,0.55,2017
82,CLE,7.67,4.42,67.42,13.02,7.60,0.50,2017
83,PIT,8.38,4.62,68.15,12.87,7.36,0.62,2017
84,CHI,8.64,4.64,67.86,12.86,7.21,0.57,2017
85,MIN,8.33,4.47,65.33,13.01,7.23,0.53,2017
86,DET,8.44,4.56,66.31,13.04,7.29,0.50,2017
87,BAL,8.53,4.41,63.41,12.77,6.96,0.47,2017
88,IND,9.00,4.00,54.50,11.90,6.60,0.50,2018
89,BAL,9.00,4.33,59.33,12.53,6.97,1.33,2018
90,CAR,8.75,4.50,59.00,12.30,7.02,1.00,2018
91,ATL,8.60,4.40,62.80,13.74,7.58,1.00,2018
92,MIA,8.83,4.67,71.00,14.57,8.18,0.83,2018
93,PIT,9.29,5.00,73.00,14.21,8.03,0.71,2018
94,KC,9.88,5.25,78.50,14.52,8.07,0.62,2018
95,TB,9.56,5.22,78.22,14.60,8.39,0.67,2018

In [88]:
career_shifted = shift_dict(player_career_grp)
career_shifted.head()

            games Opponent  tar_car  rec_car  yds_car  yds/rec_car  \
AJ Green 0    0.0        0     0.00     0.00     0.00         0.00
         1    1.0      BAL    11.00     5.00    70.00        14.00
         2    2.0      CLE    11.50     6.00    64.00        11.15
         3    3.0      WAS    11.33     7.00   103.67        14.20
         4    4.0      JAX    10.75     6.75   107.00        15.52

            yds/tar_car  td_car    year
AJ Green 0         0.00    0.00     0.0
         1         6.40    0.00  2012.0
         2         5.60    0.50  2012.0
         3         9.27    0.67  2012.0
         4        10.20    0.75  2012.0

In [89]:
career_shifted['year'] = career_shifted['year'].shift(-1)

In [ ]:
career_shifted.reset_index(inplace=True)

In [128]:
career_shifted.head()

,level_0,level_1,games,Opponent,tar_car,rec_car,yds_car,yds/rec_car,yds/tar_car,td_car,year
0,AJ Green,0,0.0,0,0.00,0.00,0.00,0.00,0.00,0.00,2012.0
1,AJ Green,1,1.0,BAL,11.00,5.00,70.00,14.00,6.40,0.00,2012.0
2,AJ Green,2,2.0,CLE,11.50,6.00,64.00,11.15,5.60,0.50,2012.0
3,AJ Green,3,3.0,WAS,11.33,7.00,103.67,14.20,9.27,0.67,2012.0
4,AJ Green,4,4.0,JAX,10.75,6.75,107.00,15.52,10.20,0.75,2012.0

In [129]:
career_shifted.drop(['level_0','level_1','games','Opponent'], axis=1, inplace=True)

In [130]:
career_shifted.head()

   tar_car  rec_car  yds_car  yds/rec_car  yds/tar_car  td_car    year
0     0.00     0.00     0.00         0.00         0.00    0.00  2012.0
1    11.00     5.00    70.00        14.00         6.40    0.00  2012.0
2    11.50     6.00    64.00        11.15         5.60    0.50  2012.0
3    11.33     7.00   103.67        14.20         9.27    0.67  2012.0
4    10.75     6.75   107.00        15.52        10.20    0.75  2012.0

In [131]:
career_shifted.columns

Index(['tar_car', 'rec_car', 'yds_car', 'yds/rec_car', 'yds/tar_car', 'td_car',
       'year'],
      dtype='object')

In [132]:
temp = pd.concat([temp, career_shifted], axis=1)
temp.isnull().sum()

tar_avg        0
rec_avg        0
yds_avg        0
yds/rec_avg    0
yds/tar_avg    0
td_avg         0
year           0
Name           0
games          0
Opponent       0
tar_ma         0
rec_ma         0
yds_ma         0
yds/rec_ma     0
yds/tar_ma     0
td_ma          0
tar_car        0
rec_car        0
yds_car        0
yds/rec_car    0
yds/tar_car    0
td_car         0
year           1
dtype: int64

In [134]:
wr

,year,games,Name,Week,Opponent,Team,tar,rec,yds,yds/rec,yds/tar,td,def_rk,h/a_1,surface_0,points
0,2012.0,1,AJ Green,1,BAL,CIN,11,5,70,14.0,6.4,0,30,0.0,1.0,7.0
1,2012.0,2,AJ Green,2,CLE,CIN,12,7,58,8.3,4.8,1,16,1.0,0.0,11.8
2,2012.0,3,AJ Green,3,WAS,CIN,11,9,183,20.3,16.6,1,28,0.0,1.0,25.4
3,2012.0,4,AJ Green,4,JAX,CIN,9,6,117,19.5,13.0,1,15,0.0,1.0,17.7
4,2012.0,5,AJ Green,5,MIA,CIN,13,9,65,7.2,5.0,1,22,1.0,0.0,12.5
5,2012.0,6,AJ Green,6,CLE,CIN,11,7,135,19.3,12.3,2,16,0.0,1.0,25.5
6,2012.0,7,AJ Green,7,PIT,CIN,6,1,8,8.0,1.3,1,23,1.0,0.0,6.8
7,2012.0,8,AJ Green,9,DEN,CIN,9,7,99,14.1,11.0,1,4,1.0,0.0,16.5
8,2012.0,9,AJ Green,10,NYG,CIN,10,7,85,12.1,8.5,1,11,1.0,0.0,14.5
9,2012.0,10,AJ Green,11,KC,CIN,12,6,91,15.2,7.6,1,14,0.0,1.0,15.1
10,2012.0,11,AJ Green,12,OAK,CIN,9,3,111,37.0,12.3,0,7,1.0,0.0,13.2
11,2012.0,12,AJ Green,13,LAC,CIN,13,9,85,9.4,6.5,0,13,0.0,1.0,8.5
12,2012.0,13,AJ Green,14,DAL,CIN,8,3,44,14.7,5.5,0,5,1.0,0.0,4.4
13,2012.0,14,AJ Green,15,PHI,CIN,10,6,57,9.5,5.7,1,32,0.0,1.0,11.7
14,2012.0,15,AJ Green,16,PIT,CIN,18,10,116,11.6,6.4,0,23,0.0,1.0,9.6
15,2012.0,16,AJ Green,17,BAL,CIN,2,2,26,13.0,13.0,0,30,1.0,0.0,2.6
16,2013.0,17,AJ Green,1,CHI,CIN,13,9,162,18.0,12.5,2,11,0.0,1.0,40.2
17,2013.0,18,AJ Green,3,GB,CIN,8,4,46,11.5,5.8,1,15,1.0,0.0,14.6
18,2013.0,19,AJ Green,4,CLE,CIN,15,7,51,7.3,3.4,0,28,0.0,1.0,12.1
19,2013.0,21,AJ Green,5,NE,CIN,8,5,61,12.2,7.6,0,23,1.0,0.0,11.1
20,2013.0,22,AJ Green,6,BUF,CIN,11,6,103,17.2,9.4,1,18,0.0,0.0,25.3
21,2013.0,23,AJ Green,7,DET,CIN,8,6,155,25.8,19.4,1,26,0.0,0.0,30.5
22,2013.0,24,AJ Green,8,NYJ,CIN,7,3,115,38.3,16.4,0,1,1.0,0.0,17.5
23,2013.0,25,AJ Green,9,MIA,CIN,19,11,128,11.6,6.7,0,20,0.0,1.0,26.8
24,2013.0,26,AJ Green,10,BAL,CIN,15,8,151,18.9,10.1,1,17,0.0,1.0,32.1
25,2013.0,27,AJ Green,11,CLE,CIN,5,2,7,3.5,1.4,0,28,1.0,0.0,2.7
26,2013.0,28,AJ Green,13,LAC,CIN,7,5,83,16.6,11.9,1,19,0.0,1.0,19.3
27,2013.0,29,AJ Green,14,IND,CIN,8,6,72,12.0,9.0,1,29,1.0,0.0,19.2
28,2013.0,30,AJ Green,15,PIT,CIN,18,9,93,10.3,5.2,0,6,0.0,1.0,18.3
29,2013.0,31,AJ Green,16,MIN,CIN,12,7,97,13.9,8.1,2,27,1.0,0.0,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15940,2018.0,1,Zach Pascal,1,CIN,IND,1,1,18,18.0,18.0,0,24,1.0,0.0,2.8
15941,2018.0,2,Zach Pascal,3,PHI,IND,2,1,3,3.0,1.5,0,26,0.0,1.0,1.3
15942,2018.0,3,Zach Pascal,4,HOU,IND,10,6,56,9.3,5.6,1,7,1.0,0.0,17.6
15943,2018.0,4,Zach Pascal,5,NE,IND,7,1,12,12.0,1.7,0,20,0.0,0.0,2.2
15944,2018.0,5,Zach Pascal,6,NYJ,IND,7,5,35,7.0,5.0,0,27,0.0,0.0,9.3
15945,2018.0,6,Zach Pascal,7,BUF,IND,0,0,0,0.0,0.0,0,4,1.0,0.0,0.0
15946,2018.0,7,Zach Pascal,8,OAK,IND,1,1,-4,-4.0,-4.0,0,2,0.0,1.0,0.6
15947,2017.0,1,Zay Jones,1,NYJ,BUF,4,1,21,21.0,5.2,0,19,1.0,0.0,3.1
15948,2017.0,2,Zay Jones,2,CAR,BUF,6,2,18,9.0,3.0,0,28,0.0,1.0,3.8
15949,2017.0,3,Zay Jones,3,DEN,BUF,2,0,0,0.0,0.0,0,3,1.0,0.0,0.0
15950,2017.0,4,Zay Jones,4,ATL,BUF,5,1,18,18.0,3.6,0,12,0.0,0.0,2.8
15951,2017.0,5,Zay Jones,5,CIN,BUF,6,1,9,9.0,1.5,0,4,0.0,0.0,1.9
15952,2017.0,6,Zay Jones,7,TB,BUF,9,2,17,8.5,1.9,0,32,1.0,0.0,3.7
15953,2017.0,7,Zay Jones,8,OAK,BUF,5,3,32,10.7,6.4,0,15,1.0,0.0,6.2
15954,2017.0,8,Zay Jones,9,NYJ,BUF,7,6,53,8.8,7.6,1,19,0.0,0.0,17.3
15955,2017.0,9,Zay Jones,11,LAC,BUF,7,4,68,17.0,9.7,0,7,0.0,1.0,10.8
15956,2017.0,10,Zay Jones,12,KC,BUF,10,3,33,11.0,3.3,1,31,0.0,1.0,12.3
15957,2017.0,11,Zay Jones,13,NE,BUF,7,2,22,11.0,3.1,0,30,1.0,0.0,4.2
15958,2017.0,12,Zay Jones,14,IND,BUF,0,0,0,0.0,0.0,0,26,1.0,0.0,0.0
15959,2017.0,13,Zay Jones,15,MIA,BUF,2,0,0,0.0,0.0,0,2,1.0,0.0,0.0
15960,2017.0,14,Zay Jones,16,NE,BUF,1,0,0,0.0,0.0,0,30,0.0,0.0,0.0
15961,2017.0,15,Zay Jones,17,MIA,BUF,3,2,25,12.5,8.3,0,2,0.0,1.0,4.5
15962,2018.0,16,Zay Jones,1,BAL,BUF,6,3,26,8.7,4.3,0,3,0.0,1.0,5.6
15963,2018.0,17,Zay Jones,2,LAC,BUF,3,2,63,31.5,21.0,0,19,1.0,0.0,8.3
15964,2018.0,18,Zay Jones,3,MIN,BUF,1,1,17,17.0,17.0,0,12,0.0,0.0,2.7
15965,2018.0,19,Zay Jones,4,GB,BUF,7,4,38,9.5,5.4,0,13,0.0,1.0,7.8
15966,2018.0,20,Zay Jones,5,TEN,BUF,4,3,20,6.7,5.0,0,18,1.0,0.0,5.0
15967,2018.0,21,Zay Jones,6,HOU,BUF,8,3,35,11.7,4.4,1,7,0.0,0.0,12.5
15968,2018.0,22,Zay Jones,7,IND,BUF,5,3,27,9.0,5.4,0,13,0.0,0.0,5.7
15969,2018.0,23,Zay Jones,8,NE,BUF,8,6,55,9.2,6.9,0,8,1.0,0.0,11.5

In [135]:
temp['Week'] = wr['Week']
temp['surface_0']=wr['surface_0'].values
temp['h/a_1']=wr['h/a_1'].values
temp['def_rk'] = wr['def_rk']
temp['points'] = wr['points']

In [133]:
temp

,tar_avg,rec_avg,yds_avg,yds/rec_avg,yds/tar_avg,td_avg,year,Name,games,Opponent,...,yds/rec_ma,yds/tar_ma,td_ma,tar_car,rec_car,yds_car,yds/rec_car,yds/tar_car,td_car,year
0,0.00,0.00,0.00,0.00,0.00,0.00,2012,AJ Green,1,BAL,...,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,2012.0
1,11.00,5.00,70.00,14.00,6.40,0.00,2012,AJ Green,2,CLE,...,0.000000,0.000000,0.000000,11.00,5.00,70.00,14.00,6.40,0.00,2012.0
2,11.50,6.00,64.00,11.15,5.60,0.50,2012,AJ Green,3,WAS,...,0.000000,0.000000,0.000000,11.50,6.00,64.00,11.15,5.60,0.50,2012.0
3,11.33,7.00,103.67,14.20,9.27,0.67,2012,AJ Green,4,JAX,...,0.000000,0.000000,0.000000,11.33,7.00,103.67,14.20,9.27,0.67,2012.0
4,10.75,6.75,107.00,15.52,10.20,0.75,2012,AJ Green,5,MIA,...,15.525000,10.200000,0.750000,10.75,6.75,107.00,15.52,10.20,0.75,2012.0
5,11.20,7.20,98.60,13.86,9.16,0.80,2012,AJ Green,6,CLE,...,13.860000,9.160000,0.800000,11.20,7.20,98.60,13.86,9.16,0.80,2012.0
6,11.17,7.17,104.67,14.77,9.68,1.00,2012,AJ Green,7,PIT,...,14.766667,9.683333,1.000000,11.17,7.17,104.67,14.77,9.68,1.00,2012.0
7,10.43,6.29,90.86,13.80,8.49,1.00,2012,AJ Green,8,DEN,...,13.800000,8.485714,1.000000,10.43,6.29,90.86,13.80,8.49,1.00,2012.0
8,10.25,6.38,91.88,13.84,8.80,1.00,2012,AJ Green,9,NYG,...,13.837500,8.800000,1.000000,10.25,6.38,91.88,13.84,8.80,1.00,2012.0
9,10.22,6.44,91.11,13.64,8.77,1.00,2012,AJ Green,10,KC,...,13.644444,8.766667,1.000000,10.22,6.44,91.11,13.64,8.77,1.00,2012.0
10,10.40,6.40,91.10,13.80,8.65,1.00,2012,AJ Green,11,OAK,...,13.800000,8.650000,1.000000,10.40,6.40,91.10,13.80,8.65,1.00,2012.0
11,10.27,6.09,92.91,15.91,8.98,0.91,2012,AJ Green,12,LAC,...,15.909091,8.981818,0.909091,10.27,6.09,92.91,15.91,8.98,0.91,2012.0
12,10.50,6.33,92.25,15.37,8.78,0.83,2012,AJ Green,13,DAL,...,15.366667,8.775000,0.833333,10.50,6.33,92.25,15.37,8.78,0.83,2012.0
13,10.31,6.08,88.54,15.32,8.52,0.77,2012,AJ Green,14,PHI,...,15.315385,8.523077,0.769231,10.31,6.08,88.54,15.32,8.52,0.77,2012.0
14,10.29,6.07,86.29,14.90,8.32,0.79,2012,AJ Green,15,PIT,...,14.900000,8.321429,0.785714,10.29,6.07,86.29,14.90,8.32,0.79,2012.0
15,10.80,6.33,88.27,14.68,8.19,0.73,2012,AJ Green,16,BAL,...,14.680000,8.193333,0.733333,10.80,6.33,88.27,14.68,8.19,0.73,2012.0
16,0.00,0.00,0.00,0.00,0.00,0.00,2013,AJ Green,17,CHI,...,0.000000,0.000000,0.000000,10.25,6.06,84.38,14.58,8.49,0.69,2013.0
17,13.00,9.00,162.00,18.00,12.50,2.00,2013,AJ Green,18,GB,...,0.000000,0.000000,0.000000,7.50,5.50,94.00,15.50,12.75,1.00,2013.0
18,10.50,6.50,104.00,14.75,9.15,1.50,2013,AJ Green,19,CLE,...,0.000000,0.000000,0.000000,7.67,5.00,78.00,14.17,10.43,1.00,2013.0
19,12.00,6.67,86.33,12.27,7.23,1.00,2013,AJ Green,21,NE,...,0.000000,0.000000,0.000000,9.50,5.50,71.25,12.45,8.68,0.75,2013.0
20,11.00,6.25,80.00,12.25,7.32,0.75,2013,AJ Green,22,BUF,...,12.250000,7.325000,0.750000,9.20,5.40,69.20,12.40,8.46,0.60,2013.0
21,11.00,6.20,84.60,13.24,7.74,0.80,2013,AJ Green,23,DET,...,13.240000,7.740000,0.800000,9.50,5.50,74.83,13.20,8.62,0.67,2013.0
22,10.50,6.17,96.33,15.33,9.68,0.83,2013,AJ Green,24,NYJ,...,15.333333,9.683333,0.833333,9.29,5.57,86.29,15.00,10.16,0.71,2013.0
23,10.00,5.71,99.00,18.61,10.64,0.71,2013,AJ Green,25,MIA,...,18.614286,10.642857,0.714286,9.00,5.25,89.88,17.91,10.94,0.62,2013.0
24,11.12,6.38,102.62,17.74,10.15,0.62,2013,AJ Green,26,BAL,...,17.737500,10.150000,0.625000,10.11,5.89,94.11,17.21,10.47,0.56,2013.0
25,11.56,6.56,108.00,17.87,10.14,0.67,2013,AJ Green,27,CLE,...,17.866667,10.144444,0.666667,10.60,6.10,99.80,17.38,10.43,0.60,2013.0
26,10.90,6.10,97.90,16.43,9.27,0.60,2013,AJ Green,28,LAC,...,16.430000,9.270000,0.600000,10.09,5.73,91.36,16.12,9.61,0.55,2013.0
27,10.55,6.00,96.55,16.45,9.51,0.64,2013,AJ Green,29,IND,...,16.445455,9.509091,0.636364,9.83,5.67,90.67,16.16,9.80,0.58,2013.0
28,10.33,6.00,94.50,16.08,9.47,0.67,2013,AJ Green,30,PIT,...,16.075000,9.466667,0.666667,9.69,5.69,89.23,15.84,9.74,0.62,2013.0
29,10.92,6.23,94.38,15.63,9.14,0.62,2013,AJ Green,31,MIN,...,15.630769,9.138462,0.615385,10.29,5.93,89.50,15.44,9.41,0.57,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15940,0.00,0.00,0.00,0.00,0.00,0.00,2018,Zach Pascal,1,CIN,...,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,2018.0
15941,1.00,1.00,18.00,18.00,18.00,0.00,2018,Zach Pascal,2,PHI,...,0.000000,0.000000,0.000000,1.00,1.00,18.00,18.00,18.00,0.00,2018.0
15942,1.50,1.00,10.50,10.50,9.75,0.00,2018,Zach Pascal,3,HOU,...,0.000000,0.000000,0.000000,1.50,1.00,10.50,10.50,9.75,0.00,2018.0
15943,4.33,2.67,25.67,10.10,8.37,0.33,2018,Zach Pascal,4,NE,...,0.000000,0.000000,0.000000,4.33,2.67,25.67,10.10,8.37,0.33,2018.0
15944,5.00,2.25,22.25,10.58,6.70,0.25,2018,Zach Pascal,5,NYJ,...,10.575000,6.700000,0.250000,5.00,2.25,22.25,10.58,6.70,0.25,2018.0
15945,5.40,2.80,24.80,9.86,6.36,0.20,2018,Zach Pascal,6,BUF,...,9.860000,6.360000,0.200000,5.40,2.80,24.80,9.86,6.36,0.20,2018.0
15946,4.50,2.33,20.67,8.22,5.30,0.17,2018,Zach Pascal,7,OAK,...,8.216667,5.300000,0.166667,4.50,2.33,20.67,8.22,5.30,0.17,0.0
15947,0.00,0.00,0.00,0.00,0.00,0.00,2017,Zay Jones,1,NYJ,...,0.000000,0.000000,0.000000,0.00,0.00,0.00,0.00,0.00,0.00,2017.0
15948,4.00,1.00,21.00,21.00,5.20,0.00,2017,Zay Jones,2,CAR,...,0.000000,0.000000,0.000000,4.00,1.00,21.00,21.00,5.20,0.00,2017.0
15949,5.00,1.50,19.50,15.00,4.10,0.00,2017,Zay Jones,3,DEN,...,0.000000,0.000000,0.000000,5.00,1.50,19.50,15.00,4.10,0.00,2017.0
15950,4.00,1.00,13.00,10.00,2.73,0.00,2017,Zay Jones,4,ATL,...,0.000000,0.000000,0.000000,4.00,1.00,13.00,10.00,2.73,0.00,2017.0
15951,4.25,1.00,14.25,12.00,2.95,0.00,2017,Zay Jones,5,CIN,...,12.000000,2.950000,0.000000,4.25,1.00,14.25,12.00,2.95,0.00,2017.0
15952,4.60,1.00,13.20,11.40,2.66,0.00,2017,Zay Jones,6,TB,...,11.400000,2.660000,0.000000,4.60,1.00,13.20,11.40,2.66,0.00,2017.0
15953,5.33,1.17,13.83,10.92,2.53,0.00,2017,Zay Jones,7,OAK,...,10.916667,2.533333,0.000000,5.33,1.17,13.83,10.92,2.53,0.00,2017.0
15954,5.29,1.43,16.43,10.89,3.09,0.00,2017,Zay Jones,8,NYJ,...,10.885714,3.085714,0.000000,5.29,1.43,16.43,10.89,3.09,0.00,2017.0
15955,5.50,2.00,21.00,10.62,3.65,0.12,2017,Zay Jones,9,LAC,...,10.625000,3.650000,0.125000,5.50,2.00,21.00,10.62,3.65,0.12,2017.0
15956,5.67,2.22,26.22,11.33,4.32,0.11,2017,Zay Jones,10,KC,...,11.333333,4.322222,0.111111,5.67,2.22,26.22,11.33,4.32,0.11,2017.0
15957,6.10,2.30,26.90,11.30,4.22,0.20,2017,Zay Jones,11,NE,...,11.300000,4.220000,0.200000,6.10,2.30,26.90,11.30,4.22,0.20,2017.0
15958,6.18,2.27,26.45,11.27,4.12,0.18,2017,Zay Jones,12,IND,...,11.272727,4.118182,0.181818,6.18,2.27,26.45,11.27,4.12,0.18,2017.0
15959,5.67,2.08,24.25,10.33,3.77,0.17,2017,Zay Jones,13,MIA,...,10.333333,3.775000,0.166667,5.67,2.08,24.25,10.33,3.77,0.17,2017.0
15960,5.38,1.92,22.38,9.54,3.48,0.15,2017,Zay Jones,14,NE,...,9.538462,3.484615,0.153846,5.38,1.92,22.38,9.54,3.48,0.15,2017.0
15961,5.07,1.79,20.79,8.86,3.24,0.14,2017,Zay Jones,15,MIA,...,8.857143,3.235714,0.142857,5.07,1.79,20.79,8.86,3.24,0.14,2017.0
15962,0.00,0.00,0.00,0.00,0.00,0.00,2018,Zay Jones,16,BAL,...,0.000000,0.000000,0.000000,4.93,1.80,21.07,9.10,3.57,0.13,2018.0
15963,6.00,3.00,26.00,8.70,4.30,0.00,2018,Zay Jones,17,LAC,...,0.000000,0.000000,0.000000,4.50,2.50,25.50,10.60,6.30,0.00,2018.0
15964,4.50,2.50,44.50,20.10,12.65,0.00,2018,Zay Jones,18,MIN,...,0.000000,0.000000,0.000000,4.00,2.33,38.00,17.57,11.20,0.00,2018.0
15965,3.33,2.00,35.33,19.07,14.10,0.00,2018,Zay Jones,19,GB,...,0.000000,0.000000,0.000000,3.25,2.00,32.75,17.42,12.65,0.00,2018.0
15966,4.25,2.50,36.00,16.68,11.92,0.00,2018,Zay Jones,20,TEN,...,16.675000,11.925000,0.000000,4.00,2.40,33.80,15.84,11.20,0.00,2018.0
15967,4.20,2.60,32.80,14.68,10.54,0.00,2018,Zay Jones,21,HOU,...,14.680000,10.540000,0.000000,4.00,2.50,31.50,14.32,10.17,0.00,2018.0
15968,4.83,2.67,33.17,14.18,9.52,0.17,2018,Zay Jones,22,IND,...,14.183333,9.516667,0.166667,4.57,2.57,32.00,13.94,9.34,0.14,2018.0
15969,4.86,2.71,32.29,13.44,8.93,0.14,2018,Zay Jones,23,NE,...,13.442857,8.928571,0.142857,4.62,2.62,31.38,13.32,8.85,0.12,NaN

In [144]:
cols = temp.columns.tolist()
cols = cols[6:8] + cols[-5:-4]+ cols[9:10] + cols[8:9] + cols[:6] + cols[10:-6] + cols[-4:]
temp = temp[cols]

In [146]:
temp[temp['Name']=='AJ Green']

,year,year,Name,Week,Opponent,games,tar_avg,rec_avg,yds_avg,yds/rec_avg,...,tar_car,rec_car,yds_car,yds/rec_car,yds/tar_car,td_car,surface_0,h/a_1,def_rk,points
0,2012,2012.0,AJ Green,1,BAL,1,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,1.0,0.0,30,7.0
1,2012,2012.0,AJ Green,2,CLE,2,11.00,5.00,70.00,14.00,...,11.00,5.00,70.00,14.00,6.40,0.00,0.0,1.0,16,11.8
2,2012,2012.0,AJ Green,3,WAS,3,11.50,6.00,64.00,11.15,...,11.50,6.00,64.00,11.15,5.60,0.50,1.0,0.0,28,25.4
3,2012,2012.0,AJ Green,4,JAX,4,11.33,7.00,103.67,14.20,...,11.33,7.00,103.67,14.20,9.27,0.67,1.0,0.0,15,17.7
4,2012,2012.0,AJ Green,5,MIA,5,10.75,6.75,107.00,15.52,...,10.75,6.75,107.00,15.52,10.20,0.75,0.0,1.0,22,12.5
5,2012,2012.0,AJ Green,6,CLE,6,11.20,7.20,98.60,13.86,...,11.20,7.20,98.60,13.86,9.16,0.80,1.0,0.0,16,25.5
6,2012,2012.0,AJ Green,7,PIT,7,11.17,7.17,104.67,14.77,...,11.17,7.17,104.67,14.77,9.68,1.00,0.0,1.0,23,6.8
7,2012,2012.0,AJ Green,9,DEN,8,10.43,6.29,90.86,13.80,...,10.43,6.29,90.86,13.80,8.49,1.00,0.0,1.0,4,16.5
8,2012,2012.0,AJ Green,10,NYG,9,10.25,6.38,91.88,13.84,...,10.25,6.38,91.88,13.84,8.80,1.00,0.0,1.0,11,14.5
9,2012,2012.0,AJ Green,11,KC,10,10.22,6.44,91.11,13.64,...,10.22,6.44,91.11,13.64,8.77,1.00,1.0,0.0,14,15.1
10,2012,2012.0,AJ Green,12,OAK,11,10.40,6.40,91.10,13.80,...,10.40,6.40,91.10,13.80,8.65,1.00,0.0,1.0,7,13.2
11,2012,2012.0,AJ Green,13,LAC,12,10.27,6.09,92.91,15.91,...,10.27,6.09,92.91,15.91,8.98,0.91,1.0,0.0,13,8.5
12,2012,2012.0,AJ Green,14,DAL,13,10.50,6.33,92.25,15.37,...,10.50,6.33,92.25,15.37,8.78,0.83,0.0,1.0,5,4.4
13,2012,2012.0,AJ Green,15,PHI,14,10.31,6.08,88.54,15.32,...,10.31,6.08,88.54,15.32,8.52,0.77,1.0,0.0,32,11.7
14,2012,2012.0,AJ Green,16,PIT,15,10.29,6.07,86.29,14.90,...,10.29,6.07,86.29,14.90,8.32,0.79,1.0,0.0,23,9.6
15,2012,2012.0,AJ Green,17,BAL,16,10.80,6.33,88.27,14.68,...,10.80,6.33,88.27,14.68,8.19,0.73,0.0,1.0,30,2.6
16,2013,2013.0,AJ Green,1,CHI,17,0.00,0.00,0.00,0.00,...,10.25,6.06,84.38,14.58,8.49,0.69,1.0,0.0,11,40.2
17,2013,2013.0,AJ Green,3,GB,18,13.00,9.00,162.00,18.00,...,7.50,5.50,94.00,15.50,12.75,1.00,0.0,1.0,15,14.6
18,2013,2013.0,AJ Green,4,CLE,19,10.50,6.50,104.00,14.75,...,7.67,5.00,78.00,14.17,10.43,1.00,1.0,0.0,28,12.1
19,2013,2013.0,AJ Green,5,NE,21,12.00,6.67,86.33,12.27,...,9.50,5.50,71.25,12.45,8.68,0.75,0.0,1.0,23,11.1
20,2013,2013.0,AJ Green,6,BUF,22,11.00,6.25,80.00,12.25,...,9.20,5.40,69.20,12.40,8.46,0.60,0.0,0.0,18,25.3
21,2013,2013.0,AJ Green,7,DET,23,11.00,6.20,84.60,13.24,...,9.50,5.50,74.83,13.20,8.62,0.67,0.0,0.0,26,30.5
22,2013,2013.0,AJ Green,8,NYJ,24,10.50,6.17,96.33,15.33,...,9.29,5.57,86.29,15.00,10.16,0.71,0.0,1.0,1,17.5
23,2013,2013.0,AJ Green,9,MIA,25,10.00,5.71,99.00,18.61,...,9.00,5.25,89.88,17.91,10.94,0.62,1.0,0.0,20,26.8
24,2013,2013.0,AJ Green,10,BAL,26,11.12,6.38,102.62,17.74,...,10.11,5.89,94.11,17.21,10.47,0.56,1.0,0.0,17,32.1
25,2013,2013.0,AJ Green,11,CLE,27,11.56,6.56,108.00,17.87,...,10.60,6.10,99.80,17.38,10.43,0.60,0.0,1.0,28,2.7
26,2013,2013.0,AJ Green,13,LAC,28,10.90,6.10,97.90,16.43,...,10.09,5.73,91.36,16.12,9.61,0.55,1.0,0.0,19,19.3
27,2013,2013.0,AJ Green,14,IND,29,10.55,6.00,96.55,16.45,...,9.83,5.67,90.67,16.16,9.80,0.58,0.0,1.0,29,19.2
28,2013,2013.0,AJ Green,15,PIT,30,10.33,6.00,94.50,16.08,...,9.69,5.69,89.23,15.84,9.74,0.62,1.0,0.0,6,18.3
29,2013,2013.0,AJ Green,16,MIN,31,10.92,6.23,94.38,15.63,...,10.29,5.93,89.50,15.44,9.41,0.57,0.0,1.0,27,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,2016,2016.0,AJ Green,5,DAL,66,11.00,8.00,117.00,15.23,...,9.80,7.20,100.40,13.88,9.36,0.60,0.0,0.0,12,9.0
65,2016,2016.0,AJ Green,6,NE,67,10.40,7.20,103.60,14.68,...,9.50,6.67,92.00,13.65,8.83,0.50,0.0,0.0,7,14.8
66,2016,2016.0,AJ Green,7,CLE,68,10.33,7.00,101.00,14.68,...,9.57,6.57,91.43,13.80,8.83,0.43,0.0,1.0,18,33.9
67,2016,2016.0,AJ Green,8,WAS,69,10.00,7.14,110.71,15.60,...,9.38,6.75,101.12,14.71,10.36,0.50,0.0,1.0,14,24.1
68,2016,2016.0,AJ Green,10,NYG,70,11.00,7.38,112.00,15.32,...,10.33,7.00,103.33,14.57,9.96,0.44,0.0,0.0,6,19.8
69,2016,2016.0,AJ Green,11,BUF,71,11.00,7.33,107.11,14.70,...,10.40,7.00,99.80,14.08,9.58,0.50,0.0,1.0,10,0.0
70,2017,2017.0,AJ Green,1,BAL,72,0.00,0.00,0.00,0.00,...,9.55,6.36,90.73,12.80,8.71,0.45,0.0,1.0,5,12.4
71,2017,2017.0,AJ Green,2,HOU,73,10.00,5.00,74.00,14.80,...,5.50,2.50,37.00,7.40,3.70,0.00,0.0,1.0,27,11.7
72,2017,2017.0,AJ Green,3,GB,74,9.00,5.00,70.50,14.10,...,6.33,3.33,47.00,9.40,5.27,0.00,1.0,0.0,29,30.1
73,2017,2017.0,AJ Green,4,CLE,75,10.33,6.67,84.00,13.10,...,8.00,5.00,63.00,9.83,6.08,0.25,1.0,0.0,16,17.3
74,2017,2017.0,AJ Green,5,BUF,76,9.50,6.25,78.75,12.98,...,7.80,5.00,63.00,10.38,6.66,0.40,0.0,1.0,10,33.9
75,2017,2017.0,AJ Green,7,PIT,77,10.20,6.40,100.80,15.78,...,8.67,5.33,84.00,13.15,7.97,0.50,1.0,0.0,9,7.1
76,2017,2017.0,AJ Green,8,IND,78,9.50,5.83,90.83,15.43,...,8.29,5.00,77.86,13.23,7.80,0.43,0.0,1.0,26,11.7
77,2017,2017.0,AJ Green,9,JAX,79,9.29,5.43,81.71,14.51,...,8.25,4.75,71.50,12.70,7.25,0.50,1.0,0.0,1,1.6
78,2017,2017.0,AJ Green,10,TEN,80,8.38,4.88,72.25,13.45,...,7.56,4.33,64.22,11.96,6.78,0.44,1.0,0.0,22,25.5
79,2017,2017.0,AJ Green,11,DEN,81,8.22,4.89,77.00,14.51,...,7.50,4.40,69.30,13.06,7.74,0.50,1.0,0.0,3,15.0
80,2017,2017.0,AJ Green,12,CLE,82,8.30,4.80,74.30,14.31,...,7.64,4.36,67.55,13.01,7.55,0.55,0.0,1.0,16,11.6
81,2017,2017.0,AJ Green,13,PIT,83,8.27,4.82,73.55,14.21,...,7.67,4.42,67.42,13.02,7.60,0.50,0.0,1.0,9,26.7
82,2017,2017.0,AJ Green,14,CHI,84,9.00,5.00,73.83,13.94,...,8.38,4.62,68.15,12.87,7.36,0.62,0.0,1.0,14,10.4
83,2017,2017.0,AJ Green,15,MIN,85,9.23,5.00,73.08,13.85,...,8.64,4.64,67.86,12.86,7.21,0.57,0.0,0.0,8,5.0
84,2017,2017.0,AJ Green,16,DET,86,8.86,4.79,70.00,13.94,...,8.33,4.47,65.33,13.01,7.23,0.53,0.0,1.0,17,14.1
85,2017,2017.0,AJ Green,17,BAL,87,8.93,4.87,70.73,13.91,...,8.44,4.56,66.31,13.04,7.29,0.50,1.0,0.0,5,3.7
86,2018,2018.0,AJ Green,1,IND,88,0.00,0.00,0.00,0.00,...,8.53,4.41,63.41,12.77,6.96,0.47,0.0,0.0,17,20.2
87,2018,2018.0,AJ Green,2,BAL,89,8.00,6.00,92.00,15.30,...,9.00,4.00,54.50,11.90,6.60,0.50,0.0,1.0,3,29.9
88,2018,2018.0,AJ Green,3,CAR,90,8.50,5.50,80.50,14.55,...,9.00,4.33,59.33,12.53,6.97,1.33,1.0,0.0,16,10.8
89,2018,2018.0,AJ Green,4,ATL,91,8.33,5.33,73.00,13.57,...,8.75,4.50,59.00,12.30,7.02,1.00,0.0,0.0,29,17.8
90,2018,2018.0,AJ Green,5,MIA,92,8.25,5.00,74.25,15.05,...,8.60,4.40,62.80,13.74,7.58,1.00,0.0,1.0,11,20.2
91,2018,2018.0,AJ Green,6,PIT,93,8.60,5.20,81.80,15.78,...,8.83,4.67,71.00,14.57,8.18,0.83,0.0,1.0,30,15.5
92,2018,2018.0,AJ Green,7,KC,94,9.17,5.50,82.33,15.17,...,9.29,5.00,73.00,14.21,8.03,0.71,1.0,0.0,20,21.7
93,2018,0.0,AJ Green,8,TB,95,9.86,5.71,87.29,15.39,...,9.88,5.25,78.50,14.52,8.07,0.62,0.0,1.0,25,18.6

In [147]:
wr_stats = temp
wr_stats.shape

(15970, 28)

In [65]:
#A function that will covert a time series database into a supervised learning database

def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
    n_vars = 1 if type(data) is list else data.shape[1]
    df = pd.DataFrame(data)
    cols, names = list(), list()
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -1):
            cols.append(df.shift(i))
            names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
    # forecast sequence (t, t+1, ... t+n)
    for i in range(0, n_out):
        cols.append(df.shift(-i))
        if i == 0:
            names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
        else:
            names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
    # put it all together
    agg = pd.concat(cols, axis=1)
    agg.columns = names
    # drop rows with NaN values
    if dropnan:
        agg.dropna(inplace=True)
    return agg

In [160]:
# A function to insert the non reframed columns back into the stats dataframe 

def insert_non_reframed(df, col_dict):
    non_reframed = ['games','year','Opponent','def_rk','h/a_1','surface_0','points']
    for player in df['Name'].unique():
        for col in non_reframed:
            reframed_dict['{}_reframed'.format(player)][col] = col_dict['{}'.format(player)][col].values
            
    return reframed_dict

In [148]:
wr_stats.to_csv('input/wr/wr_stats.csv', index=False)

In [149]:
wr_stats= pd.read_csv('input/wr/wr_stats.csv')

In [150]:
wr_stats.shape

(15970, 28)