In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [3]:
qb = pd.read_csv('../input/qb/qb_loc_cleaned.csv')

In [11]:
qb.sort_values(['year','games'], inplace=True)
qb.head()

,games,year,Name,Team,Week,Opponent,att,comp%,yds,td,def_rk,h/a_1,surface_0,points
1,1,2012,Aaron Rodgers,GB,1,SF,44,68.0,303,2,5,1.0,1.0,22.82
74,1,2012,Alex Smith,SF,1,GB,26,77.0,211,2,17,0.0,1.0,17.74
139,1,2012,Andrew Luck,IND,1,CHI,45,51.0,309,1,31,0.0,1.0,9.26
206,1,2012,Andy Dalton,CIN,1,BAL,37,60.0,221,0,19,0.0,1.0,5.94
282,1,2012,Ben Roethlisberger,PIT,1,DEN,40,55.0,245,2,24,0.0,1.0,16.20

In [5]:
def conv_atts(df):
    df['h/a_1'] = df['h/a_1'].astype('category')
    df['surface_0'] = df['surface_0'].astype('category')

    return df

In [6]:
qb = conv_atts(qb)
qb.dtypes

games           int64
year            int64
Name           object
Team           object
Week            int64
Opponent       object
att             int64
comp%         float64
yds             int64
td              int64
def_rk          int64
h/a_1        category
surface_0    category
points        float64
dtype: object

In [12]:
qb.shape

(2428, 14)

In [19]:
train = qb[]
train.tail()

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.numeric.Int64Index'> with these indexers [Int64Index([2385, 2386, 2376, 2365, 2380, 2383, 2384, 2354, 2373, 2381, 2389,
            2378, 2388, 2355, 2375, 2371, 2367, 2387, 2377, 2361, 2364, 2372,
            2356, 2382, 2369, 2366, 2358, 2374, 2360, 2379, 2357, 2368, 2359,
            2362, 2363, 2370],
           dtype='int64')] of <class 'pandas.core.indexes.numeric.Int64Index'>

In [15]:
test.index

Int64Index([2385, 2386, 2376, 2365, 2380, 2383, 2384, 2354, 2373, 2381, 2389,
            2378, 2388, 2355, 2375, 2371, 2367, 2387, 2377, 2361, 2364, 2372,
            2356, 2382, 2369, 2366, 2358, 2374, 2360, 2379, 2357, 2368, 2359,
            2362, 2363, 2370],
           dtype='int64')

In [14]:
test = qb[qb['year']==2018]
test = test[test['Week']==7]
test.head()

,games,year,Name,Team,Week,Opponent,att,comp%,yds,td,def_rk,h/a_1,surface_0,points
2385,1,2018,Jeff Driskel,CIN,7,KC,4,100.0,39,0,6,0.0,1.0,2.06
2386,1,2018,Sean Mannion,LAR,7,SF,0,0.0,0,0,11,0.0,1.0,0.10
2376,2,2018,Cody Kessler,JAX,7,HOU,30,70.0,156,1,8,1.0,1.0,10.04
2365,5,2018,Baker Mayfield,CLE,7,TB,34,67.6,215,2,16,0.0,1.0,20.90
2380,5,2018,Josh Rosen,ARI,7,DEN,39,53.8,194,1,2,1.0,1.0,8.16

In [14]:
df_18 = qb[qb['year']==2018]
df_18.shape

(225, 26)

In [12]:
df_18

,Name,Week,Opponent,att_avg,comp%_avg,yds_avg,td_avg,def_rk_avg,games_ma,att_ma,...,comp%_car,yds_car,td_car,def_rk_car,games,year,def_rk,h/a_1,surface_0,points
6,Aaron Rodgers,2,CHI,37.00,56.80,333.00,3.00,8.00,0.0,0.000000,...,68.60,259.80,2.00,15.80,70,2018,16,1.0,1.0,24.94
13,Aaron Rodgers,1,MIN,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,66.83,260.33,2.42,15.00,73,2018,24,1.0,1.0,16.04
18,Aaron Rodgers,2,WAS,34.00,58.80,199.00,2.00,5.00,0.0,0.000000,...,63.40,349.00,3.50,8.50,71,2018,19,0.0,1.0,19.90
23,Aaron Rodgers,3,BUF,46.00,66.35,327.00,1.50,12.00,0.0,0.000000,...,68.54,330.29,2.57,18.29,72,2018,3,1.0,1.0,17.02
30,Aaron Rodgers,6,DET,37.60,68.60,259.80,2.00,15.80,3.0,37.600000,...,69.73,294.14,2.71,11.00,68,2018,12,0.0,0.0,33.68
35,Aaron Rodgers,12,SF,35.40,66.90,261.90,2.70,14.40,5.5,35.400000,...,67.61,301.58,2.92,16.42,69,2018,26,0.0,1.0,31.40
79,Alex Smith,2,ARI,34.00,61.80,173.00,2.00,16.00,0.0,0.000000,...,68.60,217.40,1.60,12.00,61,2018,6,0.0,1.0,19.60
83,Alex Smith,4,IND,25.00,76.00,186.00,3.00,7.00,0.0,0.000000,...,72.22,192.33,1.44,13.56,65,2018,23,1.0,1.0,13.08
88,Alex Smith,4,GB,36.50,63.35,266.50,2.00,5.50,0.0,0.000000,...,46.43,123.64,0.93,15.21,62,2018,10,1.0,1.0,17.80
97,Alex Smith,4,NO,28.00,77.07,258.00,2.33,14.33,0.0,0.000000,...,66.00,209.88,1.75,17.88,64,2018,30,0.0,0.0,15.70
101,Alex Smith,5,CAR,32.00,67.23,255.67,1.33,13.00,0.0,0.000000,...,79.30,240.33,3.67,17.33,63,2018,21,1.0,1.0,15.82
144,Andrew Luck,2,CIN,23.00,78.30,178.00,2.00,25.00,0.0,0.000000,...,54.00,297.60,1.40,19.20,65,2018,27,1.0,0.0,23.46
148,Andrew Luck,2,WAS,53.00,66.00,370.00,2.00,25.00,0.0,0.000000,...,58.33,292.33,1.11,15.78,67,2018,19,0.0,1.0,13.36
154,Andrew Luck,7,PHI,43.00,57.70,271.67,2.33,19.67,0.0,0.000000,...,54.73,278.87,1.40,12.93,66,2018,17,0.0,1.0,13.86
158,Andrew Luck,5,HOU,42.00,65.07,316.67,2.33,18.00,0.0,0.000000,...,62.95,212.25,1.25,14.50,62,2018,15,1.0,0.0,39.66
163,Andrew Luck,6,NE,44.25,55.00,302.00,1.75,17.75,2.5,44.250000,...,58.78,243.00,1.78,13.11,64,2018,25,0.0,0.0,27.60
168,Andrew Luck,11,NYJ,40.22,58.33,292.33,1.11,15.78,5.0,40.222222,...,68.15,326.00,1.50,20.50,63,2018,22,0.0,0.0,28.74
211,Andy Dalton,2,IND,33.00,78.80,282.00,2.00,4.00,0.0,0.000000,...,66.60,269.00,1.80,15.80,68,2018,23,0.0,0.0,17.52
216,Andy Dalton,6,BAL,31.00,64.15,252.50,1.50,16.50,0.0,0.000000,...,64.40,255.90,2.00,16.70,66,2018,1,1.0,0.0,26.60
221,Andy Dalton,4,CAR,30.67,65.83,288.67,2.67,17.33,0.0,0.000000,...,62.07,239.40,1.73,18.73,67,2018,21,0.0,1.0,21.08
225,Andy Dalton,6,ATL,41.67,68.27,333.67,1.33,14.00,0.0,0.000000,...,68.20,218.75,1.50,9.50,65,2018,31,0.0,0.0,28.78
231,Andy Dalton,2,MIA,28.00,75.00,243.00,2.00,23.00,0.0,0.000000,...,64.42,268.80,2.40,11.00,70,2018,11,1.0,0.0,13.92
237,Andy Dalton,9,PIT,34.71,64.29,261.57,1.86,16.14,4.0,34.714286,...,67.66,275.00,1.40,11.40,69,2018,28,1.0,0.0,17.16
278,Baker Mayfield,3,NYJ,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,0.00,0.00,0.00,0.00,4,2018,22,1.0,1.0,9.84
279,Baker Mayfield,4,OAK,23.00,73.90,201.00,0.00,22.00,0.0,0.000000,...,73.90,201.00,0.00,22.00,2,2018,20,0.0,1.0,16.80
280,Baker Mayfield,5,BAL,32.00,62.55,248.00,1.00,21.00,0.0,0.000000,...,62.55,248.00,1.00,21.00,1,2018,1,1.0,1.0,21.98
281,Baker Mayfield,6,LAC,35.67,61.07,279.33,1.00,14.33,0.0,0.000000,...,61.07,279.33,1.00,14.33,3,2018,18,1.0,1.0,14.32
287,Ben Roethlisberger,4,CLE,41.00,63.40,406.00,2.00,4.00,0.0,0.000000,...,64.80,297.40,2.00,23.40,66,2018,8,0.0,1.0,17.00
292,Ben Roethlisberger,4,KC,32.00,70.45,280.50,1.50,9.00,0.0,0.000000,...,64.20,257.20,2.00,19.80,62,2018,29,1.0,1.0,41.98
296,Ben Roethlisberger,9,TB,32.50,73.10,360.00,2.00,15.50,0.0,0.000000,...,64.20,270.00,2.50,5.00,63,2018,32,0.0,1.0,28.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1993,Ryan Fitzpatrick,2,CHI,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,60.42,205.92,1.67,12.42,48,2018,16,0.0,1.0,4.04
2043,Ryan Tannehill,2,TEN,36.00,56.00,219.00,0.00,10.00,0.0,0.000000,...,56.00,219.00,0.00,10.00,54,2018,7,1.0,1.0,15.60
2048,Ryan Tannehill,5,NYJ,34.50,68.10,277.50,1.50,10.50,0.0,0.000000,...,60.00,242.33,0.67,15.50,53,2018,22,0.0,0.0,18.12
2053,Ryan Tannehill,8,OAK,31.33,72.27,266.33,2.00,21.00,0.0,0.000000,...,57.82,215.73,0.64,13.82,52,2018,20,1.0,1.0,26.16
2056,Ryan Tannehill,6,NE,46.50,60.65,328.00,2.00,23.00,0.0,0.000000,...,58.00,209.21,0.71,13.07,56,2018,25,0.0,0.0,2.00
2059,Ryan Tannehill,3,CIN,45.00,71.10,387.00,2.00,9.00,0.0,0.000000,...,62.30,277.00,0.50,11.50,55,2018,27,0.0,0.0,10.10
2102,Sam Bradford,1,WAS,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,61.50,220.25,1.00,17.75,36,2018,19,1.0,1.0,4.82
2106,Sam Bradford,1,LAR,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,60.12,224.62,1.00,16.38,37,2018,13,0.0,1.0,2.60
2108,Sam Bradford,5,CHI,40.00,61.40,303.00,2.00,14.50,0.0,0.000000,...,60.00,224.20,1.20,16.10,35,2018,16,1.0,1.0,11.28
2135,Sam Darnold,1,DET,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,0.00,0.00,0.00,0.00,4,2018,12,0.0,0.0,14.82
2136,Sam Darnold,2,MIA,21.00,76.20,198.00,2.00,12.00,0.0,0.000000,...,76.20,198.00,2.00,12.00,3,2018,11,1.0,0.0,18.46
2137,Sam Darnold,3,CLE,31.00,68.60,266.00,1.50,11.50,0.0,0.000000,...,68.60,266.00,1.50,11.50,6,2018,8,0.0,1.0,4.76
2138,Sam Darnold,4,JAX,31.00,61.87,233.67,1.00,10.33,0.0,0.000000,...,61.87,233.67,1.00,10.33,5,2018,4,0.0,1.0,11.48
2139,Sam Darnold,6,DEN,29.80,56.22,213.20,1.40,8.00,3.8,29.800000,...,58.90,217.00,1.00,8.75,1,2018,5,1.0,0.0,19.42
2140,Sam Darnold,5,IND,31.75,58.90,217.00,1.00,8.75,4.5,31.750000,...,56.22,213.20,1.40,8.00,2,2018,23,1.0,0.0,19.00
2151,Taysom Hill,1,TB,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,0.00,0.00,0.00,0.00,4,2018,32,1.0,0.0,0.00
2152,Taysom Hill,2,CLE,0.00,0.00,0.00,0.00,32.00,0.0,0.000000,...,0.00,0.00,0.00,32.00,5,2018,8,1.0,0.0,0.00
2153,Taysom Hill,3,ATL,0.00,0.00,0.00,0.00,20.00,0.0,0.000000,...,0.00,0.00,0.00,20.00,2,2018,31,0.0,0.0,3.90
2154,Taysom Hill,4,NYG,0.00,0.00,0.00,0.00,23.67,0.0,0.000000,...,0.00,0.00,0.00,23.67,3,2018,14,0.0,0.0,3.80
2155,Taysom Hill,5,WAS,0.50,12.50,2.50,0.00,21.25,3.5,0.500000,...,12.50,2.50,0.00,21.25,1,2018,19,0.0,1.0,8.30
2159,Teddy Bridgewater,14,WAS,36.33,60.67,265.00,1.00,24.33,0.0,0.000000,...,60.67,265.00,1.00,24.33,13,2018,19,0.0,1.0,-0.30
2186,Tom Brady,4,HOU,39.33,67.67,295.67,1.33,20.00,0.0,0.000000,...,67.67,295.67,1.33,20.00,75,2018,15,1.0,0.0,22.28
2190,Tom Brady,6,JAX,39.67,63.23,276.33,2.00,22.33,0.0,0.000000,...,66.00,300.57,1.71,16.00,77,2018,4,0.0,1.0,17.36
2195,Tom Brady,1,DET,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,65.42,294.75,2.08,14.25,78,2018,12,0.0,0.0,8.52
2199,Tom Brady,5,MIA,0.00,0.00,0.00,0.00,0.00,0.0,0.000000,...,63.75,301.69,2.12,13.00,76,2018,11,1.0,0.0,20.96
2205,Tom Brady,4,IND,37.00,74.15,412.50,4.00,26.50,0.0,0.000000,...,64.43,301.43,2.00,17.14,73,2018,23,1.0,0.0,32.54
2212,Tom Brady,6,KC,37.00,67.60,290.00,1.60,17.20,3.0,37.000000,...,63.65,319.50,2.75,11.75,74,2018,29,0.0,1.0,25.80
2315,Tyrod Taylor,5,PIT,1.50,33.50,15.00,0.00,5.00,0.0,0.000000,...,33.50,15.00,0.00,5.00,35,2018,28,1.0,1.0,24.58
2318,Tyrod Taylor,3,NO,30.00,76.70,242.00,3.00,15.00,0.0,0.000000,...,13.40,6.00,0.00,7.80,36,2018,30,0.0,0.0,15.44
2322,Tyrod Taylor,3,NYJ,30.00,60.00,297.00,3.00,19.00,0.0,0.000000,...,69.30,209.33,2.33,20.00,37,2018,22,1.0,1.0,2.96

In [13]:
df_18['Week'].unique()

array([ 2,  1,  3,  6, 12,  4,  5,  7, 11,  9,  8, 16, 14, 10, 13, 15, 17],
      dtype=int64)

In [12]:
train.shape

(1632, 27)

In [13]:
test = qb[qb['year']==2018]
test=test[test['Week']==4]
test.shape

(23, 27)

In [71]:
test.columns

Index(['year', 'player', 'Week', 'Opponent', 'games_avg', 'att_avg',
       'comp%_avg', 'yds_avg', 'td_avg', 'rat_avg', 'def_rk_avg', 'games_ma',
       'att_ma', 'comp%_ma', 'yds_ma', 'td_ma', 'rat_ma', 'def_rk_ma',
       'games_car', 'att_car', 'comp%_car', 'yds_car', 'td_car', 'rat_car',
       'def_rk_car', 'def_rk', 'h/a_1', 'surface_0', 'salary', 'points'],
      dtype='object')

In [72]:
# Target variables 

y_train = train['points']
y_test = test['points']

# Predictors, all numeric variables minus target variable
X_train = train.iloc[:,4:-2]
X_test = test.iloc[:,4:-2]

In [73]:

X_test.columns

Index(['games_avg', 'att_avg', 'comp%_avg', 'yds_avg', 'td_avg', 'rat_avg',
       'def_rk_avg', 'games_ma', 'att_ma', 'comp%_ma', 'yds_ma', 'td_ma',
       'rat_ma', 'def_rk_ma', 'games_car', 'att_car', 'comp%_car', 'yds_car',
       'td_car', 'rat_car', 'def_rk_car', 'def_rk', 'h/a_1', 'surface_0'],
      dtype='object')

In [90]:
scaler = MinMaxScaler()
scaler.fit_transform(X_train)

array([[ 0.        ,  1.        ,  0.0070922 , ...,  0.        ,
         0.51998093,  0.14457831],
       [ 0.01960784,  0.8335    ,  0.02600473, ...,  0.19142857,
         0.5486886 ,  0.39759036],
       [ 0.21568627,  0.785     ,  0.23799054, ...,  0.21428571,
         0.62250835,  0.5       ],
       ...,
       [ 0.46411765,  0.6547    ,  0.33174941, ...,  0.21428571,
         0.48526466,  0.81325301],
       [ 0.48039216,  0.6695    ,  0.39184397, ...,  0.22857143,
         0.45808298,  0.85542169],
       [ 0.58039216,  0.6414    ,  0.42411348, ...,  0.19142857,
         0.36185026,  0.8253012 ]])

In [74]:
X_test.shape

(29, 24)

In [75]:
X_train.shape

(1554, 24)

In [16]:
y_train.reset_index(inplace=True,drop=True)
X_train.reset_index(inplace=True, drop=True)

In [76]:
lr = LinearRegression()

In [77]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [78]:
coeff = pd.DataFrame(X_train.columns)
coeff['coefficients'] = lr.coef_
coeff

             0  coefficients
0    games_avg     -1.557618
1      att_avg      0.069540
2    comp%_avg      0.094842
3      yds_avg      0.011553
4       td_avg      1.067263
5      rat_avg     -0.096874
6   def_rk_avg      0.040532
7     games_ma     -0.086614
8       att_ma     -0.216187
9     comp%_ma      0.118289
10      yds_ma      0.001655
11       td_ma      3.743741
12      rat_ma     -0.065478
13   def_rk_ma      0.104408
14   games_car      1.646770
15     att_car     -0.029742
16   comp%_car     -0.147506
17     yds_car      0.024927
18      td_car     -1.683899
19     rat_car      0.124073
20  def_rk_car     -0.179305
21      def_rk      0.225534
22       h/a_1      1.369738
23   surface_0     -0.707260

In [79]:
X_train.shape

(1554, 24)

In [80]:
yhat = lr.predict(X_test)

In [81]:
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())

rmse_val = rmse(yhat, y_test)
print("RMSE error is: " + str(rmse_val))

RMSE error is: 11.886112724

In [82]:
results = pd.DataFrame()
results['Player'] = test['player']
#results['score'] = y_test
results['Predicted'] = yhat
results['points'] = test['points']
#results['Week'] = qb[qb['year']==2017]['Week']
#results.groupby('Player').mean()[['score','Predicted']]
results

                           Player  Predicted  points
49         Aaron Rodgers_reframed  20.573807   17.02
123          Andrew Luck_reframed  19.606521   39.66
171          Andy Dalton_reframed  24.064387   28.78
177       Baker Mayfield_reframed  14.830017   16.80
221   Ben Roethlisberger_reframed  20.109991   15.86
293        Blake Bortles_reframed  17.671645   28.32
497         Carson Wentz_reframed  18.251134   24.72
531          Case Keenum_reframed  22.272994    8.80
606         Dak Prescott_reframed  14.274891   18.40
666           Derek Carr_reframed  22.945548   36.58
677       Deshaun Watson_reframed  18.536891   35.10
743           Drew Brees_reframed  21.044687    8.58
814          Eli Manning_reframed  24.792723   15.70
910           Jared Goff_reframed  21.670753   42.30
1007          Joe Flacco_reframed  22.304024   25.22
1022          Josh Allen_reframed  12.100147    4.94
1050          Josh Rosen_reframed   5.372348   12.50
1112        Kirk Cousins_reframed  17.064334   35.68
1168      Marcus Mariota_reframed  18.549693   34.36
1265           Matt Ryan_reframed  24.913490   32.26
1320    Matthew Stafford_reframed  21.049755   23.78
1345      Mitch Trubisky_reframed  19.753895   46.46
1375     Patrick Mahomes_reframed  15.725732   25.86
1439       Philip Rivers_reframed  24.175494   22.70
1495      Russell Wilson_reframed  16.196133    8.98
1533    Ryan Fitzpatrick_reframed  19.723250    4.04
1577      Ryan Tannehill_reframed  18.185383    2.00
1614         Sam Darnold_reframed  12.919849   11.48
1698           Tom Brady_reframed  17.516351   20.96

In [83]:
results.

SyntaxError: invalid syntax (<ipython-input-83-905f1e55433b>, line 1)

In [24]:
results.to_csv('../output/qb_test.csv', index= False)