In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [ ]:
rb = pd.read_csv('../input/rb/rb_stats.csv')

In [9]:
df = pd.read_csv('../input/rb/rb_loc_cleaned.csv')

In [12]:
df.sort_values(['Name','games'],inplace=True)

In [3]:
rb.dtypes

year             int64
Name            object
games            int64
Opponent        object
att_avg        float64
yds_avg        float64
td_avg         float64
tar_avg        float64
rec_yds_avg    float64
att_ma         float64
yds_ma         float64
td_ma          float64
tar_ma         float64
rec_yds_ma     float64
att_car        float64
yds_car        float64
td_car         float64
tar_car        float64
rec_yds_car    float64
surface_0      float64
h/a_1          float64
def_rk           int64
points         float64
dtype: object

In [4]:
def conv_atts(df):
    df.rename(columns={'Unnamed: 0':'player'}, inplace=True)
    df.replace('null',0, inplace=True)
    df['h/a_1'] = df['h/a_1'].astype('category')
    df['surface_0'] = df['surface_0'].astype('category')
    

    return df

In [5]:
rb = conv_atts(rb)
rb.dtypes

year              int64
Name             object
games             int64
Opponent         object
att_avg         float64
yds_avg         float64
td_avg          float64
tar_avg         float64
rec_yds_avg     float64
att_ma          float64
yds_ma          float64
td_ma           float64
tar_ma          float64
rec_yds_ma      float64
att_car         float64
yds_car         float64
td_car          float64
tar_car         float64
rec_yds_car     float64
surface_0      category
h/a_1          category
def_rk            int64
points          float64
dtype: object

In [13]:
rb['Week'] = df['Week']
rb.columns

Index(['year', 'Name', 'games', 'Opponent', 'att_avg', 'yds_avg', 'td_avg',
       'tar_avg', 'rec_yds_avg', 'att_ma', 'yds_ma', 'td_ma', 'tar_ma',
       'rec_yds_ma', 'att_car', 'yds_car', 'td_car', 'tar_car', 'rec_yds_car',
       'surface_0', 'h/a_1', 'def_rk', 'points', 'Week'],
      dtype='object')

In [6]:
rb.head()

,year,Name,games,Opponent,att_avg,yds_avg,td_avg,tar_avg,rec_yds_avg,att_ma,...,rec_yds_ma,att_car,yds_car,td_car,tar_car,rec_yds_car,surface_0,h/a_1,def_rk,points
0,2018,Aaron Jones,1,WAS,0.0,0.0,0.00,0.00,0.00,0.0,...,0.00,0.0,0.0,0.00,0.00,0.00,1.0,0.0,15,5.7
1,2018,Aaron Jones,2,BUF,6.0,42.0,0.00,1.00,5.00,0.0,...,0.00,6.0,42.0,0.00,1.00,5.00,1.0,1.0,18,15.2
2,2018,Aaron Jones,3,DET,8.5,53.5,0.50,1.00,11.00,0.0,...,0.00,8.5,53.5,0.50,1.00,11.00,0.0,0.0,29,7.9
3,2018,Aaron Jones,4,SF,8.0,49.0,0.33,1.67,13.67,0.0,...,0.00,8.0,49.0,0.33,1.67,13.67,1.0,0.0,22,4.1
4,2018,Aaron Jones,5,LAR,8.0,47.0,0.25,1.50,10.25,8.0,...,10.25,8.0,47.0,0.25,1.50,10.25,1.0,0.0,14,16.6

In [7]:

rb.isnull().sum()

year           0
Name           0
games          0
Opponent       0
att_avg        0
yds_avg        0
td_avg         0
tar_avg        0
rec_yds_avg    0
att_ma         0
yds_ma         0
td_ma          0
tar_ma         0
rec_yds_ma     0
att_car        0
yds_car        0
td_car         0
tar_car        0
rec_yds_car    0
surface_0      0
h/a_1          0
def_rk         0
points         0
dtype: int64

In [8]:
rb = rb.sort_values(['year','Week']).reset_index(drop=True)
rb.head()

KeyError: 'Week'

In [27]:
rb_18 = rb[rb['year']==2018.0]
rb

,Name,Week,Opponent,att_avg,yds_avg,td_avg,tar_avg,rec_yds_avg,def_rk_avg,att_ma,...,tar_car,rec_yds_car,def_rk_car,games,year,def_rk,h/a_1,surface_0,points,0
0,Aaron Jones,4.0,WAS,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,3.21,16.00,16.07,11.0,2018.0,14.0,0.0,1.0,5.7,NaN
1,Aaron Jones,5.0,CHI,13.00,49.00,1.00,0.00,0.00,11.00,0.000000,...,3.20,15.93,17.13,1.0,2017.0,11.0,1.0,1.0,10.9,NaN
2,Aaron Jones,6.0,BUF,16.00,87.00,1.00,0.50,4.50,9.50,0.000000,...,3.50,16.50,18.50,12.0,2018.0,25.0,1.0,1.0,15.2,NaN
3,Aaron Jones,7.0,DAL,15.00,71.67,0.67,1.67,3.33,6.67,0.000000,...,3.67,16.67,18.33,2.0,2017.0,8.0,0.0,0.0,23.4,NaN
4,Aaron Jones,9.0,MIN,15.50,86.50,0.75,2.50,4.25,9.25,15.500000,...,3.75,14.25,19.75,3.0,2017.0,1.0,0.0,0.0,5.2,NaN
5,Aaron Jones,10.0,NO,13.40,71.60,0.60,3.00,3.20,13.60,13.400000,...,0.00,0.00,0.00,4.0,2017.0,17.0,1.0,1.0,25.8,NaN
6,Aaron Jones,13.0,DET,11.67,61.67,0.50,2.67,2.67,13.17,11.666667,...,3.00,20.00,18.00,5.0,2017.0,31.0,1.0,1.0,3.1,NaN
7,Aaron Jones,14.0,CHI,10.14,55.71,0.57,2.29,2.29,15.43,10.142857,...,4.50,21.50,22.00,6.0,2017.0,11.0,0.0,1.0,2.2,NaN
8,Aaron Jones,15.0,TB,9.38,48.50,0.50,2.00,2.00,15.12,9.375000,...,4.00,17.33,19.00,7.0,2017.0,29.0,1.0,1.0,8.0,NaN
9,Aaron Jones,16.0,CLE,8.67,48.33,0.44,2.00,2.44,13.78,8.666667,...,0.00,0.00,0.00,8.0,2017.0,13.0,0.0,1.0,-0.2,NaN
10,Aaron Jones,3.0,CAR,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,5.33,42.00,13.22,9.0,2017.0,3.0,0.0,1.0,6.3,NaN
11,Aaron Jones,4.0,MIN,6.00,42.00,0.00,1.00,5.00,14.00,0.000000,...,5.90,42.20,14.20,10.0,2017.0,1.0,1.0,1.0,1.3,NaN
12,Aaron Ripkowski,5.0,CHI,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,2.36,12.82,22.64,9.0,2017.0,11.0,1.0,1.0,2.0,NaN
13,Aaron Ripkowski,6.0,NYG,2.00,17.00,0.00,0.00,0.00,6.00,0.000000,...,2.25,11.92,21.92,1.0,2016.0,6.0,1.0,1.0,1.7,NaN
14,Aaron Ripkowski,7.0,DAL,1.50,8.50,0.00,0.50,1.00,4.50,0.000000,...,2.23,11.77,20.38,10.0,2017.0,8.0,0.0,0.0,0.2,NaN
15,Aaron Ripkowski,8.0,DAL,2.00,8.33,0.00,0.67,3.33,4.67,0.000000,...,2.36,12.07,19.43,2.0,2016.0,3.0,1.0,1.0,1.2,NaN
16,Aaron Ripkowski,9.0,CHI,3.00,14.75,0.00,0.75,2.25,10.75,3.000000,...,2.87,14.20,19.27,13.0,2016.0,5.0,1.0,1.0,2.6,NaN
17,Aaron Ripkowski,11.0,ATL,2.80,12.60,0.00,0.80,2.40,13.60,2.800000,...,2.88,16.56,19.50,3.0,2016.0,29.0,0.0,0.0,4.3,NaN
18,Aaron Ripkowski,12.0,IND,2.67,12.00,0.00,0.67,2.00,15.67,2.666667,...,1.50,26.00,21.00,4.0,2016.0,25.0,1.0,1.0,1.7,NaN
19,Aaron Ripkowski,13.0,CHI,2.71,10.43,0.14,0.86,3.86,15.14,2.714286,...,3.00,43.33,21.33,11.0,2017.0,11.0,0.0,1.0,2.5,NaN
20,Aaron Ripkowski,14.0,WAS,2.75,10.88,0.25,0.88,3.88,14.62,2.750000,...,3.25,38.00,21.75,5.0,2016.0,26.0,0.0,1.0,0.9,NaN
21,Aaron Ripkowski,17.0,PHI,2.78,9.89,0.22,0.89,3.44,13.44,2.777778,...,3.20,33.20,18.60,6.0,2016.0,12.0,0.0,1.0,9.6,NaN
22,Aaron Ripkowski,4.0,PIT,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,0.00,0.00,22.00,12.0,2017.0,18.0,0.0,1.0,0.4,NaN
23,Aaron Ripkowski,5.0,HOU,1.00,4.00,0.00,2.00,6.00,11.00,0.000000,...,0.00,0.00,22.50,7.0,2016.0,11.0,1.0,1.0,8.8,NaN
24,Aaron Ripkowski,10.0,SEA,1.00,3.00,0.00,1.00,3.00,9.50,0.000000,...,0.00,0.00,18.00,14.0,2016.0,4.0,1.0,1.0,0.2,NaN
25,Aaron Ripkowski,12.0,DET,1.33,3.00,0.00,1.00,6.00,10.00,0.000000,...,0.25,3.00,20.50,8.0,2016.0,9.0,0.0,0.0,15.6,NaN
26,Adrian Peterson,1.0,SF,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,0.00,0.00,0.00,1.0,2015.0,32.0,0.0,1.0,8.2,NaN
27,Adrian Peterson,2.0,TEN,10.00,31.00,0.00,3.00,21.00,32.00,0.000000,...,0.00,0.00,11.00,15.0,2016.0,2.0,0.0,1.0,3.1,NaN
28,Adrian Peterson,3.0,MIN,19.50,82.50,0.00,2.50,39.50,24.50,0.000000,...,0.50,4.50,9.50,18.0,2017.0,1.0,0.0,0.0,1.8,NaN
29,Adrian Peterson,4.0,ARI,19.67,97.00,0.67,1.67,26.33,25.00,0.000000,...,1.67,3.33,6.67,24.0,2018.0,31.0,0.0,1.0,23.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4839,Zach Line,10.0,CHI,2.00,4.00,0.00,0.00,0.00,29.00,0.000000,...,2.67,19.33,6.00,4.0,2015.0,22.0,1.0,0.0,7.7,NaN
4840,Zach Line,11.0,NYJ,1.50,6.50,0.00,0.00,0.00,30.50,0.000000,...,2.75,18.00,6.00,11.0,2017.0,21.0,1.0,0.0,2.3,NaN
4841,Zach Line,15.0,NYG,1.33,5.00,0.00,0.00,0.00,29.67,0.000000,...,0.00,0.00,0.00,5.0,2015.0,24.0,1.0,0.0,0.3,NaN
4842,Zach Line,17.0,TB,1.50,5.75,0.00,0.50,1.25,27.50,1.500000,...,6.00,41.00,9.00,14.0,2017.0,29.0,0.0,1.0,7.8,NaN
4843,Zach Zenner,1.0,LAC,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,0.67,7.33,20.33,1.0,2015.0,26.0,0.0,1.0,0.6,NaN
4844,Zach Zenner,4.0,ATL,2.00,6.00,0.00,0.00,0.00,26.00,0.000000,...,0.75,5.50,20.75,14.0,2017.0,14.0,1.0,0.0,0.5,NaN
4845,Zach Zenner,5.0,SEA,2.00,7.50,0.00,0.50,2.00,13.50,0.000000,...,1.80,11.60,22.40,2.0,2015.0,1.0,0.0,0.0,2.3,NaN
4846,Zach Zenner,6.0,CHI,4.67,15.00,0.00,1.00,3.67,11.67,0.000000,...,1.83,10.83,23.33,4.0,2016.0,5.0,0.0,1.0,4.4,NaN
4847,Zach Zenner,4.0,MIN,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,0.67,0.67,17.00,15.0,2017.0,1.0,0.0,0.0,0.0,NaN
4848,Zach Zenner,5.0,ARI,3.00,12.00,0.00,1.00,22.00,5.00,0.000000,...,1.25,1.75,17.00,3.0,2015.0,8.0,1.0,0.0,4.7,NaN
4849,Zach Zenner,6.0,PHI,5.00,10.50,0.00,1.50,22.50,8.50,0.000000,...,1.00,1.40,16.00,5.0,2016.0,12.0,1.0,0.0,5.2,NaN
4850,Zach Zenner,7.0,CAR,8.00,26.33,0.00,1.67,21.33,11.00,0.000000,...,1.00,1.17,16.67,16.0,2017.0,3.0,1.0,0.0,7.1,NaN
4851,Zach Zenner,8.0,LAR,8.25,27.00,0.25,1.75,16.00,14.75,8.250000,...,1.71,6.00,17.00,6.0,2016.0,16.0,1.0,0.0,9.7,NaN
4852,Zach Zenner,12.0,NO,7.20,22.00,0.20,1.60,13.80,14.00,7.200000,...,1.75,6.50,15.25,17.0,2017.0,17.0,0.0,0.0,0.0,NaN
4853,Zach Zenner,13.0,CHI,6.17,18.33,0.17,1.33,11.50,13.00,6.166667,...,1.78,6.89,16.78,19.0,2015.0,22.0,1.0,0.0,1.5,NaN
4854,Zach Zenner,14.0,WAS,6.57,21.43,0.14,1.14,9.86,15.43,6.571429,...,2.00,8.90,16.70,20.0,2016.0,26.0,1.0,0.0,8.9,NaN
4855,Zach Zenner,15.0,HOU,6.62,23.25,0.12,1.25,9.75,14.12,6.625000,...,2.27,10.00,15.55,7.0,2016.0,11.0,0.0,0.0,1.7,NaN
4856,Zach Zenner,16.0,MIN,6.22,22.00,0.11,1.67,14.44,13.22,6.222222,...,2.58,15.75,15.58,8.0,2016.0,8.0,1.0,0.0,0.0,NaN
4857,Zach Zenner,17.0,MIN,6.80,26.50,0.30,1.80,15.50,12.20,6.800000,...,3.23,17.23,16.85,21.0,2017.0,1.0,1.0,0.0,0.6,NaN
4858,Zach Zenner,3.0,NO,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,5.50,36.00,5.00,9.0,2016.0,30.0,0.0,0.0,4.0,NaN
4859,Zach Zenner,4.0,BAL,3.00,5.00,0.00,0.00,0.00,14.00,0.000000,...,5.67,40.67,10.67,18.0,2017.0,20.0,0.0,1.0,0.4,NaN
4860,Zach Zenner,5.0,CHI,3.00,2.50,0.00,0.00,0.00,7.50,0.000000,...,5.25,40.50,10.25,10.0,2016.0,5.0,1.0,0.0,6.5,NaN
4861,Zach Zenner,6.0,TB,3.00,5.33,0.33,0.00,0.00,6.00,0.000000,...,5.60,38.40,8.80,22.0,2017.0,29.0,0.0,1.0,0.0,NaN
4862,Zach Zenner,12.0,NYG,2.50,4.00,0.25,0.25,0.00,8.75,2.500000,...,5.17,36.17,9.50,11.0,2016.0,6.0,0.0,0.0,9.4,NaN
4863,Zach Zenner,13.0,DAL,2.20,4.40,0.20,0.20,0.00,7.20,2.200000,...,5.29,41.29,11.14,12.0,2016.0,3.0,0.0,0.0,23.2,NaN
4864,Zach Zenner,14.0,GB,2.00,4.33,0.17,0.17,0.00,9.33,2.000000,...,5.25,43.88,13.25,13.0,2016.0,10.0,1.0,0.0,21.0,NaN
4865,Zurlon Tipton,5.0,HOU,0.00,0.00,0.00,0.00,0.00,0.00,0.000000,...,1.86,9.86,21.57,1.0,2015.0,7.0,0.0,0.0,0.9,NaN
4866,Zurlon Tipton,13.0,PIT,2.00,9.00,0.00,1.00,0.00,7.00,0.000000,...,2.38,12.38,22.38,2.0,2015.0,2.0,0.0,1.0,1.7,NaN
4867,Zurlon Tipton,14.0,JAX,1.50,4.50,0.00,1.50,3.50,4.50,0.000000,...,2.44,11.89,22.44,3.0,2015.0,27.0,0.0,1.0,9.7,NaN
4868,Zurlon Tipton,15.0,HOU,1.33,5.33,0.00,2.67,19.00,12.00,0.000000,...,2.40,11.90,23.20,4.0,2015.0,7.0,1.0,0.0,0.4,NaN

In [10]:
# Design train and test datasets

train = rb[rb['year']!=2018]
train = train[train['Week']!=4]
train['year'].unique()

array([2017, 2016, 2015], dtype=int64)

In [11]:
train.shape

(3439, 39)

In [12]:
test = rb[rb['year']==2018]
test=test[test['Week']==4]
test.shape

(63, 39)

In [15]:
test.columns

Index(['player', 'Week', 'Opponent', 'year', 'var1(t-1)', 'var2(t-1)',
       'var3(t-1)', 'var4(t-1)', 'var5(t-1)', 'var6(t-1)', 'var7(t-1)',
       'var8(t-1)', 'var9(t-1)', 'var10(t-1)', 'var11(t-1)', 'var12(t-1)',
       'var13(t-1)', 'var14(t-1)', 'var15(t-1)', 'var1(t)', 'var2(t)',
       'var3(t)', 'var4(t)', 'var5(t)', 'var6(t)', 'var7(t)', 'var8(t)',
       'var9(t)', 'var10(t)', 'var11(t)', 'var12(t)', 'var13(t)', 'var14(t)',
       'var15(t)', 'def_rk', 'h/a_1', 'surface_0', 'salary', 'points'],
      dtype='object')

In [14]:
# Target variables 

y_train = train['points']
y_test = test['points']

# Predictors, all numeric variables minus target variable
X_train = train.iloc[:,4:-2]
X_test = test.iloc[:,4:-2]

In [90]:
scaler = MinMaxScaler()
scaler.fit_transform(X_train)

array([[ 0.        ,  1.        ,  0.0070922 , ...,  0.        ,
         0.51998093,  0.14457831],
       [ 0.01960784,  0.8335    ,  0.02600473, ...,  0.19142857,
         0.5486886 ,  0.39759036],
       [ 0.21568627,  0.785     ,  0.23799054, ...,  0.21428571,
         0.62250835,  0.5       ],
       ...,
       [ 0.46411765,  0.6547    ,  0.33174941, ...,  0.21428571,
         0.48526466,  0.81325301],
       [ 0.48039216,  0.6695    ,  0.39184397, ...,  0.22857143,
         0.45808298,  0.85542169],
       [ 0.58039216,  0.6414    ,  0.42411348, ...,  0.19142857,
         0.36185026,  0.8253012 ]])

In [16]:
X_test.shape

(63, 33)

In [17]:
X_train.shape

(3439, 33)

In [16]:
y_train.reset_index(inplace=True,drop=True)
X_train.reset_index(inplace=True, drop=True)

In [19]:
lr = LinearRegression()

In [20]:
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [21]:
coeff = pd.DataFrame(X_train.columns)
coeff['coefficients'] = lr.coef_
coeff

             0  coefficients
0    var1(t-1)      0.138881
1    var2(t-1)     -0.076445
2    var3(t-1)     -2.216490
3    var4(t-1)     -1.138667
4    var5(t-1)     -0.035783
5    var6(t-1)     -0.060778
6    var7(t-1)      0.017863
7    var8(t-1)      1.187123
8    var9(t-1)      0.168572
9   var10(t-1)     -0.006700
10  var11(t-1)      0.103015
11  var12(t-1)     -0.152682
12  var13(t-1)     -8.166758
13  var14(t-1)      0.355281
14  var15(t-1)     -0.249924
15     var1(t)     -0.191846
16     var2(t)      0.183973
17     var3(t)      3.646357
18     var4(t)      1.976133
19     var5(t)      0.043293
20     var6(t)      0.304513
21     var7(t)     -0.067347
22     var8(t)     -4.204805
23     var9(t)      0.064687
24    var10(t)     -0.028453
25    var11(t)     -0.232304
26    var12(t)      0.194420
27    var13(t)     14.009809
28    var14(t)     -0.587976
29    var15(t)      0.385734
30      def_rk      0.063934
31       h/a_1      0.385262
32   surface_0     -0.197825

In [22]:
X_train.shape

(3439, 33)

In [23]:
yhat = lr.predict(X_test)

In [24]:
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())

rmse_val = rmse(yhat, y_test)
print("RMSE error is: " + str(rmse_val))

RMSE error is: 3.8973007000451947

In [25]:
results = pd.DataFrame()
results['Player'] = test['player']
#results['score'] = y_test
results['Predicted'] = yhat
results['points'] = test['points']
#results['Week'] = qb[qb['year']==2017]['Week']
#results.groupby('Player').mean()[['score','Predicted']]
results

                            Player  Predicted  points
10            Aaron Jones_reframed  19.034514    15.2
105          Alex Collins_reframed   8.311572    10.5
144           Alfred Blue_reframed   6.304185     3.1
189         Alfred Morris_reframed   6.260747     2.8
209          Alvin Kamara_reframed  41.834977    44.1
337         Austin Ekeler_reframed  12.196285    13.6
364   Benjamin Cunningham_reframed  -4.528588     0.0
410          Bilal Powell_reframed   9.930035     9.2
588           Carlos Hyde_reframed  18.368404    14.2
658         Chase Edmonds_reframed   1.655702     0.1
707           Chris Ivory_reframed   3.768668     1.5
852           Corey Grant_reframed   5.654936     3.7
871           Dalvin Cook_reframed   4.119933     2.0
1031        David Johnson_reframed  18.249695    19.2
1190        Derrick Henry_reframed   4.907325     5.1
1268      Devontae Booker_reframed   5.568824     2.4
1314           Dion Lewis_reframed  14.032705    15.6
1359          Doug Martin_reframed   3.025780     1.1
1418         Duke Johnson_reframed  11.011626    13.6
1596           Frank Gore_reframed   6.703391    13.7
1651      Giovani Bernard_reframed  21.340622    25.6
1702       Isaiah Crowell_reframed   6.889608     1.3
1706            Ito Smith_reframed  14.187899    13.8
1778        Jalen Richard_reframed   9.003633     6.6
1820      Jamaal Williams_reframed   5.518216     2.7
1835         James Conner_reframed  14.664359     9.4
1898          James White_reframed  22.689905    31.2
1961       Javorius Allen_reframed   8.679211     6.7
2001            Jay Ajayi_reframed  12.482467    11.1
2280        Jordan Howard_reframed   8.122661     2.5
...                            ...        ...     ...
2458         Kenyan Drake_reframed   6.025223     2.6
2461      Kerryon Johnson_reframed  13.348564    12.6
2564         Lamar Miller_reframed   7.483784     4.9
2622      Latavius Murray_reframed   5.148542     5.8
2701    LeGarrette Blount_reframed   2.289030     1.2
2746         LeSean McCoy_reframed   7.855329     6.7
2760    Leonard Fournette_reframed   3.560307     4.5
2879       Marshawn Lynch_reframed  20.734276    21.7
2924          Matt Breida_reframed  14.266006    10.1
3031        Melvin Gordon_reframed  25.832235    33.9
3055           Mike Davis_reframed  32.086037    31.4
3085       Mike Gillislee_reframed   3.569757     2.5
3130           Nick Chubb_reframed  19.701699    25.5
3133         Nyheim Hines_reframed  15.445659    28.3
3204        Peyton Barber_reframed   4.596568     4.0
3207      Phillip Lindsay_reframed  16.728406    15.9
3216        Rashaad Penny_reframed   6.120504     4.9
3340            Rod Smith_reframed   4.523028     3.2
3371        Royce Freeman_reframed  15.445913    12.7
3411       Saquon Barkley_reframed  25.025613    22.0
3466          Sony Michel_reframed  18.790724    20.2
3492         Spencer Ware_reframed   2.112744     0.6
3551            TJ Yeldon_reframed  17.535771    24.0
3577          Tarik Cohen_reframed  20.962505    33.4
3667        Tevin Coleman_reframed  12.420014    10.7
3706         Theo Riddick_reframed   6.844322     6.7
3809          Todd Gurley_reframed  26.347579    25.6
3869        Ty Montgomery_reframed  12.074420     9.4
3887        Wayne Gallman_reframed   3.754823     4.3
3909    Wendell Smallwood_reframed  10.566715     8.4

[63 rows x 3 columns]

In [323]:
results.

(300, 3)

In [26]:
results.to_csv('../output/rb_test.csv', index= False)