In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [10]:
te.columns

Index(['Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets', 'Receptions',
       'ReceptionPercentage', 'ReceivingYards', 'ReceivingTouchdowns',
       'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'points', 'year', 'def_ru_rk', 'def_pass_rk'],
      dtype='object')

In [15]:
#te = pd.read_csv('../input/te/dk_te_stats.csv')
#week1 = pd.read_csv('../input/te/fantasy-football-weekly-projections (3).csv')
rb = pd.read_csv('../input/rb/dk_rb_stats.csv')
week1_def = pd.read_csv('../input/defense_2018_projections.csv')

In [3]:
te.tail()

,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,ReceivingLong,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,points,year,def_ru_rk,def_pass_rk
8769,James Hanna,DAL,17,PHI,2,1,50.0,13,0,NaN,...,0,0,0.0,0,0,0,1.3,2017,4,4
8770,Brent Celek,PHI,17,DAL,4,3,75.0,13,0,NaN,...,0,0,0.0,0,0,0,1.3,2017,13,13
8771,Jason Witten,DAL,17,PHI,3,2,66.7,17,0,NaN,...,0,0,0.0,0,0,0,1.7,2017,4,4
8772,Derek Carrier,LAR,17,SF,2,2,100.0,10,0,NaN,...,0,0,0.0,0,0,0,1.0,2017,25,25
8773,Gerald Everett,LAR,17,SF,6,3,50.0,16,0,NaN,...,0,0,0.0,0,1,1,-0.4,2017,25,25

In [4]:
week1.head()

,Rank,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGame,FantasyPoints
0,1,Rob Gronkowski,NE,TE,1,HOU,8.89,5.2,55.6,73.4,...,8.1,14.6,0.0,0.0,0,0,0.0,0.0,11.5,11.54
1,2,Travis Kelce,KC,TE,1,LAC,7.64,5.5,75.0,67.1,...,8.4,11.2,0.0,0.1,0,0,0.0,0.0,9.7,9.72
2,3,Zach Ertz,PHI,TE,1,ATL,9.34,5.4,55.6,60.2,...,6.7,12.0,0.0,0.0,0,0,0.1,0.1,8.8,8.82
3,4,Greg Olsen,CAR,TE,1,DAL,7.87,4.5,50.0,52.4,...,6.5,13.0,0.0,0.0,0,0,0.0,0.0,7.6,7.64
4,5,Delanie Walker,TEN,TE,1,MIA,6.12,4.5,66.7,52.0,...,8.7,13.0,0.0,0.0,0,0,0.0,0.0,7.6,7.60

## TE weekly projections dataframe fetaure engineering

In [ ]:
#week1.drop(['Rank','Position','FantasyPointsPerGame'], axis=1, inplace=True)

#week1['year'] =2018
week1.columns = te.columns[:-2]

indices = []
for idx,player in enumerate(week1['Name']):
    if player not in te['Name'].unique():
        indices.append(idx)

week1.drop(indices, axis=0, inplace=True)
week1.reset_index(inplace=True, drop=True)

In [32]:
te.drop('ReceivingLong', axis=1, inplace=True)

In [30]:
week1.drop('ReceivingLong',axis=1,inplace=True)

In [13]:
week1.shape

(90, 20)

# Weekly Defensive Rankings dataframe feature engineering

In [18]:
week1_def.head()

,Rank,Name,Position,Played,TacklesForLoss,Sacks,QuarterbackHits,Interceptions,FumblesRecovered,Safeties,DefensiveTouchdowns,SpecialTeamsTouchdowns,PointsAllowed,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
Team,,,,,,,,,,,,,,,
JAX,1,Jacksonville Jaguars,DST,16,103,49,113,18,14,0,4,1,268,8.1,129
LAC,2,Los Angeles Chargers,DST,16,93,44,85,17,13,0,4,2,272,7.9,127
LAR,3,Los Angeles Rams,DST,16,82,45,100,17,15,2,3,2,329,7.8,124
PHI,4,Philadelphia Eagles,DST,16,99,39,115,17,14,0,4,2,295,7.7,123
MIN,5,Minnesota Vikings,DST,16,82,42,85,17,12,1,3,1,252,7.0,112

In [ ]:
week1_def.index = week1_def['']
week1_def.drop('Team', axis=1, inplace=True)
week1_def.head()

In [19]:
week1['def_ru_rk'] = list(map(lambda x: week1_def.loc[x]['Rank'], week1['Opponent']))
week1['def_pass_rk'] = list(map(lambda x: week1_def.loc[x]['Rank'], week1['Opponent']))

In [20]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression

In [21]:
#A function that will covert a time series database into a supervised learning database

def series_to_supervised(data, n_in=1, n_out=1, dropnan=True):
    n_vars = 1 if type(data) is list else data.shape[1]
    df = pd.DataFrame(data)
    cols, names = list(), list()
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -1):
            cols.append(df.shift(i))
            names += [('var%d(t-%d)' % (j+1, i)) for j in range(n_vars)]
    # forecast sequence (t, t+1, ... t+n)
    for i in range(0, n_out):
        cols.append(df.shift(-i))
        if i == 0:
            names += [('var%d(t)' % (j+1)) for j in range(n_vars)]
        else:
            names += [('var%d(t+%d)' % (j+1, i)) for j in range(n_vars)]
    # put it all together
    agg = pd.concat(cols, axis=1)
    agg.columns = names
    # drop rows with NaN values
    if dropnan:
        agg.dropna(inplace=True)
    return agg

In [33]:
train  = te
test = week1
#te.shape
week1.shape

(90, 21)

In [27]:
te.columns

Index(['Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets', 'Receptions',
       'ReceptionPercentage', 'ReceivingYards', 'ReceivingTouchdowns',
       'ReceivingYardsPerTarget', 'ReceivingYardsPerReception',
       'RushingAttempts', 'RushingYards', 'RushingYardsPerAttempt',
       'RushingTouchdowns', 'Fumbles', 'FumblesLost', 'points', 'year',
       'def_ru_rk', 'def_pass_rk'],
      dtype='object')

In [345]:
passing = ['Comp','Att','Pct','Yds','Yds/Att','TD','Int']

In [34]:
y_train = train['points']
y_test = test['points']
X_train = train.drop('points',axis=1)
X_test = test.drop('points', axis=1)

In [35]:
X_train = X_train[X_train.columns[4:12]]
X_test = X_test[X_test.columns[4:12]]

In [36]:
X_train.head()

,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts
0,10,6,60.0,85,1,8.5,14.2,0
1,9,5,55.6,73,1,8.1,14.6,0
2,7,6,85.7,59,1,8.4,9.8,1
3,6,6,100.0,60,1,10.0,10.0,0
4,6,5,83.3,53,1,8.8,10.6,0

In [31]:
X_train.columns

Index(['ReceivingTargets', 'Receptions', 'ReceptionPercentage',
       'ReceivingYards', 'ReceivingTouchdowns', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts'],
      dtype='object')

In [37]:
reframed = series_to_supervised(X_train.values.astype('float32'),1,1)

In [38]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [39]:
coeff = pd.DataFrame(X_train.columns)
coeff['coefficients'] = lr.coef_
coeff

                            0  coefficients
0            ReceivingTargets     -0.001944
1                  Receptions     -0.020965
2         ReceptionPercentage      0.000103
3              ReceivingYards      0.101106
4         ReceivingTouchdowns      6.007600
5     ReceivingYardsPerTarget     -0.002486
6  ReceivingYardsPerReception      0.001176
7             RushingAttempts      0.620732

In [40]:
yhat = lr.predict(X_test)
yhat.shape

(90,)

In [35]:
def rmse(predictions, targets):
    return np.sqrt(((predictions - targets) ** 2).mean())

rmse_val = rmse(yhat, y_test)
print("RMSE error is: " + str(rmse_val))

RMSE error is: 0.354183080405

In [41]:
results = pd.DataFrame()
results['Name'] = week1['Name']
results['Predicted'] = yhat
#results.groupby('Player').mean()[['score','Predicted']]
results

                       Name  Predicted
0            Rob Gronkowski  11.514248
1              Travis Kelce   9.669162
2                 Zach Ertz   8.973479
3                Greg Olsen   7.606909
4            Delanie Walker   7.566126
5              Kyle Rudolph   7.177407
6              Jimmy Graham   7.119893
7               Trey Burton   6.802477
8                Jack Doyle   6.729873
9               Evan Engram   6.489279
10             Tyler Eifert   6.431886
11              Jordan Reed   6.204279
12        Ricky Seals-Jones   5.717998
13            George Kittle   5.350448
14              David Njoku   5.334121
15               Jared Cook   5.222789
16          Benjamin Watson   5.106868
17             Charles Clay   5.008309
18  Austin Seferian-Jenkins   5.074673
19                OJ Howard   4.971255
20            Cameron Brate   4.561045
21               Eric Ebron   4.509021
22            Antonio Gates   4.248906
23            Austin Hooper   4.150612
24           Vance McDonald   3.878042
25             Ryan Griffin   3.696894
26             Nick Vannett   3.378736
27              Jesse James   3.336216
28             Vernon Davis   3.102346
29             Luke Willson   3.004595
..                      ...        ...
60      James O'Shaughnessy   0.575386
61             Adam Shaheen   0.525001
62             Logan Thomas   0.512697
63            Derek Carrier   0.446861
64          Michael Roberts   0.438948
65             Eric Saubert   0.376081
66                Khari Lee   0.388278
67                CJ Uzomah   0.388239
68            Orson Charles   0.388395
69                Cole Wick   0.358043
70               Ben Koyack   0.345515
71          Jeremy Sprinkle   0.309703
72           Antony Auclair   0.299593
73          Darrell Daniels   0.287074
74           Ben Braunecker   0.279527
75            Cethan Carter   0.271746
76            Logan Paulsen   0.228857
77              Gabe Holmes   0.231323
78             Luke Stocker   0.218766
79            Hakeem Valles   0.218707
80           Chris Manhertz   0.208752
81           Xavier Grimble   0.178265
82              Ross Travis   0.180711
83          Richard Rodgers   0.011238
84     Michael Hoomanawanui   0.011238
85         Demetrius Harris   0.011238
86              Sean Culkin   0.011238
87             Matt LaCosse   0.011238
88             Ryan Malleck   0.011238
89               Ed Dickson   0.011238

[90 rows x 2 columns]

In [323]:
results.shape

(300, 3)

In [42]:
results.to_csv('2018_week1_te.csv', index= False)