## Location Dataframe

In [633]:
"""This is a program designed to add the location and surface type the DraftKings historical stats dataframe.
for every players game and a home or away attribute and the whether the game was played on grass or turf surface"""

'This is a program designed to add the location and surface type the DraftKings historical stats dataframe.\nfor every players game and a home or away attribute and the whether the game was played on grass or turf surface'

In [6]:
# Import packages

import pandas as pd
import numpy as np
import http.client, urllib.request, urllib.parse, urllib.error, base64
import json
from bs4 import BeautifulSoup
import requests
import re

In [573]:
# ead in the original DraftKings dataframe

qb = pd.read_csv('input/qb/dk_stas_sal.csv')

qb.tail()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
1795,18525,Joe Callahan,GB,17,DET,5,7,71.4,11,1.6,...,0,74.11,0,0,0.0,0,0.44,4400,2017,21
1796,18811,Mitch Trubisky,CHI,17,MIN,20,36,55.6,178,4.9,...,0,68.98,1,2,2.0,0,7.32,4700,2017,1
1797,18868,Deshone Kizer,CLE,17,PIT,16,30,53.3,314,10.5,...,1,98.47,6,61,10.2,0,28.66,4400,2017,6
1798,18890,Patrick Mahomes,KC,17,DEN,22,35,62.9,284,8.1,...,1,76.37,7,10,1.4,0,11.36,4800,2017,5
1799,19238,Taysom Hill,NO,17,TB,0,0,0.0,0,0.0,...,0,0.00,0,0,0.0,0,0.00,4500,2017,31

# Create a list of urls from Pro Football Reference.com which contain the location of every game in the 2015, 2016, 2-17 seasons

In [7]:
url1 ='https://www.pro-football-reference.com/years/2015/games.htm'

In [8]:
url2 =  'https://www.pro-football-reference.com/years/2016/games.htm'

In [9]:
url3 = 'https://www.pro-football-reference.com/years/2017/games.htm'

In [71]:
page = requests.get(url3)

page

In [72]:
# Use BeautifulSoup to retreive data the data from Pro Footbal Reference.com 

soup = BeautifulSoup(page.text,'html.parser')

weeks = []  
for tr in soup.find_all('tr'):
    weeks.append(tr.text)

In [75]:
# Remove any lines that dont describe weekly game

try:
    weeks.remove('\nWeek\nDay\nDate\nTime\nWinner/tie\n\nLoser/tie\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n')
except:
    Error

In [61]:
weeks = weeks[0:-12]

weeks

['1ThuSeptember 88:40PMDenver BroncosCarolina Panthersboxscore212030733331',
 '1SunSeptember 111:04PMBaltimore RavensBuffalo Billsboxscore13730811600',
 '1SunSeptember 111:04PMGreen Bay Packers@Jacksonville Jaguarsboxscore272329403481',
 '1SunSeptember 111:05PMPhiladelphia EaglesCleveland Brownsboxscore291040302881',
 '1SunSeptember 111:05PMHouston TexansChicago Bearsboxscore231434412581',
 '1SunSeptember 111:05PMKansas City ChiefsSan Diego Chargersboxscore332741313880',
 '1SunSeptember 111:05PMTampa Bay Buccaneers@Atlanta Falconsboxscore312437113740',
 '1SunSeptember 111:05PMMinnesota Vikings@Tennessee Titansboxscore251630103163',
 '1SunSeptember 111:05PMOakland Raiders@New Orleans Saintsboxscore353448605071',
 '1SunSeptember 111:05PMCincinnati Bengals@New York Jetsboxscore232238113401',
 '1SunSeptember 114:08PMSeattle SeahawksMiami Dolphinsboxscore121035222140',
 '1SunSeptember 114:27PMNew York Giants@Dallas Cowboysboxscore201931613280',
 '1SunSeptember 114:27PMDetroit Lions@Indianapolis Coltsboxscore393544804500',
 '1SunSeptember 118:30PMNew England Patriots@Arizona Cardinalsboxscore232136323440',
 '1MonSeptember 127:11PMPittsburgh Steelers@Washington Redskinsboxscore381643713842',
 '1MonSeptember 1210:20PMSan Francisco 49ersLos Angeles Ramsboxscore28032011852',
 '2ThuSeptember 158:26PMNew York Jets@Buffalo Billsboxscore373149313931',
 '2SunSeptember 181:02PMTennessee Titans@Detroit Lionsboxscore161536313751',
 '2SunSeptember 181:02PMPittsburgh SteelersCincinnati Bengalsboxscore241637424122',
 '2SunSeptember 181:02PMBaltimore Ravens@Cleveland Brownsboxscore252038223872',
 '2SunSeptember 181:02PMHouston TexansKansas City Chiefsboxscore191235122913',
 '2SunSeptember 181:02PMNew England PatriotsMiami Dolphinsboxscore312446314574',
 '2SunSeptember 181:03PMDallas Cowboys@Washington Redskinsboxscore272338014321',
 '2SunSeptember 181:03PMNew York GiantsNew Orleans Saintsboxscore161341732880',
 '2SunSeptember 181:03PMCarolina PanthersSan Francisco 49ersboxscore462752943023',
 '2SunSeptember 181:05PMArizona CardinalsTampa Bay Buccaneersboxscore40741603065',
 '2SunSeptember 184:08PMLos Angeles RamsSeattle Seahawksboxscore9328303061',
 '2SunSeptember 184:25PMDenver BroncosIndianapolis Coltsboxscore342040012532',
 '2SunSeptember 184:25PMSan Diego ChargersJacksonville Jaguarsboxscore381435713883',
 '2SunSeptember 184:25PMAtlanta Falcons@Oakland Raidersboxscore352852814540',
 '2SunSeptember 188:32PMMinnesota VikingsGreen Bay Packersboxscore171428412633',
 '2MonSeptember 198:30PMPhiladelphia Eagles@Chicago Bearsboxscore291428002843',
 '3ThuSeptember 228:26PMNew England PatriotsHouston Texansboxscore27028202843',
 '3SunSeptember 251:02PMMinnesota Vikings@Carolina Panthersboxscore221021103063',
 '3SunSeptember 251:02PMGreen Bay PackersDetroit Lionsboxscore342732404181',
 '3SunSeptember 251:02PMWashington Redskins@New York Giantsboxscore292740314573',
 '3SunSeptember 251:02PMDenver Broncos@Cincinnati Bengalsboxscore291735513322',
 '3SunSeptember 251:02PMBuffalo BillsArizona Cardinalsboxscore331829713485',
 '3SunSeptember 251:02PMMiami DolphinsCleveland Brownsboxscore302442634301',
 '3SunSeptember 251:02PMOakland Raiders@Tennessee Titansboxscore171036813933',
 '3SunSeptember 251:02PMBaltimore Ravens@Jacksonville Jaguarsboxscore191728332163',
 '3SunSeptember 254:05PMLos Angeles Rams@Tampa Bay Buccaneersboxscore373232024722',
 '3SunSeptember 254:05PMSeattle SeahawksSan Francisco 49ersboxscore371841822541',
 '3SunSeptember 254:25PMPhiladelphia EaglesPittsburgh Steelersboxscore34342602512',
 '3SunSeptember 254:25PMIndianapolis ColtsSan Diego Chargersboxscore262241023523',
 '3SunSeptember 254:26PMKansas City ChiefsNew York Jetsboxscore24329313058',
 '3SunSeptember 258:31PMDallas CowboysChicago Bearsboxscore311744713902',
 '3MonSeptember 268:30PMAtlanta Falcons@New Orleans Saintsboxscore453244204742',
 '4ThuSeptember 298:26PMCincinnati BengalsMiami Dolphinsboxscore22736202222',
 '4SunOctober 29:35AMJacksonville JaguarsIndianapolis Coltsboxscore302733102841',
 '4SunOctober 21:00PMChicago BearsDetroit Lionsboxscore171440802632',
 '4SunOctober 21:02PMHouston TexansTennessee Titansboxscore272035923201',
 '4SunOctober 21:02PMOakland Raiders@Baltimore Ravensboxscore282726114121',
 '4SunOctober 21:02PMBuffalo Bills@New England Patriotsboxscore16037802771',
 '4SunOctober 21:03PMSeattle Seahawks@New York Jetsboxscore271735403053',
 '4SunOctober 21:04PMAtlanta FalconsCarolina Panthersboxscore483357113782',
 '4SunOctober 21:05PMWashington RedskinsCleveland Brownsboxscore312030113803',
 '4SunOctober 24:05PMDenver Broncos@Tampa Bay Buccaneersboxscore27730702153',
 '4SunOctober 24:25PMDallas Cowboys@San Francisco 49ersboxscore241742802951',
 '4SunOctober 24:25PMNew Orleans Saints@San Diego Chargersboxscore353427523463',
 '4SunOctober 24:25PMLos Angeles Rams@Arizona Cardinalsboxscore171328814205',
 '4SunOctober 28:30PMPittsburgh SteelersKansas City Chiefsboxscore431443603572',
 '4MonOctober 38:35PMMinnesota VikingsNew York Giantsboxscore241036603392',
 '5ThuOctober 68:27PMArizona Cardinals@San Francisco 49ersboxscore332128802863',
 '5SunOctober 91:02PMNew England Patriots@Cleveland Brownsboxscore331350102621',
 '5SunOctober 91:02PMDetroit LionsPhiladelphia Eaglesboxscore242324413462',
 '5SunOctober 91:02PMIndianapolis ColtsChicago Bearsboxscore292339605221',
 '5SunOctober 91:02PMPittsburgh SteelersNew York Jetsboxscore311343613160',
 '5SunOctober 91:02PMTennessee Titans@Miami Dolphinsboxscore301739802002',
 '5SunOctober 91:03PMWashington Redskins@Baltimore Ravensboxscore161031023061',
 '5SunOctober 91:05PMMinnesota VikingsHouston Texansboxscore311335102141',
 '5SunOctober 94:05PMAtlanta Falcons@Denver Broncosboxscore231637212671',
 '5SunOctober 94:25PMDallas CowboysCincinnati Bengalsboxscore281440213450',
 '5SunOctober 94:25PMBuffalo Bills@Los Angeles Ramsboxscore301930503453',
 '5SunOctober 94:25PMOakland RaidersSan Diego Chargersboxscore343138914234',
 '5SunOctober 98:30PMGreen Bay PackersNew York Giantsboxscore231640622211',
 '5MonOctober 108:04PMTampa Bay Buccaneers@Carolina Panthersboxscore171431504144',
 '6ThuOctober 138:25PMSan Diego ChargersDenver Broncosboxscore211326523042',
 '6SunOctober 161:02PMMiami DolphinsPittsburgh Steelersboxscore301547402972',
 '6SunOctober 161:02PMNew England PatriotsCincinnati Bengalsboxscore351743703570',
 '6SunOctober 161:02PMBuffalo BillsSan Francisco 49ersboxscore451649223001',
 '6SunOctober 161:02PMTennessee TitansCleveland Brownsboxscore282640713410',
 '6SunOctober 161:02PMNew York GiantsBaltimore Ravensboxscore272343533910',
 '6SunOctober 161:02PMDetroit LionsLos Angeles Ramsboxscore312834803871',
 '6SunOctober 161:02PMJacksonville Jaguars@Chicago Bearsboxscore171631723890',
 '6SunOctober 161:03PMWashington RedskinsPhiladelphia Eaglesboxscore272049312390',
 '6SunOctober 161:03PMNew Orleans SaintsCarolina Panthersboxscore413852314062',
 '6SunOctober 164:05PMKansas City Chiefs@Oakland Raidersboxscore261040602852',
 '6SunOctober 164:25PMDallas Cowboys@Green Bay Packersboxscore301642423724',
 '6SunOctober 164:26PMSeattle SeahawksAtlanta Falconsboxscore262433303622',
 '6SunOctober 168:32PMHouston TexansIndianapolis Coltsboxscore262341413921',
 '6MonOctober 178:30PMArizona CardinalsNew York Jetsboxscore28339602302',
 '7ThuOctober 208:26PMGreen Bay PackersChicago Bearsboxscore261040611892',
 '7SunOctober 239:31AMNew York Giants@Los Angeles Ramsboxscore171023213454',
 '7SunOctober 231:02PMOakland Raiders@Jacksonville Jaguarsboxscore331634403443',
 '7SunOctober 231:02PMPhiladelphia EaglesMinnesota Vikingsboxscore211023942824',
 '7SunOctober 231:02PMDetroit LionsWashington Redskinsboxscore201734404132',
 '7SunOctober 231:02PMIndianapolis Colts@Tennessee Titansboxscore342642203311',
 '7SunOctober 231:02PMCincinnati BengalsCleveland Brownsboxscore311755913522',
 '7SunOctober 231:02PMMiami DolphinsBuffalo Billsboxscore282545402670',
 '7SunOctober 231:03PMKansas City ChiefsNew Orleans Saintsboxscore272132604632',
 '7SunOctober 231:04PMNew York JetsBaltimore Ravensboxscore241634422453',
 '7SunOctober 234:05PMSan Diego Chargers@Atlanta Falconsboxscore333042623861',
 '7SunOctober 234:05PMTampa Bay Buccaneers@San Francisco 49ersboxscore341751312733',
 '7SunOctober 234:25PMNew England Patriots@Pittsburgh Steelersboxscore271636223751',
 '7SunOctober 238:30PMSeattle Seahawks@Arizona Cardinalsboxscore6625704430',
 '7MonOctober 248:30PMDenver BroncosHouston Texansboxscore27934702712',
 '8ThuOctober 278:26PMTennessee TitansJacksonville Jaguarsboxscore362249403701',
 '8SunOctober 308:36AMWashington Redskins@Cincinnati Bengalsboxscore272754614152',
 '8SunOctober 3012:47PMCarolina PanthersArizona Cardinalsboxscore302034913402',
 '8SunOctober 301:02PMNew England Patriots@Buffalo Billsboxscore412535703760',
 '8SunOctober 301:02PMOakland Raiders@Tampa Bay Buccaneersboxscore302462612700',
 '8SunOctober 301:02PMKansas City Chiefs@Indianapolis Coltsboxscore301442202772',
 '8SunOctober 301:02PMNew York Jets@Cleveland Brownsboxscore312839304072',
 '8SunOctober 301:03PMNew Orleans SaintsSeattle Seahawksboxscore252037513591',
 '8SunOctober 301:03PMHouston TexansDetroit Lionsboxscore201326912890',
 '8SunOctober 304:05PMDenver BroncosSan Diego Chargersboxscore271932433693',
 '8SunOctober 304:25PMAtlanta FalconsGreen Bay Packersboxscore333236703310',
 '8SunOctober 308:31PMDallas CowboysPhiladelphia Eaglesboxscore292346012911',
 '8MonOctober 318:31PMChicago BearsMinnesota Vikingsboxscore201040302580',
 '9ThuNovember 38:25PMAtlanta Falcons@Tampa Bay Buccaneersboxscore432846113962',
 '9SunNovember 61:00PMBaltimore RavensPittsburgh Steelersboxscore211427412771',
 '9SunNovember 61:00PMNew York GiantsPhiladelphia Eaglesboxscore282330224432',
 '9SunNovember 61:00PMMiami DolphinsNew York Jetsboxscore272327403312',
 '9SunNovember 61:00PMKansas City ChiefsJacksonville Jaguarsboxscore191423104494',
 '9SunNovember 61:00PMDallas Cowboys@Cleveland Brownsboxscore351042302220',
 '9SunNovember 61:00PMDetroit Lions@Minnesota Vikingsboxscore221631113370',
 '9SunNovember 64:05PMNew Orleans Saints@San Francisco 49ersboxscore412357104864',
 '9SunNovember 64:05PMCarolina Panthers@Los Angeles Ramsboxscore131024403391',
 '9SunNovember 64:25PMSan Diego ChargersTennessee Titansboxscore433547603933',
 '9SunNovember 64:25PMIndianapolis Colts@Green Bay Packersboxscore312635524051',
 '9SunNovember 68:30PMOakland RaidersDenver Broncosboxscore302039702992',
 '9MonNovember 78:30PMSeattle SeahawksBuffalo Billsboxscore312527804251',
 '10ThuNovember 108:25PMBaltimore RavensCleveland Brownsboxscore28739621443',
 '10SunNovember 131:00PMKansas City Chiefs@Carolina Panthersboxscore201725613412',
 '10SunNovember 131:00PMTennessee TitansGreen Bay Packersboxscore472544604023',
 '10SunNovember 131:00PMWashington RedskinsMinnesota Vikingsboxscore262038813311',
 '10SunNovember 131:00PMHouston Texans@Jacksonville Jaguarsboxscore242127303272',
 '10SunNovember 131:00PMTampa Bay BuccaneersChicago Bearsboxscore361036012834',
 '10SunNovember 131:00PMDenver Broncos@New Orleans Saintsboxscore252333723734',
 '10SunNovember 131:00PMLos Angeles Rams@New York Jetsboxscore9628002961',
 '10SunNovember 131:00PMPhiladelphia EaglesAtlanta Falconsboxscore241542913031',
 '10SunNovember 134:05PMMiami Dolphins@San Diego Chargersboxscore312433713794',
 '10SunNovember 134:25PMDallas Cowboys@Pittsburgh Steelersboxscore353042214480',
 '10SunNovember 134:25PMArizona CardinalsSan Francisco 49ersboxscore232044342811',
 '10SunNovember 138:30PMSeattle Seahawks@New England Patriotsboxscore312442003852',
 '10MonNovember 148:30PMNew York GiantsCincinnati Bengalsboxscore212035122641',
 '11ThuNovember 178:25PMCarolina PanthersNew Orleans Saintsboxscore232022303712',
 '11SunNovember 201:00PMDetroit LionsJacksonville Jaguarsboxscore261927722853',
 '11SunNovember 201:00PMNew York GiantsChicago Bearsboxscore221632903151',
 '11SunNovember 201:00PMMinnesota VikingsArizona Cardinalsboxscore302421712902',
 '11SunNovember 201:00PMIndianapolis ColtsTennessee Titansboxscore241732713510',
 '11SunNovember 201:00PMDallas CowboysBaltimore Ravensboxscore271741703680',
 '11SunNovember 201:00PMBuffalo Bills@Cincinnati Bengalsboxscore161234213002',
 '11SunNovember 201:00PMTampa Bay Buccaneers@Kansas City Chiefsboxscore191744213432',
 '11SunNovember 201:00PMPittsburgh Steelers@Cleveland Brownsboxscore24931302092',
 '11SunNovember 204:05PMMiami Dolphins@Los Angeles Ramsboxscore141024012271',
 '11SunNovember 204:25PMNew England Patriots@San Francisco 49ersboxscore301744402990',
 '11SunNovember 204:25PMSeattle SeahawksPhiladelphia Eaglesboxscore261543903082',
 '11SunNovember 208:30PMWashington RedskinsGreen Bay Packersboxscore422451504242',
 '11MonNovember 218:30PMOakland RaidersHouston Texansboxscore272032513542',
 '12ThuNovember 2412:30PMDetroit LionsMinnesota Vikingsboxscore161330803061',
 '12ThuNovember 244:30PMDallas CowboysWashington Redskinsboxscore312635305050',
 '12ThuNovember 248:30PMPittsburgh Steelers@Indianapolis Coltsboxscore28736903102',
 '12SunNovember 271:00PMSan Diego Chargers@Houston Texansboxscore211330213534',
 '12SunNovember 271:00PMNew Orleans SaintsLos Angeles Ramsboxscore492155512472',
 '12SunNovember 271:00PMTennessee Titans@Chicago Bearsboxscore272137504112',
 '12SunNovember 271:00PMMiami DolphinsSan Francisco 49ersboxscore312435804752',
 '12SunNovember 271:00PMBaltimore RavensCincinnati Bengalsboxscore191431113252',
 '12SunNovember 271:00PMAtlanta FalconsArizona Cardinalsboxscore381936013321',
 '12SunNovember 271:00PMBuffalo BillsJacksonville Jaguarsboxscore282130403010',
 '12SunNovember 271:00PMNew York Giants@Cleveland Brownsboxscore271329613433',
 '12SunNovember 274:05PMTampa Bay BuccaneersSeattle Seahawksboxscore14533822453',
 '12SunNovember 274:25PMOakland RaidersCarolina Panthersboxscore353236623582',
 '12SunNovember 274:25PMNew England Patriots@New York Jetsboxscore221737703332',
 '12SunNovember 278:30PMKansas City Chiefs@Denver Broncosboxscore302727304641',
 '12MonNovember 288:30PMGreen Bay Packers@Philadelphia Eaglesboxscore271338702921',
 '13ThuDecember 18:25PMDallas Cowboys@Minnesota Vikingsboxscore171526423181',
 '13SunDecember 41:00PMNew England PatriotsLos Angeles Ramsboxscore261040201622',
 '13SunDecember 41:00PMGreen Bay PackersHouston Texansboxscore211330913071',
 '13SunDecember 41:00PMDetroit Lions@New Orleans Saintsboxscore281342203693',
 '13SunDecember 41:00PMChicago BearsSan Francisco 49ersboxscore26632611470',
 '13SunDecember 41:00PMDenver Broncos@Jacksonville Jaguarsboxscore201020603333',
 '13SunDecember 41:00PMBaltimore RavensMiami Dolphinsboxscore38649622773',
 '13SunDecember 41:00PMCincinnati BengalsPhiladelphia Eaglesboxscore321441223593',
 '13SunDecember 41:00PMKansas City Chiefs@Atlanta Falconsboxscore292838914181',
 '13SunDecember 44:05PMOakland RaidersBuffalo Billsboxscore382439903822',
 '13SunDecember 44:25PMArizona CardinalsWashington Redskinsboxscore312336903332',
 '13SunDecember 44:25PMTampa Bay Buccaneers@San Diego Chargersboxscore282134913302',
 '13SunDecember 44:25PMPittsburgh SteelersNew York Giantsboxscore241438922342',
 '13SunDecember 48:30PMSeattle SeahawksCarolina Panthersboxscore40753412712',
 '13MonDecember 58:30PMIndianapolis Colts@New York Jetsboxscore411042112503',
 '14ThuDecember 88:25PMKansas City ChiefsOakland Raidersboxscore211332332440',
 '14SunDecember 111:00PMMinnesota Vikings@Jacksonville Jaguarsboxscore251637713150',
 '14SunDecember 111:00PMCincinnati Bengals@Cleveland Brownsboxscore231036002541',
 '14SunDecember 111:00PMWashington Redskins@Philadelphia Eaglesboxscore272233413832',
 '14SunDecember 111:00PMPittsburgh Steelers@Buffalo Billsboxscore272046032751',
 '14SunDecember 111:00PMMiami DolphinsArizona Cardinalsboxscore262331433004',
 '14SunDecember 111:00PMCarolina PanthersSan Diego Chargersboxscore281627212785',
 '14SunDecember 111:00PMDetroit LionsChicago Bearsboxscore201732322960',
 '14SunDecember 111:00PMTennessee TitansDenver Broncosboxscore131025303482',
 '14SunDecember 111:00PMHouston Texans@Indianapolis Coltsboxscore221731613483',
 '14SunDecember 114:05PMNew York Jets@San Francisco 49ersboxscore231740413640',
 '14SunDecember 114:25PMAtlanta Falcons@Los Angeles Ramsboxscore421428603125',
 '14SunDecember 114:25PMTampa Bay BuccaneersNew Orleans Saintsboxscore161127002943',
 '14SunDecember 114:25PMGreen Bay PackersSeattle Seahawksboxscore381033003546',
 '14SunDecember 118:30PMNew York GiantsDallas Cowboysboxscore10726032603',
 '14MonDecember 128:30PMNew England PatriotsBaltimore Ravensboxscore302349633481',
 '15ThuDecember 158:25PMSeattle SeahawksLos Angeles Ramsboxscore24329911830',
 '15SatDecember 178:25PMMiami Dolphins@New York Jetsboxscore341330313604',
 '15SunDecember 181:00PMGreen Bay Packers@Chicago Bearsboxscore302745104494',
 '15SunDecember 181:00PMIndianapolis Colts@Minnesota Vikingsboxscore34641102823',
 '15SunDecember 181:00PMPittsburgh Steelers@Cincinnati Bengalsboxscore242038202221',
 '15SunDecember 181:00PMBaltimore RavensPhiladelphia Eaglesboxscore272634023281',
 '15SunDecember 181:00PMHouston TexansJacksonville Jaguarsboxscore212038721501',
 '15SunDecember 181:00PMTennessee Titans@Kansas City Chiefsboxscore191738933161',
 '15SunDecember 181:00PMBuffalo BillsCleveland Brownsboxscore331345102690',
 '15SunDecember 181:00PMNew York GiantsDetroit Lionsboxscore17630003242',
 '15SunDecember 184:05PMAtlanta FalconsSan Francisco 49ersboxscore411355012721',
 '15SunDecember 184:05PMNew Orleans Saints@Arizona Cardinalsboxscore484148814252',
 '15SunDecember 184:25PMNew England Patriots@Denver Broncosboxscore16331303093',
 '15SunDecember 184:25PMOakland Raiders@San Diego Chargersboxscore191634522632',
 '15SunDecember 188:30PMDallas CowboysTampa Bay Buccaneersboxscore262044912764',
 '15MonDecember 198:30PMCarolina Panthers@Washington Redskinsboxscore261543803353',
 '16ThuDecember 228:25PMPhiladelphia EaglesNew York Giantsboxscore241928614703',
 '16SatDecember 241:00PMCleveland BrownsSan Diego Chargersboxscore201725103561',
 '16SatDecember 241:00PMJacksonville JaguarsTennessee Titansboxscore381741512631',
 '16SatDecember 241:00PMWashington Redskins@Chicago Bearsboxscore412147804585',
 '16SatDecember 241:00PMAtlanta Falcons@Carolina Panthersboxscore331640803022',
 '16SatDecember 241:00PMNew England PatriotsNew York Jetsboxscore41332502394',
 '16SatDecember 241:00PMGreen Bay PackersMinnesota Vikingsboxscore382534804462',
 '16SatDecember 241:00PMMiami Dolphins@Buffalo Billsboxscore343149415890',
 '16SatDecember 244:05PMOakland RaidersIndianapolis Coltsboxscore332546303903',
 '16SatDecember 244:25PMArizona Cardinals@Seattle Seahawksboxscore343137013911',
 '16SatDecember 244:25PMSan Francisco 49ers@Los Angeles Ramsboxscore222132321772',
 '16SatDecember 244:25PMNew Orleans SaintsTampa Bay Buccaneersboxscore312441703492',
 '16SatDecember 248:25PMHouston TexansCincinnati Bengalsboxscore121025002941',
 '16SunDecember 254:30PMPittsburgh SteelersBaltimore Ravensboxscore312740623681',
 '16SunDecember 258:30PMKansas City ChiefsDenver Broncosboxscore331048412463',
 '16MonDecember 268:30PMDallas CowboysDetroit Lionsboxscore422137503192',
 '17SunJanuary 11:00PMPhiladelphia EaglesDallas Cowboysboxscore271334601952',
 '17SunJanuary 11:00PMTampa Bay BuccaneersCarolina Panthersboxscore171630023353',
 '17SunJanuary 11:00PMNew England Patriots@Miami Dolphinsboxscore351439602802',
 '17SunJanuary 11:00PMNew York JetsBuffalo Billsboxscore301032902303',
 '17SunJanuary 11:00PMPittsburgh SteelersCleveland Brownsboxscore272431214374',
 '17SunJanuary 11:00PMMinnesota VikingsChicago Bearsboxscore381037413235',
 '17SunJanuary 11:00PMTennessee TitansHouston Texansboxscore241723612891',
 '17SunJanuary 11:00PMIndianapolis ColtsJacksonville Jaguarsboxscore242038424702',
 '17SunJanuary 11:00PMCincinnati BengalsBaltimore Ravensboxscore271037103352',
 '17SunJanuary 14:25PMNew York Giants@Washington Redskinsboxscore191033202843',
 '17SunJanuary 14:25PMSeattle Seahawks@San Francisco 49ersboxscore252337602532',
 '17SunJanuary 14:25PMArizona Cardinals@Los Angeles Ramsboxscore44634421233',

In [62]:
# Split string a first non digit and append to week list

week =[] 
for row in weeks:
    week.append(int(re.split(r'(\d+)', row)[1]))

In [63]:
game =[]
for td in soup.find_all('td'):
    game.append(td.text)

In [64]:
home = []
away =[]
for idx,val in enumerate(game):
    if val == '':
        home.append(game[idx-1])
        away.append(game[idx+1])
    elif val =='@':
        home.append(game[idx+1])
        away.append(game[idx-1])

In [66]:
location = pd.DataFrame(columns = ['week','home','away'])

location ['week'] = week
location['home']=home[0:256]
location['away']=away[0:256]

location.shape

(256, 3)

In [67]:
location['home'] = location['home'].apply(lambda x: x[0:3].upper())
location['away'] = location['away'].apply(lambda x: x[0:3].upper())
location.tail()

     week home away
251    17  LOS  ARI
252    17  DEN  OAK
253    17  SAN  KAN
254    17  ATL  NEW
255    17  DET  GRE

In [69]:
loc_16 = location

In [36]:
loc_15 = location

In [70]:
loc_16['year']=2016

In [65]:
loc_15['year'] = 2015

In [563]:
team_dict = {'NEW':'NE',
            'GRE':'GB',
            'TAM':'TB',
            'KAN':'KC',
            'SAN':'SD',
            'ST.':'STL'}

location = location.replace({"home": team_dict})
location.head()

   week home away
0     1   NE  KAN
1     1  CLE  PIT
2     1  CIN  BAL
3     1  WAS  PHI
4     1  DET  ARI

In [566]:
location.index = location['home']
location[0:33]

      week home away
home
NE       1   NE  KAN
CLE      1  CLE  PIT
CIN      1  CIN  BAL
WAS      1  WAS  PHI
DET      1  DET  ARI
HOU      1  HOU  JAC
TEN      1  TEN  OAK
CHI      1  CHI  ATL
BUF      1  BUF  NEW
LOS      1  LOS  IND
SD       1   SD  CAR
GB       1   GB  SEA
DAL      1  DAL  NEW
MIN      1  MIN  NEW
DEN      1  DEN  LOS
CIN      2  CIN  HOU
KC       2   KC  PHI
IND      2  IND  ARI
NE       2   NE  NEW
CAR      2  CAR  BUF
PIT      2  PIT  MIN
TB       2   TB  CHI
BAL      2  BAL  CLE
JAC      2  JAC  TEN
LOS      2  LOS  MIA
OAK      2  OAK  NEW
DEN      2  DEN  DAL
LOS      2  LOS  WAS
SEA      2  SEA  SAN
ATL      2  ATL  GRE
NE       2   NE  DET
SD       3   SD  LOS
JAC      3  JAC  BAL

In [5]:
location.to_csv('inpout/location.csv', undex=False)

NameError: name 'location' is not defined

In [575]:
temp = qb[qb['year']==2017]

In [576]:
temp.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
1200,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,1,70.96,0,0,0.0,0,7.84,5500,2017,12
1201,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,0,116.11,3,11,3.7,0,20.94,6900,2017,7
1202,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,3,53.12,1,2,2.0,0,11.92,4300,2017,21
1203,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,1,86.51,7,21,3.0,0,20.54,6000,2017,8
1204,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,1,95.02,3,-8,-2.7,0,16.72,7000,2017,24

In [578]:
week1 = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [468]:
qb_stats = ['week1',
'week2',
'week3',
'week4',
'week5',
'week6',
'week7',
'week8',
'week9',
'week10',
'week11',
'week12',
'week13',
'week14',
'week15',
'week16',
'week17']

In [476]:
for row in qb_stats:
    print(int(row[4:]))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17

In [395]:
loc_df

     week home away
240    17  CHI  DET
241    17  IND  TEN
242    17  ATL  NEW
243    17  MIA  NEW
244    17  CIN  BAL
245    17  HOU  JAC
246    17  CLE  PIT
247    17  BUF  NEW
248    17  DAL  WAS
249    17   NE  PHI
250    17  DEN  SAN
251    17   SD  ST.
252    17  CAR  TAM
253    17  ARI  SEA
254    17   KC  OAK
255    17   GB  MIN

In [480]:
for row in qb_stats:
    loc_df = location[location['week']==int(row[4:])]
loc_df.shape

home_list = []
for team in '{}'['Team'].format(row):
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

TypeError: string indices must be integers

In [612]:
location[location['week']==17]
loc_df.shape

home_list = []
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')


week17['h/a'] = home_list


week17.head()

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
1762,611,Joe Flacco,BAL,17,CIN,25,47,53.2,203,4.3,...,69.73,0,0,0.0,0,15.12,6300,2017,12,away
1763,732,Matt Ryan,ATL,17,CAR,28,45,62.2,317,7.0,...,90.69,3,14,4.7,0,21.08,5300,2017,14,home
1764,4314,Tom Brady,NE,17,NYJ,18,37,48.6,190,5.1,...,82.04,0,0,0.0,0,15.60,4600,2017,24,home
1765,4737,Drew Stanton,ARI,17,SEA,15,34,44.1,145,4.3,...,54.17,1,-1,-1.0,0,8.70,4500,2017,8,away
1766,4932,Eli Manning,NYG,17,WAS,10,28,35.7,132,4.7,...,48.51,3,-4,-1.3,0,7.88,4400,2017,16,away

In [613]:
qb_2017=pd.concat([qb_2017,week17])

qb_2017.tail()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
1795,18525,Joe Callahan,GB,17,DET,5,7,71.4,11,1.6,...,74.11,0,0,0.0,0,0.44,4400,2017,21,away
1796,18811,Mitch Trubisky,CHI,17,MIN,20,36,55.6,178,4.9,...,68.98,1,2,2.0,0,7.32,4700,2017,1,away
1797,18868,Deshone Kizer,CLE,17,PIT,16,30,53.3,314,10.5,...,98.47,6,61,10.2,0,28.66,4400,2017,6,away
1798,18890,Patrick Mahomes,KC,17,DEN,22,35,62.9,284,8.1,...,76.37,7,10,1.4,0,11.36,4800,2017,5,away
1799,19238,Taysom Hill,NO,17,TB,0,0,0.0,0,0.0,...,0.00,0,0,0.0,0,0.00,4500,2017,31,away

In [531]:

qb_2016.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
600,611,Joe Flacco,BAL,1,BUF,22,33,66.7,258,7.8,...,100.32,4,-3,-0.8,0,13.02,6700,2016,10,away
601,732,Matt Ryan,ATL,1,TB,27,39,69.2,334,8.6,...,112.55,3,10,3.3,0,27.36,7100,2016,17,home
602,2428,Carson Palmer,ARI,1,NE,24,37,64.9,271,7.3,...,104.67,2,1,0.5,0,18.94,7100,2016,6,away
603,2593,Aaron Rodgers,GB,1,JAX,20,34,58.8,199,5.9,...,95.10,4,16,4.0,1,23.56,8500,2016,8,away
604,3807,Ben Roethlisberger,PIT,1,WAS,27,37,73.0,300,8.1,...,112.44,1,-2,-2.0,0,25.80,7800,2016,27,home

In [583]:
qb_2017= pd.concat([week1,week2])
qb_2017.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
1200,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,70.96,0,0,0.0,0,7.84,5500,2017,12,away
1201,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,116.11,3,11,3.7,0,20.94,6900,2017,7,home
1202,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,53.12,1,2,2.0,0,11.92,4300,2017,21,away
1203,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,86.51,7,21,3.0,0,20.54,6000,2017,8,away
1204,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,95.02,3,-8,-2.7,0,16.72,7000,2017,24,home

In [402]:
surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'
              
             }

In [614]:
surface = []
for idx, team in enumerate(qb_2017['Team']):
    if qb_2017.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[qb_2017.iloc[idx]['Opponent']])


qb_2017['surface'] = surface

In [615]:
qb_2017.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
1200,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,0,0,0.0,0,7.84,5500,2017,12,away,turf
1201,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,3,11,3.7,0,20.94,6900,2017,7,home,turf
1202,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,1,2,2.0,0,11.92,4300,2017,21,away,turf
1203,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,7,21,3.0,0,20.54,6000,2017,8,away,turf
1204,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,3,-8,-2.7,0,16.72,7000,2017,24,home,grass

In [617]:
qb_df=pd.concat([qb_df,qb_2017])

In [618]:
qb_df.tail()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
1795,18525,Joe Callahan,GB,17,DET,5,7,71.4,11,1.6,...,0,0,0.0,0,0.44,4400,2017,21,away,turf
1796,18811,Mitch Trubisky,CHI,17,MIN,20,36,55.6,178,4.9,...,1,2,2.0,0,7.32,4700,2017,1,away,turf
1797,18868,Deshone Kizer,CLE,17,PIT,16,30,53.3,314,10.5,...,6,61,10.2,0,28.66,4400,2017,6,away,grass
1798,18890,Patrick Mahomes,KC,17,DEN,22,35,62.9,284,8.1,...,7,10,1.4,0,11.36,4800,2017,5,away,grass
1799,19238,Taysom Hill,NO,17,TB,0,0,0.0,0,0.0,...,0,0,0.0,0,0.00,4500,2017,31,away,grass

In [619]:
qb_df.shape

(1796, 23)

In [620]:
qb.shape

(1800, 21)

In [628]:
for player in qb_df['Name']:
    if player not in list(qb['Name'].unique()):
        print(player)

In [629]:
qb_df.reset_index(inplace=True,drop=True)

In [631]:
qb_df.to_csv('input/qb/dk_stats_loc.csv')

In [3]:
wr = pd.read_csv('input/wr/dk_wr_stats.csv')

In [4]:
wr.head()

,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,ReceivingLong,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,points,year
0,Kevin Ogletree,DAL,1,NYG,11,8,72.7,114,2,NaN,10.4,14.2,0,0,0.0,0,0,0,23.4,2012
1,Julio Jones,ATL,1,KC,9,6,66.7,108,2,NaN,12.0,18.0,0,0,0.0,0,0,0,22.8,2012
2,Stephen Hill,NYJ,1,BUF,6,5,83.3,89,2,NaN,14.8,17.8,0,0,0.0,0,0,0,20.9,2012
3,Lance Moore,NO,1,WAS,10,6,60.0,120,1,NaN,12.0,20.0,0,0,0.0,0,0,0,18.0,2012
4,Brandon Marshall,CHI,1,IND,15,9,60.0,119,1,NaN,7.9,13.2,0,0,0.0,0,0,0,17.9,2012