In [1]:
import pandas as pd
import numpy as np

In [13]:
def read_concat(csv1, csv2):
    data=pd.read_csv(csv1)
    data2=pd.read_csv(csv2)
    df = pd.concat([data, data2])
    df.reset_index(inplace=True, drop=True)
    
    return df

In [17]:
df1= read_concat('input/wr/2015wk1_2.csv','input/wr/2015wk3_4.csv')


#df2 = read_concat('input/wr/2015_sal_1_9.csv','input/wr/2015_sal_10_17.csv')

In [ ]:
df1 = pd.concat([df1,(pd.read_csv('input/wr/2015wk5_6.csv'))])
df1.reset_index(inplace=True, drop=True)

In [16]:
df1.shape

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
736,111,14368,Nick Toon,LAR,WR,17,SF,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
737,111,7857,Jerome Simpson,SF,WR,17,LAR,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
738,111,16480,Jeff Janis,GB,WR,17,MIN,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
739,111,16469,Jared Abbrederis,GB,WR,17,MIN,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
740,155,15150,Cordarrelle Patterson,MIN,WR,17,GB,0,0,0.0,...,0.0,0.0,0,0,0.0,0,1,1,-1.0,-1.0

In [273]:
data1 = pd.read_csv('input/wr/2016wk1_2.csv')
data2 = pd.read_csv('input/wr/2016wk3_4.csv')
data3 = pd.read_csv('input/wr/2016wk5_6.csv')
data4 = pd.read_csv('input/wr/2016wk7_8.csv')
data5 = pd.read_csv('input/wr/2016wk9_10.csv')
data6 = pd.read_csv('input/wr/2016wk11_12.csv')
data7 = pd.read_csv('input/wr/2016wk13_14.csv')
data8 = pd.read_csv('input/wr/2016wk15_16.csv')
data9 = pd.read_csv('input/wr/2016wk17.csv')

In [49]:
data7.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
0,1,11611,Golden Tate,DET,WR,13,NO,10,8,80.0,...,14.5,18.1,0,0,0.0,0,0,0,31.5,31.5
1,2,11063,Emmanuel Sanders,DEN,WR,14,TEN,14,11,78.6,...,7.1,9.1,0,0,0.0,0,0,0,30.0,30.0
2,3,14005,T.Y. Hilton,IND,WR,14,HOU,13,9,69.2,...,8.8,12.8,0,0,0.0,0,0,0,29.5,29.5
3,4,4556,Jordy Nelson,GB,WR,13,HOU,10,8,80.0,...,11.8,14.8,0,0,0.0,0,0,0,28.8,28.8
4,5,14828,Chris Hogan,NE,WR,14,BAL,7,5,71.4,...,18.4,25.8,2,7,3.5,0,0,0,27.6,27.6

In [274]:
wr_2016_df= pd.concat([data1,data2])
wr_2016_df.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,13.8,15.0,0,0,0.0,0,0,0,39.0,39.0
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,15.9,23.8,1,11,11.0,0,0,0,36.4,36.4
2,3,16906,Stefon Diggs,MIN,WR,2,GB,11,9,81.8,...,16.5,20.2,0,0,0.0,0,0,0,36.2,36.2
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,11.5,15.8,0,0,0.0,0,0,0,35.6,35.6
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,19.1,19.1,0,0,0.0,0,1,0,35.2,35.2

In [73]:
data9.shape

(152, 23)

In [77]:
wr_2017 = wr_2017[0:600]

In [281]:
wr_2016_df = pd.concat([wr_2016_df, data9])
wr_2016_df.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,13.8,15.0,0,0,0.0,0,0,0,39.0,39.0
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,15.9,23.8,1,11,11.0,0,0,0,36.4,36.4
2,3,16906,Stefon Diggs,MIN,WR,2,GB,11,9,81.8,...,16.5,20.2,0,0,0.0,0,0,0,36.2,36.2
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,11.5,15.8,0,0,0.0,0,0,0,35.6,35.6
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,19.1,19.1,0,0,0.0,0,1,0,35.2,35.2

In [283]:
wr_2016_df['Week'].nunique()

17

In [97]:
wr_2015.shape

(2420, 23)

# Wide Receivers

In [44]:
df2.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,UpcomingOpponentRank,UpcomingOpponentPositionRank,DraftKingsSalary,FantasyPointsDraftKings
0,1,4314,Tom Brady,NE,QB,9,WAS,16,15,8500,26.92
1,2,8244,Philip Rivers,LAC,QB,8,BAL,31,32,6600,26.72
2,3,4314,Tom Brady,NE,QB,5,DAL,18,10,7800,26.46
3,4,2428,Carson Palmer,ARI,QB,7,BAL,30,32,6700,26.30
4,5,13320,Cam Newton,CAR,QB,7,PHI,9,9,6600,26.22

In [111]:
wr_2015['year'] = 2015
wr_2016['year']=2016
wr_2017['year'] = 2017

In [110]:
def add_salary(df,df2):
    df = df.sort_values(['Week','PlayerID'])
    df = df.drop(['FantasyPointsPerGameDraftKings','Rank','Position'], axis=1)
    df.reset_index(inplace=True, drop=True)
    df2 = df2.sort_values(['Week','PlayerID'])
    df2 = df2.drop(['Rank','Position'], axis=1)
    df2.reset_index(inplace=True, drop=True)
    df['salary'] = df2['DraftKingsSalary']
    
    return df

In [331]:
wr_2016 = add_salary(wr_2016,wr_2016_sal)
wr_2016.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,def_rk,h/a,salary
0,2429,Andre Johnson,TEN,1,MIN,7,3,42.9,30,0,...,0,0,0.0,0,0,0,6.0,17,home,3900
1,3519,Vincent Jackson,TB,1,ATL,7,2,28.6,18,0,...,0,0,0.0,0,0,0,3.8,11,away,4400
2,3601,Eric Weems,ATL,1,TB,0,0,0.0,0,0,...,0,0,0.0,0,0,0,0.0,24,home,3000
3,3943,DeSean Jackson,WAS,1,PIT,10,6,60.0,102,0,...,0,0,0.0,0,0,0,19.2,22,home,6100
4,4358,Steve Smith,BAL,1,BUF,8,5,62.5,19,0,...,0,0,0.0,0,0,0,6.9,29,home,4900

In [356]:
cols = wr_2016.columns.tolist()
cols = cols[:-2] + cols[-1:] + cols[-2:-1]
df = wr_2016[cols]

In [358]:
wr_2016 = df

In [360]:
wr_2015.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets',
       'Receptions', 'ReceptionPercentage', 'ReceivingYards',
       'ReceivingTouchdowns', 'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'year', 'salary', 'def_rk', 'h/a',
       'surface'],
      dtype='object')

######

In [116]:
def_2015 = pd.read_csv('input/def_2015.csv')
def_2017 = pd.read_csv('input/def_2017.csv')
def_2016 = pd.read_csv('input/def_2016.csv')

In [121]:
def_2015.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)

In [122]:
def_2015.index=def_2015['Team']
def_2016.index=def_2015['Team']
def_2017.index=def_2015['Team']

In [285]:
wr_2016 = wr_2016_df

In [286]:
# Add defensive rankings to dataframe

#wr_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], wr_2015['Opponent']))
wr_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], wr_2016['Opponent']))
#wr_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], wr_2017['Opponent']))

In [287]:
wr_2016.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,15.0,0,0,0.0,0,0,0,39.0,39.0,30
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,23.8,1,11,11.0,0,0,0,36.4,36.4,27
2,3,16906,Stefon Diggs,MIN,WR,2,GB,11,9,81.8,...,20.2,0,0,0.0,0,0,0,36.2,36.2,16
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,15.8,0,0,0.0,0,0,0,35.6,35.6,14
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,19.1,0,0,0.0,0,1,0,35.2,35.2,27

# Quarterbacks

In [74]:
df1= read_concat('input/qb/2016wk1_9.csv','input/qb/2016wk_10_17.csv')

df2 = read_concat('input/qb/2016_sal_wk1_9.csv','input/qb/2016_sal_wk10_17.csv')

df1= read_concat('input/qb/2017wk1_9.csv','input/qb/2017wk10_17.csv')

df2 = read_concat('input/qb/2017_sal_wk1_9.csv','input/qb/2017_sal_wk10_17.csv')

In [ ]:
# Add defensive rankings to dataframe

qb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], qb_2015['Opponent']))
qb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], qb_2016['Opponent']))
qb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], qb_2017['Opponent']))

In [76]:
qb.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,PassingTouchdowns,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary
0,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,1,1,70.96,0,0,0.0,0,7.84,5500
1,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,1,0,116.11,3,11,3.7,0,20.94,6900
2,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,1,3,53.12,1,2,2.0,0,11.92,4300
3,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,1,1,86.51,7,21,3.0,0,20.54,6000
4,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,2,1,95.02,3,-8,-2.7,0,16.72,7000

In [66]:
qb.shape

(600, 19)

In [77]:
def_2015.index=def_2015['Team']

def_2016.index=def_2016['Team']

def_2017.index = def_2017['Team']

In [58]:
qb_2015['year'] = 2015

In [68]:
qb_2016['year']=2016

In [78]:
qb_2017['year'] = 2017

In [79]:
# Map defensive rankings fron defense df to qb_df by yer and opponent

qb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], qb_2015['Opponent']))
qb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], qb_2016['Opponent']))
qb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], qb_2017['Opponent']))

In [62]:
qb_2015.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,DEN,18,32,56.2,117,3.7,...,2,38.15,0,0,0.0,0,2.68,6700,2015,2
1,732,Matt Ryan,ATL,1,PHI,23,34,67.6,298,8.8,...,2,90.07,5,7,1.4,0,18.62,7500,2015,30
2,2428,Carson Palmer,ARI,1,NO,19,32,59.4,307,9.6,...,0,122.79,3,14,4.7,0,28.68,6500,2015,32
3,2593,Aaron Rodgers,GB,1,CHI,18,23,78.3,189,8.2,...,0,140.49,8,35,4.4,0,23.06,8600,2015,15
4,3807,Ben Roethlisberger,PIT,1,NE,26,38,68.4,351,9.2,...,1,95.39,0,0,0.0,0,22.04,7300,2015,13

In [73]:
qb_2016.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,BUF,22,33,66.7,258,7.8,...,0,100.32,4,-3,-0.8,0,13.02,6700,2016,10
1,732,Matt Ryan,ATL,1,TB,27,39,69.2,334,8.6,...,0,112.55,3,10,3.3,0,27.36,7100,2016,17
2,2428,Carson Palmer,ARI,1,NE,24,37,64.9,271,7.3,...,0,104.67,2,1,0.5,0,18.94,7100,2016,6
3,2593,Aaron Rodgers,GB,1,JAX,20,34,58.8,199,5.9,...,0,95.10,4,16,4.0,1,23.56,8500,2016,8
4,3807,Ben Roethlisberger,PIT,1,WAS,27,37,73.0,300,8.1,...,1,112.44,1,-2,-2.0,0,25.80,7800,2016,27

In [80]:
qb_2017.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,1,70.96,0,0,0.0,0,7.84,5500,2017,12
1,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,0,116.11,3,11,3.7,0,20.94,6900,2017,7
2,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,3,53.12,1,2,2.0,0,11.92,4300,2017,21
3,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,1,86.51,7,21,3.0,0,20.54,6000,2017,8
4,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,1,95.02,3,-8,-2.7,0,16.72,7000,2017,24

## Merge Dataframes

In [ ]:
data_qb = [qb_2015,qb_2016,qb_2017]

In [125]:
data_wr= [wr_2015,wr_2016,wr_2017]

In [82]:
qb= pd.concat(data)

In [126]:
wr= pd.concat(data_wr)

In [ ]:
wr['ReceivingTargets'].max()

In [129]:
wr.shape

(5501, 23)

In [90]:
qb.to_csv('input/qb/dk_stas_sal.csv', index=False)
wr.to_csv('input/wr/dk_stats_sal.csv', index=False)

In [ ]:
pd.read_

In [130]:
# add location to dataframes by mapping location of game from completed qb dataframe

qb = pd.read_csv('input/qb/dk_stats_loc.csv')

In [131]:
qb.head()

,Unnamed: 0,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
0,0,611,Joe Flacco,BAL,1,DEN,18,32,56.2,117,...,0,0,0.0,0,2.68,6700,2015,2,away,grass
1,1,732,Matt Ryan,ATL,1,PHI,23,34,67.6,298,...,5,7,1.4,0,18.62,7500,2015,30,home,turf
2,2,2428,Carson Palmer,ARI,1,NO,19,32,59.4,307,...,3,14,4.7,0,28.68,6500,2015,32,home,grass
3,3,2593,Aaron Rodgers,GB,1,CHI,18,23,78.3,189,...,8,35,4.4,0,23.06,8600,2015,15,away,grass
4,4,3807,Ben Roethlisberger,PIT,1,NE,26,38,68.4,351,...,0,0,0.0,0,22.04,7300,2015,13,away,turf

In [263]:
wr.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk
0,204,Roddy White,ATL,1,PHI,8,4,50.0,84,0,...,0,0,0.0,0,0,0,12.4,2015,6500,30
1,1986,Jason Avant,KC,1,HOU,0,0,0.0,0,0,...,0,0,0.0,0,0,0,0.0,2015,3000,3
2,2429,Andre Johnson,IND,1,BUF,10,4,40.0,24,0,...,0,0,0.0,0,0,0,6.4,2015,6100,18
3,2950,Steve Johnson,LAC,1,DET,6,6,100.0,82,1,...,0,0,0.0,0,0,0,20.2,2015,3700,20
4,3330,Miles Austin,PHI,1,ATL,3,2,66.7,22,0,...,0,0,0.0,0,0,0,4.2,2015,3000,12

In [139]:
qb_2015 = qb[qb['year']==2015]
qb_2015.index = qb_2015['Team']
wr_2015.index = wr_2015['Team']

In [145]:
wr_2015.reset_index(inplace=True, drop =True)

In [148]:
location = pd.read_csv('input/location.csv')
location.drop('Unnamed: 0', axis=1,inplace=True)

In [143]:
wr_2015['h/a'] = home

In [293]:
temp = wr_2016

In [294]:
week1  = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [237]:
loc_df = location[location['year']==2016]

In [250]:
week5

Empty DataFrame
Columns: [PlayerID, Name, Team, Week, Opponent, ReceivingTargets, Receptions, ReceptionPercentage, ReceivingYards, ReceivingTouchdowns, ReceivingLong, ReceivingYardsPerTarget, ReceivingYardsPerReception, RushingAttempts, RushingYards, RushingYardsPerAttempt, RushingTouchdowns, Fumbles, FumblesLost, FantasyPointsDraftKings, year, salary, def_rk]
Index: []

[0 rows x 23 columns]

In [329]:
loc_df[loc_df['week']==17]

home_list = []
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')


week17['h/a'] = home_list


week17.head()

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk,h/a
0,1,8355,Julian Edelman,NE,WR,17,MIA,13,8,61.5,...,1,6,6.0,0,0,0,34.7,34.7,4,away
1,2,17960,Michael Thomas,NO,WR,17,ATL,14,10,71.4,...,0,0,0.0,0,0,0,34.6,34.6,11,away
2,3,13788,Rishard Matthews,TEN,WR,17,HOU,13,9,69.2,...,0,0,0.0,0,0,0,29.4,29.4,5,home
3,4,16470,Davante Adams,GB,WR,17,DET,9,6,66.7,...,0,0,0.0,0,0,0,23.1,23.1,21,away
4,5,13291,Julio Jones,ATL,WR,17,NO,9,7,77.8,...,0,0,0.0,0,0,0,22.6,22.6,12,home

In [330]:
wr_2016 = pd.concat([wr_2016,week17])
wr_2016.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk,h/a
158,124,11565,Andre Roberts,DET,WR,17,GB,1,0,0.0,...,0,0,0.0,0,0,0,0.0,0.0,16,home
159,124,16480,Jeff Janis,GB,WR,17,DET,0,0,0.0,...,0,0,0.0,0,0,0,0.0,0.0,21,away
160,124,18080,Trevor Davis,GB,WR,17,DET,0,0,0.0,...,0,0,0.0,0,0,0,0.0,0.0,21,away
161,162,16781,Nelson Agholor,PHI,WR,17,DAL,0,0,0.0,...,1,-1,-1.0,0,0,0,-0.1,-0.1,15,home
162,163,18241,Johnny Holton,OAK,WR,17,DEN,1,0,0.0,...,1,0,0.0,0,1,1,-1.0,-1.0,1,home

In [299]:
wr_2016 = pd.concat([week1,week2])
wr_2016.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk,h/a
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,0,0,0.0,0,0,0,39.0,39.0,30,home
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,1,11,11.0,0,0,0,36.4,36.4,27,away
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,0,0,0.0,0,0,0,35.6,35.6,14,home
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,0,0,0.0,0,1,0,35.2,35.2,27,away
8,9,5571,Larry Fitzgerald,ARI,WR,1,NE,10,8,80.0,...,0,0,0.0,0,0,0,28.1,28.1,26,home

In [217]:
wr_2015.shape

(2420, 24)

In [218]:
# Surface dictionary consisting of every team and the type of field they play on

surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'
              
             }

In [219]:
wr_2015.index = wr_2015['Team']

In [220]:
# Add the tyep of field the player palyed on by mapping the field on which the game was played to the surface dictionary

surface = []
for idx, team in enumerate(wr_2015['Team']):
    if wr_2015.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[wr_2015.iloc[idx]['Opponent']])


wr_2015['surface'] = surface

In [221]:
wr_2015.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a,surface
Team,,,,,,,,,,,,,,,,,,,,,
ATL,204,Roddy White,ATL,1,PHI,8,4,50.0,84,0,...,0.0,0,0,0,12.4,2015,6500,30,home,turf
KC,1986,Jason Avant,KC,1,HOU,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2015,3000,3,away,turf
IND,2429,Andre Johnson,IND,1,BUF,10,4,40.0,24,0,...,0.0,0,0,0,6.4,2015,6100,18,home,turf
LAC,2950,Steve Johnson,LAC,1,DET,6,6,100.0,82,1,...,0.0,0,0,0,20.2,2015,3700,20,away,turf
PHI,3330,Miles Austin,PHI,1,ATL,3,2,66.7,22,0,...,0.0,0,0,0,4.2,2015,3000,12,home,grass