In [114]:
import pandas as pd
import numpy as np
import json
from bs4 import BeautifulSoup
import requests
import re
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [10]:
# Read in files

df1= pd.read_csv('input/qb/fantasy-football-leaders (1).csv')
#df2 = pd.read_csv('input/qb/fantasy-football-leaders (2).csv')
df_sal1 =pd.read_csv('input/qb/daily-fantasy-football-salary-and-projection-tool.csv')
#df_sal2 =pd.read_csv('input/qb/daily-fantasy-football-salary-and-projection-tool (1).csv')

def_2018 = pd.read_csv('input/def/fantasy-football-points-allowed-defense-by-position.csv')

qb = pd.read_csv('input/qb/dk_stats_loc.csv')

In [19]:
qb.drop('Unnamed: 0', axis=1, inplace=True)
qb.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'salary', 'year',
       'def_rk', 'h/a', 'surface', 'h/a0', 'h/a1', 'surface_0', 'surface_1',
       'FantasyPointsDraftKings'],
      dtype='object')

In [14]:
qb_2018 = df1[df1['Week'] != 4]
qb_2018.Week.unique()

array([1, 3, 2], dtype=int64)

In [17]:
qb_2018_sal = df_sal1[df_sal1['Week'] != 4]
qb_2018_sal.Week.unique()

array([3, 1, 2], dtype=int64)

In [22]:
df1= pd.concat([df1,df2])
df_sal = pd.concat([df_sal1,df_sal2])

NameError: name 'df2' is not defined

In [23]:
df1 = add_salary(df1,df_sal1)

In [24]:
df1['year']=2018

## Location dataframe

In [26]:
# A dictionary of NFL team names and their appropriate abbreviations 

team_dict = {'New England Patriots':'NE',
            'Green Bay Packers':'GB',
            'Tampa Bay Buccaneers':'TB',
            'Kansas City Chiefs':'KC',
            'San Diego Chargers':'SD',
            'St. Louis Rams':'STL',
            'New Orleans Saints':'NO',
            'New York Jets':'NYJ',
            'New York Giants':'NYG',
            'San Francisco 49ers':'SF',
            'Los Angeles Rams':'LAR',
            'Jacksonville Jaguars':'JAX',
            'Los Angeles Chargers':'LAC'}

In [29]:
"""This is a function designed to create a dataframe to hold the home and away teams in every NFL football game"""

def pfr_scraper(url, current_week):


    # Set url for requests function


    page = requests.get(url)



# Use BeautifulSoup to scarpe data the data from Pro Footbal Reference.com 

    soup = BeautifulSoup(page.text,'html.parser')
    weeks = []  
    for tr in soup.find_all('tr'):
        weeks.append(tr.text)

    # Remove any lines that dont describe weekly nfl game

    for row in weeks:
        try:
             weeks.remove('\nWeek\nDay\nDate\nTime\nWinner/tie\n\nLoser/tie\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n')
        except:
            None
    
    

# Split string a first non digit and use result for week varianble of each individual matchup

    week =[] 
    for row in weeks:
        if int(re.split(r'(\d+)', row)[1]) < current_week:
            week.append(int(re.split(r'(\d+)', row)[1]))
            
    return weeks, week

In [ ]:
# Set url for requests function

url='https://www.pro-football-reference.com/years/2018/games.htm'
page = requests.get(url)

In [63]:
# Use BeautifulSoup to scarpe data the data from Pro Footbal Reference.com 

soup = BeautifulSoup(page.text,'html.parser')
weeks = []  
for tr in soup.find_all('tr'):
    weeks.append(tr.text)

In [64]:
weeks

['\nWeek\nDay\nDate\nTime\nWinner/tie\n\nLoser/tie\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '1ThuSeptember 68:20PMPhiladelphia EaglesAtlanta Falconsboxscore181223222991',
 '1SunSeptember 91:00PMCincinnati Bengals@Indianapolis Coltsboxscore342333023802',
 '1SunSeptember 91:00PMJacksonville Jaguars@New York Giantsboxscore201530513242',
 '1SunSeptember 91:00PMTampa Bay Buccaneers@New Orleans Saintsboxscore484052904752',
 '1SunSeptember 91:00PMNew England PatriotsHouston Texansboxscore272038933252',
 '1SunSeptember 91:00PMPittsburgh Steelers@Cleveland Brownsboxscore212147263271',
 '1SunSeptember 91:00PMMinnesota VikingsSan Francisco 49ersboxscore241634313274',
 '1SunSeptember 91:00PMBaltimore RavensBuffalo Billsboxscore47336911532',
 '1SunSeptember 91:00PMMiami DolphinsTennessee Titansboxscore272034223363',
 '1SunSeptember 94:05PMKansas City Chiefs@Los Angeles Chargersboxscore382836205412',
 '1SunSeptember 94:25PMWashington Redskins@Arizona Cardinalsboxscore24642912132',
 '1SunSeptember 94:25PMDenver BroncosSeattle Seahawksboxscore272447033063',
 '1SunSeptember 94:25PMCarolina PanthersDallas Cowboysboxscore16829312321',
 '1SunSeptember 98:20PMGreen Bay PackersChicago Bearsboxscore242337022941',
 '1MonSeptember 107:10PMNew York Jets@Detroit Lionsboxscore481734923395',
 '1MonSeptember 1010:20PMLos Angeles Rams@Oakland Raidersboxscore331336503953',
 '\nWeek\nDay\nDate\nTime\nWinner/tie\n\nLoser/tie\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '2ThuSeptember 138:20PMCincinnati BengalsBaltimore Ravensboxscore342337304253',
 '2SunSeptember 161:00PMLos Angeles Chargers@Buffalo Billsboxscore312034902932',
 '2SunSeptember 161:00PMMiami Dolphins@New York Jetsboxscore201225723623',
 '2SunSeptember 161:00PMAtlanta FalconsCarolina Panthersboxscore312444214391',
 '2SunSeptember 161:00PMKansas City Chiefs@Pittsburgh Steelersboxscore423744914750',
 '2SunSeptember 161:00PMIndianapolis Colts@Washington Redskinsboxscore21928123341',
 '2SunSeptember 161:00PMTampa Bay BuccaneersPhiladelphia Eaglesboxscore272143624122',
 '2SunSeptember 161:00PMTennessee TitansHouston Texansboxscore201728304371',
 '2SunSeptember 161:00PMMinnesota Vikings@Green Bay Packersboxscore292948013510',
 '2SunSeptember 161:00PMNew Orleans SaintsCleveland Brownsboxscore211827523271',
 '2SunSeptember 164:05PMSan Francisco 49ersDetroit Lionsboxscore302734604271',
 '2SunSeptember 164:05PMLos Angeles RamsArizona Cardinalsboxscore34043211371',
 '2SunSeptember 164:25PMDenver BroncosOakland Raidersboxscore201938513730',
 '2SunSeptember 164:25PMJacksonville JaguarsNew England Patriotsboxscore312048023021',
 '2SunSeptember 168:20PMDallas CowboysNew York Giantsboxscore201329802551',
 '2MonSeptember 178:15PMChicago BearsSeattle Seahawksboxscore241727122762',
 '\nWeek\nDay\nDate\nTime\nWinner/tie\n\nLoser/tie\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '3ThuSeptember 208:20PMCleveland BrownsNew York Jetsboxscore211732302683',
 '3SunSeptember 231:00PMWashington RedskinsGreen Bay Packersboxscore311738613401',
 '3SunSeptember 231:00PMBuffalo Bills@Minnesota Vikingsboxscore27629202923',
 '3SunSeptember 231:00PMMiami DolphinsOakland Raidersboxscore282037304342',
 '3SunSeptember 231:00PMNew Orleans Saints@Atlanta Falconsboxscore433753404070',
 '3SunSeptember 231:00PMKansas City ChiefsSan Francisco 49ersboxscore382738404060',
 '3SunSeptember 231:00PMBaltimore RavensDenver Broncosboxscore271434202931',
 '3SunSeptember 231:00PMPhiladelphia EaglesIndianapolis Coltsboxscore201637922090',
 '3SunSeptember 231:00PMTennessee Titans@Jacksonville Jaguarsboxscore9623302321',
 '3SunSeptember 231:00PMCarolina PanthersCincinnati Bengalsboxscore312137703964',
 '3SunSeptember 231:00PMNew York Giants@Houston Texansboxscore272237904272',
 '3SunSeptember 234:05PMLos Angeles RamsLos Angeles Chargersboxscore352352123562',
 '3SunSeptember 234:25PMChicago Bears@Arizona Cardinalsboxscore161431622214',
 '3SunSeptember 234:25PMSeattle SeahawksDallas Cowboysboxscore241329503033',
 '3SunSeptember 238:20PMDetroit LionsNew England Patriotsboxscore261041412091',
 '3MonSeptember 248:15PMPittsburgh Steelers@Tampa Bay Buccaneersboxscore302741314554',
 '\nWeek\nDay\nDate\nTime\nWinner/tie\n\nLoser/tie\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '4ThuSeptember 278:20PMLos Angeles RamsMinnesota Vikingsboxscore383155604461',
 '4SunSeptember 301:00PMTampa Bay Buccaneers@Chicago Bearspreview',
 '4SunSeptember 301:00PMDetroit Lions@Dallas Cowboyspreview',
 '4SunSeptember 301:00PMBuffalo Bills@Green Bay Packerspreview',
 '4SunSeptember 301:00PMMiami Dolphins@New England Patriotspreview',
 '4SunSeptember 301:00PMNew York Jets@Jacksonville Jaguarspreview',
 '4SunSeptember 301:00PMPhiladelphia Eagles@Tennessee Titanspreview',
 '4SunSeptember 301:00PMHouston Texans@Indianapolis Coltspreview',
 '4SunSeptember 301:00PMCincinnati Bengals@Atlanta Falconspreview',
 '4SunSeptember 304:05PMSeattle Seahawks@Arizona Cardinalspreview',
 '4SunSeptember 304:05PMCleveland Browns@Oakland Raiderspreview',
 '4SunSeptember 304:25PMSan Francisco 49ers@Los Angeles Chargerspreview',
 '4SunSeptember 304:25PMNew Orleans Saints@New York Giantspreview',
 '4SunSeptember 308:20PMBaltimore Ravens@Pittsburgh Steelerspreview',
 '4MonOctober 18:15PMKansas City Chiefs@Denver Broncospreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '5ThuOctober 48:20PMIndianapolis Colts@New England Patriotspreview',
 '5SunOctober 71:00PMNew York Giants@Carolina Pantherspreview',
 '5SunOctober 71:00PMTennessee Titans@Buffalo Billspreview',
 '5SunOctober 71:00PMGreen Bay Packers@Detroit Lionspreview',
 '5SunOctober 71:00PMMiami Dolphins@Cincinnati Bengalspreview',
 '5SunOctober 71:00PMBaltimore Ravens@Cleveland Brownspreview',
 '5SunOctober 71:00PMDenver Broncos@New York Jetspreview',
 '5SunOctober 71:00PMJacksonville Jaguars@Kansas City Chiefspreview',
 '5SunOctober 71:00PMAtlanta Falcons@Pittsburgh Steelerspreview',
 '5SunOctober 74:05PMOakland Raiders@Los Angeles Chargerspreview',
 '5SunOctober 74:25PMLos Angeles Rams@Seattle Seahawkspreview',
 '5SunOctober 74:25PMArizona Cardinals@San Francisco 49erspreview',
 '5SunOctober 74:25PMMinnesota Vikings@Philadelphia Eaglespreview',
 '5SunOctober 78:20PMDallas Cowboys@Houston Texanspreview',
 '5MonOctober 88:15PMWashington Redskins@New Orleans Saintspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '6ThuOctober 118:20PMPhiladelphia Eagles@New York Giantspreview',
 '6SunOctober 141:00PMSeattle Seahawks@Oakland Raiderspreview',
 '6SunOctober 141:00PMTampa Bay Buccaneers@Atlanta Falconspreview',
 '6SunOctober 141:00PMCarolina Panthers@Washington Redskinspreview',
 '6SunOctober 141:00PMBuffalo Bills@Houston Texanspreview',
 '6SunOctober 141:00PMIndianapolis Colts@New York Jetspreview',
 '6SunOctober 141:00PMArizona Cardinals@Minnesota Vikingspreview',
 '6SunOctober 141:00PMChicago Bears@Miami Dolphinspreview',
 '6SunOctober 141:00PMLos Angeles Chargers@Cleveland Brownspreview',
 '6SunOctober 141:00PMPittsburgh Steelers@Cincinnati Bengalspreview',
 '6SunOctober 144:05PMLos Angeles Rams@Denver Broncospreview',
 '6SunOctober 144:25PMJacksonville Jaguars@Dallas Cowboyspreview',
 '6SunOctober 144:25PMBaltimore Ravens@Tennessee Titanspreview',
 '6SunOctober 148:20PMKansas City Chiefs@New England Patriotspreview',
 '6MonOctober 158:15PMSan Francisco 49ers@Green Bay Packerspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '7ThuOctober 188:20PMDenver Broncos@Arizona Cardinalspreview',
 '7SunOctober 219:30AMTennessee Titans@Los Angeles Chargerspreview',
 '7SunOctober 211:00PMCincinnati Bengals@Kansas City Chiefspreview',
 '7SunOctober 211:00PMNew England Patriots@Chicago Bearspreview',
 '7SunOctober 211:00PMCleveland Browns@Tampa Bay Buccaneerspreview',
 '7SunOctober 211:00PMDetroit Lions@Miami Dolphinspreview',
 '7SunOctober 211:00PMCarolina Panthers@Philadelphia Eaglespreview',
 '7SunOctober 211:00PMBuffalo Bills@Indianapolis Coltspreview',
 '7SunOctober 211:00PMMinnesota Vikings@New York Jetspreview',
 '7SunOctober 211:00PMHouston Texans@Jacksonville Jaguarspreview',
 '7SunOctober 214:05PMNew Orleans Saints@Baltimore Ravenspreview',
 '7SunOctober 214:25PMDallas Cowboys@Washington Redskinspreview',
 '7SunOctober 218:20PMLos Angeles Rams@San Francisco 49erspreview',
 '7MonOctober 228:15PMNew York Giants@Atlanta Falconspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '8ThuOctober 258:20PMMiami Dolphins@Houston Texanspreview',
 '8SunOctober 289:30AMPhiladelphia Eagles@Jacksonville Jaguarspreview',
 '8SunOctober 281:00PMBaltimore Ravens@Carolina Pantherspreview',
 '8SunOctober 281:00PMDenver Broncos@Kansas City Chiefspreview',
 '8SunOctober 281:00PMSeattle Seahawks@Detroit Lionspreview',
 '8SunOctober 281:00PMCleveland Browns@Pittsburgh Steelerspreview',
 '8SunOctober 281:00PMTampa Bay Buccaneers@Cincinnati Bengalspreview',
 '8SunOctober 281:00PMNew York Jets@Chicago Bearspreview',
 '8SunOctober 281:00PMWashington Redskins@New York Giantspreview',
 '8SunOctober 284:05PMIndianapolis Colts@Oakland Raiderspreview',
 '8SunOctober 284:25PMSan Francisco 49ers@Arizona Cardinalspreview',
 '8SunOctober 284:25PMGreen Bay Packers@Los Angeles Ramspreview',
 '8SunOctober 288:20PMNew Orleans Saints@Minnesota Vikingspreview',
 '8MonOctober 298:15PMNew England Patriots@Buffalo Billspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '9ThuNovember 18:20PMOakland Raiders@San Francisco 49erspreview',
 '9SunNovember 41:00PMPittsburgh Steelers@Baltimore Ravenspreview',
 '9SunNovember 41:00PMAtlanta Falcons@Washington Redskinspreview',
 '9SunNovember 41:00PMDetroit Lions@Minnesota Vikingspreview',
 '9SunNovember 41:00PMKansas City Chiefs@Cleveland Brownspreview',
 '9SunNovember 41:00PMTampa Bay Buccaneers@Carolina Pantherspreview',
 '9SunNovember 41:00PMNew York Jets@Miami Dolphinspreview',
 '9SunNovember 41:00PMChicago Bears@Buffalo Billspreview',
 '9SunNovember 44:05PMHouston Texans@Denver Broncospreview',
 '9SunNovember 44:05PMLos Angeles Chargers@Seattle Seahawkspreview',
 '9SunNovember 44:25PMLos Angeles Rams@New Orleans Saintspreview',
 '9SunNovember 48:20PMGreen Bay Packers@New England Patriotspreview',
 '9MonNovember 58:15PMTennessee Titans@Dallas Cowboyspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '10ThuNovember 88:20PMCarolina Panthers@Pittsburgh Steelerspreview',
 '10SunNovember 111:00PMJacksonville Jaguars@Indianapolis Coltspreview',
 '10SunNovember 111:00PMNew Orleans Saints@Cincinnati Bengalspreview',
 '10SunNovember 111:00PMAtlanta Falcons@Cleveland Brownspreview',
 '10SunNovember 111:00PMNew England Patriots@Tennessee Titanspreview',
 '10SunNovember 111:00PMDetroit Lions@Chicago Bearspreview',
 '10SunNovember 111:00PMArizona Cardinals@Kansas City Chiefspreview',
 '10SunNovember 111:00PMBuffalo Bills@New York Jetspreview',
 '10SunNovember 111:00PMWashington Redskins@Tampa Bay Buccaneerspreview',
 '10SunNovember 111:00PMMiami Dolphins@Green Bay Packerspreview',
 '10SunNovember 114:05PMLos Angeles Chargers@Oakland Raiderspreview',
 '10SunNovember 114:25PMSeattle Seahawks@Los Angeles Ramspreview',
 '10SunNovember 118:20PMDallas Cowboys@Philadelphia Eaglespreview',
 '10MonNovember 128:15PMNew York Giants@San Francisco 49erspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '11ThuNovember 158:20PMGreen Bay Packers@Seattle Seahawkspreview',
 '11SunNovember 181:00PMMinnesota Vikings@Chicago Bearspreview',
 '11SunNovember 181:00PMTennessee Titans@Indianapolis Coltspreview',
 '11SunNovember 181:00PMPhiladelphia Eagles@New Orleans Saintspreview',
 '11SunNovember 181:00PMCincinnati Bengals@Baltimore Ravenspreview',
 '11SunNovember 181:00PMDallas Cowboys@Atlanta Falconspreview',
 '11SunNovember 181:00PMHouston Texans@Washington Redskinspreview',
 '11SunNovember 181:00PMTampa Bay Buccaneers@New York Giantspreview',
 '11SunNovember 181:00PMCarolina Panthers@Detroit Lionspreview',
 '11SunNovember 184:05PMDenver Broncos@Los Angeles Chargerspreview',
 '11SunNovember 184:05PMOakland Raiders@Arizona Cardinalspreview',
 '11SunNovember 188:20PMPittsburgh Steelers@Jacksonville Jaguarspreview',
 '11MonNovember 198:15PMKansas City Chiefs@Los Angeles Ramspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '12ThuNovember 2212:30PMChicago Bears@Detroit Lionspreview',
 '12ThuNovember 224:30PMWashington Redskins@Dallas Cowboyspreview',
 '12ThuNovember 228:20PMAtlanta Falcons@New Orleans Saintspreview',
 '12SunNovember 251:00PMMiami Dolphins@Indianapolis Coltspreview',
 '12SunNovember 251:00PMJacksonville Jaguars@Buffalo Billspreview',
 '12SunNovember 251:00PMCleveland Browns@Cincinnati Bengalspreview',
 '12SunNovember 251:00PMSan Francisco 49ers@Tampa Bay Buccaneerspreview',
 '12SunNovember 251:00PMOakland Raiders@Baltimore Ravenspreview',
 '12SunNovember 251:00PMSeattle Seahawks@Carolina Pantherspreview',
 '12SunNovember 251:00PMNew England Patriots@New York Jetspreview',
 '12SunNovember 251:00PMNew York Giants@Philadelphia Eaglespreview',
 '12SunNovember 254:05PMArizona Cardinals@Los Angeles Chargerspreview',
 '12SunNovember 254:25PMPittsburgh Steelers@Denver Broncospreview',
 '12SunNovember 258:20PMGreen Bay Packers@Minnesota Vikingspreview',
 '12MonNovember 268:15PMTennessee Titans@Houston Texanspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '13ThuNovember 298:20PMNew Orleans Saints@Dallas Cowboyspreview',
 '13SunDecember 21:00PMBuffalo Bills@Miami Dolphinspreview',
 '13SunDecember 21:00PMCarolina Panthers@Tampa Bay Buccaneerspreview',
 '13SunDecember 21:00PMArizona Cardinals@Green Bay Packerspreview',
 '13SunDecember 21:00PMBaltimore Ravens@Atlanta Falconspreview',
 '13SunDecember 21:00PMChicago Bears@New York Giantspreview',
 '13SunDecember 21:00PMLos Angeles Chargers@Pittsburgh Steelerspreview',
 '13SunDecember 21:00PMDenver Broncos@Cincinnati Bengalspreview',
 '13SunDecember 21:00PMCleveland Browns@Houston Texanspreview',
 '13SunDecember 21:00PMIndianapolis Colts@Jacksonville Jaguarspreview',
 '13SunDecember 21:00PMLos Angeles Rams@Detroit Lionspreview',
 '13SunDecember 24:05PMNew York Jets@Tennessee Titanspreview',
 '13SunDecember 24:05PMKansas City Chiefs@Oakland Raiderspreview',
 '13SunDecember 24:25PMMinnesota Vikings@New England Patriotspreview',
 '13SunDecember 28:20PMSan Francisco 49ers@Seattle Seahawkspreview',
 '13MonDecember 38:15PMWashington Redskins@Philadelphia Eaglespreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '14ThuDecember 68:20PMJacksonville Jaguars@Tennessee Titanspreview',
 '14SunDecember 91:00PMIndianapolis Colts@Houston Texanspreview',
 '14SunDecember 91:00PMLos Angeles Rams@Chicago Bearspreview',
 '14SunDecember 91:00PMNew York Jets@Buffalo Billspreview',
 '14SunDecember 91:00PMCarolina Panthers@Cleveland Brownspreview',
 '14SunDecember 91:00PMBaltimore Ravens@Kansas City Chiefspreview',
 '14SunDecember 91:00PMNew Orleans Saints@Tampa Bay Buccaneerspreview',
 '14SunDecember 91:00PMAtlanta Falcons@Green Bay Packerspreview',
 '14SunDecember 91:00PMNew England Patriots@Miami Dolphinspreview',
 '14SunDecember 91:00PMNew York Giants@Washington Redskinspreview',
 '14SunDecember 94:05PMCincinnati Bengals@Los Angeles Chargerspreview',
 '14SunDecember 94:05PMDenver Broncos@San Francisco 49erspreview',
 '14SunDecember 94:25PMPhiladelphia Eagles@Dallas Cowboyspreview',
 '14SunDecember 94:25PMDetroit Lions@Arizona Cardinalspreview',
 '14SunDecember 98:20PMPittsburgh Steelers@Oakland Raiderspreview',
 '14MonDecember 108:15PMMinnesota Vikings@Seattle Seahawkspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '15ThuDecember 138:20PMLos Angeles Chargers@Kansas City Chiefspreview',
 '15SatDecember 154:30PMHouston Texans@New York Jetspreview',
 '15SatDecember 154:30PMCleveland Browns@Denver Broncospreview',
 '15SunDecember 161:00PMTampa Bay Buccaneers@Baltimore Ravenspreview',
 '15SunDecember 161:00PMDetroit Lions@Buffalo Billspreview',
 '15SunDecember 161:00PMMiami Dolphins@Minnesota Vikingspreview',
 '15SunDecember 161:00PMArizona Cardinals@Atlanta Falconspreview',
 '15SunDecember 161:00PMWashington Redskins@Jacksonville Jaguarspreview',
 '15SunDecember 161:00PMTennessee Titans@New York Giantspreview',
 '15SunDecember 161:00PMGreen Bay Packers@Chicago Bearspreview',
 '15SunDecember 161:00PMDallas Cowboys@Indianapolis Coltspreview',
 '15SunDecember 161:00PMOakland Raiders@Cincinnati Bengalspreview',
 '15SunDecember 164:05PMSeattle Seahawks@San Francisco 49erspreview',
 '15SunDecember 164:25PMNew England Patriots@Pittsburgh Steelerspreview',
 '15SunDecember 168:20PMPhiladelphia Eagles@Los Angeles Ramspreview',
 '15MonDecember 178:15PMNew Orleans Saints@Carolina Pantherspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '16SunDecember 231:00PMNew York Giants@Indianapolis Coltspreview',
 '16SunDecember 231:00PMBuffalo Bills@New England Patriotspreview',
 '16SunDecember 231:00PMTampa Bay Buccaneers@Dallas Cowboyspreview',
 '16SunDecember 231:00PMMinnesota Vikings@Detroit Lionspreview',
 '16SunDecember 231:00PMCincinnati Bengals@Cleveland Brownspreview',
 '16SunDecember 231:00PMWashington Redskins@Tennessee Titanspreview',
 '16SunDecember 231:00PMGreen Bay Packers@New York Jetspreview',
 '16SunDecember 231:00PMHouston Texans@Philadelphia Eaglespreview',
 '16SunDecember 231:00PMJacksonville Jaguars@Miami Dolphinspreview',
 '16SunDecember 231:00PMAtlanta Falcons@Carolina Pantherspreview',
 '16SunDecember 234:05PMLos Angeles Rams@Arizona Cardinalspreview',
 '16SunDecember 234:05PMChicago Bears@San Francisco 49erspreview',
 '16SunDecember 234:05PMBaltimore Ravens@Los Angeles Chargerspreview',
 '16SunDecember 234:25PMPittsburgh Steelers@New Orleans Saintspreview',
 '16SunDecember 238:20PMKansas City Chiefs@Seattle Seahawkspreview',
 '16MonDecember 248:15PMDenver Broncos@Oakland Raiderspreview',
 '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n',
 '17SunDecember 301:00PMJacksonville Jaguars@Houston Texanspreview',
 '17SunDecember 301:00PMAtlanta Falcons@Tampa Bay Buccaneerspreview',
 '17SunDecember 301:00PMCleveland Browns@Baltimore Ravenspreview',
 '17SunDecember 301:00PMIndianapolis Colts@Tennessee Titanspreview',
 '17SunDecember 301:00PMNew York Jets@New England Patriotspreview',
 '17SunDecember 301:00PMDetroit Lions@Green Bay Packerspreview',
 '17SunDecember 301:00PMMiami Dolphins@Buffalo Billspreview',
 '17SunDecember 301:00PMCarolina Panthers@New Orleans Saintspreview',
 '17SunDecember 301:00PMChicago Bears@Minnesota Vikingspreview',
 '17SunDecember 301:00PMDallas Cowboys@New York Giantspreview',
 '17SunDecember 301:00PMPhiladelphia Eagles@Washington Redskinspreview',
 '17SunDecember 301:00PMCincinnati Bengals@Pittsburgh Steelerspreview',
 '17SunDecember 301:00PMOakland Raiders@Kansas City Chiefspreview',
 '17SunDecember 304:25PMArizona Cardinals@Seattle Seahawkspreview',
 '17SunDecember 304:25PMLos Angeles Chargers@Denver Broncospreview',
 '17SunDecember 304:25PMSan Francisco 49ers@Los Angeles Ramspreview']

In [89]:
# Remove any lines that dont describe weekly nfl game


weeks.remove( '\nWeek\nDay\nDate\nTime\nVisitor\n\nHome\n\nPtsW\nPtsL\nYdsW\nTOW\nYdsL\nTOL\n')

ValueError: list.remove(x): x not in list

In [90]:
weeks

['1ThuSeptember 68:20PMPhiladelphia EaglesAtlanta Falconsboxscore181223222991',
 '1SunSeptember 91:00PMCincinnati Bengals@Indianapolis Coltsboxscore342333023802',
 '1SunSeptember 91:00PMJacksonville Jaguars@New York Giantsboxscore201530513242',
 '1SunSeptember 91:00PMTampa Bay Buccaneers@New Orleans Saintsboxscore484052904752',
 '1SunSeptember 91:00PMNew England PatriotsHouston Texansboxscore272038933252',
 '1SunSeptember 91:00PMPittsburgh Steelers@Cleveland Brownsboxscore212147263271',
 '1SunSeptember 91:00PMMinnesota VikingsSan Francisco 49ersboxscore241634313274',
 '1SunSeptember 91:00PMBaltimore RavensBuffalo Billsboxscore47336911532',
 '1SunSeptember 91:00PMMiami DolphinsTennessee Titansboxscore272034223363',
 '1SunSeptember 94:05PMKansas City Chiefs@Los Angeles Chargersboxscore382836205412',
 '1SunSeptember 94:25PMWashington Redskins@Arizona Cardinalsboxscore24642912132',
 '1SunSeptember 94:25PMDenver BroncosSeattle Seahawksboxscore272447033063',
 '1SunSeptember 94:25PMCarolina PanthersDallas Cowboysboxscore16829312321',
 '1SunSeptember 98:20PMGreen Bay PackersChicago Bearsboxscore242337022941',
 '1MonSeptember 107:10PMNew York Jets@Detroit Lionsboxscore481734923395',
 '1MonSeptember 1010:20PMLos Angeles Rams@Oakland Raidersboxscore331336503953',
 '2ThuSeptember 138:20PMCincinnati BengalsBaltimore Ravensboxscore342337304253',
 '2SunSeptember 161:00PMLos Angeles Chargers@Buffalo Billsboxscore312034902932',
 '2SunSeptember 161:00PMMiami Dolphins@New York Jetsboxscore201225723623',
 '2SunSeptember 161:00PMAtlanta FalconsCarolina Panthersboxscore312444214391',
 '2SunSeptember 161:00PMKansas City Chiefs@Pittsburgh Steelersboxscore423744914750',
 '2SunSeptember 161:00PMIndianapolis Colts@Washington Redskinsboxscore21928123341',
 '2SunSeptember 161:00PMTampa Bay BuccaneersPhiladelphia Eaglesboxscore272143624122',
 '2SunSeptember 161:00PMTennessee TitansHouston Texansboxscore201728304371',
 '2SunSeptember 161:00PMMinnesota Vikings@Green Bay Packersboxscore292948013510',
 '2SunSeptember 161:00PMNew Orleans SaintsCleveland Brownsboxscore211827523271',
 '2SunSeptember 164:05PMSan Francisco 49ersDetroit Lionsboxscore302734604271',
 '2SunSeptember 164:05PMLos Angeles RamsArizona Cardinalsboxscore34043211371',
 '2SunSeptember 164:25PMDenver BroncosOakland Raidersboxscore201938513730',
 '2SunSeptember 164:25PMJacksonville JaguarsNew England Patriotsboxscore312048023021',
 '2SunSeptember 168:20PMDallas CowboysNew York Giantsboxscore201329802551',
 '2MonSeptember 178:15PMChicago BearsSeattle Seahawksboxscore241727122762',
 '3ThuSeptember 208:20PMCleveland BrownsNew York Jetsboxscore211732302683',
 '3SunSeptember 231:00PMWashington RedskinsGreen Bay Packersboxscore311738613401',
 '3SunSeptember 231:00PMBuffalo Bills@Minnesota Vikingsboxscore27629202923',
 '3SunSeptember 231:00PMMiami DolphinsOakland Raidersboxscore282037304342',
 '3SunSeptember 231:00PMNew Orleans Saints@Atlanta Falconsboxscore433753404070',
 '3SunSeptember 231:00PMKansas City ChiefsSan Francisco 49ersboxscore382738404060',
 '3SunSeptember 231:00PMBaltimore RavensDenver Broncosboxscore271434202931',
 '3SunSeptember 231:00PMPhiladelphia EaglesIndianapolis Coltsboxscore201637922090',
 '3SunSeptember 231:00PMTennessee Titans@Jacksonville Jaguarsboxscore9623302321',
 '3SunSeptember 231:00PMCarolina PanthersCincinnati Bengalsboxscore312137703964',
 '3SunSeptember 231:00PMNew York Giants@Houston Texansboxscore272237904272',
 '3SunSeptember 234:05PMLos Angeles RamsLos Angeles Chargersboxscore352352123562',
 '3SunSeptember 234:25PMChicago Bears@Arizona Cardinalsboxscore161431622214',
 '3SunSeptember 234:25PMSeattle SeahawksDallas Cowboysboxscore241329503033',
 '3SunSeptember 238:20PMDetroit LionsNew England Patriotsboxscore261041412091',
 '3MonSeptember 248:15PMPittsburgh Steelers@Tampa Bay Buccaneersboxscore302741314554',
 '4ThuSeptember 278:20PMLos Angeles RamsMinnesota Vikingsboxscore383155604461',
 '4SunSeptember 301:00PMTampa Bay Buccaneers@Chicago Bearspreview',
 '4SunSeptember 301:00PMDetroit Lions@Dallas Cowboyspreview',
 '4SunSeptember 301:00PMBuffalo Bills@Green Bay Packerspreview',
 '4SunSeptember 301:00PMMiami Dolphins@New England Patriotspreview',
 '4SunSeptember 301:00PMNew York Jets@Jacksonville Jaguarspreview',
 '4SunSeptember 301:00PMPhiladelphia Eagles@Tennessee Titanspreview',
 '4SunSeptember 301:00PMHouston Texans@Indianapolis Coltspreview',
 '4SunSeptember 301:00PMCincinnati Bengals@Atlanta Falconspreview',
 '4SunSeptember 304:05PMSeattle Seahawks@Arizona Cardinalspreview',
 '4SunSeptember 304:05PMCleveland Browns@Oakland Raiderspreview',
 '4SunSeptember 304:25PMSan Francisco 49ers@Los Angeles Chargerspreview',
 '4SunSeptember 304:25PMNew Orleans Saints@New York Giantspreview',
 '4SunSeptember 308:20PMBaltimore Ravens@Pittsburgh Steelerspreview',
 '4MonOctober 18:15PMKansas City Chiefs@Denver Broncospreview',
 '5ThuOctober 48:20PMIndianapolis Colts@New England Patriotspreview',
 '5SunOctober 71:00PMNew York Giants@Carolina Pantherspreview',
 '5SunOctober 71:00PMTennessee Titans@Buffalo Billspreview',
 '5SunOctober 71:00PMGreen Bay Packers@Detroit Lionspreview',
 '5SunOctober 71:00PMMiami Dolphins@Cincinnati Bengalspreview',
 '5SunOctober 71:00PMBaltimore Ravens@Cleveland Brownspreview',
 '5SunOctober 71:00PMDenver Broncos@New York Jetspreview',
 '5SunOctober 71:00PMJacksonville Jaguars@Kansas City Chiefspreview',
 '5SunOctober 71:00PMAtlanta Falcons@Pittsburgh Steelerspreview',
 '5SunOctober 74:05PMOakland Raiders@Los Angeles Chargerspreview',
 '5SunOctober 74:25PMLos Angeles Rams@Seattle Seahawkspreview',
 '5SunOctober 74:25PMArizona Cardinals@San Francisco 49erspreview',
 '5SunOctober 74:25PMMinnesota Vikings@Philadelphia Eaglespreview',
 '5SunOctober 78:20PMDallas Cowboys@Houston Texanspreview',
 '5MonOctober 88:15PMWashington Redskins@New Orleans Saintspreview',
 '6ThuOctober 118:20PMPhiladelphia Eagles@New York Giantspreview',
 '6SunOctober 141:00PMSeattle Seahawks@Oakland Raiderspreview',
 '6SunOctober 141:00PMTampa Bay Buccaneers@Atlanta Falconspreview',
 '6SunOctober 141:00PMCarolina Panthers@Washington Redskinspreview',
 '6SunOctober 141:00PMBuffalo Bills@Houston Texanspreview',
 '6SunOctober 141:00PMIndianapolis Colts@New York Jetspreview',
 '6SunOctober 141:00PMArizona Cardinals@Minnesota Vikingspreview',
 '6SunOctober 141:00PMChicago Bears@Miami Dolphinspreview',
 '6SunOctober 141:00PMLos Angeles Chargers@Cleveland Brownspreview',
 '6SunOctober 141:00PMPittsburgh Steelers@Cincinnati Bengalspreview',
 '6SunOctober 144:05PMLos Angeles Rams@Denver Broncospreview',
 '6SunOctober 144:25PMJacksonville Jaguars@Dallas Cowboyspreview',
 '6SunOctober 144:25PMBaltimore Ravens@Tennessee Titanspreview',
 '6SunOctober 148:20PMKansas City Chiefs@New England Patriotspreview',
 '6MonOctober 158:15PMSan Francisco 49ers@Green Bay Packerspreview',
 '7ThuOctober 188:20PMDenver Broncos@Arizona Cardinalspreview',
 '7SunOctober 219:30AMTennessee Titans@Los Angeles Chargerspreview',
 '7SunOctober 211:00PMCincinnati Bengals@Kansas City Chiefspreview',
 '7SunOctober 211:00PMNew England Patriots@Chicago Bearspreview',
 '7SunOctober 211:00PMCleveland Browns@Tampa Bay Buccaneerspreview',
 '7SunOctober 211:00PMDetroit Lions@Miami Dolphinspreview',
 '7SunOctober 211:00PMCarolina Panthers@Philadelphia Eaglespreview',
 '7SunOctober 211:00PMBuffalo Bills@Indianapolis Coltspreview',
 '7SunOctober 211:00PMMinnesota Vikings@New York Jetspreview',
 '7SunOctober 211:00PMHouston Texans@Jacksonville Jaguarspreview',
 '7SunOctober 214:05PMNew Orleans Saints@Baltimore Ravenspreview',
 '7SunOctober 214:25PMDallas Cowboys@Washington Redskinspreview',
 '7SunOctober 218:20PMLos Angeles Rams@San Francisco 49erspreview',
 '7MonOctober 228:15PMNew York Giants@Atlanta Falconspreview',
 '8ThuOctober 258:20PMMiami Dolphins@Houston Texanspreview',
 '8SunOctober 289:30AMPhiladelphia Eagles@Jacksonville Jaguarspreview',
 '8SunOctober 281:00PMBaltimore Ravens@Carolina Pantherspreview',
 '8SunOctober 281:00PMDenver Broncos@Kansas City Chiefspreview',
 '8SunOctober 281:00PMSeattle Seahawks@Detroit Lionspreview',
 '8SunOctober 281:00PMCleveland Browns@Pittsburgh Steelerspreview',
 '8SunOctober 281:00PMTampa Bay Buccaneers@Cincinnati Bengalspreview',
 '8SunOctober 281:00PMNew York Jets@Chicago Bearspreview',
 '8SunOctober 281:00PMWashington Redskins@New York Giantspreview',
 '8SunOctober 284:05PMIndianapolis Colts@Oakland Raiderspreview',
 '8SunOctober 284:25PMSan Francisco 49ers@Arizona Cardinalspreview',
 '8SunOctober 284:25PMGreen Bay Packers@Los Angeles Ramspreview',
 '8SunOctober 288:20PMNew Orleans Saints@Minnesota Vikingspreview',
 '8MonOctober 298:15PMNew England Patriots@Buffalo Billspreview',
 '9ThuNovember 18:20PMOakland Raiders@San Francisco 49erspreview',
 '9SunNovember 41:00PMPittsburgh Steelers@Baltimore Ravenspreview',
 '9SunNovember 41:00PMAtlanta Falcons@Washington Redskinspreview',
 '9SunNovember 41:00PMDetroit Lions@Minnesota Vikingspreview',
 '9SunNovember 41:00PMKansas City Chiefs@Cleveland Brownspreview',
 '9SunNovember 41:00PMTampa Bay Buccaneers@Carolina Pantherspreview',
 '9SunNovember 41:00PMNew York Jets@Miami Dolphinspreview',
 '9SunNovember 41:00PMChicago Bears@Buffalo Billspreview',
 '9SunNovember 44:05PMHouston Texans@Denver Broncospreview',
 '9SunNovember 44:05PMLos Angeles Chargers@Seattle Seahawkspreview',
 '9SunNovember 44:25PMLos Angeles Rams@New Orleans Saintspreview',
 '9SunNovember 48:20PMGreen Bay Packers@New England Patriotspreview',
 '9MonNovember 58:15PMTennessee Titans@Dallas Cowboyspreview',
 '10ThuNovember 88:20PMCarolina Panthers@Pittsburgh Steelerspreview',
 '10SunNovember 111:00PMJacksonville Jaguars@Indianapolis Coltspreview',
 '10SunNovember 111:00PMNew Orleans Saints@Cincinnati Bengalspreview',
 '10SunNovember 111:00PMAtlanta Falcons@Cleveland Brownspreview',
 '10SunNovember 111:00PMNew England Patriots@Tennessee Titanspreview',
 '10SunNovember 111:00PMDetroit Lions@Chicago Bearspreview',
 '10SunNovember 111:00PMArizona Cardinals@Kansas City Chiefspreview',
 '10SunNovember 111:00PMBuffalo Bills@New York Jetspreview',
 '10SunNovember 111:00PMWashington Redskins@Tampa Bay Buccaneerspreview',
 '10SunNovember 111:00PMMiami Dolphins@Green Bay Packerspreview',
 '10SunNovember 114:05PMLos Angeles Chargers@Oakland Raiderspreview',
 '10SunNovember 114:25PMSeattle Seahawks@Los Angeles Ramspreview',
 '10SunNovember 118:20PMDallas Cowboys@Philadelphia Eaglespreview',
 '10MonNovember 128:15PMNew York Giants@San Francisco 49erspreview',
 '11ThuNovember 158:20PMGreen Bay Packers@Seattle Seahawkspreview',
 '11SunNovember 181:00PMMinnesota Vikings@Chicago Bearspreview',
 '11SunNovember 181:00PMTennessee Titans@Indianapolis Coltspreview',
 '11SunNovember 181:00PMPhiladelphia Eagles@New Orleans Saintspreview',
 '11SunNovember 181:00PMCincinnati Bengals@Baltimore Ravenspreview',
 '11SunNovember 181:00PMDallas Cowboys@Atlanta Falconspreview',
 '11SunNovember 181:00PMHouston Texans@Washington Redskinspreview',
 '11SunNovember 181:00PMTampa Bay Buccaneers@New York Giantspreview',
 '11SunNovember 181:00PMCarolina Panthers@Detroit Lionspreview',
 '11SunNovember 184:05PMDenver Broncos@Los Angeles Chargerspreview',
 '11SunNovember 184:05PMOakland Raiders@Arizona Cardinalspreview',
 '11SunNovember 188:20PMPittsburgh Steelers@Jacksonville Jaguarspreview',
 '11MonNovember 198:15PMKansas City Chiefs@Los Angeles Ramspreview',
 '12ThuNovember 2212:30PMChicago Bears@Detroit Lionspreview',
 '12ThuNovember 224:30PMWashington Redskins@Dallas Cowboyspreview',
 '12ThuNovember 228:20PMAtlanta Falcons@New Orleans Saintspreview',
 '12SunNovember 251:00PMMiami Dolphins@Indianapolis Coltspreview',
 '12SunNovember 251:00PMJacksonville Jaguars@Buffalo Billspreview',
 '12SunNovember 251:00PMCleveland Browns@Cincinnati Bengalspreview',
 '12SunNovember 251:00PMSan Francisco 49ers@Tampa Bay Buccaneerspreview',
 '12SunNovember 251:00PMOakland Raiders@Baltimore Ravenspreview',
 '12SunNovember 251:00PMSeattle Seahawks@Carolina Pantherspreview',
 '12SunNovember 251:00PMNew England Patriots@New York Jetspreview',
 '12SunNovember 251:00PMNew York Giants@Philadelphia Eaglespreview',
 '12SunNovember 254:05PMArizona Cardinals@Los Angeles Chargerspreview',
 '12SunNovember 254:25PMPittsburgh Steelers@Denver Broncospreview',
 '12SunNovember 258:20PMGreen Bay Packers@Minnesota Vikingspreview',
 '12MonNovember 268:15PMTennessee Titans@Houston Texanspreview',
 '13ThuNovember 298:20PMNew Orleans Saints@Dallas Cowboyspreview',
 '13SunDecember 21:00PMBuffalo Bills@Miami Dolphinspreview',
 '13SunDecember 21:00PMCarolina Panthers@Tampa Bay Buccaneerspreview',
 '13SunDecember 21:00PMArizona Cardinals@Green Bay Packerspreview',
 '13SunDecember 21:00PMBaltimore Ravens@Atlanta Falconspreview',
 '13SunDecember 21:00PMChicago Bears@New York Giantspreview',
 '13SunDecember 21:00PMLos Angeles Chargers@Pittsburgh Steelerspreview',
 '13SunDecember 21:00PMDenver Broncos@Cincinnati Bengalspreview',
 '13SunDecember 21:00PMCleveland Browns@Houston Texanspreview',
 '13SunDecember 21:00PMIndianapolis Colts@Jacksonville Jaguarspreview',
 '13SunDecember 21:00PMLos Angeles Rams@Detroit Lionspreview',
 '13SunDecember 24:05PMNew York Jets@Tennessee Titanspreview',
 '13SunDecember 24:05PMKansas City Chiefs@Oakland Raiderspreview',
 '13SunDecember 24:25PMMinnesota Vikings@New England Patriotspreview',
 '13SunDecember 28:20PMSan Francisco 49ers@Seattle Seahawkspreview',
 '13MonDecember 38:15PMWashington Redskins@Philadelphia Eaglespreview',
 '14ThuDecember 68:20PMJacksonville Jaguars@Tennessee Titanspreview',
 '14SunDecember 91:00PMIndianapolis Colts@Houston Texanspreview',
 '14SunDecember 91:00PMLos Angeles Rams@Chicago Bearspreview',
 '14SunDecember 91:00PMNew York Jets@Buffalo Billspreview',
 '14SunDecember 91:00PMCarolina Panthers@Cleveland Brownspreview',
 '14SunDecember 91:00PMBaltimore Ravens@Kansas City Chiefspreview',
 '14SunDecember 91:00PMNew Orleans Saints@Tampa Bay Buccaneerspreview',
 '14SunDecember 91:00PMAtlanta Falcons@Green Bay Packerspreview',
 '14SunDecember 91:00PMNew England Patriots@Miami Dolphinspreview',
 '14SunDecember 91:00PMNew York Giants@Washington Redskinspreview',
 '14SunDecember 94:05PMCincinnati Bengals@Los Angeles Chargerspreview',
 '14SunDecember 94:05PMDenver Broncos@San Francisco 49erspreview',
 '14SunDecember 94:25PMPhiladelphia Eagles@Dallas Cowboyspreview',
 '14SunDecember 94:25PMDetroit Lions@Arizona Cardinalspreview',
 '14SunDecember 98:20PMPittsburgh Steelers@Oakland Raiderspreview',
 '14MonDecember 108:15PMMinnesota Vikings@Seattle Seahawkspreview',
 '15ThuDecember 138:20PMLos Angeles Chargers@Kansas City Chiefspreview',
 '15SatDecember 154:30PMHouston Texans@New York Jetspreview',
 '15SatDecember 154:30PMCleveland Browns@Denver Broncospreview',
 '15SunDecember 161:00PMTampa Bay Buccaneers@Baltimore Ravenspreview',
 '15SunDecember 161:00PMDetroit Lions@Buffalo Billspreview',
 '15SunDecember 161:00PMMiami Dolphins@Minnesota Vikingspreview',
 '15SunDecember 161:00PMArizona Cardinals@Atlanta Falconspreview',
 '15SunDecember 161:00PMWashington Redskins@Jacksonville Jaguarspreview',
 '15SunDecember 161:00PMTennessee Titans@New York Giantspreview',
 '15SunDecember 161:00PMGreen Bay Packers@Chicago Bearspreview',
 '15SunDecember 161:00PMDallas Cowboys@Indianapolis Coltspreview',
 '15SunDecember 161:00PMOakland Raiders@Cincinnati Bengalspreview',
 '15SunDecember 164:05PMSeattle Seahawks@San Francisco 49erspreview',
 '15SunDecember 164:25PMNew England Patriots@Pittsburgh Steelerspreview',
 '15SunDecember 168:20PMPhiladelphia Eagles@Los Angeles Ramspreview',
 '15MonDecember 178:15PMNew Orleans Saints@Carolina Pantherspreview',
 '16SunDecember 231:00PMNew York Giants@Indianapolis Coltspreview',
 '16SunDecember 231:00PMBuffalo Bills@New England Patriotspreview',
 '16SunDecember 231:00PMTampa Bay Buccaneers@Dallas Cowboyspreview',
 '16SunDecember 231:00PMMinnesota Vikings@Detroit Lionspreview',
 '16SunDecember 231:00PMCincinnati Bengals@Cleveland Brownspreview',
 '16SunDecember 231:00PMWashington Redskins@Tennessee Titanspreview',
 '16SunDecember 231:00PMGreen Bay Packers@New York Jetspreview',
 '16SunDecember 231:00PMHouston Texans@Philadelphia Eaglespreview',
 '16SunDecember 231:00PMJacksonville Jaguars@Miami Dolphinspreview',
 '16SunDecember 231:00PMAtlanta Falcons@Carolina Pantherspreview',
 '16SunDecember 234:05PMLos Angeles Rams@Arizona Cardinalspreview',
 '16SunDecember 234:05PMChicago Bears@San Francisco 49erspreview',
 '16SunDecember 234:05PMBaltimore Ravens@Los Angeles Chargerspreview',
 '16SunDecember 234:25PMPittsburgh Steelers@New Orleans Saintspreview',
 '16SunDecember 238:20PMKansas City Chiefs@Seattle Seahawkspreview',
 '16MonDecember 248:15PMDenver Broncos@Oakland Raiderspreview',
 '17SunDecember 301:00PMJacksonville Jaguars@Houston Texanspreview',
 '17SunDecember 301:00PMAtlanta Falcons@Tampa Bay Buccaneerspreview',
 '17SunDecember 301:00PMCleveland Browns@Baltimore Ravenspreview',
 '17SunDecember 301:00PMIndianapolis Colts@Tennessee Titanspreview',
 '17SunDecember 301:00PMNew York Jets@New England Patriotspreview',
 '17SunDecember 301:00PMDetroit Lions@Green Bay Packerspreview',
 '17SunDecember 301:00PMMiami Dolphins@Buffalo Billspreview',
 '17SunDecember 301:00PMCarolina Panthers@New Orleans Saintspreview',
 '17SunDecember 301:00PMChicago Bears@Minnesota Vikingspreview',
 '17SunDecember 301:00PMDallas Cowboys@New York Giantspreview',
 '17SunDecember 301:00PMPhiladelphia Eagles@Washington Redskinspreview',
 '17SunDecember 301:00PMCincinnati Bengals@Pittsburgh Steelerspreview',
 '17SunDecember 301:00PMOakland Raiders@Kansas City Chiefspreview',
 '17SunDecember 304:25PMArizona Cardinals@Seattle Seahawkspreview',
 '17SunDecember 304:25PMLos Angeles Chargers@Denver Broncospreview',
 '17SunDecember 304:25PMSan Francisco 49ers@Los Angeles Ramspreview']

In [91]:
# Split string a first non digit and use result for week varianble of each individual matchup

week =[] 
for row in weeks:
    if int(re.split(r'(\d+)', row)[1]) < 4:
        week.append(int(re.split(r'(\d+)', row)[1]))

In [92]:
week

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3]

In [93]:
# Use beautiful to retrieve detail on each game in an NFL season

def loc_df(bso4):

    game =[]
    for td in bso4.find_all('td'):
        game.append(td.text)

    # Create lists to establish the home and away teams in every game of an NFL season

    home = []
    away =[]
    try:
        for idx,val in enumerate(game):
            if val == '':
                home.append(game[idx-1])
                away.append(game[idx+1])
            elif val =='@':
                home.append(game[idx+1])
                away.append(game[idx-1])
    except:
        None

    # Create a dataframe to hold the location of every NFL game by week

    location = pd.DataFrame(columns = ['week','home','away','year'])

    # insert current weekly data into location dataframe

    location ['week'] = week
    location['home']=home[0:len(week)]
    location['away']=away[0:len(week)]
    location['year']=2018

    location.shape

    location= location.replace({"away": team_dict})
    location= location.replace({"home": team_dict})

    # Convert the NFL team names that are not in Team Dictiionary by capitalizing the first three character of the team name 

    try:
        location['home'] = location['home'].apply(lambda x: x[0:3].upper())
        location['away'] = location['away'].apply(lambda x: x[0:3].upper())
    except:
        None
        
        
    return location

In [94]:
soup = BeautifulSoup(page.text,'html.parser')

In [95]:
location = loc_df(soup)

In [96]:
location

    week home away  year
0      1  PHI  ATL  2018
1      1  IND  CIN  2018
2      1  NYG  JAX  2018
3      1   NO   TB  2018
4      1   NE  HOU  2018
5      1  CLE  PIT  2018
6      1  MIN   SF  2018
7      1  BAL  BUF  2018
8      1  MIA  TEN  2018
9      1  LAC   KC  2018
10     1  ARI  WAS  2018
11     1  DEN  SEA  2018
12     1  CAR  DAL  2018
13     1   GB  CHI  2018
14     1  DET  NYJ  2018
15     1  OAK  LAR  2018
16     2  CIN  BAL  2018
17     2  BUF  LAC  2018
18     2  NYJ  MIA  2018
19     2  ATL  CAR  2018
20     2  PIT   KC  2018
21     2  WAS  IND  2018
22     2   TB  PHI  2018
23     2  TEN  HOU  2018
24     2   GB  MIN  2018
25     2   NO  CLE  2018
26     2   SF  DET  2018
27     2  LAR  ARI  2018
28     2  DEN  OAK  2018
29     2  JAX   NE  2018
30     2  DAL  NYG  2018
31     2  CHI  SEA  2018
32     3  CLE  NYJ  2018
33     3  WAS   GB  2018
34     3  MIN  BUF  2018
35     3  MIA  OAK  2018
36     3  ATL   NO  2018
37     3   KC   SF  2018
38     3  BAL  DEN  2018
39     3  PHI  IND  2018
40     3  JAX  TEN  2018
41     3  CAR  CIN  2018
42     3  HOU  NYG  2018
43     3  LAR  LAC  2018
44     3  ARI  CHI  2018
45     3  SEA  DAL  2018
46     3  DET   NE  2018
47     3   TB  PIT  2018

In [275]:
df = df[df['Week']!=4]
df_sal = df_sal[df_sal['Week']!=4]

In [124]:
df['year']=2018

In [98]:
df1.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns',
       'FantasyPointsDraftKings', 'salary', 'year'],
      dtype='object')

In [99]:
qb.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'salary', 'year',
       'def_rk', 'h/a', 'surface', 'h/a0', 'h/a1', 'surface_0', 'surface_1',
       'FantasyPointsDraftKings'],
      dtype='object')

In [106]:
def_2018.columns

Index(['Rank', 'Name', 'Team', 'Position', 'Played',
       'DraftKingsQuarterbackFantasyPointsAllowedAverage',
       'DraftKingsRunningbackFantasyPointsAllowedAverage',
       'DraftKingsWideReceiverFantasyPointsAllowedAverage',
       'DraftKingsTightEndFantasyPointsAllowedAverage',
       'DraftKingsKickerFantasyPointsAllowedAverage',
       'DraftKingsFantasyPointsAllowedAverage'],
      dtype='object')

In [100]:
# Prepare defense dataframe by sorting by relevant attribute reseting the indexand using rank as the reset dataframe index +1

def_2018.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)
def_2018.reset_index(inplace=True)
def_2018['Rank']= def_2018.index+1
def_2018.index=def_2018['Team']



# Map defensive rnking to eack player in the statistical dataframe 

df1['def_rk'] = list(map(lambda x: def_2018.loc[x]['Rank'], df1['Opponent']))
df1.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,...,0,121.69,2,3,1.5,0,21.74,4900,2018,20
1,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,...,1,57.41,2,8,4.0,0,9.84,6300,2018,17
2,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,...,0,130.69,1,15,15.0,0,24.94,4500,2018,16
3,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,...,3,60.52,3,16,5.3,0,17.00,7500,2018,4
4,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,...,1,102.19,1,2,2.0,0,22.28,6600,2018,12

In [230]:
df_sal.shape

(443, 11)

In [101]:
week1  = df1[df1['Week']==1]
week2 = df1[df1['Week']==2]
week3 = df1[df1['Week']==3]

In [104]:
loc_df = location[location['week']==3];home_list = []
for team in week3['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

week3['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [105]:
week3.fillna(0, inplace=True)
week3.columns

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\pandas\core\frame.py:2754: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  downcast=downcast, **kwargs)

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns',
       'FantasyPointsDraftKings', 'salary', 'year', 'def_rk', 'h/a'],
      dtype='object')

In [107]:
qb_2018 = pd.concat([qb_2018,week3])
qb_2018.tail()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
111,19763,Josh Rosen,ARI,3,CHI,4,7,57.1,36,5.1,...,31.55,1,12,12.0,0,1.64,6000,2018,16,home
112,19781,Lamar Jackson,BAL,3,DEN,0,0,0.0,0,0.0,...,0.00,0,0,0.0,0,0.00,5000,2018,15,home
113,19790,Baker Mayfield,CLE,3,NYJ,17,23,73.9,201,8.7,...,100.09,2,-2,-1.0,0,9.84,5800,2018,6,home
114,19801,Josh Allen,BUF,3,MIN,15,22,68.2,196,8.9,...,111.17,10,39,3.9,2,27.74,5900,2018,25,away
115,19812,Sam Darnold,NYJ,3,CLE,15,31,48.4,169,5.5,...,38.24,0,0,0.0,0,4.76,4900,2018,4,away

In [282]:
te_2018.fillna(0, inplace=True)

In [283]:
te_2018['year']=2018

In [231]:
wr_2018.fillna(0, inplace=True)

In [108]:
surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'
              
             }

In [109]:
qb_2018.index = qb_2018['Team']

# Add the type of field the player palyed on by mapping the field on which the game was played to the surface dictionary

surface = []
for idx, team in enumerate(qb_2018['Team']):
    if qb_2018.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[qb_2018.iloc[idx]['Opponent']])


qb_2018['surface'] = surface

In [289]:
cols = te_2018.columns.tolist()
cols = cols[:-2] +cols[-1:]+cols[-2:-1]
te_2018=te_2018[cols]

In [252]:
rb_2018['year']=2018

In [233]:
wr_2018.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a,surface
Team,,,,,,,,,,,,,,,,,,,,,
BUF,20250,Robert Foster,BUF,3,MIN,2,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,22,away,turf
HOU,20295,Vyncint Smith,HOU,3,NYG,2,1,50.0,28,0,...,0.0,0,0,0,3.8,2018,0,8,home,turf
LAC,20310,JJ Jones,LAC,3,LAR,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,12,away,grass
CLE,20477,Derrick Willies,CLE,3,NYJ,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,17,home,grass
LAR,20679,Khadarel Hodge,LAR,3,LAC,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,30,home,grass

In [88]:
rb_2018['year']=2018

In [253]:
rb_2018.tail()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,...,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
338,20159,Mike Boone,MIN,3,BUF,2,11,5.5,0,1,...,0,0,0,0,2.1,7800,28,home,turf,2018
339,20309,Detrez Newsome,LAC,3,LAR,0,0,0.0,0,0,...,0,0,0,0,0.0,5100,12,away,grass,2018
340,20318,Gregory Howell Jr.,HOU,3,NYG,0,0,0.0,0,0,...,0,0,0,0,0.0,3200,9,home,turf,2018
341,20472,Shaun Wilson,TB,3,PIT,0,0,0.0,0,2,...,9,0,0,0,2.9,6400,4,home,grass,2018
342,20562,De'Lance Turner,BAL,3,DEN,0,0,0.0,0,0,...,0,0,0,0,0.0,4100,18,home,grass,2018

In [290]:
te_2018.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
277,19943,Durham Smythe,MIA,3,OAK,0,0,0.0,0,0,...,0,0,0,0,0.0,2500,6,home,grass,2018
278,19947,Chris Herndon IV,NYJ,3,CLE,2,2,100.0,-1,0,...,0,0,0,0,1.9,null,4,away,grass,2018
279,19950,Will Dissly,SEA,3,DAL,3,1,33.3,4,0,...,0,0,0,0,1.4,null,20,home,turf,2018
280,19988,Tyler Conklin,MIN,3,BUF,1,1,100.0,7,0,...,0,0,0,0,1.7,2500,22,home,turf,2018
281,20020,Jordan Thomas,HOU,3,NYG,2,2,100.0,53,0,...,0,0,0,0,7.3,2900,7,home,turf,2018

In [110]:
qb_2018.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
Team,,,,,,,,,,,,,,,,,,,,,
BAL,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,...,2,3,1.5,0,21.74,4900,2018,20,home,grass
ATL,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,...,2,8,4.0,0,9.84,6300,2018,17,away,grass
GB,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,...,1,15,15.0,0,24.94,4500,2018,16,home,grass
PIT,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,...,3,16,5.3,0,17.00,7500,2018,4,away,grass
NE,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,...,1,2,2.0,0,22.28,6600,2018,12,home,turf

In [112]:

def one_hot(df):
    encoder = LabelEncoder()
    df['h/a_encoded'] = encoder.fit_transform(df['h/a'])
    df['surface_encoded'] = encoder.fit_transform(df['surface'])


    home =OneHotEncoder()
    surface = OneHotEncoder()

    X = home.fit_transform(df['h/a_encoded'].values.reshape(-1,1)).toarray()
    Xs = surface.fit_transform(df['surface_encoded'].values.reshape(-1,1)).toarray()

    dfOneHot = pd.DataFrame(X, columns = ["h/a_"+str(int(i)) for i in range(X.shape[1])])
    df = pd.concat([df, dfOneHot], axis=1)


    dfOneHot = pd.DataFrame(Xs, columns = ['surface_'+str(int(i)) for i in range(Xs.shape[1])])
    df = pd.concat([df, dfOneHot], axis=1)

    return df

In [117]:
qb_2018.reset_index(inplace=True, drop=True)

In [118]:
qb_2018.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface,h/a_encoded,surface_encoded
0,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,...,1.5,0,21.74,4900,2018,20,home,grass,1,0
1,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,...,4.0,0,9.84,6300,2018,17,away,grass,0,0
2,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,...,15.0,0,24.94,4500,2018,16,home,grass,1,0
3,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,...,5.3,0,17.00,7500,2018,4,away,grass,0,0
4,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,...,2.0,0,22.28,6600,2018,12,home,turf,1,1

In [119]:
qb_2018 = one_hot(qb_2018)

In [124]:
qb_2018.drop(['h/a_encoded','surface_encoded'], axis=1, inplace=True)

In [121]:
qb.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'salary', 'year',
       'def_rk', 'h/a', 'surface', 'h/a0', 'h/a1', 'surface_0', 'surface_1',
       'FantasyPointsDraftKings'],
      dtype='object')

##

In [ ]:
qb_2018.drop(['surface', 'h/a'], axis=1, inplace=True)

In [128]:
qb_2018.rename(columns={'h/a_0':'h/a0',
                      'h/a_1':'h/a1'}, inplace=True)

In [291]:
te=pd.concat([te,te_2018])
te.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
277,19943,Durham Smythe,MIA,3,OAK,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,6,home,grass,2018
278,19947,Chris Herndon IV,NYJ,3,CLE,2,2,100.0,-1,0,...,0.0,0,0,0,1.9,null,4,away,grass,2018
279,19950,Will Dissly,SEA,3,DAL,3,1,33.3,4,0,...,0.0,0,0,0,1.4,null,20,home,turf,2018
280,19988,Tyler Conklin,MIN,3,BUF,1,1,100.0,7,0,...,0.0,0,0,0,1.7,2500,22,home,turf,2018
281,20020,Jordan Thomas,HOU,3,NYG,2,2,100.0,53,0,...,0.0,0,0,0,7.3,2900,7,home,turf,2018

In [235]:
wr.shape

(9100, 25)

In [143]:
wr_2018.Week.unique()

array([1, 2], dtype=int64)

In [292]:
te.to_csv('input/te/dk_stats_loc.csv', index=False)

## Quarterbacks

In [160]:
qb= pd.read_csv('input/qb/dk_stats_loc.csv')
qb_2018 = pd.read_csv('input/qb/fantasy-football-leaders (1).csv')
qb_2018_sal = pd.read_csv('input/qb/daily-fantasy-football-salary-and-projection-tool.csv')

In [21]:
# A function designed to add the Draftkings fantasy football salary to every players statistics dataframe

def add_salary(df,df2):
    df = df.sort_values(['Week','PlayerID'])
    df = df.drop(['FantasyPointsPerGameDraftKings','Rank','Position'], axis=1)
    df.reset_index(inplace=True, drop=True)
    df2 = df2.sort_values(['Week','PlayerID'])
    df2 = df2.drop(['Rank','Position'], axis=1)
    df2.reset_index(inplace=True, drop=True)
    df['salary'] = df2['DraftKingsSalary']
    
    return df

In [70]:
df.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,...,PassingYardsPerAttempt,PassingTouchdowns,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
0,1,8283,Ryan Fitzpatrick,TB,QB,1,NO,21,28,75.0,...,14.9,4,0,156.25,12,36,3.0,1,45.3,45.28
1,2,7242,Drew Brees,NO,QB,3,ATL,39,49,79.6,...,8.1,3,0,120.75,3,7,2.3,2,43.5,43.54
2,3,732,Matt Ryan,ATL,QB,3,NO,26,35,74.3,...,10.7,5,0,148.10,4,12,3.0,0,43.2,43.16
3,4,17922,Jared Goff,LAR,QB,4,MIN,26,33,78.8,...,14.1,5,0,158.33,2,7,3.5,0,42.3,42.30
4,5,3807,Ben Roethlisberger,PIT,QB,2,KC,39,60,65.0,...,7.5,3,0,104.31,2,9,4.5,1,42.0,41.98

In [161]:
qb.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'salary', 'year',
       'def_rk', 'h/a', 'surface', 'FantasyPointsDraftKings'],
      dtype='object')

In [162]:
# Add salary to overall dataframe

qb_2018 = add_salary(qb_2018,qb_2018_sal)

In [163]:
qb_2018['year']=2018

In [164]:
qb_2018.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,PassingTouchdowns,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year
0,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,3,0,121.69,2,3,1.5,0,21.74,4900,2018
1,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,0,1,57.41,2,8,4.0,0,9.84,6300,2018
2,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,3,0,130.69,1,15,15.0,0,24.94,4500,2018
3,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,1,3,60.52,3,16,5.3,0,17.00,7500,2018
4,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,3,1,102.19,1,2,2.0,0,22.28,6600,2018

In [167]:
# Prepare defense dataframe by sorting by relevant attribute reseting the indexand using rank as the reset dataframe index +1

def_2018.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)
def_2018.reset_index(inplace=True)
def_2018['Rank']= def_2018.index+1
def_2018.index=def_2018['Team']



# Map defensive rnking to eack player in the statistical dataframe 

qb_2018['def_rk'] = list(map(lambda x: def_2018.loc[x]['Rank'], qb_2018['Opponent']))
qb_2018.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,...,0,121.69,2,3,1.5,0,21.74,4900,2018,20
1,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,...,1,57.41,2,8,4.0,0,9.84,6300,2018,17
2,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,...,0,130.69,1,15,15.0,0,24.94,4500,2018,16
3,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,...,3,60.52,3,16,5.3,0,17.00,7500,2018,4
4,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,...,1,102.19,1,2,2.0,0,22.28,6600,2018,12

In [169]:
qb=qb[qb['Week']!=4]

In [179]:
location

    week home away  year
0      1  PHI  ATL  2018
1      1  MIN   SF  2018
2      1  BAL  BUF  2018
3      1  MIA  TEN  2018
4      1  IND  CIN  2018
5      1  NYG  JAX  2018
6      1   NO   TB  2018
7      1   NE  HOU  2018
8      1  CLE  PIT  2018
9      1  LAC   KC  2018
10     1  ARI  WAS  2018
11     1  DEN  SEA  2018
12     1  CAR  DAL  2018
13     1   GB  CHI  2018
14     1  DET  NYJ  2018
15     1  OAK  LAR  2018
16     2  CIN  BAL  2018
17     2   GB  MIN  2018
18     2   NO  CLE  2018
19     2  BUF  LAC  2018
20     2  NYJ  MIA  2018
21     2  ATL  CAR  2018
22     2  PIT   KC  2018
23     2  WAS  IND  2018
24     2   TB  PHI  2018
25     2  TEN  HOU  2018
26     2   SF  DET  2018
27     2  LAR  ARI  2018
28     2  DEN  OAK  2018
29     2  JAX   NE  2018
30     2  DAL  NYG  2018
31     2  CHI  SEA  2018
32     3  CLE  NYJ  2018
33     3  JAX  TEN  2018
34     3  CAR  CIN  2018
35     3  HOU  NYG  2018
36     3  WAS   GB  2018
37     3  MIN  BUF  2018
38     3  MIA  OAK  2018
39     3  ATL   NO  2018
40     3   KC   SF  2018
41     3  BAL  DEN  2018
42     3  PHI  IND  2018
43     3  LAR  LAC  2018
44     3  ARI  CHI  2018
45     3  SEA  DAL  2018
46     3  DET   NE  2018
47     3   TB  PIT  2018

In [170]:
# add home or away, and surface attributes

week1  = qb_2018[qb_2018['Week']==1]
week2 = qb_2018[qb_2018['Week']==2]
week3 = qb_2018[qb_2018['Week']==3]

In [182]:
loc_df = location[location['week']==];home_list = []
for team in week3['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

week3['h/a'] = home_list

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a,surface
BUF,20250,Robert Foster,BUF,3,MIN,2,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,22,home,turf
HOU,20295,Vyncint Smith,HOU,3,NYG,2,1,50.0,28,0,...,0.0,0,0,0,3.8,2018,0,8,home,turf
LAC,20310,JJ Jones,LAC,3,LAR,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,12,home,grass
CLE,20477,Derrick Willies,CLE,3,NYJ,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,17,home,grass
LAR,20679,Khadarel Hodge,LAR,3,LAC,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2018,0,30,home,grass

In [68]:
qb_2018.head()

,FantasyPointsDraftKings,Name,Opponent,PassingAttempts,PassingCompletionPercentage,PassingCompletions,PassingInterceptions,PassingRating,PassingTouchdowns,PassingYards,...,RushingAttempts,RushingTouchdowns,RushingYards,RushingYardsPerAttempt,Team,Week,def_rk,h/a,salary,year
0,21.74,Joe Flacco,BUF,34,73.5,25,0,121.69,3,236,...,2,0,3,1.5,BAL,1,20,NaN,4900,2018
1,9.84,Matt Ryan,PHI,43,48.8,21,1,57.41,0,251,...,2,0,8,4.0,ATL,1,17,NaN,6300,2018
2,24.94,Aaron Rodgers,CHI,30,66.7,20,0,130.69,3,286,...,1,0,15,15.0,GB,1,16,NaN,4500,2018
3,17.00,Ben Roethlisberger,CLE,41,56.1,23,3,60.52,1,335,...,3,0,16,5.3,PIT,1,4,NaN,7500,2018
4,22.28,Tom Brady,HOU,39,66.7,26,1,102.19,3,277,...,1,0,2,2.0,NE,1,12,NaN,6600,2018

In [186]:
qb_2018 = pd.concat([qb_2018,week3])
qb_2018.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
0,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,...,121.69,2,3,1.5,0,21.74,4900,2018,20,home
1,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,...,57.41,2,8,4.0,0,9.84,6300,2018,17,away
2,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,...,130.69,1,15,15.0,0,24.94,4500,2018,16,home
3,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,...,60.52,3,16,5.3,0,17.00,7500,2018,4,away
4,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,...,102.19,1,2,2.0,0,22.28,6600,2018,12,home

In [178]:
qb_2018[:33]

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a
0,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,...,121.69,2,3,1.5,0,21.74,4900,2018,20,home
1,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,...,57.41,2,8,4.0,0,9.84,6300,2018,17,home
2,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,...,130.69,1,15,15.0,0,24.94,4500,2018,16,home
3,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,...,60.52,3,16,5.3,0,17.00,7500,2018,4,home
4,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,...,102.19,1,2,2.0,0,22.28,6600,2018,12,home
5,4932,Eli Manning,NYG,1,JAX,23,37,62.2,224,6.1,...,67.85,1,2,2.0,0,8.16,7200,2018,1,home
6,6739,Alex Smith,WAS,1,ARI,21,30,70.0,255,8.5,...,118.06,8,14,1.8,0,19.60,4400,2018,10,home
7,7242,Drew Brees,NO,1,TB,37,45,82.2,439,9.8,...,129.54,0,0,0.0,0,34.56,4000,2018,28,home
8,8244,Philip Rivers,LAC,1,KC,34,51,66.7,424,8.3,...,103.72,0,0,0.0,0,32.96,4700,2018,30,home
9,8283,Ryan Fitzpatrick,TB,1,NO,21,28,75.0,417,14.9,...,156.25,12,36,3.0,1,45.28,4900,2018,32,home
10,8723,Matt Cassel,DET,1,NYJ,2,6,33.3,14,2.3,...,2.78,1,-1,-1.0,0,-0.54,5600,2018,6,home
11,9038,Matthew Stafford,DET,1,NYJ,27,46,58.7,286,6.2,...,47.92,1,6,6.0,0,12.04,6800,2018,6,home
12,11422,Joe Webb,HOU,1,NE,0,0,0.0,0,0.0,...,0.00,0,0,0.0,0,0.00,6400,2018,22,home
13,11527,Sam Bradford,ARI,1,WAS,20,34,58.8,153,4.5,...,57.60,2,7,3.5,0,4.82,5000,2018,3,home
14,12831,Tyrod Taylor,CLE,1,PIT,15,40,37.5,197,4.9,...,51.77,8,77,9.6,1,24.58,4900,2018,31,home
15,12841,Andy Dalton,CIN,1,IND,21,28,75.0,243,8.7,...,109.67,2,8,4.0,0,17.52,4700,2018,7,home
16,12982,Blaine Gabbert,TEN,1,MIA,11,22,50.0,117,5.3,...,46.97,0,0,0.0,0,3.68,6800,2018,8,home
17,13320,Cam Newton,CAR,1,DAL,17,26,65.4,161,6.2,...,82.37,13,58,4.5,1,18.24,4500,2018,9,home
18,13723,Nick Foles,PHI,1,ATL,19,34,55.9,117,3.4,...,50.74,1,-1,-1.0,0,6.08,4500,2018,29,home
19,13799,Ryan Tannehill,MIA,1,TEN,20,28,71.4,230,8.2,...,89.88,4,4,1.0,0,15.60,4000,2018,13,home
20,14008,Andrew Luck,IND,1,CIN,39,53,73.6,319,6.0,...,93.20,1,7,7.0,0,23.46,5200,2018,27,home
21,14252,Kirk Cousins,MIN,1,SF,20,36,55.6,244,6.8,...,95.14,4,26,6.5,0,20.36,5400,2018,26,home
22,14536,Russell Wilson,SEA,1,DEN,19,33,57.6,298,9.0,...,92.74,2,5,2.5,0,22.42,5800,2018,15,home
23,15694,Case Keenum,DEN,1,SEA,25,39,64.1,329,8.4,...,84.24,0,0,0.0,0,25.16,4500,2018,14,home
24,16041,Jimmy Garoppolo,SF,1,MIN,15,33,45.5,261,7.9,...,45.14,2,6,3.0,0,12.04,6900,2018,25,home
25,16245,Blake Bortles,JAX,1,NYG,18,33,54.5,176,5.3,...,67.23,4,42,10.5,0,14.24,5900,2018,18,home
26,16311,Derek Carr,OAK,1,LAR,29,40,72.5,303,7.6,...,62.81,2,1,0.5,0,12.22,5300,2018,11,home
27,16763,Marcus Mariota,TEN,1,MIA,9,16,56.2,103,6.4,...,36.20,3,15,5.0,0,3.62,4600,2018,8,home
28,17922,Jared Goff,LAR,1,OAK,18,33,54.5,233,7.1,...,97.16,1,-1,-1.0,0,17.22,6100,2018,19,home
29,18055,Dak Prescott,DAL,1,CAR,19,29,65.5,170,5.9,...,81.11,5,19,3.8,0,9.70,4500,2018,21,home
30,18811,Mitch Trubisky,CHI,1,GB,23,35,65.7,171,4.9,...,77.20,7,32,4.6,1,15.04,6500,2018,23,home
31,18857,Deshaun Watson,HOU,1,NE,17,34,50.0,176,5.2,...,62.87,8,40,5.0,0,13.04,4200,2018,22,home
32,18868,Deshone Kizer,GB,1,CHI,4,7,57.1,55,7.9,...,42.86,0,0,0.0,0,0.20,6200,2018,16,home

In [95]:
# Surface dictionary consisting of every team and the type of field they play on

surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'
              
             }

In [188]:
qb_2018.index = qb_2018['Team']

# Add the type of field the player palyed on by mapping the field on which the game was played to the surface dictionary

surface = []
for idx, team in enumerate(qb_2018['Team']):
    if qb_2018.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[qb_2018.iloc[idx]['Opponent']])


qb_2018['surface'] = surface

In [106]:
cols = qb_2018.columns.tolist()
cols = cols[:17]+cols[18:]+cols[17:18]
qb_2018 = qb_2018[cols]
qb_2018.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,salary,year,def_rk,h/a,surface,FantasyPointsDraftKings
Team,,,,,,,,,,,,,,,,,,,,,
BAL,611,Joe Flacco,BAL,1,BUF,25,34,73.5,236,6.9,...,2,3,1.5,0,4900,2018,20,home,grass,21.74
ATL,732,Matt Ryan,ATL,1,PHI,21,43,48.8,251,5.8,...,2,8,4.0,0,6300,2018,17,home,turf,9.84
GB,2593,Aaron Rodgers,GB,1,CHI,20,30,66.7,286,9.5,...,1,15,15.0,0,4500,2018,16,home,grass,24.94
PIT,3807,Ben Roethlisberger,PIT,1,CLE,23,41,56.1,335,8.2,...,3,16,5.3,0,7500,2018,4,home,grass,17.00
NE,4314,Tom Brady,NE,1,HOU,26,39,66.7,277,7.1,...,1,2,2.0,0,6600,2018,12,home,turf,22.28

In [98]:
qb=pd.read_csv('input/qb/dk_stats_loc.csv')

In [99]:
qb.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,salary,year,def_rk,h/a,surface,FantasyPointsDraftKings
0,611,Joe Flacco,BAL,1,DEN,18,32,56.2,117,3.7,...,0,0,0.0,0,6700,2015,1,away,grass,2.68
1,732,Matt Ryan,ATL,1,PHI,23,34,67.6,298,8.8,...,5,7,1.4,0,7500,2015,30,home,turf,18.62
2,2428,Carson Palmer,ARI,1,NO,19,32,59.4,307,9.6,...,3,14,4.7,0,6500,2015,32,home,grass,28.68
3,2593,Aaron Rodgers,GB,1,CHI,18,23,78.3,189,8.2,...,8,35,4.4,0,8600,2015,25,away,grass,23.06
4,3807,Ben Roethlisberger,PIT,1,NE,26,38,68.4,351,9.2,...,0,0,0.0,0,7300,2015,15,away,turf,22.04

In [192]:
qb.head()

,FantasyPointsDraftKings,Name,Opponent,PassingAttempts,PassingCompletionPercentage,PassingCompletions,PassingInterceptions,PassingRating,PassingTouchdowns,PassingYards,...,RushingTouchdowns,RushingYards,RushingYardsPerAttempt,Team,Week,def_rk,h/a,salary,surface,year
0,2.68,Joe Flacco,DEN,32,56.2,18,2,38.15,0,117,...,0,0,0.0,BAL,1,1,away,6700,grass,2015
1,18.62,Matt Ryan,PHI,34,67.6,23,2,90.07,2,298,...,0,7,1.4,ATL,1,30,home,7500,turf,2015
2,28.68,Carson Palmer,NO,32,59.4,19,0,122.79,3,307,...,0,14,4.7,ARI,1,32,home,6500,grass,2015
3,23.06,Aaron Rodgers,CHI,23,78.3,18,0,140.49,3,189,...,0,35,4.4,GB,1,25,away,8600,grass,2015
4,22.04,Ben Roethlisberger,NE,38,68.4,26,1,95.39,1,351,...,0,0,0.0,PIT,1,15,away,7300,turf,2015

In [190]:
cols = qb_2018.columns.tolist()
cols = cols[]

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'PassingCompletions',
       'PassingAttempts', 'PassingCompletionPercentage', 'PassingYards',
       'PassingYardsPerAttempt', 'PassingTouchdowns', 'PassingInterceptions',
       'PassingRating', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns',
       'FantasyPointsDraftKings', 'salary', 'year', 'def_rk', 'h/a',
       'surface'],
      dtype='object')

In [189]:
qb = pd.concat([qb,qb_2018])
qb.head()

,FantasyPointsDraftKings,Name,Opponent,PassingAttempts,PassingCompletionPercentage,PassingCompletions,PassingInterceptions,PassingRating,PassingTouchdowns,PassingYards,...,RushingTouchdowns,RushingYards,RushingYardsPerAttempt,Team,Week,def_rk,h/a,salary,surface,year
0,2.68,Joe Flacco,DEN,32,56.2,18,2,38.15,0,117,...,0,0,0.0,BAL,1,1,away,6700,grass,2015
1,18.62,Matt Ryan,PHI,34,67.6,23,2,90.07,2,298,...,0,7,1.4,ATL,1,30,home,7500,turf,2015
2,28.68,Carson Palmer,NO,32,59.4,19,0,122.79,3,307,...,0,14,4.7,ARI,1,32,home,6500,grass,2015
3,23.06,Aaron Rodgers,CHI,23,78.3,18,0,140.49,3,189,...,0,35,4.4,GB,1,25,away,8600,grass,2015
4,22.04,Ben Roethlisberger,NE,38,68.4,26,1,95.39,1,351,...,0,0,0.0,PIT,1,15,away,7300,turf,2015

In [194]:
qb=pd.read_csv('input/qb/dk_qb_loc.csv')

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,salary,year,def_rk,h/a,surface,h/a0,h/a1,surface_0,surface_1,FantasyPointsDraftKings
0,611,Joe Flacco,BAL,1,DEN,18,32,56.2,117,3.7,...,6700,2015,1,away,grass,1.0,0.0,1.0,0.0,2.68
1,732,Matt Ryan,ATL,1,PHI,23,34,67.6,298,8.8,...,7500,2015,30,home,turf,0.0,1.0,0.0,1.0,18.62
2,2428,Carson Palmer,ARI,1,NO,19,32,59.4,307,9.6,...,6500,2015,32,home,grass,0.0,1.0,1.0,0.0,28.68
3,2593,Aaron Rodgers,GB,1,CHI,18,23,78.3,189,8.2,...,8600,2015,25,away,grass,1.0,0.0,1.0,0.0,23.06
4,3807,Ben Roethlisberger,PIT,1,NE,26,38,68.4,351,9.2,...,7300,2015,15,away,turf,1.0,0.0,0.0,1.0,22.04

In [200]:
drop =[]
for week in enumerate(qb['Week']):
    if week==4:
        drop.append(idx)

In [203]:
qb.drop(drop, inplace=True)

In [204]:
qb.to_csv('input/qb/dk_stats_loc.csv')

## Wide Recievers

In [17]:
df1= read_concat('input/wr/2015wk1_2.csv','input/wr/2015wk3_4.csv')


#df2 = read_concat('input/wr/2015_sal_1_9.csv','input/wr/2015_sal_10_17.csv')

In [ ]:
df1 = pd.concat([df1,(pd.read_csv('input/wr/2015wk5_6.csv'))])
df1.reset_index(inplace=True, drop=True)

In [16]:
df1.shape

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
736,111,14368,Nick Toon,LAR,WR,17,SF,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
737,111,7857,Jerome Simpson,SF,WR,17,LAR,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
738,111,16480,Jeff Janis,GB,WR,17,MIN,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
739,111,16469,Jared Abbrederis,GB,WR,17,MIN,0,0,0.0,...,0.0,0.0,0,0,0.0,0,0,0,0.0,0.0
740,155,15150,Cordarrelle Patterson,MIN,WR,17,GB,0,0,0.0,...,0.0,0.0,0,0,0.0,0,1,1,-1.0,-1.0

In [257]:
data1 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool.csv')
data2 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (1).csv')
data3 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (2).csv')
data4 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (3).csv')
data5 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (4).csv')
data6 = pd.read_csv('input/te/daily-fantasy-football-salary-and-projection-tool (5).csv')
#data7 = pd.read_csv('input/rb/daily-fantasy-football-salary-and-projection-tool (6).csv')
#data8 = pd.read_csv('input/rb/daily-fantasy-football-salary-and-projection-tool (7).csv')
#data9 = pd.read_csv('input/rb/daily-fantasy-football-salary-and-projection-tool (8).csv')

In [259]:
data6.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,UpcomingOpponentRank,UpcomingOpponentPositionRank,DraftKingsSalary,FantasyPointsDraftKings
0,1,10974,Rob Gronkowski,NE,TE,16,NYJ,6,3,7600,19.4
1,2,1658,Greg Olsen,CAR,TE,16,ATL,11,28,7000,18.9
2,3,7175,Delanie Walker,TEN,TE,17,IND,26,19,5600,18.3
3,4,15100,Jordan Reed,WAS,TE,16,PHI,28,2,6500,18.0
4,5,10974,Rob Gronkowski,NE,TE,17,MIA,29,10,7400,17.5

In [198]:
#data1 = pd.read_csv('input/rb/fantasy-football-leaders.csv')
data2 = pd.read_csv('input/rb/fantasy-football-leaders (1).csv')
data3 = pd.read_csv('input/rb/fantasy-football-leaders (2).csv')
data4 = pd.read_csv('input/rb/fantasy-football-leaders (3).csv')
data5 = pd.read_csv('input/rb/fantasy-football-leaders (4).csv')
data6 = pd.read_csv('input/rb/fantasy-football-leaders (5).csv')
data7 = pd.read_csv('input/rb/fantasy-football-leaders (6).csv')
data8 = pd.read_csv('input/rb/fantasy-football-leaders (7).csv')
data9 = pd.read_csv('input/rb/fantasy-football-leaders (8).csv')
data10 = pd.read_csv('input/rb/fantasy-football-leaders (9).csv')

## Tight Ends

In [571]:
data1 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool.csv')
data2 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (1).csv')
data3 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (2).csv')
data4 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (3).csv')
data5 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (4).csv')
data6 = pd.read_csv('input/te/raw_2015_2016/daily-fantasy-football-salary-and-projection-tool (5).csv')

In [579]:
data2 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (1).csv')
data3 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (2).csv')
data4 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (3).csv')
data5 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (4).csv')
data6 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (5).csv')
data7 = pd.read_csv('input/te/raw_2015_2016/fantasy-football-leaders (6).csv')

In [572]:
data5.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,UpcomingOpponentRank,UpcomingOpponentPositionRank,DraftKingsSalary,FantasyPointsDraftKings
0,1,15048,Travis Kelce,KC,TE,13,ATL,30,28,4700,14.56
1,2,1658,Greg Olsen,CAR,TE,15,WAS,25,26,5000,14.39
2,3,11488,Jimmy Graham,SEA,TE,14,GB,17,23,5500,14.28
3,4,11488,Jimmy Graham,SEA,TE,13,CAR,25,31,5500,14.11
4,5,1658,Greg Olsen,CAR,TE,13,SEA,5,8,5100,13.95

In [504]:
te_2016.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
0,722,Jason Witten,DAL,1,NYG,14,9,64.3,66,0,...,0,0,0,0,15.6,4100,20,away,turf,2016
1,852,Jacob Tamme,ATL,1,TB,8,6,75.0,51,0,...,0,0,0,0,11.1,2800,14,away,grass,2016
2,1181,Martellus Bennett,NE,1,ARI,5,3,60.0,14,0,...,0,0,0,0,4.4,3400,1,away,grass,2016
3,1545,Anthony Fasano,TEN,1,MIN,0,0,0.0,0,0,...,0,0,0,0,0.0,2500,11,away,turf,2016
4,1658,Greg Olsen,CAR,1,DEN,9,7,77.8,73,0,...,0,0,0,0,14.3,5100,19,away,grass,2016

In [584]:
te_2016 = pd.concat([te_2016,data7])
te_2016.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
162,103,15305,Demetrius Harris,KC,TE,17,LAC,1,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
163,103,16933,James O'Shaughnessy,KC,TE,17,LAC,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
164,103,11555,Jim Dray,SF,TE,17,SEA,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
165,103,9671,Matthew Mulligan,DET,TE,17,GB,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0
166,103,11317,Clay Harbor,DET,TE,17,GB,0,0,0.0,...,0.0,0.0,0,0,0,0,0,0,0.0,0.0

In [578]:
te_2016_sal = te_2016

In [639]:
te_2016 = add_salary(te_2016,te_2016_sal)

te_2016.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,def_rk,h/a,surface,year,salary
0,722,Jason Witten,DAL,1,NYG,14,9,64.3,66,0,...,0,0,0,0,15.6,20,away,turf,2016,4100
1,852,Jacob Tamme,ATL,1,TB,8,6,75.0,51,0,...,0,0,0,0,11.1,14,away,grass,2016,2800
2,1181,Martellus Bennett,NE,1,ARI,5,3,60.0,14,0,...,0,0,0,0,4.4,1,away,grass,2016,3400
3,1545,Anthony Fasano,TEN,1,MIN,0,0,0.0,0,0,...,0,0,0,0,0.0,11,away,turf,2016,2500
4,1658,Greg Olsen,CAR,1,DEN,9,7,77.8,73,0,...,0,0,0,0,14.3,19,away,grass,2016,5100

In [586]:
def_2015.sort_values('DraftKingsTightEndFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsTightEndFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsTightEndFantasyPointsAllowedAverage', inplace=True)

In [587]:
def_2016.reset_index(inplace=True)

In [588]:
def_2016['Rank'] =def_2016.index+1

In [589]:
def_2016.index = def_2016['Team']

In [590]:
# Add defensive rankings to dataframe

#te_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], te_2015['Opponent']))
te_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], te_2016['Opponent']))
#te_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], te_2017['Opponent']))

In [592]:
te_2016.shape

(1415, 24)

In [593]:
temp = te_2016

In [594]:
week1  = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [595]:
loc_df = location[location['year']==2016]

In [627]:
loc_df[loc_df['week']==17]

home_list = []

for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

week17['h/a'] = home_list

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [628]:
te_2016 = pd.concat([te_2016,week17])
te_2016.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk,h/a
162,103,15305,Demetrius Harris,KC,TE,17,LAC,1,0,0.0,...,0,0,0,0,0,0,0.0,0.0,12,away
163,103,16933,James O'Shaughnessy,KC,TE,17,LAC,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,12,away
164,103,11555,Jim Dray,SF,TE,17,SEA,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,4,away
165,103,9671,Matthew Mulligan,DET,TE,17,GB,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,21,away
166,103,11317,Clay Harbor,DET,TE,17,GB,0,0,0.0,...,0,0,0,0,0,0,0.0,0.0,21,away

In [629]:
surface = []
for idx, team in enumerate(te_2016['Team']):
    if te_2016.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[te_2016.iloc[idx]['Opponent']])


te_2016['surface'] = surface
te_2016.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk,h/a,surface
10,11,15602,Jack Doyle,IND,TE,1,DET,4,3,75.0,...,0,0,0,0,0,18.5,18.5,27,away,turf
12,13,13027,Julius Thomas,JAX,TE,1,GB,5,5,100.0,...,0,0,0,0,0,17.4,17.4,21,away,grass
13,14,13987,Dwayne Allen,IND,TE,1,DET,6,4,66.7,...,0,0,0,0,0,17.3,17.3,27,away,turf
17,18,16451,Eric Ebron,DET,TE,1,IND,5,5,100.0,...,0,0,0,0,0,15.6,15.6,23,away,turf
18,18,722,Jason Witten,DAL,TE,1,NYG,14,9,64.3,...,0,0,0,0,0,15.6,15.6,20,away,turf

In [630]:
te_2017['year']=2017
te_2016['year'] = 2016

In [637]:
te_2017.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets',
       'Receptions', 'ReceptionPercentage', 'ReceivingYards',
       'ReceivingTouchdowns', 'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'salary', 'def_rk', 'h/a', 'surface',
       'year'],
      dtype='object')

In [667]:
te_2017.shape

(1485, 25)

In [662]:
cols = te_2016.columns.tolist()
cols = cols[:-5] + cols[-1:] +cols[-5:-1]
te_2016 = te_2016[cols]

In [663]:
te_2016.shape

(1415, 25)

In [669]:
te=pd.concat([te,te_2017])
te.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
0,3,Craig Stevens,TEN,1,TB,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,21,away,grass,2015
1,722,Jason Witten,DAL,1,NYG,9,8,88.9,60,2,...,0.0,0,0,0,26.0,4000,31,away,turf,2015
2,852,Jacob Tamme,ATL,1,PHI,3,3,100.0,19,0,...,0.0,0,0,0,4.9,2600,11,away,grass,2015
3,1181,Martellus Bennett,CHI,1,GB,7,5,71.4,55,1,...,0.0,0,0,0,16.5,4300,14,away,grass,2015
4,1545,Anthony Fasano,TEN,1,TB,1,1,100.0,18,0,...,0.0,0,0,0,2.8,2500,21,away,grass,2015

In [670]:
te.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
1480,19304,Pharaoh Brown,OAK,17,LAC,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,8,home,grass,2017
1481,19335,Antony Auclair,TB,17,NO,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,2,away,turf,2017
1482,19390,Emanuel Byrd,GB,17,DET,2,2,100.0,31,0,...,0.0,0,0,0,5.1,3500,16,away,turf,2017
1483,19410,Ricky Seals-Jones,ARI,17,SEA,1,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,9,home,grass,2017
1484,19579,Tyrone Swoopes,SEA,17,ARI,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2500,17,home,turf,2017

In [671]:
te.to_csv('input/te/dk_stats_loc.csv', index=False)

## Running Backs

In [206]:
rb_2015= pd.concat([rb_2015,data10])
rb_2015.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
115,88,13255,Matt Asiata,MIN,RB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
116,88,15555,Zach Line,MIN,FB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
117,118,15018,Denard Robinson,JAX,RB,17,HOU,5,9,1.8,0,1,0,0,0,1,1,-0.1,-0.1
118,119,17217,Raheem Mostert,CLE,RB,17,PIT,0,0,0.0,0,0,0,0,0,1,1,-1.0,-1.0
119,119,13852,Bobby Rainey,TB,RB,17,CAR,0,0,0.0,0,0,0,0,0,1,1,-1.0,-1.0

In [142]:
rb_2016 = pd.concat([rb_2016,data10])
rb_2016.tail()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
108,87,12323,Joique Bell,DET,RB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
109,87,18152,Dwayne Washington,DET,RB,17,GB,0,0,0.0,0,0,0,0,0,0,0,0.0,0.0
110,87,18452,Joe Kerridge,GB,FB,17,DET,1,0,0.0,0,0,0,0,0,0,0,0.0,0.0
111,112,18626,Brandon Burks,NYJ,RB,17,BUF,2,-4,-2.0,0,0,0,0,0,0,0,-0.4,-0.4
112,113,12985,DuJuan Harris,SF,RB,17,SEA,4,-1,-0.2,0,0,0,0,0,1,1,-1.1,-1.1

In [208]:
rb_2015 = add_salary(rb_2015,rb_2015_sal)

In [209]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary
0,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000
1,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,3000
2,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,3000
3,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,7800
4,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000

In [145]:
def_2016.head()

,Rank,Name,Team,Position,Played,DraftKingsQuarterbackFantasyPointsAllowedAverage,DraftKingsRunningbackFantasyPointsAllowedAverage,DraftKingsWideReceiverFantasyPointsAllowedAverage,DraftKingsTightEndFantasyPointsAllowedAverage,DraftKingsKickerFantasyPointsAllowedAverage,DraftKingsFantasyPointsAllowedAverage
6,7,Arizona Cardinals,ARI,DST,16,17.59,18.91,40.28,6.30,0.0,83.07
21,22,Tennessee Titans,TEN,DST,16,20.68,19.09,44.60,11.48,0.0,95.85
17,18,Dallas Cowboys,DAL,DST,16,18.22,19.23,36.69,18.12,0.0,92.26
3,4,Seattle Seahawks,SEA,DST,16,15.73,19.99,37.16,9.02,0.0,81.90
13,14,Chicago Bears,CHI,DST,16,18.20,20.71,40.41,10.42,0.0,89.74

In [385]:
def_2015.sort_values('DraftKingsRunningbackFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsRunningbackFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsRunningbackFantasyPointsAllowedAverage', inplace=True)

In [386]:
def_2017.reset_index(inplace=True)
def_2017['Rank']= def_2016.index +1

In [210]:
rb_2015.index = rb_2015['Team']

In [370]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,...,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
Team,,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,...,0,0,0,0,0.0,3000,28,away,turf,2015
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,...,0,0,0,0,0.0,3000,15,away,grass,2015
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,...,25,0,0,0,30.6,3000,5,away,grass,2015
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,...,26,2,0,0,17.6,7800,9,away,turf,2015
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,...,0,0,0,0,0.8,3000,11,away,turf,2015

In [387]:
def_2017.index=def_2017.Team

In [388]:
# Add defensive rankings to dataframe

#rb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], rb_2015['Opponent']))
#rb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], rb_2016['Opponent']))
rb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], rb_2017['Opponent']))

In [374]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,...,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
Team,,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,...,0,0,0,0,0.0,3000,18,away,turf,2015
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,...,0,0,0,0,0.0,3000,22,away,grass,2015
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,...,25,0,0,0,30.6,3000,13,away,grass,2015
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,...,26,2,0,0,17.6,7800,15,away,turf,2015
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,...,0,0,0,0,0.8,3000,9,away,turf,2015

In [213]:
temp=rb_2015

In [214]:
week1  = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [53]:
location = pd.read_csv('input/location.csv')

In [215]:
loc_df=location[location['year']==2015]

In [247]:
loc_df[loc_df['week']==17]

home_list = []
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')

week17['h/a'] = home_list


week17.head()

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,17,NYJ,0,0,0.0,0,0,0,0,0,0,0,0.0,3500,6,away
WAS,957,Pierre Thomas,WAS,17,DAL,7,30,4.3,0,2,1,5,0,0,0,4.5,3600,8,away
GB,1589,John Kuhn,GB,17,MIN,1,3,3.0,0,2,2,14,0,0,0,3.7,3000,11,away
NE,1652,Steven Jackson,NE,17,MIA,14,35,2.5,1,1,1,20,0,0,0,12.5,3800,26,away
NO,2262,Tim Hightower,NO,17,ATL,16,66,4.1,1,5,5,41,0,0,0,21.7,3000,12,away

In [155]:
rb_2016 = pd.concat([rb_2015,week2]) 
rb_2016.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
NO,1589,John Kuhn,NO,1,OAK,2,4,2.0,0,1,0,0,0,0,0,0.4,3000,21,away
NO,2262,Tim Hightower,NO,1,OAK,4,9,2.2,0,1,1,1,0,0,0,2.0,null,21,away
NYJ,2699,Matt Forte,NYJ,1,CIN,22,96,4.4,0,7,5,59,0,0,0,20.5,4300,11,away
BUF,4640,Reggie Bush,BUF,1,BAL,3,-4,-1.3,0,1,0,0,0,0,0,-0.4,6100,12,away
CAR,4738,Mike Tolbert,CAR,1,DEN,2,6,3.0,0,1,1,1,0,0,0,1.7,3000,1,away

In [248]:
rb_2015 = pd.concat([rb_2015, week17])
rb_2015.tail()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
LAC,17120,Dreamius Smith,LAC,17,DEN,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,2,away
HOU,17199,Akeem Hunt,HOU,17,JAX,3,28,9.3,0,3,1,27,0,0,0,6.5,4500,29,away
CLE,17217,Raheem Mostert,CLE,17,PIT,0,0,0.0,0,0,0,0,0,1,1,-1.0,3000,23,away
SF,17254,Jarryd Hayne,SF,17,LAR,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,16,away
DAL,17360,Rod Smith,DAL,17,WAS,0,0,0.0,0,0,0,0,0,0,0,0.0,4600,27,away

In [613]:
rb_2016.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000,25,home
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,null,8,away
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,4300,16,home
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,6100,18,home
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000,17,away

In [523]:
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a
Team,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000,28,home
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,15,away
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,3000,5,home
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,7800,9,home
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000,11,away

In [249]:
surface = []
for idx, team in enumerate(rb_2015['Team']):
    if rb_2015.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[rb_2015.iloc[idx]['Opponent']])


rb_2015['surface'] = surface
rb_2015.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,Receptions,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface
Team,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,0,0,0,0,0,0.0,3000,28,away,turf
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,0,0,0,0,0,0.0,3000,15,away,grass
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,5,25,0,0,0,30.6,3000,5,away,grass
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,3,26,2,0,0,17.6,7800,9,away,turf
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,0,0,0,0,0,0.8,3000,11,away,turf

In [250]:
rb_2017['year']=2017
rb_2016['year']=2016
rb_2015['year']=2015

In [389]:
rb = pd.concat([rb_2015,rb_2016])
rb.head()

,PlayerID,Name,Team,Week,Opponent,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,ReceivingTargets,...,ReceivingYards,ReceivingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,salary,def_rk,h/a,surface,year
Team,,,,,,,,,,,,,,,,,,,,,
BUF,733,Jerome Felton,BUF,1,IND,0,0,0.0,0,1,...,0,0,0,0,0.0,3000,18,away,turf,2015
GB,1589,John Kuhn,GB,1,CHI,0,0,0.0,0,0,...,0,0,0,0,0.0,3000,22,away,grass,2015
CHI,2699,Matt Forte,CHI,1,GB,24,141,5.9,1,8,...,25,0,0,0,30.6,3000,13,away,grass,2015
OAK,3382,Marcel Reece,OAK,1,CIN,0,0,0.0,0,4,...,26,2,0,0,17.6,7800,15,away,turf,2015
SF,4640,Reggie Bush,SF,1,MIN,2,8,4.0,0,1,...,0,0,0,0,0.8,3000,9,away,turf,2015

In [390]:
rb = pd.concat([rb,rb_2017])

In [391]:
rb.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'RushingAttempts',
       'RushingYards', 'RushingYardsPerAttempt', 'RushingTouchdowns',
       'ReceivingTargets', 'Receptions', 'ReceivingYards',
       'ReceivingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'salary', 'def_rk', 'h/a', 'surface',
       'year'],
      dtype='object')

In [392]:
rb.to_csv('input/rb/dk_stats_loc.csv', index=False)

# Wide Receivers

In [281]:
wr_2016_df = pd.concat([wr_2016_df, data9])
wr_2016_df.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerTarget,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,13.8,15.0,0,0,0.0,0,0,0,39.0,39.0
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,15.9,23.8,1,11,11.0,0,0,0,36.4,36.4
2,3,16906,Stefon Diggs,MIN,WR,2,GB,11,9,81.8,...,16.5,20.2,0,0,0.0,0,0,0,36.2,36.2
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,11.5,15.8,0,0,0.0,0,0,0,35.6,35.6
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,19.1,19.1,0,0,0.0,0,1,0,35.2,35.2

In [77]:
wr_2017 = wr_2017[0:600]

In [44]:
df2.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,UpcomingOpponentRank,UpcomingOpponentPositionRank,DraftKingsSalary,FantasyPointsDraftKings
0,1,4314,Tom Brady,NE,QB,9,WAS,16,15,8500,26.92
1,2,8244,Philip Rivers,LAC,QB,8,BAL,31,32,6600,26.72
2,3,4314,Tom Brady,NE,QB,5,DAL,18,10,7800,26.46
3,4,2428,Carson Palmer,ARI,QB,7,BAL,30,32,6700,26.30
4,5,13320,Cam Newton,CAR,QB,7,PHI,9,9,6600,26.22

In [111]:
wr_2015['year'] = 2015
wr_2016['year']=2016
wr_2017['year'] = 2017

In [40]:
def add_salary(df,df2):
    df = df.sort_values(['Week','PlayerID'])
    df = df.drop(['FantasyPointsPerGameDraftKings','Rank','Position'], axis=1)
    df.reset_index(inplace=True, drop=True)
    df2 = df2.sort_values(['Week','PlayerID'])
    df2 = df2.drop(['Rank','Position'], axis=1)
    df2.reset_index(inplace=True, drop=True)
    df['salary'] = df2['DraftKingsSalary']
    
    return df

In [331]:
wr_2016 = add_salary(wr_2016,wr_2016_sal)
wr_2016.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,def_rk,h/a,salary
0,2429,Andre Johnson,TEN,1,MIN,7,3,42.9,30,0,...,0,0,0.0,0,0,0,6.0,17,home,3900
1,3519,Vincent Jackson,TB,1,ATL,7,2,28.6,18,0,...,0,0,0.0,0,0,0,3.8,11,away,4400
2,3601,Eric Weems,ATL,1,TB,0,0,0.0,0,0,...,0,0,0.0,0,0,0,0.0,24,home,3000
3,3943,DeSean Jackson,WAS,1,PIT,10,6,60.0,102,0,...,0,0,0.0,0,0,0,19.2,22,home,6100
4,4358,Steve Smith,BAL,1,BUF,8,5,62.5,19,0,...,0,0,0.0,0,0,0,6.9,29,home,4900

In [383]:
cols =wr_2016.columns.tolist()
cols = cols[:-4] + cols[-1:] +cols[-3:-2] +cols[-4:-3] +cols[-2:-1]
df = wr_2016[cols]

In [385]:
df

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
0,2429,Andre Johnson,TEN,1,MIN,7,3,42.9,30,0,...,0,0.0,0,0,0,6.0,2016,3900,17,home
1,3519,Vincent Jackson,TB,1,ATL,7,2,28.6,18,0,...,0,0.0,0,0,0,3.8,2016,4400,11,away
2,3601,Eric Weems,ATL,1,TB,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,24,home
3,3943,DeSean Jackson,WAS,1,PIT,10,6,60.0,102,0,...,0,0.0,0,0,0,19.2,2016,6100,22,home
4,4358,Steve Smith,BAL,1,BUF,8,5,62.5,19,0,...,0,0.0,0,0,0,6.9,2016,4900,29,home
5,4556,Jordy Nelson,GB,1,JAX,9,6,66.7,32,1,...,0,0.0,0,0,0,15.2,2016,7700,19,away
6,5571,Larry Fitzgerald,ARI,1,NE,10,8,80.0,81,2,...,0,0.0,0,0,0,28.1,2016,6300,26,home
7,6211,Harry Douglas,TEN,1,MIN,5,2,40.0,21,0,...,0,0.0,0,0,0,4.1,2016,3400,17,home
8,6767,Pierre Garcon,WAS,1,PIT,6,6,100.0,51,0,...,0,0.0,0,0,0,11.1,2016,4400,22,home
9,7082,Devin Hester,BAL,1,BUF,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,null,29,home
10,7389,Eddie Royal,CHI,1,HOU,6,4,66.7,57,1,...,0,0.0,0,0,0,15.7,2016,3200,5,home
11,7651,Matthew Slater,NE,1,ARI,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,6100,6,away
12,8355,Julian Edelman,NE,1,ARI,7,7,100.0,66,0,...,16,5.3,0,0,0,15.2,2016,4200,6,away
13,8373,Brandon Tate,BUF,1,BAL,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3900,9,home
14,8529,Mike Wallace,BAL,1,BUF,6,3,50.0,91,1,...,11,11.0,0,0,0,19.2,2016,3600,29,home
15,8532,Kenny Britt,LAR,1,SF,6,4,66.7,67,0,...,0,0.0,0,0,0,10.7,2016,6500,32,away
16,8771,Darrius Heyward-Bey,PIT,1,WAS,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,5500,14,home
17,8914,Jeremy Maclin,KC,1,LAC,7,5,71.4,63,1,...,-1,-1.0,0,0,0,17.2,2016,4200,2,away
18,9331,Michael Crabtree,OAK,1,NO,9,7,77.8,87,0,...,0,0.0,0,0,0,17.7,2016,9800,12,home
19,9906,Danny Amendola,NE,1,ARI,4,3,75.0,48,0,...,0,0.0,0,0,0,7.8,2016,5700,6,away
20,11056,Antonio Brown,PIT,1,WAS,11,8,72.7,126,2,...,0,0.0,0,0,0,35.6,2016,3000,14,home
21,11063,Emmanuel Sanders,DEN,1,CAR,8,5,62.5,49,0,...,0,0.0,0,0,0,9.9,2016,6600,10,home
22,11084,Marc Mariani,TEN,1,MIN,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,7000,17,home
23,11182,Eric Decker,NYJ,1,CIN,7,2,28.6,37,1,...,0,0.0,0,0,0,11.7,2016,8500,18,away
24,11197,Demaryius Thomas,DEN,1,CAR,6,4,66.7,48,0,...,0,0.0,0,0,0,8.8,2016,3900,10,home
25,11270,Dez Bryant,DAL,1,NYG,5,1,20.0,8,0,...,0,0.0,0,0,0,1.8,2016,3000,7,home
26,11463,Brandon LaFell,CIN,1,NYJ,4,4,100.0,91,0,...,0,0.0,0,0,0,13.1,2016,7300,30,home
27,11501,Arrelious Benn,JAX,1,GB,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,7800,16,away
28,11565,Andre Roberts,DET,1,IND,1,1,100.0,8,0,...,0,0.0,0,0,0,1.8,2016,4500,25,home
29,11611,Golden Tate,DET,1,IND,7,7,100.0,41,0,...,2,2.0,0,0,0,11.3,2016,4100,25,home
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2480,18036,Ricardo Louis,CLE,17,PIT,2,2,100.0,22,0,...,0,0.0,0,0,0,4.2,2016,3500,22,home
2481,18039,Pharoh Cooper,LAR,17,ARI,6,4,66.7,36,0,...,0,0.0,0,0,0,6.6,2016,null,6,away
2482,18047,Demarcus Robinson,KC,17,LAC,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,2,away
2483,18058,Tajae Sharpe,TEN,17,HOU,2,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3200,5,home
2484,18080,Trevor Davis,GB,17,DET,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3400,21,away
2485,18082,Tyreek Hill,KC,17,LAC,7,5,71.4,46,0,...,15,5.0,0,0,0,17.1,2016,3900,2,away
2486,18089,Rashard Higgins,CLE,17,PIT,1,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,4300,22,home
2487,18103,Jakeem Grant,MIA,17,NE,0,0,0.0,0,0,...,1,1.0,0,1,0,0.1,2016,null,26,home
2488,18116,Cody Core,CIN,17,BAL,5,4,80.0,82,0,...,0,0.0,0,0,0,12.2,2016,null,9,home
2489,18129,Aaron Burbridge,SF,17,SEA,2,1,50.0,24,0,...,0,0.0,0,0,0,3.4,2016,3000,3,away
2490,18145,Demarcus Ayers,PIT,17,CLE,12,5,41.7,44,1,...,-12,-6.0,0,0,0,14.2,2016,null,20,home
2491,18157,Charone Peake,NYJ,17,BUF,5,2,40.0,22,0,...,0,0.0,0,0,0,4.2,2016,null,29,away
2492,18187,Robby Anderson,NYJ,17,BUF,7,4,57.1,43,0,...,0,0.0,0,0,0,8.3,2016,null,29,away
2493,18197,Alex Erickson,CIN,17,BAL,0,0,0.0,0,0,...,0,0.0,0,1,0,0.0,2016,5600,9,home
2494,18221,Rashawn Scott,MIA,17,NE,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,null,26,home
2495,18234,Paul McRoberts,LAR,17,ARI,1,1,100.0,6,0,...,0,0.0,0,0,0,1.6,2016,3000,6,away
2496,18241,Johnny Holton,OAK,17,DEN,1,0,0.0,0,0,...,0,0.0,0,1,1,-1.0,2016,3000,1,home
2497,18257,Jalin Marshall,NYJ,17,BUF,4,3,75.0,22,1,...,0,0.0,0,0,0,11.2,2016,3000,29,away
2498,18269,Geronimo Allison,GB,17,DET,6,4,66.7,91,1,...,0,0.0,0,0,0,19.1,2016,4700,21,away
2499,18285,Roger Lewis,NYG,17,WAS,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,5800,14,away
2500,18323,Wendall Williams,HOU,17,TEN,4,2,50.0,41,0,...,0,0.0,0,0,0,6.1,2016,5000,13,home
2501,18361,Chester Rogers,IND,17,JAX,7,4,57.1,72,0,...,0,0.0,0,0,0,11.2,2016,3800,19,home
2502,18401,Tommylee Lewis,NO,17,ATL,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,11,away
2503,18407,Bralon Addison,CHI,17,MIN,1,1,100.0,11,0,...,4,4.0,0,1,1,1.5,2016,3000,17,home
2504,18422,Khalif Raymond,DEN,17,OAK,1,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,3000,27,home
2505,18443,Maurice Harris,WAS,17,NYG,2,1,50.0,15,0,...,0,0.0,0,0,0,2.5,2016,5100,7,home
2506,18445,Mike Thomas,LAR,17,ARI,1,1,100.0,15,0,...,0,0.0,0,0,0,2.5,2016,null,6,away
2507,18596,Paul Turner,PHI,17,DAL,4,2,50.0,30,0,...,0,0.0,0,0,0,5.0,2016,5400,15,home
2508,18602,Tanner McEvoy,SEA,17,SF,2,2,100.0,16,0,...,0,0.0,0,0,0,3.6,2016,null,32,home
2509,18611,Bryce Treggs,PHI,17,DAL,2,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2016,5100,15,home

In [400]:
wr = pd.read_csv('input/wr/dk_stats_loc.csv')

In [404]:
wr_2015 = wr[wr['year']==2015] 
wr_2016 = wr[wr['year']==2016]
wr_2017 = wr[wr['year']==2017]

In [371]:
wr_2016['year']=2016

In [386]:
wr_2016 = df

In [394]:
def_2015.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsWideReceiverFantasyPointsAllowedAverage', inplace=True)

In [409]:
def_2017.reset_index(inplace=True)
def_2017['Rank'] = def_2017.index+1

In [410]:
#def_2015.index=def_2015['Team']
#def_2016.index=def_2016['Team']
def_2017.index=def_2017['Team']

In [285]:
wr_2016 = wr_2016_df

In [412]:
# Add defensive rankings to dataframe

#wr_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], wr_2015['Opponent']))
#wr_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], wr_2016['Opponent']))
wr_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], wr_2017['Opponent']))

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [287]:
wr_2016.head()

,Rank,PlayerID,Name,Team,Position,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,...,ReceivingYardsPerReception,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsPerGameDraftKings,FantasyPointsDraftKings,def_rk
0,1,12845,AJ Green,CIN,WR,1,NYJ,13,12,92.3,...,15.0,0,0,0.0,0,0,0,39.0,39.0,30
1,2,16568,Brandin Cooks,NO,WR,1,OAK,9,6,66.7,...,23.8,1,11,11.0,0,0,0,36.4,36.4,27
2,3,16906,Stefon Diggs,MIN,WR,2,GB,11,9,81.8,...,20.2,0,0,0.0,0,0,0,36.2,36.2,16
3,4,11056,Antonio Brown,PIT,WR,1,WAS,11,8,72.7,...,15.8,0,0,0.0,0,0,0,35.6,35.6,14
4,5,16141,Willie Snead,NO,WR,1,OAK,9,9,100.0,...,19.1,0,0,0.0,0,1,0,35.2,35.2,27

# Quarterbacks

In [74]:
df1= read_concat('input/qb/2016wk1_9.csv','input/qb/2016wk_10_17.csv')

df2 = read_concat('input/qb/2016_sal_wk1_9.csv','input/qb/2016_sal_wk10_17.csv')

df1= read_concat('input/qb/2017wk1_9.csv','input/qb/2017wk10_17.csv')

df2 = read_concat('input/qb/2017_sal_wk1_9.csv','input/qb/2017_sal_wk10_17.csv')

In [ ]:
# Add defensive rankings to dataframe

qb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], qb_2015['Opponent']))
qb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], qb_2016['Opponent']))
qb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], qb_2017['Opponent']))

In [76]:
qb.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,PassingTouchdowns,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary
0,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,1,1,70.96,0,0,0.0,0,7.84,5500
1,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,1,0,116.11,3,11,3.7,0,20.94,6900
2,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,1,3,53.12,1,2,2.0,0,11.92,4300
3,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,1,1,86.51,7,21,3.0,0,20.54,6000
4,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,2,1,95.02,3,-8,-2.7,0,16.72,7000

In [421]:
qb=pd.read_csv('input/qb/dk_stats_loc.csv')

In [422]:
qb_2015 = qb[qb['year']==2015]
qb_2016 = qb[qb['year']==2016]
qb_2017 = qb[qb['year']==2017]

In [426]:
def_2015.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)
def_2016.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)
def_2017.sort_values('DraftKingsQuarterbackFantasyPointsAllowedAverage', inplace=True)

In [436]:
def_2017.reset_index(inplace=True)
def_2017['Rank'] = def_2017.index +1

In [437]:
#def_2015.index=def_2015['Team']

#def_2016.index=def_2016['Team']

def_2017.index = def_2017['Team']

In [58]:
qb_2015['year'] = 2015

In [68]:
qb_2016['year']=2016

In [78]:
qb_2017['year'] = 2017

In [438]:
# Map defensive rankings fron defense df to qb_df by yer and opponent

#qb_2015['def_rk'] = list(map(lambda x: def_2015.loc[x]['Rank'], qb_2015['Opponent']))
#qb_2016['def_rk'] = list(map(lambda x: def_2016.loc[x]['Rank'], qb_2016['Opponent']))
qb_2017['def_rk'] = list(map(lambda x: def_2017.loc[x]['Rank'], qb_2017['Opponent']))

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [439]:
qb=pd.concat([qb_2015,qb_2016])

In [440]:
qb= pd.concat([qb, qb_2017])

In [441]:
qb.to_csv('input/qb/dk_stats_loc.csv')

In [73]:
qb_2016.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,BUF,22,33,66.7,258,7.8,...,0,100.32,4,-3,-0.8,0,13.02,6700,2016,10
1,732,Matt Ryan,ATL,1,TB,27,39,69.2,334,8.6,...,0,112.55,3,10,3.3,0,27.36,7100,2016,17
2,2428,Carson Palmer,ARI,1,NE,24,37,64.9,271,7.3,...,0,104.67,2,1,0.5,0,18.94,7100,2016,6
3,2593,Aaron Rodgers,GB,1,JAX,20,34,58.8,199,5.9,...,0,95.10,4,16,4.0,1,23.56,8500,2016,8
4,3807,Ben Roethlisberger,PIT,1,WAS,27,37,73.0,300,8.1,...,1,112.44,1,-2,-2.0,0,25.80,7800,2016,27

In [80]:
qb_2017.head()

,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,PassingYardsPerAttempt,...,PassingInterceptions,PassingRating,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk
0,611,Joe Flacco,BAL,1,CIN,9,17,52.9,121,7.1,...,1,70.96,0,0,0.0,0,7.84,5500,2017,12
1,732,Matt Ryan,ATL,1,CHI,21,30,70.0,321,10.7,...,0,116.11,3,11,3.7,0,20.94,6900,2017,7
2,2428,Carson Palmer,ARI,1,DET,27,48,56.2,268,5.6,...,3,53.12,1,2,2.0,0,11.92,4300,2017,21
3,2593,Aaron Rodgers,GB,1,SEA,28,42,66.7,311,7.4,...,1,86.51,7,21,3.0,0,20.54,6000,2017,8
4,3807,Ben Roethlisberger,PIT,1,CLE,24,36,66.7,263,7.3,...,1,95.02,3,-8,-2.7,0,16.72,7000,2017,24

## Merge Dataframes

In [ ]:
data_qb = [qb_2015,qb_2016,qb_2017]

In [413]:
data_wr= [wr_2015,wr_2016,wr_2017]

In [82]:
qb= pd.concat(data)

In [414]:
wr= pd.concat(data_wr)

In [417]:
wr['ReceivingTargets'].max()

23

In [129]:
wr.shape

(5501, 23)

In [416]:
#qb.to_csv('input/qb/dk_stas_sal.csv', index=False)
wr.to_csv('input/wr/dk_stats_loc.csv', index=False)

In [ ]:
pd.read_

In [130]:
# add location to dataframes by mapping location of game from completed qb dataframe

qb = pd.read_csv('input/qb/dk_stats_loc.csv')

In [131]:
qb.head()

,Unnamed: 0,PlayerID,Name,Team,Week,Opponent,PassingCompletions,PassingAttempts,PassingCompletionPercentage,PassingYards,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,FantasyPointsDraftKings,salary,year,def_rk,h/a,surface
0,0,611,Joe Flacco,BAL,1,DEN,18,32,56.2,117,...,0,0,0.0,0,2.68,6700,2015,2,away,grass
1,1,732,Matt Ryan,ATL,1,PHI,23,34,67.6,298,...,5,7,1.4,0,18.62,7500,2015,30,home,turf
2,2,2428,Carson Palmer,ARI,1,NO,19,32,59.4,307,...,3,14,4.7,0,28.68,6500,2015,32,home,grass
3,3,2593,Aaron Rodgers,GB,1,CHI,18,23,78.3,189,...,8,35,4.4,0,23.06,8600,2015,15,away,grass
4,4,3807,Ben Roethlisberger,PIT,1,NE,26,38,68.4,351,...,0,0,0.0,0,22.04,7300,2015,13,away,turf

In [263]:
wr.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingAttempts,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk
0,204,Roddy White,ATL,1,PHI,8,4,50.0,84,0,...,0,0,0.0,0,0,0,12.4,2015,6500,30
1,1986,Jason Avant,KC,1,HOU,0,0,0.0,0,0,...,0,0,0.0,0,0,0,0.0,2015,3000,3
2,2429,Andre Johnson,IND,1,BUF,10,4,40.0,24,0,...,0,0,0.0,0,0,0,6.4,2015,6100,18
3,2950,Steve Johnson,LAC,1,DET,6,6,100.0,82,1,...,0,0,0.0,0,0,0,20.2,2015,3700,20
4,3330,Miles Austin,PHI,1,ATL,3,2,66.7,22,0,...,0,0,0.0,0,0,0,4.2,2015,3000,12

In [139]:
qb_2015 = qb[qb['year']==2015]
qb_2015.index = qb_2015['Team']
wr_2015.index = wr_2015['Team']

In [145]:
wr_2015.reset_index(inplace=True, drop =True)

In [148]:
location = pd.read_csv('input/location.csv')
location.drop('Unnamed: 0', axis=1,inplace=True)

In [143]:
wr_2015['h/a'] = home

In [401]:
temp = wr_2017

In [395]:
week1  = temp[temp['Week']==1]
week2 = temp[temp['Week']==2]
week3 = temp[temp['Week']==3]
week4 = temp[temp['Week']==4]
week5 = temp[temp['Week']==5]
week6 = temp[temp['Week']==6]
week7 = temp[temp['Week']==7]
week8 = temp[temp['Week']==8]
week9 = temp[temp['Week']==9]
week10 = temp[temp['Week']==10]
week11 = temp[temp['Week']==11]
week12 = temp[temp['Week']==12]
week13 = temp[temp['Week']==13]
week14 = temp[temp['Week']==14]
week15 = temp[temp['Week']==15]
week16 = temp[temp['Week']==16]
week17 = temp[temp['Week']==17]

In [393]:
loc_df = location[location['year']==2017]

In [402]:
week1.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets',
       'Receptions', 'ReceptionPercentage', 'ReceivingYards',
       'ReceivingTouchdowns', 'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'year', 'salary', 'def_rk', 'h/a'],
      dtype='object')

In [403]:
week2.columns

Index(['PlayerID', 'Name', 'Team', 'Week', 'Opponent', 'ReceivingTargets',
       'Receptions', 'ReceptionPercentage', 'ReceivingYards',
       'ReceivingTouchdowns', 'ReceivingLong', 'ReceivingYardsPerTarget',
       'ReceivingYardsPerReception', 'RushingAttempts', 'RushingYards',
       'RushingYardsPerAttempt', 'RushingTouchdowns', 'Fumbles', 'FumblesLost',
       'FantasyPointsDraftKings', 'year', 'salary', 'def_rk'],
      dtype='object')

In [434]:
loc_df[loc_df['week']==17]

home_list = []
for team in week17['Team']:
    if team in list(loc_df['home']):
        home_list.append('home')
    else:
        home_list.append('away')


week17['h/a'] = home_list


week17.head()

C:\Users\bobal\Anaconda2\envs\py36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
2329,3601,Eric Weems,TEN,17,JAX,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,3400,23,home
2330,5571,Larry Fitzgerald,ARI,17,SEA,13,8,61.5,55,0,...,0,0.0,0,0,0,13.5,2017,6600,5,home
2331,7651,Matthew Slater,NE,17,NYJ,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,4100,24,away
2332,8373,Brandon Tate,BUF,17,MIA,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,null,21,home
2333,8529,Mike Wallace,BAL,17,CIN,13,5,38.5,40,1,...,0,0.0,0,0,0,15.0,2017,3000,11,home

In [435]:
wr_2017 = pd.concat([wr_2017,week17])
wr_2017.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
2476,19501,Justin Hardee,NO,17,TB,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,null,20,away
2477,19514,Keelan Cole,JAX,17,TEN,8,4,50.0,33,0,...,0,0.0,0,1,1,6.3,2017,3200,15,away
2478,19539,Travis Rudolph,NYG,17,WAS,4,1,25.0,29,0,...,0,0.0,0,0,0,3.9,2017,3000,14,away
2479,19627,Chris Thompson,HOU,17,IND,3,3,100.0,54,0,...,0,0.0,0,0,0,8.4,2017,3500,26,home
2480,19668,Lance Lenoir,DAL,17,PHI,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,6200,22,home

In [405]:
wr_2017 = pd.concat([week1,week2])
wr_2017.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYards,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a
0,3601,Eric Weems,TEN,1,OAK,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,3000,7,home
1,4556,Jordy Nelson,GB,1,SEA,8,7,87.5,79,1,...,0,0.0,0,0,0,20.9,2017,7600,5,away
2,5571,Larry Fitzgerald,ARI,1,DET,13,6,46.2,74,0,...,0,0.0,0,0,0,13.4,2017,5900,24,home
3,6767,Pierre Garcon,SF,1,CAR,10,6,60.0,81,0,...,0,0.0,0,0,0,14.1,2017,3000,17,away
4,8373,Brandon Tate,BUF,1,NYJ,0,0,0.0,0,0,...,0,0.0,0,0,0,0.0,2017,5300,24,home

In [217]:
wr_2015.shape

(2420, 24)

In [109]:
# Surface dictionary consisting of every team and the type of field they play on

surface_dict={'KC':'grass',
             'CAR':'grass',
              'WAS':'grass',
              'CLE':'grass',
              'MIA':'grass',
              'PIT':'grass',
              'GB':'grass',
              'SF':'grass',
              'PHI':'grass',
              'LAR':'grass',
              'BAL': 'grass',
              'TEN':'grass',
              'OAK':'grass',
              'LAC':'grass',
              'TB':'grass',
              'CHI':'grass',
              'DEN':'grass',
              'ARI':'grass',
              'DAL':'turf',
              'SEA':'turf',
              'DET':'turf',
              'ATL':'turf',
              'NE':'turf',
              'IND':'turf',
              'NO':'turf',
              'NYG':'turf',
              'NYJ':'turf',
              'HOU':'turf',
              'BUF':'turf',
              'CIN':'turf',
              'MIN':'turf',
              'JAX':'grass'
              
             }

In [387]:
wr_2016.index = wr_2016['Team']

In [436]:
# Add the tyep of field the player palyed on by mapping the field on which the game was played to the surface dictionary

surface = []
for idx, team in enumerate(wr_2017['Team']):
    if wr_2017.iloc[idx]['h/a']=='home':
        surface.append(surface_dict[team])
    else:
        surface.append(surface_dict[wr_2017.iloc[idx]['Opponent']])


wr_2017['surface'] = surface

In [437]:
wr_2017.head()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a,surface
0,3601,Eric Weems,TEN,1,OAK,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,3000,7,home,grass
1,4556,Jordy Nelson,GB,1,SEA,8,7,87.5,79,1,...,0.0,0,0,0,20.9,2017,7600,5,away,turf
2,5571,Larry Fitzgerald,ARI,1,DET,13,6,46.2,74,0,...,0.0,0,0,0,13.4,2017,5900,24,home,grass
3,6767,Pierre Garcon,SF,1,CAR,10,6,60.0,81,0,...,0.0,0,0,0,14.1,2017,3000,17,away,grass
4,8373,Brandon Tate,BUF,1,NYJ,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,5300,24,home,turf

In [438]:
wr = pd.concat([wr,wr_2017])

In [439]:

wr.tail()

,PlayerID,Name,Team,Week,Opponent,ReceivingTargets,Receptions,ReceptionPercentage,ReceivingYards,ReceivingTouchdowns,...,RushingYardsPerAttempt,RushingTouchdowns,Fumbles,FumblesLost,FantasyPointsDraftKings,year,salary,def_rk,h/a,surface
2476,19501,Justin Hardee,NO,17,TB,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,null,20,away,grass
2477,19514,Keelan Cole,JAX,17,TEN,8,4,50.0,33,0,...,0.0,0,1,1,6.3,2017,3200,15,away,grass
2478,19539,Travis Rudolph,NYG,17,WAS,4,1,25.0,29,0,...,0.0,0,0,0,3.9,2017,3000,14,away,grass
2479,19627,Chris Thompson,HOU,17,IND,3,3,100.0,54,0,...,0.0,0,0,0,8.4,2017,3500,26,home,turf
2480,19668,Lance Lenoir,DAL,17,PHI,0,0,0.0,0,0,...,0.0,0,0,0,0.0,2017,6200,22,home,turf

In [441]:
wr.to_csv('input/wr/dk_stats_loc.csv', index=False)